### ISSUE TITLE
syntax error in runtime_CLI.py

### ISSUE THREAD

**Issue by larseggert** [p4lang/behavioral-model#100]
I'm following the instructions in the README, trying to run the `simple_router` target. The first step works OK:
```
# bash run.sh
Thrift port was not specified, will use 9090
Adding interface veth1 as port 0
Adding interface veth3 as port 1
Adding interface veth5 as port 2
Adding interface veth7 as port 3
Thrift server was started
```

But `runtime_CLI.py` throws an error:
```
# ./runtime_CLI --json simple_router.json < commands.txt
Traceback (most recent call last):
  File "./runtime_CLI", line 38, in <module>
    from bm_runtime.standard import Standard
  File "/mnt/home/vmhome/bmv2/tools/bm_runtime/standard/Standard.py", line 368
    def bm_register_write_range(self, cxt_id, register_array_name, from, to, value):
                                                                      ^
SyntaxError: invalid syntax
```

This seems to be due to 483373e, which added `bm_register_write_range`. It has a `from` parameter, and that is obviously reserved in python. Rename the parameter?

**Comment by antoninbas** [comment]
Thanks for reporting this, I changed the parameter name in the Thrift service so that it does not generate Python code with a `from` parameter. The commit SHA is 432122b6806a6407b800606d1b22192b3b85d12f
