### ISSUE TITLE
Can  ./configure 'CFLAGS=-g -03' 'CXXFLAGS=-g -03' be used in version 1.13.0

### ISSUE THREAD

**Issue by Itwaits** [p4lang/behavioral-model#1003]
Hi
When I run stress test the bmv2 throughput is only 5Mbps
I try to run ./autogen,sh &&  ./configure 'CFLAGS=-g -03' 'CXXFLAGS=-g -03' be used in version 1.13.0 which is introduce in performance READE.ME
It shows that: configure: error: C++ compiler cannot create executables

**Comment by antoninbas** [comment]
Is that `-03` or `-O3`? Looks like it is the former, which is not valid.

**Comment by Itwaits** [comment]
03

**Comment by Itwaits** [comment]
zero three I think
