### ISSUE TITLE
Running BMV2 on a baremetal switch or server

### ISSUE THREAD

**Issue by mharris-t** [p4lang/behavioral-model#1010]
Hi,

Has anyone been able to run BMV2 simple_switch on a standalone linux based switchboxes or servers? I am able to run simple_switch in a VM and am able to ensure connectivity between two VM endhosts in Virtual box. 

I am using `simple_switch -i 1@if1 -i 2@if2 basic.json` command to map physical interfaces to the bmv2 switch. But so far I have not been able to connect two physical end hosts with the bmv2 switch in the switchbox.

**Comment by antoninbas** [comment]
There is no difference between connecting to a physical NIC or a virtual NIC as far as bmv2 is concerned. I recommend asking this question on the P4 Slack, and I will be closing this issue. It will be helpful if you can provide information about your P4 program, table entries, etc. I believe that looking at the simple_switch console logs and capturing packets with tcpdump / Wireshark should be enough to figure out what's wrong. In Wireshark I recommend looking for checksum / packet fragmentation issues.

**Comment by mharris-t** [comment]
Basically, my P4 program is similar to the basic forwarding program from the tutorial. The same program works with BMV2 in a VM with two VM end-hosts. However, when replicated in a real-world scenario with linux based machines, this does not work. 

For example, the end-hosts don't respond to ICMP request even when packets correctly reach the interface. I have confirmed this with wireshark and I'm not really sure what I might be doing wrong.
