### ISSUE TITLE
P4 bmv2 mtu fragmentation and reassembly

### ISSUE THREAD

**Issue by sarashakeri** [p4lang/behavioral-model#1012]
Hi all, 
I have a question about how I can handle fragmentation because of the limited MTU in bmv2. I am adding new headers in one P4 software switch in one server and send it out to another server that is also running a software switch and wants to use the added header. By adding new headers the size of the packet will increase and it may be fragmented at the source. When it arrives at the destination P4 switch, how the switch can reassemble the packets? Are the packets already reassembled in the physical interface before reaching to destination switch?

**Comment by antoninbas** [comment]
I'm a bit rusty on this, but I don't think you are able to send packets larger than the MTU using bmv2. bmv2 uses libpcap to send packets (`pcap_sendpacket` if I recall correctly), which _should_ give you an error if you try to send a packet that exceeds the MTU (errno 90, message too long).

When you grow the packet size in bmv2 by adding new headers, you should make sure you stay under the MTU. You should not assume that your P4 switch is capable of IP fragmentation (at least you should not assume bmv2 is).

**Comment by sarashakeri** [comment]
Thanks a lot for your reply. Searching about this issue, I have another question. Is the BMv2 switch running in kernel or user space or both? and where exactly packet switching happens in BMv2, does it need any context change between user space and kernel space?

**Comment by jfingerh** [comment]
BMv2 runs completely in user space.  It makes system calls, e.g. to read packets from network interfaces, or send them to network interfaces, but all packet modifications and/or forwarding decisions are made in the user space program.
