### ISSUE TITLE
Compiling P4 to eBpf, why?

### ISSUE THREAD

**Issue by sarashakeri** [p4lang/behavioral-model#1014]
Hello,
Recently I have read some documents about compiling the P4 program to eBpf. I read about both P4 and eBpf and their potential overlap. I am wondering what is the advantage of converting P4 to eBpf? What other capabilities eBpf can provide? is it something related to performance or security?

Thanks

**Comment by antoninbas** [comment]
That has nothing to do with this repository so I'll be closing this issue. Please ask on the p4.org Slack or forum.
