### ISSUE TITLE
Measure total number of Range Match or Ternary entries used for rule

### ISSUE THREAD

**Issue by drobinkent** [p4lang/behavioral-model#1015]
Is it possible to count how many entries are required to store a Range Match or Ternary key-based rule ?

**Comment by antoninbas** [comment]
That's out of scope of bmv2. bmv2 stores all entries (no matter the match type) using simple C++ data structures. It doesn't try to model how networking hardware would store match entries in SRAM / TCAM, assuming that's what you meant with your question. This would be very hardware-dependent.
