### ISSUE TITLE
Running p4dbg.py with python3

### ISSUE THREAD

**Issue by mahfida** [p4lang/behavioral-model#1016]
Hi,
I am using debugging for my p4 program. When starting simple_switch with --debugging command, it works. But when running the p4dbg.py (with python3), it gives following error 
---------------------------------------------------
'--socket' not provided, using ipc:///tmp/bmv2-0-debug.ipc (obtained from switch)
Obtaining JSON from switch...
Done
Connecting to the switch...
Unknow error, detaching and exiting
initializer for ctype 'char' must be a bytes of length 1, not int_
---------------------------------------------------
I think it is because of setting line number 393 to
                       req += struct.pack(">3s", b"\x01\x02\x03")
but without placing 'b', the code does not execute. Any guidance to solve the issue will be highly appreciated.
Regards.

**Comment by antoninbas** [comment]
Thanks for reporting this, I have submitted a patch

**Comment by mahfida** [comment]
Thank you Antoni, 
There some other changes that also need to done
i.e. changes to statement 290 and 291, such as follows
                    v_str = ':'.join(repr(x).encode('utf-8').hex() for x in v)
                    v_int = int(repr(v).encode('utf-8').hex(), 16)

and secondly the code issues an error of "initializer for ctype 'char' must be a bytes of length 1, not int", when it reaches at statement 628 i.e. at self.sok.send(req.generate()). Can you please see it also. Regards

**Comment by antoninbas** [comment]
@mahfida I don't understand your comments. These look like the exact same issues that I already have fixed.

I am able to run some basic tests with the debugger. If you find more issues, please open a new Github issue and provide the steps needed for reproduction. Or feel free to submit a PR directly with your changes, with justification as to why they are needed.
