### ISSUE TITLE
How to add a new match_kind 

### ISSUE THREAD

**Issue by aaapuuuuu** [p4lang/behavioral-model#1019]
Hi ,all
I hope to add a new match_kind, its specific implementation is a combination of Bloom filters, and then I hope to use my new match kind for key lookup in a lookup table like the existing lpm, exact, ternary, etc. What source file may I need to modify ? 
I guess the file below may need to be changed : lookup_structure.cpp , match_units.cpp , P4Object.cpp , etc. I am not very sure whether p4c needs to be modified . 
Look forward to your reply. :)

**Comment by antoninbas** [comment]
I don't want to discourage you but this is not an easy task. This is an old PR which added support for the `range` match kind, and you may be able to use it as a reference: https://github.com/p4lang/behavioral-model/pull/145. And yes, you will also need to make some changes on the p4c side.

Are you sure you cannot do what you want using an extern?

**Comment by aaapuuuuu** [comment]
Thank you so much for your reply. 
I also found the difficulty of doing this. :( I will take a closer look at the example you mentioned.
I have not carefully considered the feasibility of using an extern, thank you for your reminder, I will think about it carefully.

**Comment by antoninbas** [comment]
Closing this issue as there is no update
