### ISSUE TITLE
Can we access the payload of a packet from the c++ code of an extern that I added ? 

### ISSUE THREAD

**Issue by zakariaCreate** [p4lang/behavioral-model#1021]
Hi all,

I would like to access the payload of a packet from the c++ code of an extern that I added (file : simple_switch.cpp).
Is it possible to do that ?
if not what is the best/easy way to achieve that ? (please provide some clear steps)

Thank you very much !

**Comment by antoninbas** [comment]
You didn't specify if you were writing an extern function or an extern type, but in both cases the answer is yes. You just need to call `get_packet()` and then you will get a non-const reference to the `Packet` object. You then have access to all the public methods in the `Packet` class (https://github.com/p4lang/behavioral-model/blob/main/include/bm/bm_sim/packet.h), including `payload()`.
