### ISSUE TITLE
Connect mininet hosts to root namespace

### ISSUE THREAD

**Issue by p4pifor** [p4lang/behavioral-model#1022]
Hi, How could I do to have a mininet host in root namespace? I've read in this link http://mininet.org/walkthrough/ that one can have everything running in root namespace, I do not know how to do it though. I've read there is a parameter (innamespace) which can be set to false. However, topology is defined in json files instead of using python API. Is there any way to do what I wanna get?
Thanks in advance

**Comment by antoninbas** [comment]
I don't think this is really related to this specific repository.
I invite you to ask your question on the P4.org slack workspace or on the [P4 forum](https://forum.p4.org/)
