### ISSUE TITLE
Assertion `pos == s` failed

### ISSUE THREAD

**Issue by pierventre** [p4lang/behavioral-model#1024]
When using the following commits `a5fd855d4b3293e23816ef6154e83dc6621aed6a` and `760183c17ab3de714cf818db45038f9f9f088b1d` for PI and BMV2 respectively, we have seen the failure of this assertion in `stratum_bmv2: ../../include/bm/bm_sim/handle_mgr.h:156: int bm::HandleMgr::get_handle(bm::handle_t*)`

Please find attached switch logs and write-reqs.

[leaf1.log](https://github.com/p4lang/PI/files/6947919/leaf1.log)
[leaf1-write.log](https://github.com/p4lang/PI/files/6947921/leaf1-write.log)

**Comment by pudelkoM** [comment]
I think this could be related to PR https://github.com/p4lang/behavioral-model/pull/1002 where the bitarray implemenation was changed from judy to `DynamicBitset`. We might be hitting an edgecase.

**Comment by antoninbas** [comment]
The implementation of `release_handle` is not correct:
```cpp
  int release_handle(handle_t handle) {
    auto pos = static_cast<size_type>(handle);
    auto s = handles.size();
    if (pos >= s || !handles.reset(pos)) return -1;
    if (first_unset > pos) first_unset = pos;
    return 0;
  }
```
`first_unset` is not set correctly, it should perform a reverse search.

**Comment by pierventre** [comment]
@antoninbas thanks for picking this up quickly!
