### ISSUE TITLE
Does bmv2 consider concurrency among multiple logical stages in a physical stage?

### ISSUE THREAD

**Issue by jijinfanhua** [p4lang/behavioral-model#1034]
Hi, I read the article "Forwarding Metamorphosis: Fast Programmable Match-Action Processing in Hardware for SDN", i.e., RMT, and I think the idea of concurrency among multiple logical stages in a physical stage is excellent, because it can reduce the number of logical stages. I'm interested in how bmv2 defines the logical stage and physical stage, and how bmv2 implements concurrency among multiple logical stages in a physical stage.
Thanks a lot.

**Comment by jafingerhut** [comment]
bmv2 does all data packet processing on a general purpose CPU, not on RMT-style hardware.  It has no notion of "stages" at all.  For any tables that should be applied while processing a packet, they are all processed sequentially.

bmv2 _can_ perform ingress processing in parallel for different packets from different input ports, in separate threads.  However, each thread will perform all table apply steps sequentially, independently of the other threads doing ingress processing.

Similarly bmv2 can perform egress processing in parallel for different packets destined to different output ports, in separate threads.

If you want to compile P4 programs to run on RMT-style hardware, you need a P4 compiler with a back end that is specifically focused on that hardware, and that P4 compiler _back end_ code would be reponsible for determining when it was compatible with the language semantics to execute two tables in parallel, or not.

**Comment by jijinfanhua** [comment]
Got it! Thank you. I will close this.
