### ISSUE TITLE
Make check FAIL: test_switch FAIL: test_target_parser

### ISSUE THREAD

**Issue by Elbediwy** [p4lang/behavioral-model#1037]
I installed all the required dependencies including Thrift version 0.11.0, however I can't pass the "make check" command while building bmv2. I always get Fails for test_switch and test_target_parser.

Here is the output in the "test_suite.log"

==============================================
   bm 1.14.0-71dc4bd8: tests/test-suite.log
==============================================

# TOTAL: 38
# PASS:  36
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test_switch
=================

[==========] Running 12 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 12 tests from Switch
[ RUN      ] Switch.GetConfig
[       OK ] Switch.GetConfig (0 ms)
[ RUN      ] Switch.ConfigOptions
[       OK ] Switch.ConfigOptions (0 ms)
[ RUN      ] Switch.InitObjectsEmpty
[       OK ] Switch.InitObjectsEmpty (2001 ms)
[ RUN      ] Switch.GetP4Objects
[       OK ] Switch.GetP4Objects (2 ms)
[ RUN      ] Switch.SerializeState1
[       OK ] Switch.SerializeState1 (4 ms)
[ RUN      ] Switch.SerializeState2
lt-test_switch: utils.cpp:71: CLIWrapper::CLIWrapper(int, bool): Assertion `fs::is_directory(bm_runtime_dir) && "Could not find Thrift bindings"' failed.
FAIL test_switch (exit status: 134)

FAIL: test_target_parser
========================

[==========] Running 15 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 5 tests from TargetParserIfaceTest
[ RUN      ] TargetParserIfaceTest.NoDispatch
Error while parsing command line arguments
Usage: SWITCH_NAME [options] <path to JSON config file>
Options:
  -h [ --help ]               Display this help message
  -i [ --interface ] arg      <port-num>@<interface-name>: Attach network 
                              interface <interface-name> as port <port-num> at 
                              startup. Can appear multiple times
  --pcap [=arg(=.)]           Generate pcap files for interfaces. Argument is 
                              optional and is the directory where pcap files 
                              should be written. If omitted, files will be 
                              written in current directory.
  --use-files arg             Read/write packets from files (interface X 
                              corresponds to two files X_in.pcap and 
                              X_out.pcap). Argument is the time to wait (in 
                              seconds) before starting to process the packet 
                              files.
  --packet-in arg             Enable receiving packet on this (nanomsg) socket.
                              The --interface options will be ignored.
  --thrift-port arg           TCP port on which to run the Thrift runtime 
                              server
  --device-id arg             Device ID, used to identify the device in IPC 
                              messages (default 0)
  --nanolog arg               IPC socket to use for nanomsg pub/sub logs 
                              (default: no nanomsg logging
  --log-console               Enable logging on stdout
  --log-file arg              Enable logging to given file
  -L [ --log-level ] arg      Set log level, supported values are 'trace', 
                              'debug', 'info', 'warn', 'error', off'; default 
                              is 'trace'
  --log-flush                 If used with '--log-file', the logger will flush 
                              to disk after every log message
  --notifications-addr arg    Specify the nanomsg address to use for 
                              notifications (e.g. learning, ageing, ...); 
                              default is ipc:///tmp/bmv2-<device-id>-notificati
                              ons.ipc
  --restore-state arg         Restore state from file
  --dump-packet-data arg      Specify how many bytes of packet data to dump 
                              upon receiving & sending a packet. We use the 
                              logger to dump the packet data, with log level 
                              'info', so make sure the log level you have set 
                              does not exclude 'info' messages; default is 0, 
                              which means that nothing is logged.
  -v [ --version ]            Display version information
  --json-version              Display max bmv2 JSON version supported in the 
                              format <major>.<minor>; all bmv2 JSON versions 
                              with the same <major> version number are also 
                              supported.
  --no-p4                     Enable the switch to start without an inout 
                              configuration
  --max-port-count arg (=512) Maximum number of interfaces that can be bound to
                              the switch; this is not an upper bound on each 
                              port number, which can be arbitrary. Depending on
                              the target, this max value may or may not be 
                              enforced.
FAIL test_target_parser (exit status: 1)

How can I fix this ?!

**Comment by antoninbas** [comment]
The first test may be failing because the Thrift python bindings were not generated (maybe because you built Thrift without Python support?). You could check the contents of `thrift_src/gen-py/` to confirm.

I don't know about the second test. AFAIK, it would only fail if `"empty_config.json"` is missing.

I am not able to reproduce and these tests are run successfully as part of CI. If you want to dig deeper and find an issue with the tests, I would be grateful for a patch. But these tests failures are unlikely to prevent you from using bmv2 (if the Thrift python bindings were indeed not generated, some tools such as simple_switch_CLI will not be available).

**Comment by Elbediwy** [comment]
Thanks for you reply. 
I checked the directory thrift_src/gen-py/ , you can find it shared in my repository here 
https://github.com/Elbediwy/Behavioral-model-installation-failure

I hope it can help.
