### ISSUE TITLE
How to create and send a new packet from an extern written in c++ in simple_switch.cpp ?

### ISSUE THREAD

**Issue by zakariaCreate** [p4lang/behavioral-model#1038]
I am implementing an extern on simple_switch.cpp that works as follow : 
1/extract payloads of some specific packets (done)
2/aggregate payloads stored after receiving an x number of those packets (done)
3/send the aggregated payloads(that are currently stored in memory of the switch) to another node using a packet from the switch (no idea how to do it)

I will appreciate it if someone could explain to me how can I do the third step.

Thank you.

**Comment by antoninbas** [comment]
You need to give your extern instance access to the main `switch` object itself, which inherits from `bm::Switch`. In the case of the `simple_switch` target, this object is declared there: https://github.com/p4lang/behavioral-model/blob/71dc4bd8ee8ba949fa19644833a841b43f7d37ee/targets/simple_switch/main.cpp#L33.

You can then send a packet directly by calling `transmit_fn` directly on that object: https://github.com/p4lang/behavioral-model/blob/71dc4bd8ee8ba949fa19644833a841b43f7d37ee/include/bm/bm_sim/dev_mgr.h#L101

The packet will be sent out on the specified interface, without any P4 packet processing. If you do need packet processing, the answer will be a bit more complex.

**Comment by zakariaCreate** [comment]
Thank you @antoninbas so much for your answer.

1) Could you please explicit more how could I access the "SimpleSwitch" object from my c++ extern code located at : 
"behavioral-model/targets/simple_switch/simple_switch.cpp"
I am using the same switch used in P4 tutoriel VM exercices (in Makefile of basic exercices I can see : BMV2_SWITCH_EXE = simple_switch_grpc) thus I think I am working with "simple_switch_grpc"

2) The buffer pointer of the parameters of the "transmit_fn" function should point at the first bit of the ethernet header, am I right ?

3) If I use "transmit_fn" function to send a packet with a payload of 20 000 Bytes for example, and knowing that the MTU of the link is 1500Bytes (limit due to the ethernet protocol) the switch will do the fragmentation automatically or should I do it by myself ?

And no I don't need P4 packet processing for this step.

Thank you !

**Comment by antoninbas** [comment]
1. If you are using `simple_switch_grpc` you will need to do some extra work as you need to ensure your extern can access the correct `SimpleSwitch` instance, which is this one: https://github.com/p4lang/behavioral-model/blob/8ce90975d816dec1f1a0fa05289d6f8d1a9c5124/targets/simple_switch_grpc/switch_runner.h#L83 I suggest that you define a global variable somewhere which will be a pointer to this instance. You will need to set this global variable https://github.com/p4lang/behavioral-model/blob/8ce90975d816dec1f1a0fa05289d6f8d1a9c5124/targets/simple_switch_grpc/switch_runner.cpp#L496 The global variable will need to be visible to your extern, so you can just declare it twice (once in switch_runner.cpp and once in your extern file).
2. yes
3. no, we use raw sockets intentionally and you should not assume that there will be IP fragmentation. I would expect `pcap_sendpacket` to return an error.

**Comment by zakariaCreate** [comment]
Thank you @antoninbas for your answer.

In my case, I implemented my extern class inside "behavioral-model/targets/simple_switch_grpc/switch_runner.cpp" at the bottom.
Before my extern class I declared a global instance using this instruction : 
auto &runner = sswitch_grpc::SimpleSwitchGrpcRunner::get_instance();
So that I can access to simpleswitch through it and then the transmit_fn method.
But by adding that, the switch don't start any more.

I will appreciate your help !
Thank you !

**Comment by antoninbas** [comment]
You cannot do that. This needs to be the first call to `SimpleSwitchGrpcRunner::get_instance()` or the switch won't be initialized properly.
https://github.com/p4lang/behavioral-model/blob/306a7c8368a189f0323dc643ca3ab0967fee5c0b/targets/simple_switch_grpc/main.cpp#L106-L107

Why not call `SimpleSwitchGrpcRunner::get_instance()` in the extern's `init` function?

**Comment by antoninbas** [comment]
Closing this issue as there is no update

**Comment by zakariaCreate** [comment]
> Closing this issue as there is no update

Sorry for not updating, your solution works very fine ! 

Thank you so much @antoninbas for your help !
