### ISSUE TITLE
Conditional execution in actions unsupported on this target

### ISSUE THREAD

**Issue by xjywhu** [p4lang/behavioral-model#1041]
I am a p4 novice， when I did register read and write operation in if statement, I met the error and didn't know why:
Conditional execution in actions unsupported on this target
the code just like this:
 if(up){
            hash(meta.flow_hash, 
                HashAlgorithm.crc16, 
                (bit<13>)0, 
                { hdr.ipv4.srcAddr, hdr.ipv4.dstAddr, hdr.ipv4.protocol, hdr.tcp.srcPort, hdr.tcp.dstPort },
                (bit<26>) 13);

            //calculate batch
            meta.batch = standard_metadata.ingress_global_timestamp/WINDOW_SIZE%WINDOW_NUMBER;

            cal_hash();
            add_batch_counter();
            
            // syn
            if (hdr.tcp.syn == 1){
                add_syn_counter();
            }
            // pkt
            add_packet_counter();
            // fin
            if (hdr.tcp.fin == 1){
                add_fin_counter();
            }

            // window
            flow_window_register.write((bit<32>) meta.flow_hash, hdr.tcp.window);
            
            flow_window_register.read(meta.flow_window, (bit<32>) meta.flow_hash);
}

**Comment by jafingerhut** [comment]
I would recommend asking questions like this on https://forum.p4.org, which is intended for answering both novice and experienced user questions, and also maintaining a history of questions and answers that can be searched later.

Github issues in this repository are more appropriate if you believe you have found a bug in the BMv2 simple_switch behavioral model, or want to propose enhancements to its features.

**Comment by rst0git** [comment]
@xjywhu The restrictions on code within actions are described [here](https://github.com/p4lang/behavioral-model/blob/f746edec9400fb51fab27f28462d228bbd29c87c/docs/simple_switch.md#restrictions-on-code-within-actions).

> P4 programs using if statements within actions are likely to be less portable than programs that avoid doing so.

**Comment by antoninbas** [comment]
I will close this issue. As mentioned in the document shared by @rst0git, this is actually a p4c limitation, and bmv2 support conditional operations in actions.
