### ISSUE TITLE
Assertion `now_ms >= meta.ts.get_ms()` failed

### ISSUE THREAD

**Issue by machadoatz** [p4lang/behavioral-model#1046]
Hi,

When using the following commits `66da143288d4f02f17cd6a63d0f4b2a87b011499` and `fc54206cab45a9d8d64db0661578828ce78e962b` for PI and BMV2 respectively, the assertion `now_ms >= meta.ts.get_ms()` fails for the target `simple_switch_grpc`.

I am using tcpreplay to introduce traffic in a Mininet network. The topology is pretty simple, with only two hosts connected to a P4 Switch.

The assertion occurs here:

https://github.com/p4lang/behavioral-model/blob/fc54206cab45a9d8d64db0661578828ce78e962b/src/bm_sim/match_units.cpp#L736

This is the P4 program I'm using:
[simple-dyn-bridge.txt](https://github.com/p4lang/behavioral-model/files/7388783/simple-dyn-bridge.txt)

I made sure that the bmv2 and PI environments were correctly setup:
[bmv2-make-check.txt](https://github.com/p4lang/behavioral-model/files/7388239/bmv2-make-check.txt)
[PI-make-check.txt](https://github.com/p4lang/behavioral-model/files/7388242/PI-make-check.txt)

Here are the switch logs and requests:
[s1-p4rt-requests.txt](https://github.com/p4lang/behavioral-model/files/7399621/s1-p4rt-requests.txt)
[switch1.txt](https://github.com/p4lang/behavioral-model/files/7399416/switch1.txt)

Please let me know if I can provide more useful logs
Thank you,
Francisco Machado

**Comment by antoninbas** [comment]
Two things would be very helpful:
- run `simple_switch_grpc` with `--log-flush` and share the switch logs again. Your `switch1.txt` file doesn't include any useful information at the moment. Ideally it would have table entry logs and packet logs, which would be helpful. (Make sure the default log verbosity is used as well).
- if you are able to re-build bmv2, replacing the `system_clock` with a `steady_clock` instance: https://github.com/p4lang/behavioral-model/blob/fc54206cab45a9d8d64db0661578828ce78e962b/include/bm/bm_sim/packet.h#L103

**Comment by Malathi-Poojari** [comment]
@machadoatz Is this issue resolved?
