### ISSUE TITLE
use bmv2 to encoding some data

### ISSUE THREAD

**Issue by muyingluo1997** [p4lang/behavioral-model#1049]
I want to know whether bmv2 provides a method to encode data. If not, I would like to know how I should add a function written by myself to bmv2?

**Comment by jafingerhut** [comment]
"encode data" is pretty general.  Encode it how?

Encode only packet headers, or also the complete payload of a maximum-sized packet?  If the complete payload, then the P4 programming language is not strong in operations on payloads, although it is possible to add code to bmv2 to change the packet payload, if you wish.

**Comment by muyingluo1997** [comment]
"Encode data" refers to, for example, I want to encode, encrypt, and compress the ingress_timestamp on bmv2. 
I don't know if bmv2 provides such a function. 
Why is it not recommended to use p4 to handle the load part? I currently understand that p4 does not seem to support division.

**Comment by jafingerhut** [comment]
Most (not all) P4 implementations are focused on parsing, processing, and modifying packet headers, not on performing processing on packet payload data that can be up to 9+ Kbytes with Ethernet jumbo frames.  Many low-cost-per-Tbps P4 implementations limit themselves to 512 bytes or less of packet header parsing and packet modification.

Some programmable NICs do have support for IPsec and perhaps other forms of encryption, but most likely those are focused on implementing IPsec full-payload encryption, not on encrypting one particular field of a packet.  Of course you can put the field you want to encrypt after the IPsec header, and then it should be encrypted.

If you can do the encode, encrypt, and compress functions of interest to you with the math operations that P4 provides, i.e. add, subtract, shift left/right, bitwise and/or/xor operations, which should be enough for many kinds of operations, you can implement them that way yourself.  P4 does not have loops, so you can only write code to implement that for a fixed number of bits in your packets.

Most P4 target devices have an implementation-specific limit on the number of such operations they can perform per packet at line rate, and if you run out of those, you would need to use packet recirculation features, which typically reduce the packet processing throughput of the device, to do more processing per packet.

**Comment by muyingluo1997** [comment]
Thank you very much for your answer, it is very helpful to me. In addition, I would like to ask, do you know if you want to provide a hash code similar to the one provided in the v1model.p4 file, which interface can I extend to achieve the function I want to design?

**Comment by jfingerh** [comment]
If the hash function in the v1model.p4 file returns a value that is of use to you, then by all means, please call that function in the P4 code that you write.

It isn't yet clear to me what function you want to design.  If you write it in at least some kind of pseudocode, or precise description of "when this packet comes in, I want this packet to go out", that might help.  I would also recommend asking these kinds of questions in this web forum devoted to P4, since this Github repository is really more suited to bugs or enhancements to behavioral-model, not how to write P4 programs: https://forum.p4.org/

**Comment by muyingluo1997** [comment]
Thanks!
