### ISSUE TITLE
Can't read digest message when using simple_switch_grpc target

### ISSUE THREAD

**Issue by crx892476808** [p4lang/behavioral-model#1051]
I am using bmv2 in Mininet. With Simple_Switch target, I can read digest messages through Thrift with _notifications_socket_. However, when using simple_switch_grpc target, I can not get _notifications_socket_ and I can not read digest messages through Thrift. Does simple_switch_grpc prevents users from using Thrift to get digest messages? If so, how can I read digest messages through grpc?
(I have configured simple_switch_target with --with-thrift).

**Comment by antoninbas** [comment]
> I can read digest messages through Thrift with notifications_socket.

This is inaccurate. The digest messages you are referring to here are sent by nanomsg, and Thrift is only involved to ack notifications.

> Does simple_switch_grpc prevents users from using Thrift to get digest messages?

Yes, when using simple_switch_grpc, digest messages are sent through P4Runtime exclusively and are not broadcast on a nanomsg socket anymore.

> If so, how can I read digest messages through grpc?

Please refer to the P4Runtime specification for information on how to consume digest messages with P4Runtime (over gRPC): https://p4.org/p4-spec/p4runtime/v1.2.0/P4Runtime-Spec.html#sec-digestentry
