### ISSUE TITLE
bmv2 stop at Obtaining JSON from switch after obtaining 10 json

### ISSUE THREAD

**Issue by muyingluo1997** [p4lang/behavioral-model#1053]
I have created 12 switches in Mininet. And I import the flow table by a shell, such as '''sudo simple_switch_CLI --thrift-port 9090 <s1.txt'''.
And after I import 10 flow tables to switches, the program stopped at the 11th switch flow table import command：
'''Obtaining JSON from switch...'''
Can anyone give some suggestions？

**Comment by jafingerhut** [comment]
There is probably some Python code somewhere using a regular expression to recognize switch names that only allows a single digit number in the name of the switch, or something similar to that.  At least, if you use the p4lang/tutorials code or something based upon that, there was once a similar limitation in the Python code there somewhere in the past that I noticed -- I do not recall whether it was changed.

**Comment by muyingluo1997** [comment]
I didn't use the p4lang/tutorials code. I have started 50 switches with bmv2 and imported the flow tables through a python file, and I didn't meet the problem. And I don't know why the problem appears.
I found that the program stop at "Obtaining JSON from switch...", this sentence appear at /behavioral-model/tools/bmpy_utils.py, and then my program didn't occur other error info, such as "Error when requesting JSON config from switch...", it just stop at "Obtaining...".
And the next code to be executed is "standard_client.bm_get_config()", I don't know what happens in this code, it doesn't give me any information.

**Comment by jafingerhut** [comment]
My only suggestion is "add more debug print statements to the code to narrow down where the problem occurs".  Generic debugging advice, I know, and it can be time consuming, but given persistence and effort it can pay off eventually.

**Comment by muyingluo1997** [comment]
ok, thanks a lot

**Comment by jfingerh** [comment]
Also, if you find anything in one of the open source P4 projects that you find is causing this issue, and you believe you find a fix for it, please create a pull request for that project, explaining the change and why you think it helps.

**Comment by muyingluo1997** [comment]
ok, I'll try my best.

**Comment by muyingluo1997** [comment]
I know why I have this problem.
This is because the --thrift-port I used started from 9090, but when the 10th switch was started, port 9100 was already occupied by another process, so the correct port could not be used when obtaining the JSON configuration file.
But I am executing 
`/home/p4/behavioral-model/targets/simple_switch/simple_switch` -i 1@p1_l1-eth1 -i 2@p1_l1-eth2 -i 3@p1_l1-eth3 -i 4@p1_l1-eth4 --thrift- port 10004 --nanolog ipc:///tmp/bm-4-log.ipc --device-id 4 ../p4_source_code/my.json `--log-console` 
This command does not give any port occupied hint or report an error.
I wonder if this code can be improved.

**Comment by antoninbas** [comment]
I can't reproduce this issue. If another process has already bound to the port, I get an error as expected during start-up:
```
$ nc -l 9090
```
```
$ sudo simple_switch --thrift-port 9090 --no-p4 --device-id 1
Calling target program-options parser
Thrift: Thu Dec  2 09:39:34 2021 TServerSocket::listen() BIND 9090
Thrift returned an exception when trying to bind to port 9090
The exception is: Could not bind: Address already in use
You may have another process already using this port, maybe another instance of bmv2.
```
```
$ sudo simple_switch --thrift-port 9091 --no-p4 --device-id 1
Calling target program-options parser
...
```

**Comment by muyingluo1997** [comment]
Then I don't know what the problem is, but my problem has been solved.
