### ISSUE TITLE
how to use different simple_switch_CLI file?

### ISSUE THREAD

**Issue by muyingluo1997** [p4lang/behavioral-model#1054]
I write a simple_switch_CLI file in my path(/flow_table) and I want to use it. 
The only difference with simple_switch_CLI file in /behavioral-model/targets/simple_switch is that 
original file use '''sys.path.append("/usr/local/lib/python3.6/site-packages")'''
and i use '''sys.path.append("/usr/local/lib/python2.7/dist-packages")'''

when I execute the command:
sudo ../flow_table/simple_switch_CLI --thrift-port 9090 <../flow_table/s1.txt
the error occur: '''sudo ../flow_table/simple_switch_CLI: command not found'''

**Comment by antoninbas** [comment]
That sounds like a python question, not a behavioral-model question. I'll just point out that there is a pyhton2 shebang in the file you are trying to modify: https://github.com/p4lang/behavioral-model/blob/982dec26720dee35735939ed699e8510d5f9f768/targets/simple_switch/simple_switch_CLI.in#L1

**Comment by jafingerhut** [comment]
Yeah, you can try out forum.p4.org for issues like this, where you are making changes that might not be supported.  In particular, changing a Python2 program to Python3, or vice versa, is likely to cause issues unless you also make corresponding changes throughout the program.  Python3 support in several open source P4.org projects is fairly recent, e.g. in the last 6-12 months or so, so it also could depend upon which versions of those tools you have installed.
