### ISSUE TITLE
Add port operation failed

### ISSUE THREAD

**Issue by muyingluo1997** [p4lang/behavioral-model#1055]
when i run `sudo simple_switch -i 0@eth0 -i 1@eth1 --log-console try1.json`
it occurs:

You disabled logging macros when building this binary; however, the log level is currenty set to include 'debug' and possibly 'trace' messages; therefore the logs will be missing most messages
Calling target program-options parser
Adding interface eth0 as port 0
[11:18:50.548] [bmv2] [E] [thread 9889] Add port operation failed
Adding interface eth1 as port 1
[11:18:50.573] [bmv2] [E] [thread 9889] Add port operation failed
[11:18:50.573] [bmv2] [I] [thread 9889] Starting Thrift server on port 9090
[11:18:50.574] [bmv2] [I] [thread 9889] Thrift server was started

Could someone give the advice to solve this problem?

**Comment by jfingerh** [comment]
Usually this means that one or more of the Ethernet interface given as command line arguments does not exist on your system, thus simple_switch cannot send packets to, or receive packets from, a non-existent Ethernet interface.

There is a veth_setup.sh script you can use to create several Ethernet veth interfaces described here: https://github.com/jafingerhut/p4-guide/blob/master/README-troubleshooting.md

You can use the command `ip link show` command to see what interfaces exist on your system.

**Comment by antoninbas** [comment]
As @jafingerhut pointed out, you don't have interfaces named `eth0` and `eth1` on your machine. If you do have these interfaces, feel free to re-open.

**Comment by muyingluo1997** [comment]
ok, thanks a lot
