### ISSUE TITLE
Add more documentation of simple_switch_CLI commands to runtime_CLI.md

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/behavioral-model#1056]
Creating this issue as one that can be marked as good for P4 beginners that are looking for a way to contribute things that take relatively small amount of learning and time.

This file documents many of the commands available in `simple_switch_CLI`, but there are plenty remaining marked as "TODO": https://github.com/p4lang/behavioral-model/blob/main/docs/runtime_CLI.md

Even picking one of those and writing some documentation would be useful, or if you feel energetic, a group of related commands.

**Comment by jafingerhut** [comment]
@antoninbas Does this repository have support for labels on issues, e.g. "beginner"?

**Comment by antoninbas** [comment]
@jafingerhut I added the `good first issue` label. I also bumped up your permissions for this repo to `Triage` so you can now label issues and assign them.

**Comment by abhijeet007rocks8** [comment]
@antoninbas Can you assign me this issue I wanna take a shot at this ?

**Comment by antoninbas** [comment]
@abhijeet007rocks8 sure, thanks for looking into this

**Comment by abhijeet007rocks8** [comment]
@antoninbas Can you provide some resources that i can take look into for writing the documentation

**Comment by antoninbas** [comment]
The only resources are the existing incomplete documentation (https://github.com/p4lang/behavioral-model/blob/main/docs/runtime_CLI.md) and the CLI code (https://github.com/p4lang/behavioral-model/blob/main/tools/runtime_CLI.py) which includes docstrings for most command.
