### ISSUE TITLE
bmv2 log file didn't show the detail of packet processing procedure

### ISSUE THREAD

**Issue by muyingluo1997** [p4lang/behavioral-model#1058]
I have no idea that when I use the command of 
`simple_switch -i 1@s1-eth1 -i 2@s1-eth2 -i 3@s1-eth3 --pcap=/home/test/pcap --thrift-port 40000 --nanolog ipc:///tmp/bm-1-log.ipc --device-id 1 try1.json --log-console >/home/test/log/s1.log`

The output file only print a small amount of initialization information. And there is some warning:
``Warning: you requested the nanomsg event logger, but bmv2 was compiled without -DBMELOG, and the event logger cannot be activated
You disabled logging macros when building this binary; however, the log level is currenty set to include 'debug' and possibly 'trace' messages; therefore the logs will be missing most messages``

This occurred after i use the command of `simple_switch -L 'trace'`, and i haven't modify the code. Could anyone give me some tips to solve this problem?

**Comment by antoninbas** [comment]
This warning tells you what's wrong:

> You disabled logging macros when building this binary; however, the log level is currenty set to include 'debug' and possibly 'trace' messages; therefore the logs will be missing most messages

logging macros were disabled when building bmv2 / simple_switch, so packet-level logs are not available. Thes macros are enabled by default as indicated in the README:

> Debug logging is enabled by default. If you want to disable it for performance reasons, you can pass --disable-logging-macros to the configure script.

So whoever built the code had to explicitly disable them. A rebuild of bmv2 / simple_switch is required (`make clean; ./configure; make`).
