### ISSUE TITLE
PNA target progress/plans?

### ISSUE THREAD

**Issue by kheradmandG** [p4lang/behavioral-model#1059]
I wanted to check if there is any progress on the PNA target. Is there a work in progress that one can play with? If there is no such target, I was wondering if there is any plan for adding the target and/or if anybody is working on it?

**Comment by antoninbas** [comment]
I think this is a question for @jafingerhut. Given the rate ai which the PSA implementation is progressing, I doubt a PNA implementation is in the cards.

**Comment by jafingerhut** [comment]
My guess is that the DPDK back end will have a complete PSA and implementation and PNA implementation before bmv2 does.

This is only a guess, but it is based on the fact that there are several Intel employees paid for at least part of their time to enhance the DPDK back end towards this goal, and to my knowledge, no one is paid to enhance the bmv2 back end, and there are very few volunteer hours going into enhancing the bmv2 back end (not 0, but closer to maintenance-level than adding-features level, as far as I know).

Of course, that could change.  If several engineers either voluntarily decided to, or were paid at least part of their salaries to enhance bmv2, then bmv2 could very well win that race.
