### ISSUE TITLE
Idle timeout notifications for unmatched entries seem more frequent than recommend by P4Runtime API spec

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/behavioral-model#1071]
I created a simple PTF test for a P4_16+v1model architecture program with one table that supports idle timeout.  You can find the P4 program and PTF test code here: https://github.com/jafingerhut/p4-guide/tree/master/ptf-tests/idletimeout

In that test, I configured the idle timeout for a table entry to be 5 seconds.  After sending in a few packets that matched the entry, the controller stops and waits for idle timeout notifications.  One does appear about 5 to 6 seconds after the last packet matches the entry, as expected.  After that the test continues waiting for another 10 seconds, and the switch sends another idle timeout notification for the entry about once every 2 seconds.

This is far better than never sending another idle timeout notification.  I am only creating the issue because the P4Runtime API specification recommends that the later idle timeout notifications occur once every TTL, i.e. 5 seconds in my test case, according to the following sentence in Section 16.4 (see https://p4.org/p4-spec/p4runtime/v1.3.0/P4Runtime-Spec.html#sec-table-idle-timeout-notification ):

"After generating an idle notification, the P4Runtime server must “reset” the timer for the corresponding entry, which means a new notification will be generated after another TTL if the entry is not hit"

**Comment by antoninbas** [comment]
I agree that the behavior is a bit surprising to someone familiar with the P4Runtime spec. However, it's a bit tricky to fix properly IMO. I believe that the purpose of the spec is to ensure that if a notification doesn't make it to the controller, there will eventually be a new notification generated. The current implementation does ensure that since there will be a new notification generated after 2 seconds (which is twice the default sweep interval). So I am tempted to leave it as it is...

**Comment by jafingerhut** [comment]
Agreed that this does not seem like a serious issue.  Maybe I can simply add a note to the docs for bmv2 explaining the existing behavior, then?

**Comment by antoninbas** [comment]
sounds good to me, you may have to start a new doc

**Comment by jafingerhut** [comment]
OK.  I was just thinking of adding a new section somewhere in this file, which already has lots of bmv2+v1model-specific details and limitations: https://github.com/p4lang/behavioral-model/blob/main/docs/simple_switch.md

**Comment by antoninbas** [comment]
A new section in this doc (for simple_switch_grpc) works for me

**Comment by antoninbas** [comment]
See https://github.com/p4lang/behavioral-model/pull/1074
