### ISSUE TITLE
CPU idle during stess test

### ISSUE THREAD

**Issue by FurryChicken** [p4lang/behavioral-model#1072]
Hi,
I installed the switch as follows
```
./autogen.sh && ./configure --disable-logging-macros --disable-elogger 'CFLAGS=-O3' 'CXXFLAGS=-O3'
```
Then I ran the benchmark script stress_test_ipv4.py, here is what I got
```
Running iperf measurement 1 of 5
924 Mbps
Running iperf measurement 2 of 5
809 Mbps
Running iperf measurement 3 of 5
779 Mbps
Running iperf measurement 4 of 5
907 Mbps
Running iperf measurement 5 of 5
1158 Mbps
Median throughput is 809 Mbps
```
Although most people achieve 1Gbps throughput in this test, the throughput is still too low as I am using an 80 cores CPU (Intel Xeon Gold 6230). I monitored the CPU utilization and found only a few CPU went up to 70% while the rest of the cores are completely idle. 

Same thing happened as I launched the `simple_switch_grpc` and connected it to real physical interfaces to perform stress test. 
![image.png](https://s2.loli.net/2022/01/02/McHbqSTpUDXeyjf.png)

Is it normal to have such CPU utilization? Can we improve the performance?

**Comment by antoninbas** [comment]
The way bmv2 can leverage multiple CPUs is based on the ingress & egress ports for the traffic being processed. If you send a single "flow" through the switch, or more generally if all the traffic uses the same ingress port and the same egress port, you will typically only use 2 CPUs (one for ingress processing and one for egress processing). In this case you are using 4 CPUs: 2 CPUs are quite busy (ingress processing for both traffic directions) and 2 CPUs are used but less busy (egress processing for both traffic directions). The only way to achieve higher CPU utilization and higher cumulative throughput is to leverage more ports. The reason why we avoid using different CPUs for a given port is to avoid packet re-ordering within a flow.

**Comment by antoninbas** [comment]
Also asked in the p4 forum: https://forum.p4.org/t/cpu-idle-during-stess-test/213
please do not double post
