### ISSUE TITLE
bmv2 crashes as soon as recirculation is performed

### ISSUE THREAD

**Issue by EmanueleGallone** [p4lang/behavioral-model#1076]
Hi, 
I'm trying the latest p4c feature that enables the developer to decide what metadata is going to be preserved, using field lists (https://github.com/p4lang/p4c/pull/2985)

but the following occurs, after calling the `recirculate_preserving_field_list`:

> [18:29:20.069] [bmv2] [D] [thread 89] [0.0] [cxt 0] Deparsing header '_ingress_ethernet3'
[18:29:20.069] [bmv2] [D] [thread 89] [0.0] [cxt 0] Deparsing header '_ingress_eth_type5'
[18:29:20.069] [bmv2] [D] [thread 89] [0.0] [cxt 0] Deparsing header '_ingress_inner_ipv418'
[18:29:20.069] [bmv2] [D] [thread 89] [0.0] [cxt 0] Deparsing header '_ingress_inner_udp20'
[18:29:20.069] [bmv2] [D] [thread 89] [0.0] [cxt 0] Deparser 'deparser': end
[18:29:20.069] [bmv2] [D] [thread 89] [0.0] [cxt 0] Recirculating packet
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
*** Aborted at 1641580160 (unix time) try "date -d @1641580160" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x52) received by PID 82 (TID 0x7f98b1af3700) from PID 82; stack trace: ***
    @     0x7f98b64a80e0 (unknown)
    @     0x7f98b5f13fff gsignal
    @     0x7f98b5f1542a abort
    @     0x7f98b78730ad __gnu_cxx::__verbose_terminate_handler()
    @     0x7f98b7871066 (unknown)
    @     0x7f98b78710b1 std::terminate()
    @     0x7f98b789be9e (unknown)
    @     0x7f98b649e4a4 start_thread
    @     0x7f98b5fc9d0f clone
    @                0x0 (unknown)

I'm already trying to replicate this behavior using a custom p4 program but nothing so far.

Any idea? Could it be related to the size of the custom metadata struct to be preserved being 'too large'?

**Comment by antoninbas** [comment]
It may be looking up a field name that hasn't been defined. It's pretty hard to say without a backtrace with bmv2 symbols. Right now I have no idea which map lookup triggers the crash.

Any chance you can provide the JSON file generated by the compiler? It may let me reproduce or maybe we can spot the field name causing the issue.

**Comment by EmanueleGallone** [comment]
Thanks @antoninbas. Unfortunately I don't think I can provide the json file, main reason why I'm trying to reproduce the behavior with a custom p4 program.

**Comment by antoninbas** [comment]
As long as you can run bmv2 through gdb, you should be able to see where the program crashes and it should be pretty straightforward to figure out what's wrong with the JSON (it's likely to be a p4c bug). But without the program, it will be hard for the compiler folks to fix it.

**Comment by EmanueleGallone** [comment]
I'm unable to reproduce the bug. Closing the issue.
I will re-open the issue in case I find a way to reproduce it.
