### ISSUE TITLE
The `p4lang-bmv2` deb package failed to build

### ISSUE THREAD

**Issue by qobilidop** [p4lang/behavioral-model#1088]
I've been trying to set up the environment for the [P4 tutorials](https://github.com/p4lang/tutorials) but [this script](https://github.com/p4lang/tutorials/blob/27ffd3bfdff8bf43bdbbfd01f03e90c0057eb246/vm-ubuntu-20.04/root-release-bootstrap.sh#L42) would fail with this error: `Package 'p4lang-bmv2' has no installation candidate`. Some digging leads me to [this page](https://build.opensuse.org/package/show/home:p4lang/p4lang-bmv2) that shows the `p4lang-bmv2` deb package failed to build from a recent revision:
<img width="1377" alt="image" src="https://user-images.githubusercontent.com/5176695/153097624-c250ac37-391a-4d80-9396-c5fe1b7d5839.png">

I guess that's the reason why I cannot `apt-get install` it?

**Comment by rst0git** [comment]
@qobilidop Thank you for reporting this. I maintain the p4lang-bmv2 package in https://github.com/rst0git/p4lang-packages
I tried to rebuild it a few hours ago with the latest changes from GitHub but the build failed. I will update the package with a fix soon.

**Comment by rst0git** [comment]
@qobilidop I've updated all p4lang packages in https://build.opensuse.org/project/show/home:p4lang and the problem should be resolved now.

**Comment by qobilidop** [comment]
Thanks a lot!
