### ISSUE TITLE
[Question] Modify match-action table entry at runtime

### ISSUE THREAD

**Issue by CaribouW** [p4lang/behavioral-model#1095]
Hi~
I'm now looking for an opeation with the semantic `value = hash(key)`. In the P4 program, the match-action could be one solution after setting the table entries.
However, I want to change the table entries at runtime (dynamically add/remove those entries). The CLI could help (the `table_add` command) but I want to ask "is there a way to change entries in P4-16 ?" 
Furthermore, if we cannot change entries at runtime in P4-16, is there exist the operations in P4-16 that has the same(or similar) semantic as `hash` ?

**Comment by antoninbas** [comment]
I am not sure I understand your question, but in any case it doesn't seem related to bmv2 specifically, so I suggest you ask it on the P4 forum: https://forum.p4.org/
