### ISSUE TITLE
Simple_switch packet flooding

### ISSUE THREAD

**Issue by makrofag1** [p4lang/behavioral-model#1097]
Hi, 
I know it may be pretty simple question, but I really don't know how to move forward. I am using bmv2 simple_switches and ONOS as a controller. **The question is how can I program packet flooding mechanism, preferably without the use of controller**.
Thanks in advance.

**Comment by antoninbas** [comment]
You should use the multicast feature, which requires going through a runtime API and hence the use of a controller.
For information about multicast, I recommend reading:
* https://github.com/p4lang/behavioral-model/blob/main/docs/simple_switch.md
* https://p4.org/p4-spec/p4runtime/v1.3.0/P4Runtime-Spec.html#sec-packetreplicationengineentry
You can ask follow-up questions on the P4 forum: https://forum.p4.org/

If you are using ONOS, there may be a way to configure broadcast / flooding through ONOS, but you should ask the ONOS community.
