### ISSUE TITLE
Simple switch priority and queue id - possibly getting the same value?

### ISSUE THREAD

**Issue by italovalcy** [p4lang/behavioral-model#1099]
I'm using simple_switch and simple_switch_grpc (master branch from github) with the Multi Queueing support (as documented in https://github.com/nsg-ethz/p4-learning/tree/master/examples/multiqueueing), as well as some additional p4 code to do INT (in-band network telemetry). It called to my attention that `standard_metadata.priority` and `standard_metadata.qid` gets the same value, while they should be the complement of each other based on SSWITCH_PRIORITY_QUEUEING_NB_QUEUES, right? I mean, if I set the priority to 0 (lowest priority), simple_switch should set the queue to 7 (assuming the default value of 8 queues); whereas if I set the priority to 7, the queue id should be 0, right?

Looking into the code, it seems like `egress_buffers.push` is doing the calculation to convert from priority to queue_id (https://github.com/p4lang/behavioral-model/blob/main/targets/simple_switch/simple_switch.cpp#L415-L417), but then `egress_buffers.pop` assumes the parameter as the original priority value (https://github.com/p4lang/behavioral-model/blob/main/targets/simple_switch/simple_switch.cpp#L641-L642) and also does the same calculation (https://github.com/p4lang/behavioral-model/blob/main/targets/simple_switch/simple_switch.cpp#L668).

Sorry in advance if I understood something wrong, but maybe the `egress_buffers.pop` code should use the queue_id as it is, and benefit from the calculation already done by `egress_buffers.push`. What do you guys think? If you guys think it is okay, I can help by sending a PR for your evaluation. I did some tests using a local build of the docker image with that change and the behavior seems to be correct (while the INT metadata now reports the correct queue id).

```
diff --git a/targets/simple_switch/simple_switch.cpp b/targets/simple_switch/simple_switch.cpp
index d7171ae..d83373a 100644
--- a/targets/simple_switch/simple_switch.cpp
+++ b/targets/simple_switch/simple_switch.cpp
@@ -638,8 +638,8 @@ SimpleSwitch::egress_thread(size_t worker_id) {
     std::unique_ptr<Packet> packet;
     size_t port;
 #ifdef SSWITCH_PRIORITY_QUEUEING_ON
-    size_t priority;
-    egress_buffers.pop_back(worker_id, &port, &priority, &packet);
+    size_t qid;
+    egress_buffers.pop_back(worker_id, &port, &qid, &packet);
 #else
     egress_buffers.pop_back(worker_id, &port, &packet);
 #endif
@@ -665,7 +665,7 @@ SimpleSwitch::egress_thread(size_t worker_id) {
       if (phv->has_field("queueing_metadata.qid")) {
         auto &qid_f = phv->get_field("queueing_metadata.qid");
 #ifdef SSWITCH_PRIORITY_QUEUEING_ON
-        qid_f.set(SSWITCH_PRIORITY_QUEUEING_NB_QUEUES - 1 - priority);
+        qid_f.set(qid);
 #else
         qid_f.set(0);
 #endif
```

**Comment by antoninbas** [comment]
> It called to my attention that standard_metadata.priority and standard_metadata.qid gets the same value, while they should be the complement of each other based on SSWITCH_PRIORITY_QUEUEING_NB_QUEUES, right?

Not necessarily. The `standard_metadata.qid` value doesn't necessarily have to match the actual queue index used by the bmv2 implementation of priority queues.  Having `standard_metadata.priority == standard_metadata.qid` is perfectly fine IMO. The only guarantee would be that packets going through different queues have different qids and packets going through the same queue have the same qid. The value of a field like `standard_metadata.qid` is not completely clear to me anymore. Nowadays, it is really a bmv2-specific field, as it is not part of [v1model.p4](https://github.com/p4lang/p4c/blob/main/p4include/v1model.p4). As a result P4 users writing programs for the v1model architecture don't have access to the field unless they modify v1model.p4 themselves, which is pretty unusual.

Thanks for raising this question, but I don't see a reason to change the current implementation. That would break backwards-compatibility and in my view both the current implementation and your proposed change are equally valid. Any bijection would be equally valid actually, although not very intuitive...

Note that you can always transform the queue id in the P4 program directly if you want to change the value included in the INT header.

**Comment by italovalcy** [comment]
Hi @antoninbas, thanks for your comment.  Sounds good to me.
