### ISSUE TITLE
Digesting header type introduces extra bytes

### ISSUE THREAD

**Issue by zhangks98** [p4lang/behavioral-model#1104]
It looks like when I'm trying to `digest` a struct with a field of type `header` in the ingress pipeline, the control plane receives more bytes than what is defined in the header. Moreover the size of the extra bytes is vaired. For instance, digesting a header of length 10 bytes introduces 2 bytes extra, and digesting a 20 byte IPv4 header intrdocues 3 bytes extra.

This is especially frustrating when the send buffer contains more than one digest, or when the digest packet contains multiple headers, because I cannot just rely on the size of the header to parse the digest.

My suspicion is that the digest also contains the "hidden fields" of the `header` (as noted in the `header.cpp`), but the "hidden fields" are not stripped away during the digest as it is for `deparse`.
https://github.com/p4lang/behavioral-model/blob/27c235944492ef55ba061fcf658b4d8102d53bd8/src/bm_sim/headers.cpp#L277

**Comment by jafingerhut** [comment]
As a workaround, it should be better supported to use digests that are a struct where all fields of that struct have type `bit<W>`, and perhaps also `int<W>`, `bool`, or serializable enums (I haven't tried the last three myself to test), and avoid fields with a header type.

**Comment by zhangks98** [comment]
@jafingerhut Thanks for your advice! `struct` also seems to be fine. 
This issue arises when I'm trying to `digest` a custom `header` and the output is always off by a couple of bytes when parsing in the control plane. 
For now it's probably better stick with the aforementioned types because the size of the hidden fields in the header changes as I change the header and can even introduce more surprises. But it would be more convenient if `header` is stripped away of hidden fields when digested.

**Comment by jafingerhut** [comment]
Understood that it would be nice if what you tried worked.  I'm not recommending closing this issue as irrelevant, just trying to get you making progress in the mean time, since this limitation might not be high on anyone's priority list to fix for a while.

**Comment by antoninbas** [comment]
There are no hidden fields in digests AFAIK. But each field is padded to byte boundaries. So if you have a header, with 3 fields with respective types `bit<3>`,  `bit<7>` and `bit<6>`, the resulting digest will have 3 bytes (one for each field) and not 2 bytes (which is the header size).

The recommended way to consume digests would be through P4Runtime, which would take care of unmarshalling digests for you.
