### ISSUE TITLE
pop semantics: bottom fields not invalidated

### ISSUE THREAD

**Issue by dhankook** [p4lang/behavioral-model#111]
When popping from a header stack, the bottom-most fields that had nothing shifted into them should be invalidated, according to both language specs 1.0.2 and 1.1.0, but it appears this is not happening.  The attached files demonstrate code (pop_test.txt) that checks whether both elements of a two-element header stack are valid, both before and after popping one element from the header stack.  Nano output shows that even after the pop, both elements are valid, though only the first element should be valid.
[commands.txt](https://github.com/p4lang/behavioral-model/files/230707/commands.txt)
[nano_out.txt](https://github.com/p4lang/behavioral-model/files/230709/nano_out.txt)
[pop_test.txt](https://github.com/p4lang/behavioral-model/files/230712/pop_test.txt)

I performed this test after pulling the latest repos for behavioral-model and p4c-bm and performing all setup steps for each per the README for each repo.

**Comment by antoninbas** [comment]
Works with the following parser:
```
parser start {
  extract(ext[next]);
  extract(ext[next]);
  return ingress;
}
```
We need to figure out if David's code is valid and should run on bmv2.
Also, what about the following:
```
parser start {
  extract(ext[1]);
  return ingress;
}
```
Is it valid or does it contradict the definition of a header stack?

**Comment by dhankook** [comment]
Thanks.  With a refined example, I can trigger the behavior a different way: define two header stacks, ext and ext_cpy.  Extract to ext.  Copy all elements from ext to ext_cpy.  Pop from ext_cpy.  The bottom-most elements of ext_cpy will not be invalidated, but should, I believe.  I've attached revised code, commands, and nano output.
[copy_pop_test.txt](https://github.com/p4lang/behavioral-model/files/231089/copy_pop_test.txt)
[commands.txt](https://github.com/p4lang/behavioral-model/files/231091/commands.txt)
[nano_out.txt](https://github.com/p4lang/behavioral-model/files/231092/nano_out.txt)

**Comment by antoninbas** [comment]
That is exactly the same thing happening actually. You are copying headers to the stack without allocating space in the stack. If you add a call to `push(ext_copy, 2)` before the 2 calls to `copy_header`, you will be fine.
I have been investigating a little and I think that the next iteration of the P4 spec will describe the operational semantics of header stacks much more precisely than the current version. When this is released I will see if I can update bmv2.
In the mean time, I will say that as far as bmv2 is concerned, only the following operations can affect the size of a stack: `extract(stack[next])`, `push(stack, count)` and `pop(stack, count)`. Other operations may change header content but will not affect header validity in the stack.

**Comment by dhankook** [comment]
OK, makes sense; I hadn't been equating validity/non-validity with allocating space in the stack, because in my mind the space for the stack is allocated when it is declared.  And the copy_header semantics per the spec say the mere act of copying one valid header stack element to another makes the destination valid: "If the source header instance was invalid, the destination header instance becomes invalid; otherwise the destination will be valid after the operation."
I will adjust in the meantime.

**Comment by antoninbas** [comment]
Strict conformance with the P4_16 spec with regards to stack operational semantics has been enabled by default with release 1.11 (https://github.com/p4lang/behavioral-model/releases/tag/1.11.0). Pop will now shift the entire stack, instead of just the elements of the stack extracted in the parser. It is possible to revert back to the old behavior at compile time with the `--disable-WP4-16-stacks` configure flag.
