### ISSUE TITLE
Error Bmv2. Could not connect to thrift client on port 9090

### ISSUE THREAD

**Issue by freddysaav** [p4lang/behavioral-model#1112]
I am testing my P4tree algorithm (https://github.com/freddysaav/P4Tree) on a simple mininet network of a switch connected to two hosts with datasets UNI1 and UNI2 (https://pages.cs.wisc.edu/~tbenson/IMC10_Data.html). But sending it through tcpreplay gives me the error:  
![Captura de pantalla 2022-04-25 141958](https://user-images.githubusercontent.com/73503002/165159062-e440e2de-c5d9-4c44-ab98-c7a229171324.png)
I was able to solve this error by considerably reducing the speed or sending a small part of the pcap (20000 packets).
I would like to know if there is a possibility to solve this error to be able to send the complete pcap at its normal speed?

**Comment by antoninbas** [comment]
You have a pretty specific use case here, so I don't think I can help you with that little information.
It does seem that the bmv2 process for that switch may be crashing if the Thrift service cannot be reached any more. If you can provide a backtrace, I could look into it. BTW, I assume you are aware if bmv2 [performance limitations](https://github.com/p4lang/behavioral-model/blob/main/docs/performance.md).
