### ISSUE TITLE
query BMv2 switch  statistics form Control plane.

### ISSUE THREAD

**Issue by ahmedkh91** [p4lang/behavioral-model#1115]
Hi,

I Wanted to know how the controller can query BMv2 switch  statistics , and which statitcs exposes to the control plane .

Thanks

**Comment by rst0git** [comment]
@ahmedkh91 I would recommend reading through the P4Runtime tutorial and specification:
- https://github.com/p4lang/tutorials/tree/master/exercises/p4runtime
- https://p4.org/p4-spec/p4runtime/v1.3.0/P4Runtime-Spec.html

There is also an excellent talk from Antonin Bas on this topic: https://www.youtube.com/watch?v=YGdcZ6PYiUo

I hope this helps.
