### ISSUE TITLE
Assume/Assert error

### ISSUE THREAD

**Issue by OleksandrLetychevskyiIntel** [p4lang/behavioral-model#1120]
If we set assume/assert to bool value as shown here: `assume(false);` . 
We will get a message `simple_switch died with return code -6` and error `Assume error`.
But if we use an expression like this: `assume(h.eth_hdr.eth_type != 0x8847)`
That will not be an error. If I understand v1model.p4 correctly, and in particular the description of assume/assert, then it shouldn't be a mistake that we just set the bool value. 
I am attaching an example test that will cause an error
[bmv2_assume.p4.txt](https://github.com/p4lang/behavioral-model/files/8908599/bmv2_assume.p4.txt)
.

**Comment by OleksandrLetychevskyiIntel** [comment]
```
#include <v1model.p4>

header ethernet_t {
    bit<48> dst_addr;
    bit<48> src_addr;
    bit<16> eth_type;
}

header H {
    bit<8> a;
    bit<8> b;
    bit<16> c;
}

struct Headers {
    ethernet_t eth_hdr;
    H          h;
}

struct Meta {}

parser p(packet_in pkt, out Headers h, inout Meta meta, inout standard_metadata_t stdmeta) {
    state start {
        pkt.extract(h.eth_hdr);
        transition parse_h;
    }
    state parse_h {
        pkt.extract(h.h);
        transition accept;
    }
}

control vrfy(inout Headers h, inout Meta meta) {
  apply { }
}

control ingress(inout Headers h, inout Meta m, inout standard_metadata_t s) {
    apply {
        assume(false);
    }
}

control egress(inout Headers h, inout Meta m, inout standard_metadata_t s) {
    apply { }
}

control update(inout Headers h, inout Meta m) {
    apply { }
}

control deparser(packet_out pkt, in Headers h) {
    apply {
        pkt.emit(h);
    }
}

V1Switch(p(), vrfy(), ingress(), egress(), update(), deparser()) main;

```

**Comment by jafingerhut** [comment]
The documentation for the v1model architecture says that if you execute assert() or assume() and the expression evaluates to false, then the precise behavior is target-specific.  For simple_switch and simple_switch_grpc, the behavior is to print out a message about the expression that evaluated to false, and to abort the process.

If you change the `assert(false)` in your program to `assume(h.eth_hdr.eth_type != 0x8847)`, and then send in a packet with eth_type equal to 0x8847, you should also see simple_switch print a message and abort.

**Comment by OleksandrLetychevskyiIntel** [comment]
Oh I got it, thanks for the informative answer
