### ISSUE TITLE
Some question about bmv2 control plane implementation

### ISSUE THREAD

**Issue by RuSeKon** [p4lang/behavioral-model#1122]
I have my own implementation of the logic of some protocols (eg LACP). The control plane itself generates the necessary packets, how can I pass them to simple_switch? Is there a socket to connect? I apologize if the question was stupid.

**Comment by antoninbas** [comment]
Please refer to the P4Runtime specification: https://p4.org/p4-spec/p4runtime/main/P4Runtime-Spec.html
Search for Packet I/O and the `PacketOut` message.
Also check out https://github.com/antoninbas/p4runtime-go-client/tree/main/cmd/l2_switch for an example written in Golang.
BTW, such questions are better asked on the P4 forum.
