### ISSUE TITLE
modify_field semantics: takes effect even when src or dest parent header invalid

### ISSUE THREAD

**Issue by dhankook** [p4lang/behavioral-model#113]
According to the spec, modify_field should behave like this: "If the parent header instance of dest is not valid, the action has no effect. If value is a field reference and its parent header is not valid, the operation has no effect."

The attached files demonstrate that modify_field does have an effect when the parent header of dest is not valid, which by itself would not be a big problem (what's the harm in writing to an invalid header?), except that modify_field also has an effect when the parent header of the value parameter (the 'source') is not valid.

[modify_field_test.txt](https://github.com/p4lang/behavioral-model/files/237100/modify_field_test.txt)
[commands.txt](https://github.com/p4lang/behavioral-model/files/237101/commands.txt)
[nano_out.txt](https://github.com/p4lang/behavioral-model/files/237102/nano_out.txt)

**Comment by dhankook** [comment]
Sorry, I was sloppy with the versions of the modify_field_test and commands files; some incorrect table and action names are in the versions I supplied earlier.  Here are the corrected versions:
[modify_field_test.txt](https://github.com/p4lang/behavioral-model/files/237141/modify_field_test.txt)
[commands.txt](https://github.com/p4lang/behavioral-model/files/237142/commands.txt)

**Comment by antoninbas** [comment]
Hi David,
This is what I wrote on p4-dev: it is likely that a bunch of P4 capable switches won't be able to enforce these semantics for modify_field. Therefore, it is likely that the next iteration of the P4 spec will change these semantics to "undefined behavior".
Regarding bmv2, it would be in theory be possible to add an action primitive `modify_field_with_check`, which would only perform the assignment if a condition is valid. It could be used like this: `modify_field_with_check(hA.f1, hB.f1, valid(hA) and valid(hB))`. I am not sure it is worth the trouble though, as this would probably be only valid on bmv2. Note that the following is supported (and will be supported by the future spec): `modify_field(hA.f1, valid(hB) ? hB.f1 : 0)`. It does not do what you want though.
I think the bottom line is that a "conditional write" is not something you can get right now.

**Comment by dhankook** [comment]
Thanks for your response.  I would be the last one to argue for anything that will only be valid on bmv2, since one of the foundational points of my research is to provide a vehicle for P4 code portability across different switches.
I will adjust.

**Comment by antoninbas** [comment]
cool, let's hope that the new version of the spec comes out soon and addresses this issue

**Comment by antoninbas** [comment]
The proposed P4_16 spec states that this is undefined behavior (http://p4.org/wp-content/uploads/2016/12/P4_16-prerelease-Dec_16.html#sec-ops-on-hdrs): "The result of reading or writing a field in an invalid header is undefined. The result of reading an uninitialized header field is undefined — even if the header itself is valid.".
However, since bmv2 is meant first and foremost as a P4 debugging tool, we could consider having a "strict" mode that would print a warning when this happens, which is why I'm leaving this issue open for now.

**Comment by jafingerhut** [comment]
There is now an updated version 1.0.4 of the P4-14 spec published: https://p4lang.github.io/p4-spec/

It defines that if the source field of modify_field is part of an invalid header, then the read value is undefined.

Like v1.0.3 did, v1.0.4 still says that if the dest field is part of an invalid header, the modify_field operation has no effect.
