### ISSUE TITLE
Fail to clone

### ISSUE THREAD

**Issue by Benature** [p4lang/behavioral-model#1130]
In switch log, I can find that clone is called

```log
[07:31:30.430] [bmv2] [T] [thread 2293] [1410.0] [cxt 0] /home/test.p4(925) Primitive clone3(CloneType.E2E, E2E_CLONE_SESSION_ID, standard_metadata)
```
![image](https://user-images.githubusercontent.com/35028647/180173375-08cbb806-505f-41b3-82bd-edeb73f4639e.png)

The packet id is `1410.0`, the cloned packet id should be `1410.1` I think. However, I cannot find any other `1410.x` packets in log

![image](https://user-images.githubusercontent.com/35028647/180173650-7c9226a8-818f-4fe1-b0f2-0c232249562d.png)

Seems like that the clone is failed?

**Comment by Benature** [comment]
Seems like if I increase the value of set_queue_depth and set_queue_rate, then the problem is solved. How does the packet process rate calculate? If I clone a packet, will the new cloned packet count as another one?

**Comment by jafingerhut** [comment]
I do not know the BMv2 details well enough to tell you exactly why the clone failed in this particular case, but note that it is common that when sending packets to a traffic manager or packet buffer or queue of any kind, that it might be too full, and drop the packet.

If you want _guaranteed_ reliability that such operations succeed, you need to check with the vendor of the device if that is possible, and if so, how.

For example, enabling Ethernet PFC might be one way to ensure that a traffic manager never drops unicast packets of a particular class of service sent to the traffic manager, but it has consequences of introducing backpressure between the switch and the upstream device.
