### ISSUE TITLE
The debugger is not enabled on the switch

### ISSUE THREAD

**Issue by Johnny-dai-git** [p4lang/behavioral-model#1137]
Hi,

I am trying to use the p4 debugger with the simple_switch_grpc. However, it seems there are some problem.

I configure the bmv2 with --enable-debugger and also with thrift support.

It seems that I need to use the --debugger option to launch the switch before I runt he p4dbg.py.

However, there is no option for the simple_switch_grpc. 

When I try to run the simple_switch_grpc with the --debugger option. The switch can not be launched.

Meanwhile, if run the simple_switch_grpc without the --debugger option. The switch can run. 
However, the p4dbg.py shows "The debugger is not enabled on the switch".

What should I do to solve this problem ?

Best Regards

w

**Comment by antoninbas** [comment]
Not able to reproduce:
```bash
$ ./simple_switch_grpc --debugger --no-p4
Calling target program-options parser
Server listening on 0.0.0.0:9559
^C
$ 
```
After running `./configure --enable-debugger`, did you run `make` again? once for bmv2 (from the root of the repo) and once for simple_switch_grpc (from `targets/simple_switch_grpc`)?

**Comment by antoninbas** [comment]
**I am not able to reproduce this situation either**. Even without a clean build, the following steps work fine:
* `./configure --with-pi --enable-debugger`
*  `make`

These steps work as they should: running `configure` again with different flags will cause the `include/bm/config.h` header to be updated. And running `make` will ensure that whatever code needs to be recompiled will be recompiled (any code that depends on `include/bm/config.h`).

I am happy that you resolved your issue, but I wanted to clarify things here in case someone else thinks they have the same issue and ends up here.
