### ISSUE TITLE
Simple_switch_grpc set_crc_parameters

### ISSUE THREAD

**Issue by Johnny-dai-git** [p4lang/behavioral-model#1141]
Hi,

I have some question about setting the CRC polynomial parameters via CLI using Simple_Switch_Grpc.

Based on my understanding, if we are using the p4runtime to controller the Simple_Switch_Grpc instance then the server we are running on the switch are based on grpc. In such scenario, we are actually using the cli via p4dbg connected with thrift-port. 
If we are trying to configure the CRC polynomial parameters, it seems that we are configuring the CRC polynomial in the thrift server instead of the grpc server. Is that correct ?

In this case, what should we do to configure the CRC polynomial parameters or how we could it in terms of simple_switch_grpc?

Best Regards,

**Comment by antoninbas** [comment]
P4Runtime (gRPC) doesn't support configuring the CRC polynomials, so if you want to do that you need to enable the Thrift server in simple_switch_grpc: https://github.com/p4lang/behavioral-model/tree/main/targets/simple_switch_grpc#enabling-the-thrift-server
