### ISSUE TITLE
Can we obtain the switch configuration in the controller ?

### ISSUE THREAD

**Issue by Johnny-dai-git** [p4lang/behavioral-model#1143]
Hi,

I am wondering if it is possible the controller can get the switch configuration in the P4runtime ?

For example, is it possible for us to get the port:interface mapping relationship and the mac address of each interface from the p4runtime controller ?

Best Regards,

**Comment by jafingerhut** [comment]
It is possible to write P4 programs that run on BMv2 where there is no Ethernet headers in the packets, and/or where there are Ethernet headers, but the control plane software does not support configuring a mac address on interfaces.  I am not saying that either of these are common occurrences, but they are supported.  In such supported situations, it does not make sense for a controller to read a mac address configured on interfaces.  Thus the p4runtime API does not automatically support messages that read such values that might not exist.

I do not know whether there might be ways to read the port:interface mapping, but if so, they are not defined in the P4runtime API specification (at least not last time I looked at the P4Runtime API spec in detail, a year or two ago).
