### ISSUE TITLE
Can we reset/cleear the registers in simple_switch via thrift controller ?

### ISSUE THREAD

**Issue by Johnny-dai-git** [p4lang/behavioral-model#1144]
HI, 

I am trying to reset the registers in the simple_switch data plane via the thrift controller. After I did some research, I have the following two question or concerns.

Firstly, it seems that we can use the simple_switch_cli as the controller application to send cli command to clear/reset the registers array.  However, I do not whether the simple_switch_cli can achieve remote control or not. For example, if the simple_switch application is running on a bare metal machine and the simple_switch_cli control application is running on another bare metal machine. Is that possible the control application can still connect to the simple_switch and send commands to it ?

Secondly, If we are not using the simple_switch_cli,  can we implement an thrift controller (like p4runtime controller) to perform such operation?  Is there any write/reset register API we can use ?

Best Regards,

**Comment by jfingerh** [comment]
The Thrift message-based API implemented by the simple_switch (and also optionally the simple_switch_grpc process, if you enable Thrift API support when you compile the code) is a custom message-based API that to my knowledge is implemented by these processes, and no other P4 devices in the world.  There _might_ be other P4 devices that implement these Thrift APIs that I have not heard of, but this API is not any kind of standard, except perhaps a "de facto" standard by virtue of being implemented in the BMv2 code.

You can write any program you wish that sends and receives messages using these Thrift formats implemented by simple_switch.  I am not aware of any documentation of these message formats and behavior other than the code that implements them.  I have copied parts of simple_switch_CLI Python code into another program, and removed the CLI parts of it, at one point in the past.   That works fine if Python has sufficiently good performance for your use case, but it most likely will not support tens of thousands or more of table operations per second, as some lower-level APIs can implement.

**Comment by af12abw** [comment]
Last time I was able to use simple_switch_cli with --thrift-ip and
--thrift-port parameter to be able to control bmv2 remotely.

Not sure whether those parameters are still supported with the current
version.

Best regards,
