### ISSUE TITLE
Add port operation failed

### ISSUE THREAD

**Issue by Beau-Chen** [p4lang/behavioral-model#1146]
Hello, when I run the command `simple_switch -i 1@veth1-1 -i 2@veth2-1 --thrift-port 9090 --nanolog ipc:///tmp/bm-1-log.ipc lab1.json --log-console`, it occurred that:
```
Calling target program-options parser
[19:59:56.316] [bmv2] [D] [thread 51584] Set default default entry for table 'MyIngress.ipv4_lpm': MyIngress.drop - 
Adding interface veth1-1 as port 1
[19:59:56.317] [bmv2] [D] [thread 51584] Adding interface veth1-1 as port 1
[19:59:56.317] [bmv2] [E] [thread 51584] Add port operation failed
Adding interface veth2-1 as port 2
[19:59:56.317] [bmv2] [D] [thread 51584] Adding interface veth2-1 as port 2
[19:59:56.317] [bmv2] [E] [thread 51584] Add port operation failed
[19:59:56.317] [bmv2] [I] [thread 51584] Starting Thrift server on port 9090
[19:59:56.318] [bmv2] [I] [thread 51584] Thrift server was started
```

I saw from the issue #1055 , and then, I ran `ip link show`, it showed that:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: ens33: <BROADCAST,MULTICAST> mtu 1500 qdisc fq_codel state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:0c:29:ac:fa:7e brd ff:ff:ff:ff:ff:ff
    altname enp2s1
4: veth1-1@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 96:5d:8f:8f:ae:f4 brd ff:ff:ff:ff:ff:ff link-netns ns1
6: veth2-1@if5: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 7e:50:82:f3:1f:23 brd ff:ff:ff:ff:ff:ff link-netns ns2
```
It seems that I do have that two interface, so I don't know what's wrong with it.

I'm preciated for your reply.

**Comment by jafingerhut** [comment]
I do not know for sure, but can ask a couple of questions, and if they do not lead to the answer, perhaps someone else will see your question and know the cause.

1. Are you running simple_switch as the superuser, i.e. user 'root'?  If not, the process probably does not have permission to access those interfaces.

2. Even if you are running with proper permissions, the '@if3' and '@if5' in the output of the show command make me wonder whether you might be running Linux with multiplet network namespaces?  If so, that might affect which namespaces from which these interfaces are visible at all, even with superuser permissions.

**Comment by Beau-Chen** [comment]
Thanks for your detailed reply, it really helped me a lot and successfully solved my problem. 

The reason is the permission as I ran the command under user environment and I added `sudo` and then the problem solved.

Thanks again for your reply.

> I do not know for sure, but can ask a couple of questions, and if they do not lead to the answer, perhaps someone else will see your question and know the cause.
> 
> 1. Are you running simple_switch as the superuser, i.e. user 'root'?  If not, the process probably does not have permission to access those interfaces.
> 2. Even if you are running with proper permissions, the '@If3' and '@iF5' in the output of the show command make me wonder whether you might be running Linux with multiplet network namespaces?  If so, that might affect which namespaces from which these interfaces are visible at all, even with superuser permissions.
