### ISSUE TITLE
How to extract the IP header if the size of IP header is variant ?

### ISSUE THREAD

**Issue by Johnny-dai-git** [p4lang/behavioral-model#1148]
HI, 

While I am doing my project, I come out one question. The IP header size is variant because of the options field. 
However, before we run the p4 program, we need to define the IP header format and structure. And we will never know the size of the IP header until we extract the IP header in the parser. 

In such scenario, if the size of IP header is variant,  it is possible for us to extract the wrong header field in the sub-sequent headers.  What should we do to solve such problem ?

Best Regards,
Johnny

**Comment by antoninbas** [comment]
This is a question about the P4 language, not about the behavioral model.
I encourage you to read the P4 specification and ask your question on the P4 forum if you can't figure it out.
