### ISSUE TITLE
clone3 can not be used. And new function(clone_preserving_field_list) replace it. but there is not T data. Now, i want to clone in ingress and bring a metadata to the cloned packet. so what should i do for this? maybe an example? Thank you.

### ISSUE THREAD

**Issue by Janene-Li** [p4lang/behavioral-model#1149]

**Comment by jafingerhut** [comment]
Here is documentation for it, which you can find for that and most or all other extern functions in the v1model architecture, inside of the v1model.p4 include file: https://github.com/p4lang/p4c/blob/main/p4include/v1model.p4#L606-L640

I would recommend creating a clone of the https://github.com/p4lang/p4c repo, and grep'ing for the string clone_preserving in the testdata/p4_16_samples directory, if you want some test program examples.  They aren't necessarily tutorial quality, but there are examples in the context of test programs.
