### ISSUE TITLE
Registering Externs.

### ISSUE THREAD

**Issue by srihari39** [p4lang/behavioral-model#1153]
I've been trying to add a new extern, based on my usecase to the v1 model.
The C++ functionality is up and running but I'm actually confused on registering the externs.

There is no clear description on what's being happening with these.
`BM_REGISTER_EXTERN_W_NAME_METHOD`
`BM_REGISTER_EXTERN_W_NAME`
`BM_EXTERN_ATTRIBUTE_ADD`
`BM_REGISTER_EXTERN`
`BM_REGISTER_EXTERN_METHOD` and so.

It would be much helpful if someone leads me to the documentation if it is present somewhere.

+ Can we use C++ primitive types in the extern thing or we need to use the types defined in `<bm/bm_sim/extern.h>`

**Comment by antoninbas** [comment]
There is a comprehensive end-to-end example in https://github.com/p4lang/behavioral-model/tree/main/examples/custom_extern

**Comment by srihari39** [comment]
@antoninbas Hey man! thanks for the link.
I need to implement a Hash algorithm as an extern for our use case.

I implemented all the files and correspondingly changed all the frontends and backends on the p4c compiler on BMV2.

I couldn't run my algorithm after all.
Do we need to run any commands for rebuilding the compiler? I remember doing ```./configure``` as mentioned in [https://github.com/p4lang/behavioral-model/issues/697#issuecomment-565554370](url).

Also, I'm using p4 user and changes are made in vagrant user. I don't think so, there should be any issue. Please correct me if I'm wrong.

**Comment by srihari39** [comment]
@antoninbas , I'm getting errors while running make in extern_lib directory.

make: *** No rule to make target 'definition.so', needed by 'all'.  Stop. Is the error message to be precise.

**Comment by srihari39** [comment]
@antoninbas , I want to use char* in the cpp file instead of bm::Data, how can I do that.
Also, my return type is uint64_t, how can the p4 program support this?
