### ISSUE TITLE
simple_switch_grpc time synchronization

### ISSUE THREAD

**Issue by yhx-coder** [p4lang/behavioral-model#1154]
hi, I use simple_switch_grpc  to build a bmv2 switch topology.  I have read the `BMv2 timestamp implementation notes`
and I want to ask if I want to call a method like gettimeofday, how should I implement it? Is it in the [simple_switch.cpp](https://github.com/p4lang/behavioralmodel/blob/b7a5c105e5c21414ac07f7f2879b45c000ab2aa4/targets/simple_switch/simple_switch.cpp#L399) ,the same as simple_switch?

**Comment by jafingerhut** [comment]
You would need to look for occurrences of the metadata field names `ingress_global_timestamp` and `egress_global_timestamp`, and update the code there.  It appears there are only a few such places, as far as I know (I have not tried to make this change before):

ingress_global_timestamp: https://github.com/p4lang/behavioral-model/blob/main/targets/simple_switch/simple_switch.cpp#L265

egress_global_timestamp: https://github.com/p4lang/behavioral-model/blob/main/targets/simple_switch/simple_switch.cpp#L654

**Comment by yhx-coder** [comment]
> You would need to look for occurrences of the metadata field names `ingress_global_timestamp` and `egress_global_timestamp`, and update the code there. It appears there are only a few such places, as far as I know (I have not tried to make this change before):
> 
> ingress_global_timestamp: https://github.com/p4lang/behavioral-model/blob/main/targets/simple_switch/simple_switch.cpp#L265
> 
> egress_global_timestamp: https://github.com/p4lang/behavioral-model/blob/main/targets/simple_switch/simple_switch.cpp#L654

Thanks for your reply. So may I understand that there are no related files in the `targets/simple_switch_grpc` folder ? And I just need to find it in the simple_switch.cpp?
Best wishes.

**Comment by jfingerh** [comment]
As far as I know, the simple_switch_grpc process is compiled from nearly the same source code as the simple_switch process, except it also has some additional source files for a gRPC server for P4Runtime API.

That said, try it out and see what happens.  Add some debug print statements to your changes, and see whether they appear in the output or not when you run simple_switch_grpc.  Then you will know for sure, no matter what I write here :-)

**Comment by yhx-coder** [comment]
Thanks. I'll try it.
