### ISSUE TITLE
Add entries priority and life in CLI table dump

### ISSUE THREAD

**Issue by ccascone** [p4lang/behavioral-model#116]
When dumping a table using the CLI, it would be helpful to get also the following information for each entry:
- the priority
- the life in milliseconds (since it has been added)

**Comment by antoninbas** [comment]
I think people may be more interested in the time since the entry was last hit.

**Comment by ccascone** [comment]
Yes, that would be also useful

**Comment by antoninbas** [comment]
- priority was added a while ago
- under some conditions we also print some life information (see #191)
