### ISSUE TITLE
No python modules for bmv2 and PI

### ISSUE THREAD

**Issue by Cheb-Zh** [p4lang/behavioral-model#1163]
Hi,

I installed the bmv2 and PI, but there are no python modules for them neither in site-packages nor dist-packages under /usr/lib/python3. But the CLIs for both work well. Could someone give some solutions? Thanks!

**Comment by antoninbas** [comment]
If the CLI executables (installed on your system) work well, then the Python modules have been installed somewhere, and you just didn't find them. Location will vary based on distribution.

**Comment by jfingerh** [comment]
If you have an Ubuntu 18.04, 20,04, or 22.04 system, freshly installed, then one of the install scripts mentioned on this page I test to work every month: https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md

There are also links on that page to VM images that can be loaded into VirtualBox (and maybe other similar VM software, but I have not tested others to verify) with already-compiled open source P4 software installed on them.

**Comment by Cheb-Zh** [comment]
Thanks for your answers. I have removed the modules from the site-packages to dist-packages. But when I import them, a ModuleNotFoundError: No module named 'p4.tmp' occurs. Since I used VSCode, the path of this module is linked to the PI/proto/py_out/p4. 
![image](https://user-images.githubusercontent.com/93914673/204673439-65f200e7-f295-4b29-b203-b41cc4ce3bb4.png)

**Comment by jafingerhut** [comment]
I make no claims that there is any sane simple way to fix the system you
have right now, and I have no interest in helping you figure out how to
debug it.  Sorry.  It could take hours, or never work, and since I have a
tested script that works starting from a freshly installed system, I
recommend trying that out. It might save you time and frustration.

Andy

**Comment by Cheb-Zh** [comment]
Really thanks for your answers!!! I have moved the modules to the dist-packages and given the read permission. Now the modules can be imported. But the other error shows up **AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'**. I installed protobuf with version 3.18.1 which is mentioned in the[ PI repository](https://github.com/p4lang/PI).

**Comment by Cheb-Zh** [comment]
Got the solution from your hint. Thanks! The README of PI maybe should be updated. 
![image](https://user-images.githubusercontent.com/93914673/204678798-f70a8e6e-c45c-4bb9-8567-e58f37ba0dd2.png)

**Comment by jfingerh** [comment]
You can struggle with this for as long as you enjoy it :-)

If you have a freshly installed Ubuntu 18.04, 20.04, or 22.04 system, my scripts will get you there much faster.

**Comment by Cheb-Zh** [comment]
Hahaha, I have already struggled with it for two months. Currently I want to communicate with the switch via P4runtime API. That's why several problems raised up. But everything works well right now. I believe there will be the other problems as long as I get deeper into that. :) 
BTW I was impressed how quickly and you guys replied. Nice community here.
