### ISSUE TITLE
BMV2 forwarding delay measurement 

### ISSUE THREAD

**Issue by ugobright** [p4lang/behavioral-model#1164]
In Mininet, I want to measure forwarding delay  BMV2 as a function of Header parsing, Header field modification and Table. Similar works were done using the Moongen traffic generator on hardware-based P4 targets but the Moongen tool cannot be used in Mininet because it takes a time stamp from the hardware NIC
Is it a good idea to measure the difference between ingress and egress time stamps to be the switch forwarding delay? 
Any idea will be much appreciated

**Comment by Dscano** [comment]
Yes, in this way you obtain the hop latency, e.i the time needed to a packet to traverse the switch
