### ISSUE TITLE
Add enable-debugger option in 1sw_demo.py.

### ISSUE THREAD

**Issue by r12f** [p4lang/behavioral-model#1173]
I recently found 1sw_demo.py doesn't have any option for enabling the debugger, when trying to use bmv2. So I am wondering if we are interested in adding an extra option for enabling debugger in it?

I have found this thread discussing it, but I believe the issue creator didn't make the ask clear, so I would like to give it a try again.

If so, I have a quick prototype here. And I can send the PR out, if it makes sense:
- Commit: <https://github.com/r12f/behavioral-model/commit/f2185eb29085ffcd17a579e93b1b923b07c133b4>.
- Branch: <https://github.com/r12f/behavioral-model/commits/debugger>

## Result

And here is the result for running it:

### 1. Without `--enable-debugger` option:
```
sudo python "/home/r12f/code/p4/behavioral-model/mininet/1sw_demo.py" --behavioral-exe "/home/r12f/code/p4/behavioral-model/targets/simple_switch/simple_switch" --json "/home/r12f/code/p4/alioth-app/out/basic/basic.json"
*** Creating network
*** Adding hosts:
h1 h2
*** Adding switches:
s1
*** Adding links:
(h1, s1) (h2, s1)
*** Configuring hosts
h1 h2
*** Starting controller

*** Starting 1 switches
s1 Starting P4 switch s1.
/home/r12f/code/p4/behavioral-model/targets/simple_switch/simple_switch -i 1@s1-eth1 -i 2@s1-eth2 --thrift-port 9090 --nanolog ipc:///tmp/bm-0-log.ipc --device-id 0 /home/r12f/code/p4/alioth-app/out/basic/basic.json
P4 switch s1 has been started.
```

And pydbg cannot be connected, which is expected:
```
sudo "/home/r12f/code/p4/behavioral-model/tools/p4dbg.py" --thrift-port 9090
Could not connect to any of [('127.0.0.1', 9090)]
Could not connect to thrift client on port 9090
Make sure the switch is running and that you have the right port
error: Recipe `bm-dbg` failed on line 159 with exit code 1

```

### 2. With `--enable-debugger` option:

We will see the `--debugger` option appended in the end.

```
sudo python "/home/r12f/code/p4/behavioral-model/mininet/1sw_demo.py" --behavioral-exe "/home/r12f/code/p4/behavioral-model/targets/simple_switch/simple_switch" --json "/home/r12f/code/p4/alioth-app/out/basic/basic.json" --enable-debugger
*** Creating network
*** Adding hosts:
h1 h2
*** Adding switches:
s1
*** Adding links:
(h1, s1) (h2, s1)
*** Configuring hosts
h1 h2
*** Starting controller

*** Starting 1 switches
s1 Starting P4 switch s1.
/home/r12f/code/p4/behavioral-model/targets/simple_switch/simple_switch -i 1@s1-eth1 -i 2@s1-eth2 --thrift-port 9090 --nanolog ipc:///tmp/bm-0-log.ipc --device-id 0 /home/r12f/code/p4/alioth-app/out/basic/basic.json --debugger
P4 switch s1 has been started.
```

And pydbg will be able to run too:
```
sudo "/home/r12f/code/p4/behavioral-model/tools/p4dbg.py" --thrift-port 9090
[sudo] password for r12f:
'--socket' not provided, using ipc:///tmp/bmv2-0-debug.ipc (obtained from switch)
Obtaining JSON from switch...
Done
Connecting to the switch...
Connection established
Prototype for Debugger UI
P4DBG: 
```

**Comment by antoninbas** [comment]
I don't have a strong objection to this change if you want to submit a PR, but I will note that the debugger is not enabled by default in the simple_switch binary, so if someone wants to use this flag, they need to ensure that they build bmv2 with debugger support.

**Comment by r12f** [comment]
thank you! and you are absolutely correct. let me update the command description with the enablement mentioned and send out the PR.

**Comment by antoninbas** [comment]
Done in #1174
