### ISSUE TITLE
simple_switch_grpc: "At index 0: UNKNOWN, 'Error when adding match entry to target'" when using errors/enums as key

### ISSUE THREAD

**Issue by fruffy** [p4lang/behavioral-model#1178]
Trying to run tests for the following program using PTF and P4Runtime I am seeing the error: 
```
At index 0: UNKNOWN, 'Error when adding match entry to target'
```
https://github.com/p4lang/p4c/blob/main/testdata/p4_16_samples/issue1062-1-bmv2.p4

It looks like enums are not supported, either by PI or the BMv2 back end. If I change the type of `error my_err` to `bit<8>` I can pass the test. 

From my reading of https://p4.org/p4-spec/p4runtime/main/P4Runtime-Spec.html#sec-enum-serializable-enum-and-error it looks like simple integer keys should be sufficient? 

[issue1062-1-bmv2.json.txt](https://github.com/p4lang/behavioral-model/files/10492401/issue1062-1-bmv2.json.txt)
[issue1062-1-bmv2.p4info.txt](https://github.com/p4lang/behavioral-model/files/10492402/issue1062-1-bmv2.p4info.txt)
[issue1062-1-bmv2.py.txt](https://github.com/p4lang/behavioral-model/files/10492404/issue1062-1-bmv2.py.txt)
[switchlog.txt](https://github.com/p4lang/behavioral-model/files/10492405/switchlog.txt)
[testlog.txt](https://github.com/p4lang/behavioral-model/files/10492406/testlog.txt)

**Comment by antoninbas** [comment]
Safe (i.e. non-serializable) enums and errors are not supported because they don't have a known bitwidth.
This is specified in https://p4.org/p4-spec/p4runtime/main/P4Runtime-Spec.html#sec-known-limitations-of-current-p4runtime-version.

**Comment by fruffy** [comment]
Thanks for the quick clarification!

**Comment by jafingerhut** [comment]
I don't know if I wrote that test program off hand (sorry, being lazy and not checking right now), but I suspect I have written at least one or two test programs for p4c with error or enum as table key field or action parameter, when exercising the edges of what is possible in p4c even if it was not supported by the P4Runtime API.  Some day the P4Runtime API may be extended to explicitly support such things, but it would be at least many months before that is likely to be spec'ed and implemented.
