### ISSUE TITLE
How to setup the interface while using bmv2 to take over the physical interface 

### ISSUE THREAD

**Issue by Johnny-dai-git** [p4lang/behavioral-model#1186]
HI, I am trying to use a bmv2 instance to take over the physical interface on a bare metal machine.

In order to do so, I know I need to flush the ip address of the interface by using the following command:

sudo ip addr flush dev <interface_name>

However, do I need to shut the interface down by using the command before I launch the bmv2 instance ? 

sudo ip link set dev <interface_name> down

After the bmv2 instance launched, I run the same command to bring up int corresponding interface. 

The purpose of using such command is trying to avoid the packet to go through the ip stack from the host and let the packet go into the bmv2 instance directly. 

Is it a right procedure ? 

Best Regards,
Johnny

**Comment by antoninbas** [comment]
Removing the IP address should be good enough.
Typically, you want to disable some L4 offloads as well.

I see that we discussed this with you in the past already: https://github.com/p4lang/behavioral-model/issues/1172

**Comment by 10212** [comment]
I guess I get questions like, "let the packet go into the bmv2 instance directly."
It is not practical to go directly through -interface 0@physical interface though (at least it failed in my experiment) because bmv2 works in user space, so I thought it would be a good idea to connect veth to the physical interface via br
The views expressed are my own

**Comment by antoninbas** [comment]
Connecting directly to physical interfaces work fine. Raw sockets are meant to let userspace applications have "direct" access to network packets.
The things to look out for are:
- running bmv2 as root (or with the right capabilities)
- interfaces should not have IP addresses
- offloads (checksum offloads) usually need to be disabled
