### ISSUE TITLE
Incorrect output when using HashAlgorithm.crc16_custom consecutive times

### ISSUE THREAD

**Issue by giancarloliver** [p4lang/behavioral-model#1192]
Dear all,

We have been using the bmv2 simple_switch to test some research proposals that explore the hash operation with the HashAlgorithm.crc16_custom algorithm.

Our most recent proposal needs to perform consecutive hash operations, but we are getting an incorrect output from the hash function if a custom CRC polynomial is configured.

For reproducing the issue, we extended a basic calculator from P4 tutorials: [GitHub - giancarloliver/hash-custom: hash-custom 2](https://github.com/giancarloliver/hash-custom)

This tutorial shows a simple example that reproduces the issue when executing consecutive hash operations with custom CRC.

Could you please help us to understand this behavior? Are we using the hash extern in an incorrect manner? Is it a bug in the simple_switch library?

**Comment by antoninbas** [comment]
Looking at your repository, it's not clear what the issue is?
Why do you expect `1#6` and `1%6` to produce the same value?

There are 3 independent CRCs in your P4 program: 1 in `operation_crc` and 2 in `operation_dcrc`. Looking at the generated bmv2 JSON file, their names are `calc`, `calc_0` and `calc_1`. `calc` is the one used in `operation_crc`.

In your README, you write that you configured the custom CRC with this command:
```
RuntimeCmd: set_crc16_parameters calc 0x002b 0x0 0x0 false false
```

However, if you meant to configure all 3 (independent) CRCs using the same polynomials, you would need to run 3 commands:
```
RuntimeCmd: set_crc16_parameters calc 0x002b 0x0 0x0 false false
RuntimeCmd: set_crc16_parameters calc_0 0x002b 0x0 0x0 false false
RuntimeCmd: set_crc16_parameters calc_1 0x002b 0x0 0x0 false false
```

**Comment by giancarloliver** [comment]
'%' The result is a hash using OperandA as input, as described below in the operation_crc() function. OperandB is not used. It performs a single hashing operation.

action operation_crc() {

    bit<32> nbase=0;
    bit<64> ncount=4294967296*2;
    bit<32> nselect;
    bit<32> ninput = hdr.p4calc.operand_a;

    hash(nselect,
    HashAlgorithm.crc16_custom,
    nbase,
    {ninput},ncount);

    send_back(nselect);
}

'#' The result is a hash using OperandA as input, as described below in the operation_dcrc function. It performs two consecutive hash operations. OperandB is used as input for the first hash operation and OperandA is used as input for the second hash operation. The two hash operations must be independent.

action operation_dcrc() {

    bit<32> nbase=0;
    bit<64> ncount=4294967296*2;
    bit<32> nselect;
    bit<32> ninput = hdr.p4calc.operand_b;

    hash(nselect,
    HashAlgorithm.crc16_custom,
    nbase,
    {ninput},ncount);

    bit<32> nbase2=0;
    bit<64> ncount2=4294967296*2;
    bit<32> nselect2;
    bit<32> ninput2 = hdr.p4calc.operand_a;

    hash(nselect2,
    HashAlgorithm.crc16_custom,
    nbase2,
    {ninput2},ncount2);

    send_back(nselect2);
}

The operation_crc() and operation_dcrc() functions perform the same operation as OperandA. The difference is that in operation_dcrc() OperandA is executed after OperandB causing the bug.

**Comment by giancarloliver** [comment]
> Looking at your repository, it's not clear what the issue is? Why do you expect `1#6` and `1%6` to produce the same value?
> 
> There are 3 independent CRCs in your P4 program: 1 in `operation_crc` and 2 in `operation_dcrc`. Looking at the generated bmv2 JSON file, their names are `calc`, `calc_0` and `calc_1`. `calc` is the one used in `operation_crc`.
> 
> In your README, you write that you configured the custom CRC with this command:
> 
> ```
> RuntimeCmd: set_crc16_parameters calc 0x002b 0x0 0x0 false false
> ```
> 
> However, if you meant to configure all 3 (independent) CRCs using the same polynomials, you would need to run 3 commands:
> 
> ```
> RuntimeCmd: set_crc16_parameters calc 0x002b 0x0 0x0 false false
> RuntimeCmd: set_crc16_parameters calc_0 0x002b 0x0 0x0 false false
> RuntimeCmd: set_crc16_parameters calc_1 0x002b 0x0 0x0 false false
> ```

'%' The result is a hash using OperandA as input, as described below in the operation_crc() function. OperandB is not used. It performs a single hashing operation.

action operation_crc() {

bit<32> nbase=0;
bit<64> ncount=4294967296*2;
bit<32> nselect;
bit<32> ninput = hdr.p4calc.operand_a;

hash(nselect,
HashAlgorithm.crc16_custom,
nbase,
{ninput},ncount);

send_back(nselect);
}

'#' The result is a hash using OperandA as input, as described below in the operation_dcrc function. It performs two consecutive hash operations. OperandB is used as input for the first hash operation and OperandA is used as input for the second hash operation. The two hash operations must be independent.

action operation_dcrc() {

bit<32> nbase=0;
bit<64> ncount=4294967296*2;
bit<32> nselect;
bit<32> ninput = hdr.p4calc.operand_b;

hash(nselect,
HashAlgorithm.crc16_custom,
nbase,
{ninput},ncount);

bit<32> nbase2=0;
bit<64> ncount2=4294967296*2;
bit<32> nselect2;
bit<32> ninput2 = hdr.p4calc.operand_a;

hash(nselect2,
HashAlgorithm.crc16_custom,
nbase2,
{ninput2},ncount2);

send_back(nselect2);
}

The operation_crc() and operation_dcrc() functions perform the same operation as OperandA. The difference is that in operation_dcrc() OperandA is executed after OperandB causing the bug.

**Comment by antoninbas** [comment]
That clarifies things for me, but could you confirm that you configured both hashes in the same way (with the same polynomials) in `operation_crc()` and `operation_dcrc()`? I want to emphasize that all your `hash` calls in P4 are implemented using _independent_ hash objects in bmv2. `HashAlgorithm.crc16_custom` does not identify a unique hash object. So please make sure that `calc` and `calc_1` are configured using the same polynomials. If you confirm that both were configured the same using the runtime_CLI, I'll take a deeper look.

**Comment by giancarloliver** [comment]
> '%' The result is a hash using OperandA as input, as described below in the operation_crc() function. OperandB is not used. It performs a single hashing operation.
> 
> action operation_crc() {
> 
> bit<32> nbase=0; bit<64> ncount=4294967296*2; bit<32> nselect; bit<32> ninput = hdr.p4calc.operand_a;
> 
> hash(nselect, HashAlgorithm.crc16_custom, nbase, {ninput},ncount);
> 
> send_back(nselect); }
> 
> '#' The result is a hash using OperandA as input, as described below in the operation_dcrc function. It performs two consecutive hash operations. OperandB is used as input for the first hash operation and OperandA is used as input for the second hash operation. The two hash operations must be independent.
> 
> action operation_dcrc() {
> 
> bit<32> nbase=0; bit<64> ncount=4294967296*2; bit<32> nselect; bit<32> ninput = hdr.p4calc.operand_b;
> 
> hash(nselect, HashAlgorithm.crc16_custom, nbase, {ninput},ncount);
> 
> bit<32> nbase2=0; bit<64> ncount2=4294967296*2; bit<32> nselect2; bit<32> ninput2 = hdr.p4calc.operand_a;
> 
> hash(nselect2, HashAlgorithm.crc16_custom, nbase2, {ninput2},ncount2);
> 
> send_back(nselect2); }
> 
> The operation_crc() and operation_dcrc() functions perform the same operation as OperandA. The difference is that in operation_dcrc() OperandA is executed after OperandB causing the bug.

'%' The result is a hash using OperandA as input, as described below in the operation_crc() function. OperandB is not used. It performs a single hashing operation.

action operation_crc() {

bit<32> nbase=0;
bit<64> ncount=4294967296*2;
bit<32> nselect;
bit<32> ninput = hdr.p4calc.operand_a;

hash(nselect,
HashAlgorithm.crc16_custom,
nbase,
{ninput},ncount);

send_back(nselect);
}

'#' The result is a hash using OperandA as input, as described below in the operation_dcrc function. It performs two consecutive hash operations. OperandB is used as input for the first hash operation and OperandA is used as input for the second hash operation. The two hash operations must be independent.

action operation_dcrc() {

bit<32> nbase=0;
bit<64> ncount=4294967296*2;
bit<32> nselect;
bit<32> ninput = hdr.p4calc.operand_b;

hash(nselect,
HashAlgorithm.crc16_custom,
nbase,
{ninput},ncount);

bit<32> nbase2=0;
bit<64> ncount2=4294967296*2;
bit<32> nselect2;
bit<32> ninput2 = hdr.p4calc.operand_a;

hash(nselect2,
HashAlgorithm.crc16_custom,
nbase2,
{ninput2},ncount2);

send_back(nselect2);
}

The operation_crc() and operation_dcrc() functions perform the same operation as OperandA. The difference is that in operation_dcrc() OperandA is executed after OperandB causing the bug.

**Comment by giancarloliver** [comment]
> Thanks for the detailed steps to reproduce the behavior you found. I have not tried to reproduce it yet myself.
> 
> I would not be surprised if it is a bug in the simple_switch C++ code implementing the hash function, but have not tried to get to the root cause. The implementation of the hash function should simply be that the return value is a pure function of the input parameters and the configured polynomial.
> 
> When you are going for bit-exact expectation of outputs from a CRC, there may be differences in the implementation and what you expect in terms of things like this:
> 
> * which order the input bits are fed into the CRC, e.g. "most significant bit first" vs. "least significant bit first"
> * how the bit order of the CRC polynomial is configured
> * whether there is some modification applied to the final CRC value before it is returned, e.g. bit reversing
> 
> Have you attempted to check what your assumptions are on what you are expecting, vs. what you are getting back?

'%' The result is a hash using OperandA as input, as described below in the operation_crc() function. OperandB is not used. It performs a single hashing operation.

action operation_crc() {

bit<32> nbase=0;
bit<64> ncount=4294967296*2;
bit<32> nselect;
bit<32> ninput = hdr.p4calc.operand_a;

hash(nselect,
HashAlgorithm.crc16_custom,
nbase,
{ninput},ncount);

send_back(nselect);
}

'#' The result is a hash using OperandA as input, as described below in the operation_dcrc function. It performs two consecutive hash operations. OperandB is used as input for the first hash operation and OperandA is used as input for the second hash operation. The two hash operations must be independent.

action operation_dcrc() {

bit<32> nbase=0;
bit<64> ncount=4294967296*2;
bit<32> nselect;
bit<32> ninput = hdr.p4calc.operand_b;

hash(nselect,
HashAlgorithm.crc16_custom,
nbase,
{ninput},ncount);

bit<32> nbase2=0;
bit<64> ncount2=4294967296*2;
bit<32> nselect2;
bit<32> ninput2 = hdr.p4calc.operand_a;

hash(nselect2,
HashAlgorithm.crc16_custom,
nbase2,
{ninput2},ncount2);

send_back(nselect2);
}

The operation_crc() and operation_dcrc() functions perform the same operation as OperandA. The difference is that in operation_dcrc() OperandA is executed after OperandB causing the bug.

**Comment by giancarloliver** [comment]
> No entanto, se você pretende configurar todos os 3 CRCs (independentes) usando os mesmos polinômios, precisará executar 3 comandos:

**Comment by giancarloliver** [comment]
> That clarifies things for me, but could you confirm that you configured both hashes in the same way (with the same polynomials) in `operation_crc()` and `operation_dcrc()`? I want to emphasize that all your `hash` calls in P4 are implemented using _independent_ hash objects in bmv2. `HashAlgorithm.crc16_custom` does not identify a unique hash object. So please make sure that `calc` and `calc_1` are configured using the same polynomials. If you confirm that both were configured the same using the runtime_CLI, I'll take a deeper look.

As recommended, I set up all 3 (independent) CRCs using the same polynomials, running the 3 commands:
RuntimeCmd: set_crc16_parameters calc 0x002b 0x0 0x0 false false
RuntimeCmd: set_crc16_parameters calc_0 0x002b 0x0 0x0 false false
RuntimeCmd: set_crc16_parameters calc_1 0x002b 0x0 0x0 false false

And both operations returned the same result, working as expected:
1#6
43
> 1%6
1%6
43
> 

Thank you very much!

**Comment by giancarloliver** [comment]
> That clarifies things for me, but could you confirm that you configured both hashes in the same way (with the same polynomials) in `operation_crc()` and `operation_dcrc()`? I want to emphasize that all your `hash` calls in P4 are implemented using _independent_ hash objects in bmv2. `HashAlgorithm.crc16_custom` does not identify a unique hash object. So please make sure that `calc` and `calc_1` are configured using the same polynomials. If you confirm that both were configured the same using the runtime_CLI, I'll take a deeper look.

As recommended, I set up all 3 (independent) CRCs using the same polynomials, running the 3 commands:
RuntimeCmd: set_crc16_parameters calc 0x002b 0x0 0x0 false false
RuntimeCmd: set_crc16_parameters calc_0 0x002b 0x0 0x0 false false
RuntimeCmd: set_crc16_parameters calc_1 0x002b 0x0 0x0 false false

And both operations returned the same result, working as expected:
> 1#6
1#6
43
> 1%6
1%6
43

Thank you very much!
