### ISSUE TITLE
Connection VM to P4 simple_switch

### ISSUE THREAD

**Issue by MOGZEM** [p4lang/behavioral-model#1193]
Greetings!

I am trying to test the bandwidth of a switch using iperf using two VMs. But I am faced with the problem that the tcp connection is not established, although the SYN packet passes the switch and gets to the desired port. At the same time, the ping command works perfectly.

What am I doing wrong? And have there been cases that someone tried to connect virtual machines to simple_switch?

Host is Ubuntu 20.04, VM is Ubuntu 20.04 in Virtual Machine Manager. 
simple_switch is launched with simple_router.json, all connections are made via veth interfaces.

**Comment by dpinedaa** [comment]
Hello @MOGZEM. I'm also experiencing an issue something similar to yours. I'm using simple_switch between VMs, and the connections are also made via veth interfaces. I can ping, but nothing with the transport layer is properly working. Have you fixed your problem yet?
