### ISSUE TITLE
Installation error with thrift

### ISSUE THREAD

**Issue by febinpsunny** [p4lang/behavioral-model#1211]
Running into the following error when running make:
/home/febinps/behavioral-model/src/bm_runtime/server.cpp:122: undefined reference to `apache::thrift::concurrency::PosixThreadFactory::PosixThreadFactory(bool)'

I have already installed thrift0.11 and nanomsg5. I have installed behavior-model on another system with these settings before but now, when trying a fresh install in a new system (Ubuntu22 on WSL2 on Windows 10, the other system was the same) I am running into this error. Am I missing some libraries?

**Comment by antoninbas** [comment]
`PosixThreadFactory` was removed in Thrift 1.0, so my guess is that you may have a discrepancy between the version of the Thrift compiler (`thrift` program) and the version of the Thrift libraries.

Unless you need to modify bmv2, you should consider installing it using the available package for Ubuntu: https://github.com/p4lang/behavioral-model#installing-packaged-versions-of-bmv2

**Comment by febinpsunny** [comment]
I am planning on modifying the simulator. So I need to have the capability to compile from source. So any help in resolving this will be greatly appreciated.

**Comment by febinpsunny** [comment]
I checked my current thrift version using "thrift -version" which returned "Thrift version 0.11.0".

**Comment by febinpsunny** [comment]
running `ldconfig -v | grep thrift` yielded the following
```
(from <builtin>:0 and <builtin>:0)
        libthrift-0.11.0.so -> libthrift.so
        libthriftnb-0.11.0.so -> libthriftnb.so
        libthriftz-0.11.0.so -> libthriftz.so
        libthriftqt5-0.16.0.so -> libthriftqt5.so
        libthrift-0.16.0.so -> libthrift.so
        libbmpdfixedthrift.so.0 -> libbmpdfixedthrift.so.0.0.0
/sbin/ldconfig.real: /lib/x86_64-linux-gnu/ld-linux-x86-64.so.2 is the dynamic linker, ignoring

        libthriftnb-0.16.0.so -> libthriftnb.so
        libsimpleswitch_thrift.so.0 -> libsimpleswitch_thrift.so.0.0.0
        libthriftz-0.16.0.so -> libthriftz.so
        libpsaswitch_thrift.so.0 -> libpsaswitch_thrift.so.0.0.0
```

The available thrift libraries seem to match the thrift program version.

**Comment by febinpsunny** [comment]
I removed everything from the WSL, restarted the installation process, relying on the installation scripts provided for thrift and nanomsg. Still running into thrift error, as follows:

```
make[4]: Entering directory '/home/febinps/behavioral-model/targets/l2_switch/learn_client'
depbase=`echo learn_client.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I. -I../../..  -I../../../include                           -I../../../include                           -isystem../../../third_party/jsoncpp/include                           -isystem../../../third_party/spdlog -I../../../thrift_src/gen-cpp  -Wall -Wextra -pthread -g -O2 -MT learn_client.o -MD -MP -MF $depbase.Tpo -c -o learn_client.o learn_client.cpp &&\
mv -f $depbase.Tpo $depbase.Po
/bin/bash ../../../libtool  --tag=CXX   --mode=link g++ -Wall -Wextra -pthread -g -O2   -o learn_client learn_client.o ../../../src/bm_apps/libbmapps.la -lboost_thread -lpcap -lgmp -lnanomsg
libtool: link: g++ -Wall -Wextra -pthread -g -O2 -o .libs/learn_client learn_client.o  ../../../src/bm_apps/.libs/libbmapps.a /home/febinps/behavioral-model/thrift_src/.libs/libruntimestubs.so -lthrift -lboost_thread -lpcap -lgmp -lnanomsg -pthread
/usr/bin/ld: ../../../src/bm_apps/.libs/libbmapps.a(learn.o): in function `bm_apps::LearnListener::start()':
/home/febinps/behavioral-model/src/bm_apps/learn.cpp:103: undefined reference to `apache::thrift::transport::TSocket::TSocket(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:380: learn_client] Error 1
make[4]: Leaving directory '/home/febinps/behavioral-model/targets/l2_switch/learn_client'
make[3]: *** [Makefile:494: all-recursive] Error 1
make[3]: Leaving directory '/home/febinps/behavioral-model/targets/l2_switch'
make[2]: *** [Makefile:393: all-recursive] Error 1
make[2]: Leaving directory '/home/febinps/behavioral-model/targets'
make[1]: *** [Makefile:465: all-recursive] Error 1
make[1]: Leaving directory '/home/febinps/behavioral-model'
make: *** [Makefile:395: all] Error 2
```

**Comment by febinpsunny** [comment]
This seems to be an issue with dependency conflicts between p4c and bmv2. If I install bmv2 at first, and then p4c it works. I use the packaged version of p4c, which from the dump installs thrift-compiler using apt-get, which I'm guessing causes the version mismatch?
