### ISSUE TITLE
 Can BMv2 interfaces be bound to virtual network cards of two virtual machines? How should this be done specifically?

### ISSUE THREAD

**Issue by asfdd3** [p4lang/behavioral-model#1222]
Can BMv2 interfaces be bound to virtual network cards of two virtual machines? How should this be done specifically?

**Comment by jafingerhut** [comment]
I would recommend that if you have "how to" kinds of questions like this, that are not bugs or issues with the BMv2 software switch, that you ask them on this web site, rather than creating Github issues: https://forum.p4.org
