### ISSUE TITLE
How to track fileds of metadata with p4dbg?

### ISSUE THREAD

**Issue by Klaymini** [p4lang/behavioral-model#1233]
Hi, I'm confused that it didn't work when I tried to set a watch point on a filed of metadata. My input and output are as follows. `udp_Rp` is one of fileds in metadata.

```bash
P4DBG: w udp_Rp
Error: Unknow field name 'udp_Rp'
```

How do I fix it?

**Comment by jafingerhut** [comment]
I agree that your question appears quite specific to the behavioral-model repo and its implementation.  I would suggest that. you might also want to ask your question in the web forum at https://forum.p4.org, as you might find a somewhat larger audience of people reading the questions, who may know the answer (I have not used p4dbg myself, so do not know).

**Comment by Klaymini** [comment]
> I agree that your question appears quite specific to the behavioral-model repo and its implementation. I would suggest that. you might also want to ask your question in the web forum at https://forum.p4.org, as you might find a somewhat larger audience of people reading the questions, who may know the answer (I have not used p4dbg myself, so do not know).

Thank you very much. I would like to share this question on the forum.
