### ISSUE TITLE
Queue metadata with multiqueue

### ISSUE THREAD

**Issue by carlos-hfm** [p4lang/behavioral-model#1258]
Hi! I am working with 3 priority queues on simple_switch, and I am trying to collect InBand Network Telemetry data, about the occupation of these queues. But when I am generating traffic in only one queue (for example queue 0), the enq_qdepth and deq_qdepth values of all three queues are getting high, while the other queues (1 and 2) are supposed to be empty.

I am also checking deq_timedelta, and in this case only in queue 0 I am getting high values (it is the correct behavior I think).

Other thing that I noticed is that when I am generating traffic in 2 queues, the queue depth values are getting higher than 64 (I set the size with set_queue_depth command)

So I have a question: the enq_qdepth and deq_qdepth metadata are about the number of packets adding all the queues in total? Or something is wrong here?

**Comment by antoninbas** [comment]
Yes, in the simple_switch implementation it seems that the qdepth is measured across all priority queues for a given port:

https://github.com/p4lang/behavioral-model/blob/a8e2947aefe660d11df53ff44854d112d545db38/targets/simple_switch/simple_switch.cpp#L411-L412

https://github.com/p4lang/behavioral-model/blob/a8e2947aefe660d11df53ff44854d112d545db38/include/bm/bm_sim/queueing.h#L616-L635

Notice how the first variant is called by simple_switch

**Comment by carlos-hfm** [comment]
Thank you @antoninbas. I changed the _simple_switch.cpp_ code to use the second _size_ method variant and recompiled bmv2. It seems that now I can get the depth of only specific priority queues using the enq_qdepth metadata.

But it is strange for me that the standard behavior implemented is to return the depth of all priority queues of the egress port together, instead of the specific queue that the packet is crossing.
