### ISSUE TITLE
How to access the packet data from extern function in c++ code?

### ISSUE THREAD

**Issue by rupesh-chiluka-marvell** [p4lang/behavioral-model#1269]
```
void custom_extern_function() {
    std::cout << "packet data: " << get_packet().data() << std::endl;
}

BM_REGISTER_EXTERN_FUNCTION(custom_extern_function);
```

When I try to compile the above command, I got the below compilation error:

```
error: ‘get_packet’ was not declared in this scope
   50 |     std::cout << "packet data: " << get_packet().data() << std::endl;
      |                                     ^~~~~~~~~~
```

For extern type and its methods, I can access packet data fine. But not able to access the packet inside the extern function.

**Comment by rupesh-chiluka-marvell** [comment]
The `ExternType` class has the `get_packet()` method. 
Custom extern classes inherit `ExternType` class so they can access `get_packet().`

**Comment by antoninbas** [comment]
This PR has more context: https://github.com/p4lang/behavioral-model/pull/604
It introduced support for extern functions. Prior to that, it was only primitives and extern types.
The discussion in the PR corroborates my earlier statement that primitives should be preferred over extern functions.

**Comment by rupesh-chiluka-marvell** [comment]
Ok . Thanks for the reply :)
