### ISSUE TITLE
bmi_port_interface_add

### ISSUE THREAD

**Issue by underriver** [p4lang/behavioral-model#166]
when I run ./behavioral-model ,I got an error like this .who can tell me why?
bmi_port_interface_add(port_mgr, veth_name, n_veth, pcap_filename): ERROR -1 at main.c:430

**Comment by antoninbas** [comment]
I am not sure why you raised the issue in this repo. AFAIK, there is no binary called `behavioral-model` here. In any case, this type of error can arise 1) when you haven't created the veth interfaces (by running `sudo ./tools/veth_setup.sh` or 2) when you are not running the switch model as `sudo`.
