### ISSUE TITLE
simple_switch crashes when any ternary operator's  conditional expression involves action params

### ISSUE THREAD

**Issue by shouxi** [p4lang/behavioral-model#174]
Hi, this issue comes with [#14 at HLIR](https://github.com/p4lang/p4-hlir/issues/14). 
the simple_switch target crashes if I feed it with the hand-corrected json file. 
[simple_router.json.txt](https://github.com/p4lang/behavioral-model/files/416781/simple_router.json.txt)

**Comment by antoninbas** [comment]
The hand-generated JSON is not correct. `"runtime_data"` is not correct, the correct type in expressions is `"local"`.
