### ISSUE TITLE
bmv2 crashed during TCP connections

### ISSUE THREAD

**Issue by MountainShan** [p4lang/behavioral-model#184]
Hi all, 

I am trying to implement a P4 program about modifying TCP fields. 
However when I start the bmv2 and set up a TCP connection by using iperf, there is an error shows up. 
`lt-simple_switch: ../../include/bm/bm_sim/stateful.h:116: const bm::Register& bm::RegisterArray::operator[](size_t) const: Assertion `idx < size()' failed.`
My topology like this : 
+------+      +------------+       +------+
|   PC1  | - - -|   P4 Switch | - - - |  PC2  |
+------+      +------------+       +------+ 

Does anyone have same problem?

Best regards, 
Peter

**Comment by antoninbas** [comment]
This looks like you are simply trying to access a P4 register array out of bounds.

**Comment by MountainShan** [comment]
Thank you, Antoninbas. 
I reconfigured the P4 program and now it works.
