### ISSUE TITLE
Cascading Switch Instances

### ISSUE THREAD

**Issue by cw299** [p4lang/behavioral-model#197]
Is there any way to run and interconnect multiple instances of the software switch? I want to simulate a network that consists of two or more switch instances.

**Comment by antoninbas** [comment]
Yes, we do this in Python using Mininet. You can see an example under the `mininet` directory of this repository: https://github.com/p4lang/behavioral-model/tree/master/mininet
And here are the instructions to run the example: https://github.com/p4lang/behavioral-model#integrating-with-mininet
