### ISSUE TITLE
Behavioral model does not build with the latest version of thrift

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/behavioral-model#198]
g++ -DHAVE_CONFIG_H -I. -I../.. -DBMLOG_DEBUG_ON -DBMLOG_TRACE_ON -DBMELOG_ON -I../../include -isystem../../third_party/jsoncpp/include -isystem../../third_party/spdlog -I./thrift/src/ -I./gen-cpp -Wall -Werror -Wextra -g -O2 -std=c++11 -MT gen-cpp/bm/simple_switch_constants.lo -MD -MP -MF gen-cpp/bm/.deps/simple_switch_constants.Tpo -c gen-cpp/bm/simple_switch_constants.cpp -o gen-cpp/bm/simple_switch_constants.o >/dev/null 2>&1
gen-cpp/bm/SimpleSwitch.cpp: In member function ‘uint32_t sswitch_runtime::SimpleSwitch_mirroring_mapping_add_args::write(apache::thrift::protocol::TProtocol*) const’:
gen-cpp/bm/SimpleSwitch.cpp:66:10: error: ‘class apache::thrift::protocol::TProtocol’ has no member named ‘incrementRecursionDepth’
   oprot->incrementRecursionDepth();

**Comment by ChrisDodd** [comment]
I think that means that you have an old version of thrift installed that
the build is picking up instead of the newer (needed) version.  When I've
run into this before, I've fixed it with:

sudo apt-get remove -y python-thrift
sudo pip install thrift

basically, it seems that the version of thrift installed by apt-get is old,
AND takes priority over any other version installed.  So you need to make
sure to uninstall it.  The version installed by pip seems to be correct,
but is in a lower-priority location (/usr/local vs /usr I believe).

**Comment by antoninbas** [comment]
This is not a problem with the Python code I think.
I believe you may have a mismatch between your Thrift compiler version (which generates the C++ code from the IDL file) and your Thrift library version. Other people have had this problem, according to SO: http://stackoverflow.com/questions/36070720/tprotocol-does-not-contain-a-definition-for-incrementrecursiondepth.

**Comment by mbudiu-vmw** [comment]
The behavioral model repo has a link to the thrift sources https://github.com/apache/thrift, which I installed.

This API in thrift has been changed relatively recently:
https://github.com/apache/thrift/blob/master/lib/cpp/src/thrift/protocol/TProtocol.h

The method incrementRecursionDepth has been replaced with two methods incrementInputRecursionDepth and *Output*.

**Comment by antoninbas** [comment]
Please check your compiler and library versions and make sure that they match:
```
antonin@antonin-torpille:~$ thrift -version
Thrift version 0.9.2
antonin@antonin-torpille:~$ ldconfig -p | grep thrift
	libthriftz-0.9.2.so (libc6,x86-64) => /usr/local/lib/libthriftz-0.9.2.so
	libthriftnb-0.9.2.so (libc6,x86-64) => /usr/local/lib/libthriftnb-0.9.2.so
	libthrift_c_glib.so.0 (libc6,x86-64) => /usr/local/lib/libthrift_c_glib.so.0
	libthrift_c_glib.so (libc6,x86-64) => /usr/local/lib/libthrift_c_glib.so
	libthrift-0.9.2.so (libc6,x86-64) => /usr/local/lib/libthrift-0.9.2.so
```
Version `0.9.3` shoudl work as well.
When installing Thrift, I would recommend that you install a released version, not the top of tree.
