### ISSUE TITLE
Activating Queue Function failed

### ISSUE THREAD

**Issue by MountainShan** [p4lang/behavioral-model#207]
Hi all, 

I  am trying to active the queue module in bmv2 by using the method mentioned from this link. 
(http://lists.p4.org/pipermail/p4-dev_lists.p4.org/2016-May/000314.html)
>The simple_switch bmv2 target supports multiple egress queues per port with
>strict priority scheduling (only algorithm available at this time).
>However, this cannot be activated at runtime yet. You will need to
>uncomment this line in the simple_switch target implementation and
>recompile:
>https://github.com/p4lang/behavioral-model/blob/master/targets/simple_switch/simple_switch.h#L42.

However, when I used command "make check" and its failed. The error log is down below: 

> FAIL: test_packet_redirect
>../../../test-driver: line 107: 19708 Aborted                 "$@" > $log_file 2>&1
>FAIL: test_truncate
>../../../test-driver: line 107: 19737 Aborted                 "$@" > $log_file 2>&1
>FAIL: test_swap
>../../../test-driver: line 107: 19766 Aborted                 "$@" > $log_file 2>&1
>FAIL: test_queueing

Then I ran 2 sample codes (meter and simple nat), but it also failed and showed this error message: 
> terminate called after throwing an instance of 'std::out_of_range'
>    what():     _Map_base::at

How can I enable the queuing function in bmv2?

**Comment by antoninbas** [comment]
By activating the queuing module, you change the behavior of the switch, so I would recommend not running the unit tests as some may fail.
That being said, the exception you are getting points to an "undefined field" in the P4 program. The email you are referencing here explains that you need to define the `intrinsic_metadata.priority` field in your P4 program. By default the sample P4 programs in the tutorial repo do not define this field and you will need to add it.
For example, if I look at `meter.p4`, I see the following definition for `intrinsic_metadata_t`:
```
header_type intrinsic_metadata_t {
    fields {
        mcast_grp : 4;
        egress_rid : 4;
        mcast_hash : 16;
        lf_field_list: 32;
    }
}
```
You need to update the list of fields to include `intrinsic_metadata.priority : 8`. You can then write to this field in the `ingress` control flow to set the priority of the packet.
