### ISSUE TITLE
Why simple_switch target doesn't have p4 file?

### ISSUE THREAD

**Issue by hamkuu** [p4lang/behavioral-model#215]
I studied the targets directory in this repository.

And I notice that l2_switch target has a file named "l2_switch.p4", 

simple_router target also has a file named "simple_router.p4".

But simple_switch target does not have any p4 file.

Any one can explain this? Thanks in advance.

**Comment by antoninbas** [comment]
In this email to the p4-dev mailing list, I give some details about the 3 different bmv2 target architectures: http://lists.p4.org/pipermail/p4-dev_lists.p4.org/2016-June/000380.html
In a nutshell, bmv2 is a library that can be used to implement multiple (all?) P4 architectures. Although the original P4 spec describes a single architecture (referred to as the abstract switch model), different P4-programmable hardware may expose different architectures. An architecture can support a different number of parsers, different fixed function blocks (e.g. packet replication engine), a single or multiple pipelines... An architecture can support an infinite number of P4 programs, but each program needs to be aware of the architecture it was written for and programs may not be portable across architectures.
In this repo, we provide 3 example architectures implemented with the bmv2 library: simple_switch, simple_router and l2_switch. simple_switch implements the abstract switch model in the p4 spec. The other 2 are really meant purely as examples and should not be of use to most people.
We have many P4 programs that can run on simple_switch (e.g. all of these: https://github.com/p4lang/tutorials). But these programs won't run on the simple_router and l2_switch architectures. For the sake of completeness, I create one P4 program for each of these 2 architectures and I named them after the architecture they are meant to run on -once again it does not mean that they are the only P4 programs able to run on these architectures. For example, you will notice that the simple_router architecture only has one pipeline vs 2 for simple_switch (ingress + egress).
