### ISSUE TITLE
Failed to 'fed' json file to bmv2

### ISSUE THREAD

**Issue by hamkuu** [p4lang/behavioral-model#216]
I was following the instruction on [behavioral-model-repository](https://github.com/p4lang/behavioral-model#behavioral-model-repository), and built the code and passed the unit tests. But I had problems on running P4 program, i.e. the step where json file being 'fed' to bmv2:

    sudo ./simple_switch -i 0@<iface0> -i 1@<iface1> <path to JSON file>

For simplicity to show the problem, I typed as follows:

    sudo simple_switch

and the command line didn't recognized this command

Then I tried:

    make install
    sudo simple_switch

Output:

    simple_switch: error while loading shared libraries: libruntimestubs.so.0: cannot open shared object file: No such file or directory

Interestingly, I also download the VM provided in [2015 P4 Bootcamp Labs Guild](http://p4.org/wp-content/uploads/2015/12/Nov-2015-P4-Bootcamp-Labs-Guide.pdf), and under the directory ~/bmv2, which seems to be very similar to [behavioral-model-repository](https://github.com/p4lang/behavioral-model#behavioral-model-repository), I tried:

    sudo simple_switch

it immediately prompted for usage info:

    Usage: SWITCH_NAME [options] <path to JSON config file>
    Options:
    (neglected for simplicity)

It seems that I got some installation issue on my original VM, but what did I miss?

Also, how "simple_switch" being recognized as a command?

Besides, before running the 'feeding', veth pairs should be setup in advance, my veth pair setup is done through the script tools/veth_setup.sh. But the instruction doesn't mention about it, which can be tricky for beginners. Additionally related information is recommended.

**Comment by antoninbas** [comment]
you may need to run `sudo ldconfig` after `sudo make install`
