### ISSUE TITLE
Add entries at run time without using runtime CLI(with c++)

### ISSUE THREAD

**Issue by Raymondma-public** [p4lang/behavioral-model#222]
I am implementing a protocol that learns how to forward packet when communicating with other switches. Therefore, I need to add entries at run time without using runtime CLI. 
But I have some problem when implementing this.
I have started trying to make the action work for ECMP example first. Then, implement my own protocol next.

Eg. I want to do the following action in C++
	table_add send_frame rewrite_mac 1 => 00:aa:bb:00:00:00

I have tried to use C++ to implement this.
I have tried to view the source code and tried writing the following code.

```
//Connect to thrift
	boost::shared_ptr<TTransport> tsocket(new TSocket("localhost", 9090));
	boost::shared_ptr<TTransport> transport(new TBufferedTransport(tsocket));
	boost::shared_ptr<TProtocol> protocol(new TBinaryProtocol(transport));
	boost::shared_ptr<TMultiplexedProtocol> standard_protocol(
			new TMultiplexedProtocol(protocol, "standard"));
	bm_client = boost::shared_ptr<bm_runtime::standard::StandardClient>(
			new bm_runtime::standard::StandardClient(standard_protocol));
	assert(bm_client);
	transport->open();

```
```

//Set table entries data
	runtime::BmMatchParam match_param;
	match_param.type = runtime::BmMatchParamType::type::EXACT;
	runtime::BmMatchParamExact match_param_exact;
	match_param_exact.key = std::string("1");
	match_param.__set_exact(match_param_exact);
	runtime::BmAddEntryOptions options;
	std::vector<std::string> my_action_data = { std::string("00:aa:bb:00:00:00") };
```
```
//Add to entry
	bm_client->bm_mt_add_entry(0, "send_frame", { match_param },"rewrite_mac", std::move(my_action_data), options);

```

But when my codes call to add table entry. The following exception occurs,

```
[22:49:27.508] [bmv2] [T] [thread 3784] bm_table_add_entry
[22:49:27.508] [bmv2] [E] [thread 3784] Error when trying to add entry to table 'send_frame'
terminate called after throwing an instance of 'bm_runtime::standard::InvalidTableOperation'
  what():  Default TException.
```

I am not sure how should I implement this.
Would any one please give me some tips for solving this problem?
Or are there any better ways to do this?
Thank you very much.

**Comment by antoninbas** [comment]
You are almost there. But why would you assume that `"00:aa:bb:00:00:00"` is a valid format for the action data?
I believe that if you use `std::string("\x00\xaa\xbb\x00\x00\x00", 6)` instead, it should work.
Actually, you probably need to fix your match key parameter as well. Maybe try `std::string("\x01", 1)` instead.
All of those (match params, action args) expect binary strings, so you should write all of them in hexadecimal like I did.
Let me know if it is still not working for you, or close the issue if this solves your problem.
Thanks

**Comment by Raymondma-public** [comment]
It works for me. Thank you very much.
But if the string size is not correct, the same problem(InvalidTableOperation) will occur.
eg. 
I need `std::string("\x00\x01", 2) `
If I entered` std::string("\x01", 1)`, it will say InvalidTableOperation.

Thank you very much for your answer again.
