### ISSUE TITLE
Scheduler// Timer

### ISSUE THREAD

**Issue by Raymondma-public** [p4lang/behavioral-model#229]
I need a "very quick" and regularly looping timer for doing some actions continuous calculation.

The following is the properties I need:
- doing things **regularly** and **accurately** 
(eg .do somethings exactly every 100 microsecond (1.0 × 10-6 seconds )without pausing between)
(Could be slower if not possible)

I have read the documents ,but seems that what I need cannot be fulfilled with "Match + action" model.
Is there any solution to do this with P4?

As I did not find solution, I have tried creating a thread in C++ to loop very quickly. Every iteration can be done in 100 microsecond. But seems that due to CPU scheduling, the process/ thread will be paused for while. 

For example:

```
For every 100 microsecond
      do action
```

```
For evey second
      Display number of time of action

```
Normally I should get about 10000 times action, but due to CPU scheduling, I only get about 4 thousand times action.

Could I have any better way to do it in P4?

**Comment by antoninbas** [comment]
There is no P4 programmable construct (yet?) to achieve what you want.
Feel free to modify the simple_switch C++ code in any way you need (or better still create your own target). However, I am pretty sure that your goal to execute a task every 100 microseconds in this software switch is not very realistic. I think 10ms would be more achievable. It's difficult to say precisely without looking at the kind of code you have in mind.

**Comment by chkim4142** [comment]
Some P4 targets can have a programmable packet generator, and I presume you can achieve something similar to what you're looking for with that.

**Comment by antoninbas** [comment]
Closing this, please re-open if further information required
