### ISSUE TITLE
See more logging detail of switches in mininet

### ISSUE THREAD

**Issue by Raymondma-public** [p4lang/behavioral-model#230]
I know that I can see logs of switches in mininet with following tool.
`./tools/nanomsg_client.py  --thrift-port 9094`

However,for switches in mininet,  is there any way to show more details like `--log-console` with directly running the switch in localhost?
eg1.
What command is added with parameters
```
RuntimeCmd: Adding entry to exact match table send_frame
match key:           EXACT-00:01
action:              rewrite_mac
runtime data:        00:0c:00:00:00:12


```
eg2.
What data is being looked up
```
[08:42:32.275] [bmv2] [D] [thread 25179] [499.0] [cxt 0] Looking up key:
* ipv4.dstAddr        : 0a000001
```

eg3.
What condition is being matched
```
[08:42:32.275] [bmv2] [D] [thread 25179] [499.0] [cxt 0] Dumping entry 0
Match key:
* ipv4.dstAddr        : LPM       0a000001/32
Index: group(0)
Group members:
  mbr 1: set_nhop - a000101,1,
  mbr 2: set_nhop - a000201,2,


```

**Comment by antoninbas** [comment]
You can edit the Python code used to start a new switch instance in Mininet (see for example https://github.com/p4lang/behavioral-model/blob/master/mininet/p4_mininet.py#L81). You can add `--log-console` and look at the file to which simple_switch's output is being redirected. A better solution may be to use `--log-file <your file name>` along with `--log-flush`.
