### ISSUE TITLE
How learn_client work with l2_switch in mininet?

### ISSUE THREAD

**Issue by dannyxx001** [p4lang/behavioral-model#252]
I try to run l2_switch in mininet, and I add the entries which are commands.txt in l2_switch's directory.

I read the learn_client.cpp, and I think it should add the entry when it get the message from  `generate_digest`, right? But I don't see any new entry except the default entries when using Runtime CLI with `table_dump`.

The switch is triggered in mininet by the following instructions.
../bmv2/targets/l2_switch/l2_switch -i 1@s1-eth1 -i 2@s1-eth2 --thrift-port 9090 --nanolog ipc:///tmp/bm-0-log.ipc --device-id 0 l2_switch.json --debugger --log-console --log-level debug --notifications-addr ipc:///tmp/bmv2-0-notifications.ipc

Should learn_client be additionally triggered in another terminal? By the way, I had tried this, but it was still not working.

And I also don't understand why the `MAC_LEARN_RECEIVER` is defined `1` in l2_switch.p4 and why there is a comment  `// discared receiver for now` in primitives.cpp. Does it mean the receiver is not working here?

Can anyone explain?
Thank you.

**Comment by antoninbas** [comment]
You need to run mininet like this: `sudo python mininet/1sw_demo.py --behavioral-exe targets/l2_switch/l2_switch --json targets/l2_switch/l2_switch.json --mode l2`. Notice the `--mode l2`.
You also need to start the `learn_client` in a separate terminal after running `commands.txt`:
```
cd targets/l2_switch/
./runtime_CLI < commands.txt
sudo ./learn_client/learn_client
```
Please notice how I am running the `learn_client` as `sudo`.
After starting everything and starting a ping in the mininet CLI, I can see new entries being added to the `smac` and `dmac` tables.
Please make sure that you are using the latest version of bmv2. When I ran the code today in response to your issue, I realized that the `l2_switch.json` file was too old and was causing the runtime CLI to crash so I updated it by running the latest version of the p4c-bm compiler.

**Comment by dannyxx001** [comment]
Thank you for your reply. I had followed your suggestion. And it's working now. I thought the difference is that I didn't use `sudo` to run learn_client.
Don't worry about the version. I always use the latest version of bmv2 to run switch and p4c-bm to compile p4 program. So I didn't face the crash problem when using runtime CLI.
Could you please tell me where is the code that the switch send message to receiver when doing `generate_digest`? I only saw primitives.cpp which define `generate_digest` class. And I think the learn_client is using `ipc:///tmp/bmv2-0-notifications.ipc` to receive message, right? But I didn't find the code sending the message through `ipc:///tmp/bmv2-0-notifications.ipc`.
Thank you.

**Comment by antoninbas** [comment]
This is the `simple_switch` code which executes the learn engine (i.e. add the learned sample for the current packet to the learning buffer): https://github.com/p4lang/behavioral-model/blob/master/targets/simple_switch/simple_switch.cpp#L370
This is the learn engine implementation: https://github.com/p4lang/behavioral-model/blob/master/src/bm_sim/learning.cpp#L45. It accumulates samples until the buffer is full (or a timeout is reached) then broadcast them on the notifications channel.

**Comment by dannyxx001** [comment]
Thank you very much. I think it's enough for me to do my work.
