### ISSUE TITLE
Could not connect to localhost:9090 in simple_router

### ISSUE THREAD

**Issue by realmanhw** [p4lang/behavioral-model#255]
The first time I ran **simple_route**, it workd well. But after I restart the machine, when running **_run_demo.bash_**, it worked, then I try to run **_run_cli.bash_**, there is a  error

> - root@iZ2zec18vwwtn1ixn4g4dqZ:/home/p4factory/targets/simple_router# ./run_cli.bash
> Using default thrift server and port localhost:9090
> Traceback (most recent call last):
>   File "../../cli/pd_cli.py", line 677, in <module>
>     main(sys.argv[1:])
>   File "../../cli/pd_cli.py", line 665, in main
>     pd_cli = PdCli(p4_name, thrift_client_module, thrift_server, port)
>   File "../../cli/pd_cli.py", line 35, in __init__
>     self._thrift_client = pd_thrift_client.ThriftClient(self._module, thrift_server, port, self._p4_name)
>   File "/home/p4factory/cli/pd_thrift_client.py", line 55, in __init__
>     self.setup(hostname, port)
>   File "/home/p4factory/cli/pd_thrift_client.py", line 77, in setup
>     self._transport.open()
>   File "/usr/local/lib/python2.7/dist-packages/thrift/transport/TTransport.py", line 149, in open
>     return self.__trans.open()
>   File "/usr/local/lib/python2.7/dist-packages/thrift/transport/TSocket.py", line 101, in open
>     message=message)
> _**thrift.transport.TTransport.TTransportException: Could not connect to localhost:9090**_

And when I tried other port like 22222, 11111, there is the same error **Could not connect to……**

Then, I ran **./behavioral-model**, there is also a error

> - No PD RPC server address specified, using 127.0.0.1:9090
>   No listener specified, switch will run in standalone mode
>   P4 Program:  simple_router
>   Starting RPC server on port 9090
>   bmi_port_interface_add(port_mgr, veth_name, n_veth, pcap_filename): **ERROR -1** at       main.c:430root@iZ2zec18vwwtn1ixn4g4dqZ:/home/p4factory/targets/simple_router# 

Does someone know how to deal with it?

**Comment by antoninbas** [comment]
See https://github.com/p4lang/p4factory/issues/178
