### ISSUE TITLE
Problem when cloning packet

### ISSUE THREAD

**Issue by Raymondma-public** [p4lang/behavioral-model#257]
** I need to decide egress port for cloned packet.( More precisely, I want to create a new packet but seems that P4 do not have this feature currently.)**

I am trying to implement as following code:
P4:
`clone_ingress_pkt_to_egress(user_metadata.egress_port,copy_to_ingress_fields);`

Commands:
for all switch port
```
mirroring_add 1 1
mirroring_add 2 2
mirroring_add 3 3
...

```

This error occur:
`Semantic error: Error when calling primitive clone_ingress_pkt_to_egress (expeditus_stage1_tor_target_compute_egress_port -> compute_and_set_later_forward_egress -> clone_ingress_pkt_to_egress) in file /home/raymondma/behavioral-model3/targets/ecmp/solution_2/p4src/simple_router.p4 at line 363: argument 0 has type field, but formal clone_spec has type integer value`

I think it want an integer instead of field. But how could I implement what I want? To clone packet to dynamic egress port?

**Comment by antoninbas** [comment]
This is not a bmv2 issue, the error you are getting is from the compiler.
According to the p4-spec, the `clone_spec` parameter is either an immediate value or action data from a table, and the compiler simply enforces this. I don't know why the spec has such a restriction on the `clone_spec` parameter, but I can try to find out.

**Comment by Raymondma-public** [comment]
I tried to add "field" to clone_ingress_pkt_to_egress in primitives.json from P4 compiler and seems that it can solve the problem

**Comment by antoninbas** [comment]
It was decided to update primitives.json to accept field references in clone primitives (https://github.com/p4lang/p4-hlir/commit/49a0759410a7cc327d158e77a4503aa52c5b410f). I am not sure when the P4_14 spec will be updated to reflect this.
