### ISSUE TITLE
Assigning to bit slices is a no-op

### ISSUE THREAD

**Issue by vikramnathan** [p4lang/behavioral-model#266]
Using the following code for the egress pipeline:
```
register<bit<32>>(32w2) debug;
action test() {
    bit<32> val = 8;
    bit<32> finalVal = 0;
    debug.write(0, val);
    finalVal[31:0] = val;
    debug.write(1, finalVal);
}
apply {
    test();
}
```
Observed output after running a packet through:
```
$> $BM/tools/runtime_CLI.py
RuntimeCmd: register_read debug 0
debug[0]=  8
RuntimeCmd: register_read debug 1
debug[1]=  0
```
Expected output:
```
$> $BM/tools/runtime_CLI.py
RuntimeCmd: register_read debug 0
debug[0]=  8
RuntimeCmd: register_read debug 1
debug[1]=  8
```
This seems to indicate that `finalVal` isn't modified when `finalVal[31:0]` is assigned to.

Reference code:
[test_bug3.json.txt](https://github.com/p4lang/behavioral-model/files/711824/test_bug3.json.txt)
[test_bug3.p4.txt](https://github.com/p4lang/behavioral-model/files/711823/test_bug3.p4.txt)

**Comment by antoninbas** [comment]
This seems to be an issue with the `p4c-bm2-ss` compiler (i.e. an invalid JSON is produced). Please find an issue for the p4c repo instead.
