### ISSUE TITLE
Learn_Client Exception 

### ISSUE THREAD

**Issue by Wasdns** [p4lang/behavioral-model#287]
Hi, @antoninbas 

Thanks to your help last week, I connected the learn_client successfully using the right notification sockets. It's very kind of you.

Last week, I created a demo and started mininet which has two switches and four hosts, using the thrift port 22222 and 22223. The topo logic showed below:

![mininet_2sw_2host](https://cloud.githubusercontent.com/assets/16839162/22875095/ccd0e8cc-f204-11e6-94a2-2ebf04f2d6bf.png)

The topo logic INFO: 

```
IP: 10.0.0.i 
MAC: 00:00:00:00:00:0i 
(i = 1, 2, 3, 4)
```

I'm using the l2_switch.p4 for my software switch. 

Then I apply the commands to the two switches. The content of commands.txt:

```
table_set_default smac mac_learn
table_set_default dmac broadcast

mc_mgrp_create 1
mc_node_create 0 1
mc_node_create 1 2
mc_node_create 2 3
mc_node_create 3 4
mc_node_associate 1 0
mc_node_associate 1 1
mc_node_associate 1 2
mc_node_associate 1 3
```

It made `pingall` successfully but not very steady. I used the cmds below to check the entries of table `dmac` in s1 and s2.

```
RuntimeCmd: table_dump dmac
==========
TABLE ENTRIES
==========
Dumping default entry
Action entry: broadcast - 
==========
```

It's empty. Then I started the learn clients of the switches by using the right notification sockets. I opened two terminals, one for s1 and the other one for s2, running the `./learn_client`.

Then I started `pingall` in the mininet:

```
mininet> pingall
*** Ping: testing ping reachability
h1 -> h2 h3 h4 
h2 -> h1 h3 h4 
h3 -> h1 h2 h4 
h4 -> h1 h2 h3 
*** Results: 0% dropped (12/12 received)
```

Unexceptedly, the two learn_client closed after throwing the exception:

s1:

```
I received 6 samples
Calling callback function
CB with 6 samples
ingress port is 1
ingress port is 2
ingress port is 3
terminate called after throwing an instance of 'bm_runtime::standard::InvalidTableOperation'
  what():  Default TException.
Aborted (core dumped)
```

s2:

```
I received 6 samples
Calling callback function
CB with 6 samples
ingress port is 3
ingress port is 3
ingress port is 1
ingress port is 3
terminate called after throwing an instance of 'bm_runtime::standard::InvalidTableOperation'
  what():  Default TException.
Aborted (core dumped)
```

Then I check the entries of dmac:

s1:

```
RuntimeCmd: table_dump dmac
==========
TABLE ENTRIES
**********
Dumping entry 0x0
Match key:
* ethernet.dstAddr    : EXACT     000000000001
Action entry: forward - 01
**********
Dumping entry 0x1
Match key:
* ethernet.dstAddr    : EXACT     000000000002
Action entry: forward - 02
==========
Dumping default entry
Action entry: broadcast - 
==========
```

s2:

```
RuntimeCmd: table_dump dmac
==========
TABLE ENTRIES
**********
Dumping entry 0x0
Match key:
* ethernet.dstAddr    : EXACT     000000000001
Action entry: forward - 03
**********
Dumping entry 0x1
Match key:
* ethernet.dstAddr    : EXACT     000000000002
Action entry: forward - 03
**********
Dumping entry 0x2
Match key:
* ethernet.dstAddr    : EXACT     000000000003
Action entry: forward - 01
==========
Dumping default entry
Action entry: broadcast - 
==========
```

As we can see, the learn_client insert some entries. I restart the learn_client but it didn't show any response.

Is there something wrong with my steps? How can I fix it? 

Thank you very much!

reference: 
[SimplePreLAG_server.cpp](https://github.com/p4lang/behavioral-model/blob/master/src/bm_runtime/SimplePreLAG_server.cpp)
[#284](https://github.com/p4lang/behavioral-model/issues/284)

**Comment by antoninbas** [comment]
Hi,
You are doing an invalid table operation. My guess is that you are trying to add a duplicate entry (i.e. a table entry with the same match-key). I updated the learn client to catch the exception and print an informative message. You can look at my pull request (https://github.com/p4lang/behavioral-model/pull/288/files) and improve your code accordingly.

**Comment by Wasdns** [comment]
@antoninbas 

Thanks to your work. Follow your words, I changed the learn_client.cpp and make again. The learn_client printed the information message below:

s1:

```
I received 6 samples
Calling callback function
CB with 6 samples
ingress port is 1
ingress port is 2
ingress port is 3
Invalid table (smac) operation (17): DUPLICATE_ENTRY
Invalid table (dmac) operation (17): DUPLICATE_ENTRY
ingress port is 3
Invalid table (smac) operation (17): DUPLICATE_ENTRY
Invalid table (dmac) operation (17): DUPLICATE_ENTRY
ingress port is 3
ingress port is 3
```

s2:

```
I received 6 samples
Calling callback function
CB with 6 samples
ingress port is 1
ingress port is 2
ingress port is 3
Invalid table (smac) operation (17): DUPLICATE_ENTRY
Invalid table (dmac) operation (17): DUPLICATE_ENTRY
ingress port is 3
Invalid table (smac) operation (17): DUPLICATE_ENTRY
Invalid table (dmac) operation (17): DUPLICATE_ENTRY
ingress port is 3
ingress port is 3
```

As your words, the exception was caused by adding a duplicate entry. But I'm confused about why it printed this INFO. I didn't add any entry to the table of the P4 switches after inserting the cmds of the command.txt:

```
table_set_default smac mac_learn
table_set_default dmac broadcast

mc_mgrp_create 1
mc_node_create 0 1
mc_node_create 1 2
mc_node_create 2 3
mc_node_create 3 4
mc_node_associate 1 0
mc_node_associate 1 1
mc_node_associate 1 2
mc_node_associate 1 3
```

Then I check the entries of smac and dmac in the switches:

s1:

```
RuntimeCmd: table_dump smac
==========
TABLE ENTRIES
**********
Dumping entry 0x0
Match key:
* ethernet.srcAddr    : EXACT     000000000001
Action entry: _nop - 
**********
Dumping entry 0x1
Match key:
* ethernet.srcAddr    : EXACT     000000000002
Action entry: _nop - 
**********
Dumping entry 0x2
Match key:
* ethernet.srcAddr    : EXACT     000000000003
Action entry: _nop - 
**********
Dumping entry 0x3
Match key:
* ethernet.srcAddr    : EXACT     000000000004
Action entry: _nop - 
==========
Dumping default entry
Action entry: mac_learn - 
==========

RuntimeCmd: table_dump dmac
==========
TABLE ENTRIES
**********
Dumping entry 0x0
Match key:
* ethernet.dstAddr    : EXACT     000000000001
Action entry: forward - 01
**********
Dumping entry 0x1
Match key:
* ethernet.dstAddr    : EXACT     000000000002
Action entry: forward - 02
**********
Dumping entry 0x2
Match key:
* ethernet.dstAddr    : EXACT     000000000003
Action entry: forward - 03
**********
Dumping entry 0x3
Match key:
* ethernet.dstAddr    : EXACT     000000000004
Action entry: forward - 03
==========
Dumping default entry
Action entry: broadcast - 
==========
```

The informations of s2 are the same with s1. Then I apply `pingall` in the mininet:

```
*** Ping: testing ping reachability
h1 -> h2 X X 
h2 -> h1 X X 
h3 -> X X X 
h4 -> X X X 
*** Results: 83% dropped (2/12 received)
mininet> 
```

Only h1 and h2 can communicated each other. However, it was successful before I started the learn_client.

**Comment by antoninbas** [comment]
Looks like the entries you are adding from the learn_client are breaking connectivity.
At this point there is no point in guessing, I invite you to look at the switch logs and at pcap file to try and figure out what's wrong.

**Comment by Wasdns** [comment]
@antoninbas 

You're right. I used the `bmv2/tools/nanomsg_client.py` to print the information of packets when the demo is running. 

The steps I took:

### 1.start the mininet.

### 2.start the learn_client.

### 3.start the nanomsg client to print the info:

```
./nanomsg_client.py --thrift-port 22222
```

A part of the printed log showes below(you can see the whole logs here: [log1](https://github.com/Emil-501/P4NetworkSlices/blob/master/slices_demo4/debug/log/log1.md)):

```
···
type: PIPELINE_START, switch_id: 0, cxt_id: 0, sig: 3358402051929873787, id: 235, copy_id: 0, pipeline_id: 0 (ingress)
type: TABLE_MISS, switch_id: 0, cxt_id: 0, sig: 3358402051929873787, id: 235, copy_id: 0, table_id: 0 (smac)
type: TABLE_MISS, switch_id: 0, cxt_id: 0, sig: 3358402051929873787, id: 235, copy_id: 0, table_id: 1 (dmac)
type: PIPELINE_DONE, switch_id: 0, cxt_id: 0, sig: 3358402051929873787, id: 235, copy_id: 0, pipeline_id: 0 (ingress)
···
```

As we can see, the table `smac` and `dmac` is empty. So the packets `TABLE_MISS`. The learn_client didn't print any info.

ps. I started `pingall` as soon as the nanomsg_client started and it failed. Then I checked the table `smac` and `dmac`: there was no entry in `smac` and `dmac`.

### 4.send the runtime cmds of commands.txt to the P4 switches.

A part of logs(the whole logs: [log2](https://github.com/Emil-501/P4NetworkSlices/blob/master/slices_demo4/debug/log/log2.md)):

```
type: TABLE_HIT, switch_id: 0, cxt_id: 0, sig: 15309147182895934544, id: 5910, copy_id: 0, table_id: 0 (smac), entry_hdl: 1
type: ACTION_EXECUTE, switch_id: 0, cxt_id: 0, sig: 15309147182895934544, id: 5910, copy_id: 0, action_id: 4 (_nop)
type: TABLE_MISS, switch_id: 0, cxt_id: 0, sig: 15309147182895934544, id: 5910, copy_id: 0, table_id: 1 (dmac)
type: ACTION_EXECUTE, switch_id: 0, cxt_id: 0, sig: 15309147182895934544, id: 5910, copy_id: 0, action_id: 3 (broadcast)
```

The logs shows that the learn_client received some digest from the P4 switches and generate some table entries of the `smac` and `dmac`.

I set the `broadcast` to be the default action of table `dmac`. So the log reflects that a packet hit one entry of `smac`, however, it didn't find any match entry in the `dmac` so it applied the default action.

### 5.`pingall`

As my words one day ago, `pingall` showed that only h1 and h2 can communicate each other successfully.

```
mininet> pingall
*** Ping: testing ping reachability
h1 -> h2 X X 
h2 -> h1 X X 
h3 -> X X X 
h4 -> X X X 
*** Results: 83% dropped (2/12 received)
```

The log shows below([log3](https://github.com/Emil-501/P4NetworkSlices/blob/master/slices_demo4/debug/log/log3.md)), there are two types of log:

first:

```
type: PIPELINE_START, switch_id: 0, cxt_id: 0, sig: 16748884929993570229, id: 268232, copy_id: 0, pipeline_id: 0 (ingress)
type: TABLE_HIT, switch_id: 0, cxt_id: 0, sig: 16748884929993570229, id: 268232, copy_id: 0, table_id: 0 (smac), entry_hdl: 9
type: ACTION_EXECUTE, switch_id: 0, cxt_id: 0, sig: 16748884929993570229, id: 268232, copy_id: 0, action_id: 4 (_nop)
type: TABLE_HIT, switch_id: 0, cxt_id: 0, sig: 16748884929993570229, id: 268232, copy_id: 0, table_id: 1 (dmac), entry_hdl: 8
type: ACTION_EXECUTE, switch_id: 0, cxt_id: 0, sig: 16748884929993570229, id: 268232, copy_id: 0, action_id: 2 (forward)
type: PIPELINE_DONE, switch_id: 0, cxt_id: 0, sig: 16748884929993570229, id: 268232, copy_id: 0, pipeline_id: 0 (ingress)
```

second:

```
type: PIPELINE_START, switch_id: 0, cxt_id: 0, sig: 3743839640928961760, id: 268236, copy_id: 0, pipeline_id: 0 (ingress)
type: TABLE_HIT, switch_id: 0, cxt_id: 0, sig: 3743839640928961760, id: 268236, copy_id: 0, table_id: 0 (smac), entry_hdl: 0
type: ACTION_EXECUTE, switch_id: 0, cxt_id: 0, sig: 3743839640928961760, id: 268236, copy_id: 0, action_id: 4 (_nop)
type: TABLE_MISS, switch_id: 0, cxt_id: 0, sig: 3743839640928961760, id: 268236, copy_id: 0, table_id: 1 (dmac)
type: ACTION_EXECUTE, switch_id: 0, cxt_id: 0, sig: 3743839640928961760, id: 268236, copy_id: 0, action_id: 3 (broadcast)
type: PIPELINE_DONE, switch_id: 0, cxt_id: 0, sig: 3743839640928961760, id: 268236, copy_id: 0, pipeline_id: 0 (ingress)
```

The first type of log shows that the packet found the match entry in both `smac` and `dmac`, and excute the action `forward` finally. But the second type of log tells that some packet didn't find the match entry in the table `dmac`, just like the log2.

Other Informations:

> learn_client(s1):

```
I received 2 samples
Calling callback function
CB with 2 samples
ingress port is 2
ingress port is 1
I received 2 samples
Calling callback function
CB with 2 samples
ingress port is 3
ingress port is 3
I received 1 samples
Calling callback function
CB with 1 samples
ingress port is 3
I received 1 samples
Calling callback function
CB with 1 samples
ingress port is 3
I received 6 samples
Calling callback function
CB with 6 samples
ingress port is 1
ingress port is 2
ingress port is 3
Invalid table (smac) operation (17): DUPLICATE_ENTRY
Invalid table (dmac) operation (17): DUPLICATE_ENTRY
ingress port is 3
Invalid table (smac) operation (17): DUPLICATE_ENTRY
Invalid table (dmac) operation (17): DUPLICATE_ENTRY
ingress port is 3
ingress port is 3
```

> the results of the table `smac` in s1.

```
RuntimeCmd: table_dump smac
==========
TABLE ENTRIES
**********
Dumping entry 0x0
Match key:
* ethernet.srcAddr    : EXACT     ba0b520240c7
Action entry: _nop - 
**********
Dumping entry 0x1
Match key:
* ethernet.srcAddr    : EXACT     c697fd4b7173
Action entry: _nop - 
**********
Dumping entry 0x2
Match key:
* ethernet.srcAddr    : EXACT     c6cdc1411844
Action entry: _nop - 
**********
Dumping entry 0x3
Match key:
* ethernet.srcAddr    : EXACT     0ec569f9f445
Action entry: _nop - 
**********
Dumping entry 0x4
Match key:
* ethernet.srcAddr    : EXACT     d22d5b75d4af
Action entry: _nop - 
**********
Dumping entry 0x5
Match key:
* ethernet.srcAddr    : EXACT     a26bb0e26271
Action entry: _nop - 
**********
Dumping entry 0x6
Match key:
* ethernet.srcAddr    : EXACT     000000000001
Action entry: _nop - 
**********
Dumping entry 0x7
Match key:
* ethernet.srcAddr    : EXACT     000000000002
Action entry: _nop - 
**********
Dumping entry 0x8
Match key:
* ethernet.srcAddr    : EXACT     000000000003
Action entry: _nop - 
**********
Dumping entry 0x9
Match key:
* ethernet.srcAddr    : EXACT     000000000004
Action entry: _nop - 
==========
Dumping default entry
Action entry: mac_learn - 
==========
```

> the results of the table `dmac` in s1.

```
RuntimeCmd: table_dump dmac
==========
TABLE ENTRIES
**********
Dumping entry 0x0
Match key:
* ethernet.dstAddr    : EXACT     ba0b520240c7
Action entry: forward - 02
**********
Dumping entry 0x1
Match key:
* ethernet.dstAddr    : EXACT     c697fd4b7173
Action entry: forward - 01
**********
Dumping entry 0x2
Match key:
* ethernet.dstAddr    : EXACT     c6cdc1411844
Action entry: forward - 03
**********
Dumping entry 0x3
Match key:
* ethernet.dstAddr    : EXACT     0ec569f9f445
Action entry: forward - 03
**********
Dumping entry 0x4
Match key:
* ethernet.dstAddr    : EXACT     d22d5b75d4af
Action entry: forward - 03
**********
Dumping entry 0x5
Match key:
* ethernet.dstAddr    : EXACT     a26bb0e26271
Action entry: forward - 03
**********
Dumping entry 0x6
Match key:
* ethernet.dstAddr    : EXACT     000000000001
Action entry: forward - 01
**********
Dumping entry 0x7
Match key:
* ethernet.dstAddr    : EXACT     000000000002
Action entry: forward - 02
**********
Dumping entry 0x8
Match key:
* ethernet.dstAddr    : EXACT     000000000003
Action entry: forward - 03
**********
Dumping entry 0x9
Match key:
* ethernet.dstAddr    : EXACT     000000000004
Action entry: forward - 03
==========
Dumping default entry
Action entry: broadcast - 
==========
RuntimeCmd: 
```

My conclusion depending on the informations above:

1.The learn_client started work after the step4: "send the runtime cmds of commands.txt to the P4 switches."

2.According to the information the cmd `table_dump dmac` printed, it should be successful when `pingall` in the mininet despite of the invalid table operations. However, not all packets could find the match entry in `dmac` refer to the log3.

The contents of the commands.txt using in this demo are based on the [commands.txt](https://github.com/p4lang/behavioral-model/blob/master/targets/l2_switch/commands.txt) of the target `l2_switch`. I created four multicast node based on the four switches in my topo and joined them to one multicast group. From my point of view, I don't think the commands.txt is the reason why the learn_client throw out the exception.

I'm sorry that my problem take your precious time, but could you give me some advise? Thank you very much! You can refer my demo here if you like: [github](https://github.com/Emil-501/P4NetworkSlices/tree/master/slices_demo4)

**Comment by antoninbas** [comment]
Can't help but notice you are not setting the default action for the `mcast_pruning` table to `_drop`. This may be a long shot but it could end up messing up the L2 tables.
In case this doesn't work, you need to stop trying to run `pingall` at all cost. Try to figure out why the first ping from `h1` to `h2` works, but not the next two.

**Comment by Wasdns** [comment]
@antoninbas 

Thank you so much! I solved my problem. 

1.add the `table_set_default mcast_pruning _drop => ` to the commands.txt, it solved the duplicate entries problem.

2.Using the simple_switch_CLI, I `table_dump` the entries of `dmac` in s2 and I found that the entries was not correct. It caused s2 cannot ping h3 and h4 successfully. Then I found that I'm using the wrong notification sockets in learn_client_s2. What a silly mistake!

Thank you very much. And my little suggestion is, could you add the command `table_set_default mcast_pruning _drop => ` to the commands.txt of the target `l2_switch`(here: [commands.txt](https://github.com/p4lang/behavioral-model/blob/master/targets/l2_switch/commands.txt))? I think it can avoid the duplicate entry. 

Best wishes!
