### ISSUE TITLE
The debugger is not enabled on the switch

### ISSUE THREAD

**Issue by realmanhw** [p4lang/behavioral-model#290]
When using P4 DEBUGGER, I run the command 

> sudo ./p4dbg.py --thrift-ip 127.0.0.1 --thrift-port 9090

But it displays that `The debugger is not enabled on the switch`
I have run
`1. ./autogen.sh
2. ./configure --enable-debugger
3. make
4. [sudo] make install 
sudo ldconfig`
and then I have run the switch, but it doesn't work. 
I want to know why？
Thank you！

**Comment by antoninbas** [comment]
My best guess is that you are not passing `--debugger` when starting the switch (https://github.com/p4lang/behavioral-model#using-the-debugger):
<pre>
antonin@ubuntu:~/Documents/p4lang/bmv2_dbg$ ./targets/simple_switch/simple_switch -h
Usage: SWITCH_NAME [options] <path to JSON config file>
Options:
  -h [ --help ]            Display this help message
  -i [ --interface ] arg   <port-num>@<interface-name>: Attach network 
                           interface <interface-name> as port <port-num> at 
                           startup. Can appear multiple times
  --pcap                   Generate pcap files for interfaces
  --use-files arg          Read/write packets from files (interface X 
                           corresponds to two files X_in.pcap and X_out.pcap). 
                           Argument is the time to wait (in seconds) before 
                           starting to process the packet files.
  --packet-in arg          Enable receiving packet on this (nanomsg) socket. 
                           The --interface options will be ignored.
  --thrift-port arg        TCP port on which to run the Thrift runtime server
  --device-id arg          Device ID, used to identify the device in IPC 
                           messages (default 0)
  --nanolog arg            IPC socket to use for nanomsg pub/sub logs (default:
                           no nanomsg logging
  --log-console            Enable logging on stdout
  --log-file arg           Enable logging to given file
  -L [ --log-level ] arg   Set log level, supported values are 'trace', 
                           'debug', 'info', 'warn', 'error', off'; default is 
                           'trace'
  --log-flush              If used with '--log-file', the logger will flush to 
                           disk after every log message
  --notifications-addr arg Specify the nanomsg address to use for notifications
                           (e.g. learning, ageing, ...); default is 
                           ipc:///tmp/bmv2-<device-id>-notifications.ipc
<b>
  --debugger               Activate debugger
  --debugger-addr arg      Specify the nanomsg address to use for debugger 
                           communication; there is no need to use --debugger in
                           addition to this option; default is 
                           ipc:///tmp/bmv2-<device-id>-debug.ipc
</b>
  --restore-state arg      Restore state from file
  --dump-packet-data arg   Specify how many bytes of packet data to dump upon 
                           receiving & sending a packet. We use the logger to 
                           dump the packet data, with log level 'info', so make
                           sure the log level you have set does not exclude 
                           'info' messages; default is 0, which means that 
                           nothing is logged.
  -v [ --version ]         Display version information
  --no-p4                  Enable the switch to start without an inout 
                           configuration
This target also comes with its own command line parser, make sure you separate general bmv2 options from, target specific options with '--'
Target specific options:
Target options:
  --enable-swap         enable JSON swapping at runtime
</pre>

**Comment by realmanhw** [comment]
I will try it again! Thank you.

**Comment by realmanhw** [comment]
**But When I run** 
```
root@hw:/home/hw/behavioral-model/targets/simple_switch# ./simple_switch -h
Usage: SWITCH_NAME [options] <path to JSON config file>
Options:
  -h [ --help ]            Display this help message
  -i [ --interface ] arg   <port-num>@<interface-name>: Attach network 
                           interface <interface-name> as port <port-num> at 
                           startup. Can appear multiple times
  --pcap                   Generate pcap files for interfaces
  --use-files arg          Read/write packets from files (interface X 
                           corresponds to two files X_in.pcap and X_out.pcap). 
                           Argument is the time to wait (in seconds) before 
                           starting to process the packet files.
  --packet-in arg          Enable receiving packet on this (nanomsg) socket. 
                           The --interface options will be ignored.
  --thrift-port arg        TCP port on which to run the Thrift runtime server
  --device-id arg          Device ID, used to identify the device in IPC 
                           messages (default 0)
  --nanolog arg            IPC socket to use for nanomsg pub/sub logs (default:
                           no nanomsg logging
  --log-console            Enable logging on stdout
  --log-file arg           Enable logging to given file
  -L [ --log-level ] arg   Set log level, supported values are 'trace', 
                           'debug', 'info', 'warn', 'error', off'; default is 
                           'trace'
  --log-flush              If used with '--log-file', the logger will flush to 
                           disk after every log message
  --notifications-addr arg Specify the nanomsg address to use for notifications
                           (e.g. learning, ageing, ...); default is 
                           ipc:///tmp/bmv2-<device-id>-notifications.ipc
  --restore-state arg      Restore state from file
  --dump-packet-data arg   Specify how many bytes of packet data to dump upon 
                           receiving & sending a packet. We use the logger to 
                           dump the packet data, with log level 'info', so make
                           sure the log level you have set does not exclude 
                           'info' messages; default is 0, which means that 
                           nothing is logged.
  -v [ --version ]         Display version information
  --no-p4                  Enable the switch to start without an inout 
                           configuration
This target also comes with its own command line parser, make sure you separate general bmv2 options from, target specific options with '--'
Target specific options:
Target options:
  --enable-swap         enable JSON swapping at runtime
```
**There are no** 
```
  --debugger               Activate debugger
  --debugger-addr arg      Specify the nanomsg address to use for debugger 
                           communication; there is no need to use --debugger in
                           addition to this option; default is 
                           ipc:///tmp/bmv2--debug.ipc
```
**option, I just do not know why, Can you tell me? Thank you very much!**

**Comment by vgurevich** [comment]
Hello,

Please, check how you built BMv2. For these options to be valid, BMv2
should be build with the debugger support enabled.

To enable debugger support add "--enable-debugger" parameter to the command
line parameters you pass to the ./configure script.

Happy hacking,
Vladimir

**Comment by realmanhw** [comment]
The **steps** that I built BMv2 are 
```
1. sudo ./autogen.sh 
2. sudo ./configure --enable-debugger 
3. sudo make 
4. sudo make install sudo ldconfig
```
**is there any mistake?**  I intend to uninstall it and then install it by running the 4 steps above again.

**Comment by vgurevich** [comment]
Hello,

Normally, steps 1-3 should not require "sudo"  :), but you might need to do
it now, otherwise you won't be able to overwrite the older files.

I would also recommend doing "make clean" after running configure.
Alternatively, it might be easier to delete the whole directory and start
afresh.

Other  than that looks OK.

Happy hacking,
Vladimir

**Comment by antoninbas** [comment]
Closing this issue. If the steps in the README are followed, there should be no problem. After running configure again with different flags, `make clean` needs to be run before building again.
