### ISSUE TITLE
DUPLICATE_ENTRY in commands on empty line

### ISSUE THREAD

**Issue by Starl1ght** [p4lang/behavioral-model#293]
I have following commands.txt file for very simple internal sample:

> table_set_default check_multicast_4 _nop
> table_add check_multicast_4 _drop 224.0.0.0/4 =>
> 
> table_set_default check_multicast_6 _nop
> table_add check_multicast_6 _drop ff00::/8 =>

There is a problem, when I use it - bmv2 outputs following:

> Control utility for runtime P4 table manipulation
> RuntimeCmd: Setting default action of check_multicast_4
> action:              _nop
> runtime data:        
> [13:52:18.564] [bmv2] [T] [thread 13164] bm_set_default_action
> [13:52:18.564] [bmv2] [D] [thread 13164] Set default entry for table 'check_multicast_4': _nop - 
> RuntimeCmd: Adding entry to lpm match table check_multicast_4
> match key:           LPM-e0:00:00:00/4
> action:              _drop
> runtime data:        
> [13:52:18.564] [bmv2] [T] [thread 13164] bm_table_add_entry
> [13:52:18.565] [bmv2] [D] [thread 13164] Entry 0 added to table 'check_multicast_4'
> [13:52:18.565] [bmv2] [D] [thread 13164] Dumping entry 0
> Match key:
> * ipv4.dstAddr        : LPM       e0000000/4
> Action entry: _drop - 
> 
> Entry has been added with handle 0
> RuntimeCmd: Adding entry to lpm match table check_multicast_4
> match key:           LPM-e0:00:00:00/4
> action:              _drop
> runtime data:        
> [13:52:18.565] [bmv2] [T] [thread 13164] bm_table_add_entry
> [13:52:18.565] [bmv2] [E] [thread 13164] Error when trying to add entry to table 'check_multicast_4'
> Invalid table operation (DUPLICATE_ENTRY)
> RuntimeCmd: Setting default action of check_multicast_6
> action:              _nop
> runtime data:        
> [13:52:18.565] [bmv2] [T] [thread 13164] bm_set_default_action
> [13:52:18.565] [bmv2] [D] [thread 13164] Set default entry for table 'check_multicast_6': _nop - 
> RuntimeCmd: Adding entry to lpm match table check_multicast_6
> match key:           LPM-ff:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00/8
> action:              _drop
> runtime data:        
> [13:52:18.566] [bmv2] [T] [thread 13164] bm_table_add_entry
> [13:52:18.566] [bmv2] [D] [thread 13164] Entry 0 added to table 'check_multicast_6'
> [13:52:18.566] [bmv2] [D] [thread 13164] Dumping entry 0
> Match key:
> * ipv6.dstAddr        : LPM       ff000000000000000000000000000000/8
> Action entry: _drop - 

Interesting thing here is DUPLICATE_ENTRY, but there is no duplicate entry in my commands. I can "fix" this error by simply removing empty line between statements. This is reproduced multiple times on different p4 programs, if I have empty line in commands - previous line executes once again for some reason.

And moreover - a simple related feature request, if possible. Make "comments" for commands file, i.e. ignore output which is starting by '#', for example. This would be good for big commands.txt files, without producing errors in loading.

**Comment by antoninbas** [comment]
Leaving an empty line in your input file is the same thing as hitting `enter` in the CLI shell without typing a new command, it will replay the previous command. This is a very common feature for CLI tools (gdb?).
Ignoring lines starting with `#` may make sense and I might do it in a future pull request. However, the runtime CLI is more meant for debugging and experimentation than for heavy use, so if you find yourself using it with very large input files, that may not be the right thing to use in your case. Anyway, I suggest that you write your own little script (maybe using `awk`) to preprocess your `commands.txt` file before piping it to the CLI. Your script can remove empty lines, remove comment lines...
