### ISSUE TITLE
How can I debug in mininet?

### ISSUE THREAD

**Issue by realmanhw** [p4lang/behavioral-model#296]
Excuse me, following your suggestions I can debug simple_router in bmv2. But it is still not convenient because I have to connect each computer and start behavioral-model in each computer. 
When I run
`sudo python mininet/1sw_demo.py --behavioral-exe targets/simple_router/simple_router --json targets/simple_router/simple_router.json `
mininet start, it works well. **But I just wonder if there is a way to start Debugger mode in mininet? How can I do that? Thanks!**

**Comment by antoninbas** [comment]
Feel free to update the Python scripts `1sw_demo.py` and `p4_mininet.py` to suit your needs. You will need to provide a different `--debugger-addr` for each switch instance (see the help message for `simple_switch`).

**Comment by realmanhw** [comment]
OK, I will try to modify it. Thank you.
