### ISSUE TITLE
P4 switch performance

### ISSUE THREAD

**Issue by Raymondma-public** [p4lang/behavioral-model#301]
I have implemented a protocol based on the ECMP sample code.

I build a network with 1 switch and 2 hosts in CloudLab.us and the code for ECMP doesn't change.
However, when I try to test it on CloudLab.us , I found that it is much slower than the Linux original routing behavior.

For Ubuntu, I removed the route for disabling the original routing behavior.

For P4, I have done the following steps

1. ./configure --disable-logging-macros --disable-elogger
2. make
3. run the switch without logging and packet capture.

I found that the switch can only handle about 10 Mbps traffic. That is much less that 1Gbps , that is how the original Linux routing behavior performs.

The below image is the performance of P4. It is showing how much data can host 1 send to host 2.  It indicate that the P4 switch can handle about 10 Mb/s traffic.
![image](https://cloud.githubusercontent.com/assets/11516250/23457141/a62d3752-feb1-11e6-9359-159bb5db26e2.png)

And the following is the performance of normal linux routing. It is showing how much data can host 1 send to host 2. It show the route can handle about 1 Gb/s traffic.
![image](https://cloud.githubusercontent.com/assets/11516250/23457159/b09de7c2-feb1-11e6-8022-c8c11ceeec8c.png)

**Is there any other configurations that can enhance the performance of my switch?**
Thank you very much

**Comment by antoninbas** [comment]
This is definitely too low, unless you have a huge P4 program and many ternary matches happening.
I recommend running `sudo python stress_test_ipv4.py` under the `mininet` folder and seeing what kind of throughput you get. In my case I get 217 Mbps, which is 20x what you are observing.
If you re-run `configure` in an existing clone, you need to make sure you run `make clean` before `make`, otherwise new pre-processor flags will not be taken into account. That may be the issue here. Also make sure that you are compiling with `-O2` (but that should be the default).
Actually, even 217 Mbps is too low for the stress test, so I need to look into this. It should be > 1 Gbps.

**Comment by antoninbas** [comment]
I was able to confirm that for some reason, the throughput was much slower on my VM (200 Mbps). On my native Linux laptop, the throughput is as expected: ~1200 Mbps. That's the kind of throughput you should be able to observe for simple P4 programs.

**Comment by Raymondma-public** [comment]
After make clean and compile again, the switch get some performance enhanced to about 20-40 Mbps.

My P4 source code has about 1000 lines of code. 

But for some cases I do not need "match" originally. But I have to make a new table to call the action in pipeline.

eg.
```

...
action myAction(){
	...
}

table myTable{
	actions{
		myAction;	//I make this as default action, when mismatch, it will be called. 
					//But actually I don't need any matching

	}
	size:..
}

ingress{
	if(...){
		apply(myTable);
	}
}

```
Would my P4 source file be too large?
And would my implementation approach affect the performance?

**Comment by antoninbas** [comment]
it's hard to tell without looking at your P4 program and the entries you install. If you send me both I can try running it on my machine.
you could just be running on a very slow machine; if you have less than 4 cores, the throughput would be impacted as well

**Comment by Raymondma-public** [comment]
I am quite sure the machine is powerful enough.
I am using the following machine.
https://wiki.emulab.net/Emulab/wiki/d430
It get :
- Two 2.4 GHz 64-bit 8-Core E5-2630 "Haswell" processors, 8.0 GT/s bus speed, 20 MB cache, and VT (VT-x, EPT, and VT-d) support
- 64 GB 2133 MT/s DDR4 RAM (8 x 8GB modules)
- 1 dual-port or 1 quad-port Intel I350 1GbE PCI-Express NICs
- 1 dual-port or 1 quad-port Intel X710 10GbE PCI-Express NICs

=======================================================

I have turned off TSO, GSO, GRO on every interface of the switch and hosts. 
Then I get significant increase of performance.
![image](https://cloud.githubusercontent.com/assets/11516250/23575560/8f7495ea-00c9-11e7-8bc4-af79229f50c0.png)

I get about 700Mbps. However it is still not be able to reach about 1Gps. 
Would there be any other setting on the switch that can improve the performance ?

Thank you

**Comment by antoninbas** [comment]
700Mbps is a decent number for bmv2. You have to understand that it very much depends on the P4 program you are running and (for now) the number of ternary match entries.
This is why I recommended that you run `sudo python stress_test_ipv4.py` (under the `mininet` folder) on the machine you use to run the switch. Then you will have a real point of comparison with my own results.

**Comment by Raymondma-public** [comment]
By running  `sudo python stress_test_ipv4.py`, I get the below result that is similar to that of the network.

![image](https://cloud.githubusercontent.com/assets/11516250/23644931/9895d67a-0344-11e7-9a43-2d5ad43bfa8f.png)

Does it mean by using 

- this machine
- bmv2
- simplest P4 protocol

~700 Mbps is already the maximum throughput with this combination no matter what other configurations are set?

**Comment by antoninbas** [comment]
Yes you seem to be capped at 700Mbps for some reason. Given that I get 1Gbps on my laptop, you should logically get much more on the server. IMO the bottleneck is unlikely to be the CPU. Somehow you may not be getting packets fast enough on the interface, but I am not sure how to diagnose / fix this.

**Comment by Raymondma-public** [comment]
I find that when I am using iperf to test the performance. I get very high CPU value. Is it normal to have high CPU value like this? Is there any P4 configurations that may lead to this?
![image](https://cloud.githubusercontent.com/assets/11516250/24318917/59aa46c2-1149-11e7-8d77-ddc2e383921d.png)

**Comment by antoninbas** [comment]
It's quite the opposite actually. Your CPU usage values are not high enough. bmv2 is supposed to be CPU-bounded, yet somehow when you run it it behaves as if IO bounded.
