### ISSUE TITLE
Simple_switch queue capacity

### ISSUE THREAD

**Issue by qq995002966** [p4lang/behavioral-model#311]
I'm doing a experiment about ECN with p4 . I found the following information in `docs/simple_switch.md` : 
```
header_type queueing_metadata_t {
    fields {
        enq_timestamp : 48;
        enq_qdepth : 16;
        deq_timedelta : 32;
        deq_qdepth : 16;
    }
}
metadata queueing_metadata_t queueing_metadata;
```
but it seemed that I still can't get the total queue capacity to calculate `queue usage` out by `current_depth/queue_capacity` , So my question is how can I get queue capacity.

Any help would be appreciate.thanks.

John.

**Comment by antoninbas** [comment]
I believe the default queue size in bmv2 is 64 packets. This can be changed using the runtime API. The simple_switch_CLI has a `set_queue_depth` command. You can either hard code the value in your P4 program or have the control plane store it in a table / register.

**Comment by qq995002966** [comment]
Thank you , @antoninbas 
but
It seemed I still can't access to the switch queue status . Here is what my `run_demo.sh` looks like 

```bash
BMV2_PATH=/home/mininet/documents/p4lang/behavioral-model

P4C_BM_PATH=/home/mininet/documents/p4lang/p4c-bm

P4C_BM_SCRIPT=$P4C_BM_PATH/p4c_bm/__main__.py

SWITCH_PATH=$BMV2_PATH/targets/simple_switch/simple_switch

CLI_PATH=$BMV2_PATH/tools/runtime_CLI.py
$P4C_BM_SCRIPT p4src/simple_router.p4 --json simple_router.json
# $P4C_BM_SCRIPT p4src/testQueue/queueing.p4 --json simple_router.json

sudo python $BMV2_PATH/mininet/1sw_demo.py \
      --behavioral-exe $SWITCH_PATH \
      --json simple_router.json
```

and this is my p4 source file [simple_router.p4](https://github.com/qq995002966/my_pro/blob/master/p4src/simple_router.p4) , I just copy it from    `p4lang/p4factory/targets/simple_router/p4src/simple_router.p4`  and add some test code in `action rewrite_mac` which is belong to `control egress` at line 78 . The code I add has no real meanings but for the conveniences that I can see the result intuitively from `packages' ttl` at `Wireshark` . The result are as follow 

|code|can access?|
|-----|-----|
|modify_field(ipv4.ttl,queueing_metadata.enq_timestamp);|yes|
|modify_field(ipv4.ttl,queueing_metadata.enq_qdepth);|no , ipv4.ttl == 0|
modify_field(ipv4.ttl,queueing_metadata.deq_timedelta); |yes|
modify_field(ipv4.ttl,queueing_metadata.deq_qdepth); |no , ip4.ttl == 0|

Is it because the packages flow is too small or my code has some problems ?
Sorry for those newbie questions , any help would be appreciate.

John.

**Comment by antoninbas** [comment]
If you don't saturate the link, there won't be a queue buildup and `enq_qdepth` and `deq_qdepth` will always be 0.
My advice is to use the `set_queue_rate` command of the `simple_switch_CLI` to set the queue output rate to something low. For example `set_queue_rate 10` will use a rate of 10 packets per second. Then you can start an iperf connection between your 2 hosts in the mininet CLI and you should be able to observe queue build-up, with non-0 values for `enq_qdepth` and `deq_qdepth`.

**Comment by qq995002966** [comment]
That works , 👍 
 thanks a lot , antoninbas .

**Comment by shahzad46** [comment]
I am also working on ECN, I have a question. How can we flush the whole switch queue? Like when the max threshold is met, I want all the packets in the queue to be dropped.

**Comment by drobinkent** [comment]
I have a nearly related question. here. 

Assume we have a link in mininet and it's bw is 10 Mbps. Now assume we are testing the link speed with iperf3. In iperf3 we are setting bitrate to 15 Mbps. Will bmv2 take the link speed into account here? If bmv2 passes packets at rate of 10 Mbps, then the queue will build up. Which is not happening in my testing scenario. 
Now my question is,  what is the correct way to generate such kind of queue build up behavior. a) using set_queue_rate or b) setting link bandwidth in mininet?

**Comment by jafingerhut** [comment]
@drobinkent I am not certain, but I believe it is likely that one of the following is true:

(a) simple_switch has no way of knowing what the link bandwidths are in mininet, or
(b) simple_switch does have a way to find out what link bandwidths are assigned in mininet, but ignores those values in its behavior

If one of those is true, I would guess that set_queue_rate is more likely to achieve the results similar to what a real switch ASIC would do, with is to evenly schedule packets destined for the same output port far enough apart so that they match the link rate.

I do not know the answers to your other questions, but by using a debug table on simple_switch v1model standard metadata fields like ingress_global_timestamp, egress_global_timestamp, enq_qdepth, and deq_qdepth, logged during egress processing, and using `--log-console` or `--log-file filename.txt` command line options to simple_switch so you can save those logs and postprocess them, you could likely learn the answers to some of them via experimentation.

From that kind of experimentation, I learned that it is definitely possible when you do _not_ use set_queue_rate, that egress processing can be performed on packets destined to the same output port in very quick bursts at a much faster rate than the mininet link rate.

**Comment by drobinkent** [comment]
I am trying to understand from experimentation. But there are so many factors, it's always better to get some definite behaviors. 

>  From that kind of experimentation, I learned that it is definitely possible when you do not use set_queue_rate, that egress processing can be performed on packets destined to the same output port in very quick bursts at a much faster rate than the mininet link rate.

Exactly. I was trying to create a bottleneck link. I was using the code for debug table from your p4-guide, assuming that bmv2 switch will follow the mininet link speed. then I realized it may not work in this way. I guess these questions will be also applicable for psa switch. So thought to get totally clear concept about bmv2. For the people who do not have access to real P4 enabled switch, it may be helpful.

**Comment by drobinkent** [comment]
@antoninbas , I am setting queue rate for all ports of a switch (with 2 ports) as 10 pps. While I do testing with Iperf (using 1400 byte mss), I get bandwidth two hosts connected via the switch as 2Mbits. But if queue rate is 10 pps and a switch have 2 ports, and traffic can be transferred between the hosts using both the ports.  then I should get maximum  2*10**1400*8 = 224000 bits per second = .21 Mbits per second. But this is not happening. Iperf gives me 2 Mbits speed between the hosts (I have setup the bit rate in iPerf3 test as 2 MBits/sec). Am I missing something here? Can you kindly help me with this issue?

**Comment by antoninbas** [comment]
I'm unable to reproduce the issue.

Here are the steps I followed:

### Create topology with simple_router program
```
cd mininet
sudo python 1sw_demo.py --behavioral-exe ../targets/simple_switch/simple_switch --json ../targets/simple_router/simple_router.json
```

### Install necessary entries for forwarding
```
cd targets/simple_router
./runtime_CLI < commands.txt
```

### Make sure ping is working
```
mininet> pingall
*** Ping: testing ping reachability
h1 -> h2 
h2 -> h1 
*** Results: 0% dropped (2/2 received)
```

### Run iperf test without rate limit
```
mininet> h1 iperf -s&
mininet> h2 iperf -c 10.0.0.10
------------------------------------------------------------
Client connecting to 10.0.0.10, TCP port 5001
TCP window size: 85.3 KByte (default)
------------------------------------------------------------
[  3] local 10.0.1.10 port 43348 connected with 10.0.0.10 port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-10.0 sec   126 MBytes   105 Mbits/sec
```

### Set rate limit to 10 pps
```
abas@ubuntu:~/p4lang/bmv2/targets/simple_switch$ cd targets/simple_switch
abas@ubuntu:~/p4lang/bmv2/targets/simple_switch$ ./simple_switch_CLI 
Obtaining JSON from switch...
Done
Control utility for runtime P4 table manipulation
RuntimeCmd: set_queue_rate 10
RuntimeCmd:
```

### Run iperf test again
```
mininet> h2 iperf -c 10.0.0.10
------------------------------------------------------------
Client connecting to 10.0.0.10, TCP port 5001
TCP window size: 85.3 KByte (default)
------------------------------------------------------------
[  3] local 10.0.1.10 port 43352 connected with 10.0.0.10 port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-11.2 sec   384 KBytes   281 Kbits/sec
```

Maybe still a bit high? But the rate is so small there is probably some inaccuracy.

**Comment by drobinkent** [comment]
My mistake. I was interpreting the iperf output incorrectly.

**Comment by drobinkent** [comment]
> I believe the default queue size in bmv2 is 64 packets. This can be changed using the runtime API. The simple_switch_CLI has a `set_queue_depth` command. You can either hard code the value in your P4 program or have the control plane store it in a table / register.
> The most reasonable and portable thing to do would probably have the control plane specify a threshold above which packets are tagged.

Is it possible to set the queue depth from a P4 program? Can you kindly point to some example or give some hints?

One more question, in bmv2, when we work with the priority queues and set rate using set_queue_rate command of simple_switch_CLI-- does that set same rate for all the queues of a port? Or there is mechanism to set queue rate for each of the priority queue for a port?

**Comment by Meerkhan12** [comment]
Hi @antoninbas ..I need to check the queuing delay and for this I made a topology with 2 hosts and one bmv2 switch. I need to change the output rate of switch but I am unable to enter into simple-switch-cli.. In one terminal I run my topology and in other terminal I give the command:

> p4@p4:~/tutorials/exercises/NAQM$ simple_switch_CLI --thrift-port 50051
> Obtaining JSON from switch...
> Error when requesting JSON config from switch

I need your guidance about this problem.

**Comment by antoninbas** [comment]
The default port for the Thrift RPC service in simple_switch is 9090, not 50051, so unless you specified a different value with `--thrift-port` when starting `simple_switch`, you should use 9090 (or omit the argument altogether). If you have a topology with multiple switches running on the same host (e.g. with Mininet), there will be a different port assigned to each one.

Also note that `simple_switch_grpc` does not run a Thrift RPC service by default, unlike `simple_switch` (https://github.com/p4lang/behavioral-model/tree/master/targets/simple_switch_grpc#enabling-the-thrift-server). It's hard to provide exact guidance without knowing which one you are using.

An easy way to find out which bmv2 processes are running and with which command-line arguments could be to run:
```
ps -aux | grep simple_switch
```

**Comment by sandhyarathee** [comment]
I have a question related to queues in BMV2 switch. I want to configure multiple queues on a given port of a BMV2 switch. How to do this? I am using P4 tutorial VM.

**Comment by nagmat1** [comment]
> I believe the default queue size in bmv2 is 64 packets. This can be changed using the runtime API. The simple_switch_CLI has a `set_queue_depth` command. You can either hard code the value in your P4 program or have the control plane store it in a table / register. The most reasonable and portable thing to do would probably have the control plane specify a threshold above which packets are tagged.

How can we check the queue_rate of the switch by either using runtime_CLI or simple_switch_CLI?
