### ISSUE TITLE
How to handle a table with two match fields each one having lpm match type?

### ISSUE THREAD

**Issue by ali64Mon** [p4lang/behavioral-model#327]
Hi everyone,
I have the following tablee:

table t {
    reads {
        ipv4.protocol : exact;
        ipv4.srcAddr  : lpm;
        ipv4.dstAddr  : lpm;
        tcp.srcPort   : ternary;
        tcp.dstPort   : ternary;
        udp.srcPort   : ternary;
        udp.dstPort   : ternary;
    }
    actions {
        _nop;
        set_vlan;

    }

}

The p4c-bm2-ss gives no warning or error. However, simple_switch cannot run the p4 program !!!
Any thoughts?

**Comment by jafingerhut** [comment]
I challenge you to define what it means to mix lpm and ternary fields in the same search table.  I don't know what the intended behavior such a table is supposed to have, nor why you would want one.

My opinion is that it would make sense for the p4c-bm2-ss to allow at most one lpm field in a search key, and if one was present, all other fields must be exact.

If such a restriction were made, one could effectively get an lpm match across multiple fields by concatenating them together into a longer field that is lpm, e.g. concatenate 32-bit IPv4 dstAddr with 32-bit IPv4 srcAddr to get a 64-bit metadata field, then use that 64-bit field with lpm match type in the search key.

**Comment by cc10512** [comment]
@jafingerhut those constraints are already in bmv2.

**Comment by ali64Mon** [comment]
Thanks for your comment.
Well I'm trying to implement a DOCSIS classifier in P4. As you may know, they assign a service flow to each packet arriving at  a switch based on some matching metrics. In my first post's example, the classifier checks ipv4 protocol, source & destination address, and either tcp or upd src/des addresses to assign the packet to the corresponding service flow.

**Comment by jafingerhut** [comment]
It would probably make more sense for your use case if you also made ipv4.srcAddr and ipv4.dstAddr as ternary, like most of the other fields.
