### ISSUE TITLE
P4_16 program struct field name collision causes simple_switch crash

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/behavioral-model#331]
Attached is a fairly short P4_16 program that when compiled with the latest p4c-bm2-ss creates a JSON file, that when read by the latest simple_switch code, causes it to crash.

I believe this is happening because both the structs 'Parsed_packet' and 'metadata' have a field named 'ipv4', but the JSON file does not use full 'path names' to disambiguate this.

Also attaching the JSON file produced.

I know I can work around this by making the member names different, but this seems like something that ought to be allowed and implemented to work correctly, long term.
[name-collision.p4.txt](https://github.com/p4lang/behavioral-model/files/923940/name-collision.p4.txt)
[name-collision.json.txt](https://github.com/p4lang/behavioral-model/files/923942/name-collision.json.txt)

**Comment by antoninbas** [comment]
Shouldn't this be opened with p4c? The JSON should probably be using the full path name, or at least a unique suffix.

**Comment by jafingerhut** [comment]
I'm fine opening an issue for p4c, but maybe bmv2 should give an error about the input file rather than crash?

**Comment by antoninbas** [comment]
Ultimately at the bmv2 level, you only have headers and fields inside headers (if we omit header stacks and the upcoming unions for now). Nested headers are not supported (even for metadata), so everything has to be flattened by the compiler.
So yes I would expect the header string to be 'meta.ipv4' or 'hdr.ipv4'. If the header names in the JSON file are like this, I don't think we need to expect any issue from bmv2.

I do agree that bmv2 should check for name & id duplicates. I'll update the code today and close this issue when I'm done.

**Comment by antoninbas** [comment]
checking for duplicates with #334

**Comment by jafingerhut** [comment]
Working nicely.  Thanks!
