### ISSUE TITLE
Enhancement: sanitize runtime_data indexes in JSON input

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/behavioral-model#337]
See this issue for an example erroneous JSON file the current p4c-bm2-ss can create: https://github.com/p4lang/p4c/issues/497

One nice thing about Java, Python, Clojure, ... vs. C, C++

**Comment by antoninbas** [comment]
I can add a test for this specific issue. However, if we want to be exhaustive in sanitizing the JSON input, there is a lot of code that needs to be written. I'll be honest, this is not a very high priority for me. The user is not expected to write JSON, the user will write P4 that is compiled to JSON by p4c. It would be nice to be able to rely on the correctness of the JSON produced by the compiler. SO usually I had sanity checks as issues arise with the p4c compiler, I'll add one for this issue.
I'm not sure I understand why that would be different in Java / Python / Clojure? Do you mean that the bmv2 action execution engine could be different in these languages (e.g. use names vs indices), or do you mean the JSON sanitizing would be easier (in this case I don't see how)?

**Comment by jafingerhut** [comment]
Sorry for the off-hand comment about Java, Python, etc.  Not really helpful.  Most languages do automatic run-time array index bounds checking.  C/C++/assembly are in the minority there.

Understood that there are all kinds of checks that could be done and they take time to add.  p4c is still kind of alpha/beta in what it generates for bmv2 it seems, and debugging bmv2 crashes on 15,000 line P4 programs is challenging.

**Comment by antoninbas** [comment]
By using the `at` method when using standard library objects, you get runtime bounds checking. Usually I try to do that as much as possible.

**Comment by jafingerhut** [comment]
Warning: like the other sanity check you committed and then backed out for checking for duplicate names, because it caused some automated p4c tests to fail, if there are any p4c test P4 programs that have unused action parameters, this change might cause those tests to fail.  If so, that is because p4c hasn't fixed this issue yet: https://github.com/p4lang/p4c/issues/497

**Comment by antoninbas** [comment]
I doubt they are p4c test P4 programs with unused parameters, but if there are I'll just let them fix the affected test programs.
