### ISSUE TITLE
Configure two different switches in mininet

### ISSUE THREAD

**Issue by huniyaarif1** [p4lang/behavioral-model#340]
I want a topology that is connecting hosts with two different switches l1 and l2 which are also connected to each other. They have different configurations, match+action tables and flow entries. I can add entries in one switch l1. I have given a different sw_path to the switch l2, but how do i add flow entries for this switch?
lb1 = self.addSwitch('l2',
sw_path = nlb_path, //my custom path
thrift_port = thrift_port,
pcap_dump = True)

**Comment by antoninbas** [comment]
Each switch should have its own thrift port. You can then spawn 2 instances of the runtime CLI, one for each switch, each with the appropriate thrift port value. For example:
```
./tools/runtime_CLI --thrift-port 9090
./tools/runtime_CLI --thrift-port 9091
```

**Comment by huniyaarif1** [comment]
Thank you for the quick response.
I did it this way using tutorials/SIGCOMM_2015/source_routing as my base. It assigns different thrift ports to the switches. I'm assigning corresponding json files and command.txt to switches l1 and l2. Their p4 files is in the same folder and the generated json file is created in same directory under different names. The switch path is behavioral-model/targets/simple_switch/simple_switch as explained in the example in run_demo.sh. I'm getting this in runtime_CLI.py:

WARNING: the JSON files loaded into the switch and the one you just provided to this CLI don't have the same md5 sum. Are you sure they describe the same program?
switch md5     : 84b1e820a40c7d557276a58a7c2443ac
CLI input md5  : 33a8728d87a9fdc3fe2e021b8e22bd03

Control utility for runtime P4 table manipulation
RuntimeCmd: *** Unknown syntax: 
This goes on for each line in the json file for the other switch l2.

Can you please guide me if source_routing is the best fit for multiple switches? What am I doing wrong?

**Comment by antoninbas** [comment]
You can use source_routing as your base, but in the source_routing case, all the switches are running the same P4 program, which does not appear to be what you want to do. If you use different P4 programs on you switches, you will need to make quite a few changes.

I think the error you are seeing is pretty much self-explanatory. You appear to be providing a different JSON file to the runtime_CLI than the one you started the switch with.
Note that you don't even need to explicitly provide the JSON file to the runtime_CLI anymore. If you omit the `--json` command-line option when starting the CLI, it will automatically retrieve the JSON configuration from the running switch (you have to provide the correct thrift port); this way you are guaranteed to have the correct JSON.

**Comment by huniyaarif1** [comment]
I made it work. I changed the topo.py so that the switches have different json path. I created their jsons using p4c-bm. The sw path remains the same. 
The runtime_CLI.py is now using commands.txt specific to thrift port. Do you agree with this method? Thank you for the tips.

**Comment by antoninbas** [comment]
Approach sounds correct to me, I am closing this issue.
