### ISSUE TITLE
test_tables.cpp:2575:59: error: left shift of negative value [-Werror=shift-negative-value]

### ISSUE THREAD

**Issue by junghongkao** [p4lang/behavioral-model#360]
run into the following compiler error in make check to run unit test with 
gcc version 6.2.0 20161005 (Ubuntu 6.2.0-5ubuntu12) on ubuntu 16.10

tem../third_party/spdlog -isystem ../third_party/gtest/include -isystem ../third_party/jsoncpp/include -DTESTDATADIR=\"/home/jkao/sdb/bmv2/tests/testdata\"   -pthread -Wall -Werror -Wextra -g -O2 -MT test_tables.o -MD -MP -MF $depbase.Tpo -c -o test_tables.o test_tables.cpp &&\
mv -f $depbase.Tpo $depbase.Po
test_tables.cpp: In function ‘bool {anonymous}::cmp_LPM(const string&, const string&, int)’:
test_tables.cpp:2575:59: error: left shift of negative value [-Werror=shift-negative-value]
     char mask = static_cast<char>(0xff) << (8 - (pref % 8));

It might cast it as <uint> instead
    char mask = static_cast<uint> (0xff) << (8 - (pref % 8));

**Comment by antoninbas** [comment]
should probably cast to `unsigned char` instead, I'll see if I can reproduce this and fix it

**Comment by antoninbas** [comment]
Fixed by https://github.com/p4lang/behavioral-model/pull/361
