### ISSUE TITLE
Divide by zero crash in simple_switch

### ISSUE THREAD

**Issue by sreedhaa** [p4lang/behavioral-model#365]
This is seen occasionally while tearing down lag.
I guess it means simple_switch is trying to replicate multicast packets across LAG members but there aren’t any members added to the LAG?
Is putting a check to avoid divide by zero a complete solution or there may be problem with other areas as well (my suspicion is on sequence of pd calls in switch_api_lag_member_delete())?

kernel:[  296.182623] traps: simple_switch[2594] trap divide error ip:4e0e0f sp:7fb8afffba00 error:0 in simple_switch[400000+183000]

(gdb) bt
#0  0x00000000004e0e0f in bm::McSimplePreLAG::replicate (this=0x1309b50, ingress_info=...) at /usr/src/debug/ops-p4dp/gitAUTOINC+69bb29d1a961a3c1bc87-r0/git/src/bm_sim/simple_pre_lag.cpp:178
#1  0x000000000045603a in SimpleSwitch::ingress_thread (this=0x1305580) at /usr/src/debug/ops-p4dp/gitAUTOINC+69bb29d1a961a3c1bc87-r0/git/targets/simple_switch/simple_switch.cpp:390
#2  0x00007ff09b7042b0 in std::(anonymous namespace)::execute_native_thread_routine (__p=<optimized out>)
    at ../../../../../../../../../../work-shared/gcc-5.3.0-r0/gcc-5.3.0/libstdc++-v3/src/c++11/thread.cc:84
#3  0x00007ff09a3ae394 in start_thread (arg=0x7ff095a7b700) at /usr/src/debug/glibc/2.23-r0/git/nptl/pthread_create.c:333
#4  0x00007ff09a0ed73d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb) p lag_entry
$1 = {member_count = 0, port_map = {port_map = {<std::_Base_bitset<4ul>> = {_M_w = {0, 0, 0, <optimized out>}}, <No data fields>}}}
(gdb) p port_map
$2 = {port_map = {<std::_Base_bitset<4ul>> = {_M_w = {0, 0, 0, 0}}, <No data fields>}}
(gdb) p lag_hash
$3 = 255
(gdb) p lag_index
$4 = 1
(gdb)

**Comment by antoninbas** [comment]
Thanks for reporting this. Should be fixed by #367.
Independently of whether there is an issue in switchapi, bmv2 should not crash because of an invalid PRE configuration.

**Comment by sreedhaa** [comment]
That was quick, thank you!!
