### ISSUE TITLE
simple_switch_grpc

### ISSUE THREAD

**Issue by dingrui37** [p4lang/behavioral-model#371]
I want to use simple_switch_grpc target, but I find an error as below:
hll@hll:/home/opendaylight/p4lang/behavioral-model$ ./autogen.sh 
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:112: installing './compile'
configure.ac:7: installing './missing'
PI/Makefile.am: installing './depcomp'
checking for thrift... /usr/local/bin/thrift
checking thrift/Thrift.h usability... yes
checking thrift/Thrift.h presence... yes
checking for thrift/Thrift.h... yes
checking PI/pi.h usability... no
checking PI/pi.h presence... no
checking for PI/pi.h... no
configure: error: Cannot find PI headers, did you install https://github.com/p4lang/PI/
but I have cloned PI project.
hll@hll:/home/opendaylight/p4lang$ tree -L 1
.
├── behavioral-model
├── p4app
├── p4c-bm
├── p4-hlir
├── PI
└── tutorials-master

**Comment by antoninbas** [comment]
As indicated by the error message you need to install PI. Installing is different than cloning. To install PI, just like for any other project using autotools as the build system, you need to run `./configure` with the appropriate command line parameters, followed by `make` and `[sudo] make install`.
There is a Dockerfile in this repo (https://github.com/p4lang/behavioral-model/blob/master/Dockerfile.grpc) which installs all the dependencies and builds `simple_switch_grpc`. Feel free to get some inspiration there.
