### ISSUE TITLE
flowlet test from tutorials/SIGCOMM_2015/flowlet fails

### ISSUE THREAD

**Issue by jeonsi** [p4lang/behavioral-model#372]
When I send test packets to bmv2 using "sudo ./run_test.py", the bmv2 process dies and the following logs occur:

lt-simple_switch: ../../include/bm/bm_sim/data.h:182: T bm::Data::get() const [with T = long unsigned int; typename std::enable_if<std::is_integral<_Tp>::value, int>::type <anonymous> = 0]: Assertion `arith' failed.
./run_demo.sh: line 42: 19468 Aborted sudo $SWITCH_PATH simple_router.json -i 0@veth0 -i 1@veth2 -i 2@veth4 -i 3@veth6 -i 4@veth8 --nanolog ipc:///tmp/bm-0-log.ipc --pcap

**Comment by antoninbas** [comment]
Thanks for reporting this issue. It has been fixed by #373
