### ISSUE TITLE
simple_switch_grpc install and run problems

### ISSUE THREAD

**Issue by dingrui37** [p4lang/behavioral-model#374]
I have installed PI repository(./autogen.sh & make & make install), then configure bmv2:
```
./configure --with-pi
make
sudo make install
```
but it still only installed the simpe_switch target, so I enter the simple_switch_grpc dir,
```
cd simple_switch_grpc
./autogen.sh
./configure
make
sudo make install
```
and then I find simple_switch_grpc is installed, is there any problems during install the simple_switch_grpc target? I have tryed to build image with Dockerfile, but the network always unreachable.
```
hll@hll:/home/opendaylight/p4lang/behavioral-model/targets/simple_switch_grpc$ sudo simple_switch_grpc ../../../PI/tests/testdata/simple_router.json 
Thrift port was not specified, will use 9090
Calling target program-options parser
Server listening on 0.0.0.0:50051
```
The note "Thrift port was not specified, will use 9090" perhaps is a bug, I checked the port status, 9090 isn't started.
```
hll@hll:/home/opendaylight/p4lang/PI$ netstat -tuan | grep 9090
hll@hll:/home/opendaylight/p4lang/PI$ netstat -tuan | grep 50051
tcp6       0      0 :::50051                :::*                    LISTEN   
```
Now, I can write my grpc client code to connect to 50051(just as  PI/examples/example_1.c), is it right?

**Comment by antoninbas** [comment]
This all looks good to me, you can ignore the "Thrift port was not specified, will use 9090" message.
You can indeed connect to port 50051 with a gRPC client and send P4Runtime messages. However, this is totally different from PI/examples/example_1.c, which is using the PI C API directly (not the P4Runtime RPC interface). You can find an example here: https://github.com/p4lang/behavioral-model/blob/master/targets/simple_switch_grpc/tests/test.cpp#L88

**Comment by WangchukSherpa** [comment]
Even after performing all the installation process for installing the simple_switch_grpc .

**![Screenshot from Screencast from 02-23-2024 08:18:35 AM webm](https://github.com/p4lang/behavioral-model/assets/95025561/84f77c7b-8d7e-47e4-8733-c2aceeed1c11)**

**Comment by WangchukSherpa** [comment]
Even after performing all the installation process for installing the simple_switch_grpc .
ERROR
**simple_switch_grpc: No such file or directory**
![Screenshot from Screencast from 03-06-2024 12:26:33 PM webm](https://github.com/p4lang/behavioral-model/assets/95025561/db21d9e4-876f-40b4-9568-6f1bd04c3811)

**Comment by WangchukSherpa** [comment]
Even after performing all the installation process for installing the simple_switch_grpc .
ERROR
simple_switch_grpc: No such file or directory
![Uploading Screenshot from Screencast from 03-06-2024 12:26:33 PM.webm.png…]()

**Comment by WangchukSherpa** [comment]
Even after performing all the installation process for installing the simple_switch_grpc .
ERROR
**![Screenshot from Screencast from 03-06-2024 12:26:33 PM webm](https://github.com/p4lang/behavioral-model/assets/95025561/58b204e9-0f2b-46d2-b3ee-b73fe734620e)**

**Comment by WangchukSherpa** [comment]
Even after following each and every installation process for simple_switch_grpc
ERROR
**simple_switch_grpc: command not found**

![Screenshot from Screencast from 03-06-2024 12:26:33 PM webm](https://github.com/p4lang/behavioral-model/assets/95025561/77012ba8-8d5a-400e-9852-2532e225d783)

**Comment by jafingerhut** [comment]
There are only a few ways to install the open source P4 development tools so that they all work together to run these tutorials. There are thousands of variations on those that do not quite work.

If you have used one of the two methods described on this page https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md
then those are some of the few ways I have personally tested to work.

If you have used any other way to install open source P4 development tools, then I do not think that I have time to spend helping you debug your setup. Maybe someone else might, but they would need to know a lot of details about exactly how your system was installed.
