### ISSUE TITLE
test simple_switch_grpc code problems

### ISSUE THREAD

**Issue by dingrui37** [p4lang/behavioral-model#376]
@antoninbas According to your advice,  I have readed  the example(targets/simple_switch_grpc/tests/test.cpp), but I need to write a java client, so I want to ask you a few questions.

1. why we need simple_router.proto.txt ?
 I think perhaps it is a "DB", because there isn't a API which can query id by name, the file is used to simulate
query result.
2. what's the meaning of Entity and ExternEntry ? I am confused about them. I have searched p4 spec(p4_14), but nothing was found.
```
message Entity {
  oneof entity {
    ExternEntry extern_entry = 1;
    TableEntry table_entry = 2;
    ActionProfileMember action_profile_member = 3;
    ActionProfileGroup action_profile_group = 4;
    MeterEntry meter_entry = 5;
    DirectMeterEntry direct_meter_entry = 6;
    CounterEntry counter_entry = 7;
    DirectCounterEntry direct_counter_entry = 8;
  }
}
```
```
message ExternEntry {
  // the extern_type_id is assigned during compilation. It is likely that this
  // id will in fact come from a P4 annotation to the extern declaration and
  // that each vendor will receive a prefix to avoid collisions.
  uint32 extern_type_id = 1;
  uint32 extern_id = 2;  // id of the instance
  google.protobuf.Any entry = 3;
}

```

**Comment by antoninbas** [comment]
1. This serialized protobuf message is the output of the P4 compiler. Among other things it maps P4 names to P4Runtime / PI IDs. There is no DB per se; if you want to build an in-memory database, you have to parse this file and instantiate it yourself. We are not trying to simulate anything, this is the actual compiler output.
2. P4Runtime is meant to be usable for P4 programs written in P4_14 or P4_16. The P4_16 language supports externs. An "Entity" has no P4 equivalent. It is just the way we decided to write the API. An Entity is either a table entry, a counter entry, an extern entry...

**Comment by dingrui37** [comment]
I am still confused, how to generate simple_router.proto.txt? I think the whole process should be like this.
first start a simple_switch_grpc target with xxx.json
`simple_switch_grpc xxx.json`
then start a client connect to gRPC server, use specific RPC to query id by name, such as table name, action name, etc. 
why we use  simple_router.proto.txt?

**Comment by antoninbas** [comment]
The bmv2 json file is not required to include the mapping you are describing and it doesn't. bmv2 does not know about the P4Runtime IDs.
Also what you are describing conflicts with the actual expected workflow:
1. the P4 device starts without any P4 configuration (no forwarding happens). This can be done in bmv2 using the --no-p4 flag.
2. the controller receives a new P4 configuration from the compiler. This includes the P4Info data (e.g. simple_router.proto.txt). For bmv2, this also includes the bmv2 input JSON.
3. the controller sends the P4 configuration to the P4 device
With this workflow the control-plane is aware of the name -> id mapping before the P4 device. We don't believe there is any interest in the RPC you are describing. As I said before you can load the P4Info and store it in memory in any format you want.
By the way to generate the P4Info data for a given P4 program, you need to run the p4c compiler for the bmv2 backend with the `--p4runtime-file` flag: `p4c-bm2-ss <P4 program> --p4runtime-file <x.proto.txt> --p4runtime-format text`. The reason why I have checked in simple_router.proto.txt in this repository is to make it convenient to run the `test` program.

**Comment by antoninbas** [comment]
Note that the workflow I am describing has not been fully implemented yet.
