### ISSUE TITLE
send packets with 13000KB/S to bmv2,but only receive 1020KB/S

### ISSUE THREAD

**Issue by cool-leng** [p4lang/behavioral-model#393]
HI,

I make the test as following  procedure to test bmv2's gbps : 

1、/p4/behavioral-model# sudo targets/simple_switch/simple_switch -i 0@veth2 -i 1@veth4 rm.json
2、add entry
table_add rm_color_LSID_exact_nhop set_nport 0x000102030405060708090a0b0c0d0e0f10111213 => 1
table_add rm_color_LSID_exact_nhop set_nport 0x020102030405060708090a0b0c0d0e0f10111213 => 1
table_add rm_color_LSID_exact_nhop set_nport 0x030102030405060708090a0b0c0d0e0f10111213 => 1
table_add rm_color_LSID_exact_push_next_pid push_new_pid 1 => 0x020057f8
table_add forward set_dmac 1 => 0x333333333333
table_add send rewrite_smac 1 => 0x222222222222
table_add rm_color_LSID_exact_nhop set_nport 0x010102030405060708090a0b0c0d0e0f10111213 => 2
table_add forward set_dmac 2 => 0xaaaaaaaaaaaa
table_add send rewrite_smac 2 => 0x222222222222
3、tx send packets by click with 13000KB/S speed to bmv2,but rx only receive packets  1020KB/S

I don't know why bmv2 can't receive packet with 13000KB/S speed,is there any limit?

Thank you!

Cool

**Comment by antoninbas** [comment]
I don't know why you are including a bunch of CLI commands, they are pretty useless without the P4 program. The topic of bmv2 performance has been covered in several issues and p4-dev email threads already. See for example: https://github.com/p4lang/behavioral-model/issues/301
bmv2 simple_switch should be able to achieve 100Mbps on all but the nastiest of P4 programs (with the right compilation flags).

**Comment by cool-leng** [comment]
@antoninbas ,thank you for your replay!
I write a piece of P4 code,and compile to JSON,then run the test, I wanted add JSON file to attachment but failed,json like the following:
{
    "__meta__": {
        "version": [
            2,
            5
        ],
        "compiler": "https://github.com/p4lang/p4c-bm"
    },
    "header_types": [
        {
            "name": "standard_metadata_t",
            "id": 0,
            "fields": [
                [
                    "ingress_port",
                    9
                ],
                [
                    "packet_length",
                    32
                ],
                [
                    "egress_spec",
                    9
                ],
                [
                    "egress_port",
                    9
                ],
                [
                    "egress_instance",
                    32
                ],
                [
                    "instance_type",
                    32
                ],
                [
                    "clone_spec",
                    32
                ],
                [
                    "_padding",
                    5
                ]
            ],
            "length_exp": null,
            "max_length": null
        },
        {
            "name": "ethernet_t",
            "id": 1,
            "fields": [
                [
                    "dstAddr",
                    48
                ],
                [
                    "srcAddr",
                    48
                ],
                [
                    "etherType",
                    16
                ]
            ],
            "length_exp": null,
            "max_length": null
        },
        {
            "name": "ipv4_t",
            "id": 2,
            "fields": [
                [
                    "version",
                    4
                ],
                [
                    "ihl",
                    4
                ],
                [
                    "diffserv",
                    8
                ],
                [
                    "totalLen",
                    16
                ],
                [
                    "identification",
                    16
                ],
                [
                    "flags",
                    3
                ],
                [
                    "fragOffset",
                    13
                ],
                [
                    "ttl",
                    8
                ],
                [
                    "protocol",
                    8
                ],
                [
                    "hdrChecksum",
                    16
                ],
                [
                    "srcAddr",
                    32
                ],
                [
                    "dstAddr",
                    32
                ]
            ],
            "length_exp": null,
            "max_length": null
        },
        {
            "name": "color_t",
            "id": 3,
            "fields": [
                [
                    "version_Type",
                    8
                ],
                [
                    "ttl",
                    8
                ],
                [
                    "total_len",
                    16
                ],
                [
                    "port_no1",
                    16
                ],
                [
                    "port_no2",
                    16
                ],
                [
                    "minpid",
                    16
                ],
                [
                    "pids_o",
                    8
                ],
                [
                    "oqkres",
                    8
                ],
                [
                    "mtu",
                    16
                ],
                [
                    "checksum",
                    16
                ],
                [
                    "nid_s",
                    128
                ],
                [
                    "l_sid",
                    160
                ],
                [
                    "nid_c",
                    128
                ],
                [
                    "mac",
                    32
                ],
                [
                    "offset",
                    32
                ],
                [
                    "Length",
                    32
                ],
                [
                    "data",
                    64
                ]
            ],
            "length_exp": null,
            "max_length": null
        },
        {
            "name": "color_pid_t",
            "id": 4,
            "fields": [
                [
                    "pid",
                    32
                ]
            ],
            "length_exp": null,
            "max_length": null
        },
        {
            "name": "my_metadata_t",
            "id": 5,
            "fields": [
                [
                    "color_total_len",
                    16
                ],
                [
                    "packet_length",
                    16
                ],
                [
                    "pid_count",
                    16
                ]
            ],
            "length_exp": null,
            "max_length": null
        }
    ],
    "headers": [
        {
            "name": "standard_metadata",
            "id": 0,
            "header_type": "standard_metadata_t",
            "metadata": true
        },
        {
            "name": "ethernet",
            "id": 1,
            "header_type": "ethernet_t",
            "metadata": false
        },
        {
            "name": "ipv4",
            "id": 2,
            "header_type": "ipv4_t",
            "metadata": false
        },
        {
            "name": "color",
            "id": 3,
            "header_type": "color_t",
            "metadata": false
        },
        {
            "name": "pid[0]",
            "id": 4,
            "header_type": "color_pid_t",
            "metadata": false
        },
        {
            "name": "pid[1]",
            "id": 5,
            "header_type": "color_pid_t",
            "metadata": false
        },
        {
            "name": "pid[2]",
            "id": 6,
            "header_type": "color_pid_t",
            "metadata": false
        },
        {
            "name": "pid[3]",
            "id": 7,
            "header_type": "color_pid_t",
            "metadata": false
        },
        {
            "name": "pid[4]",
            "id": 8,
            "header_type": "color_pid_t",
            "metadata": false
        },
        {
            "name": "pid[5]",
            "id": 9,
            "header_type": "color_pid_t",
            "metadata": false
        },
        {
            "name": "pid[6]",
            "id": 10,
            "header_type": "color_pid_t",
            "metadata": false
        },
        {
            "name": "pid[7]",
            "id": 11,
            "header_type": "color_pid_t",
            "metadata": false
        },
        {
            "name": "pid[8]",
            "id": 12,
            "header_type": "color_pid_t",
            "metadata": false
        },
        {
            "name": "pid[9]",
            "id": 13,
            "header_type": "color_pid_t",
            "metadata": false
        },
        {
            "name": "pid[10]",
            "id": 14,
            "header_type": "color_pid_t",
            "metadata": false
        },
        {
            "name": "pid[11]",
            "id": 15,
            "header_type": "color_pid_t",
            "metadata": false
        },
        {
            "name": "pid[12]",
            "id": 16,
            "header_type": "color_pid_t",
            "metadata": false
        },
        {
            "name": "pid[13]",
            "id": 17,
            "header_type": "color_pid_t",
            "metadata": false
        },
        {
            "name": "pid[14]",
            "id": 18,
            "header_type": "color_pid_t",
            "metadata": false
        },
        {
            "name": "pid[15]",
            "id": 19,
            "header_type": "color_pid_t",
            "metadata": false
        },
        {
            "name": "pid[16]",
            "id": 20,
            "header_type": "color_pid_t",
            "metadata": false
        },
        {
            "name": "pid[17]",
            "id": 21,
            "header_type": "color_pid_t",
            "metadata": false
        },
        {
            "name": "pid[18]",
            "id": 22,
            "header_type": "color_pid_t",
            "metadata": false
        },
        {
            "name": "pid[19]",
            "id": 23,
            "header_type": "color_pid_t",
            "metadata": false
        },
        {
            "name": "my_metadata",
            "id": 24,
            "header_type": "my_metadata_t",
            "metadata": true
        }
    ],
    "header_stacks": [
        {
            "name": "pid",
            "id": 0,
            "size": 20,
            "header_type": "color_pid_t",
            "header_ids": [
                4,
                5,
                6,
                7,
                8,
                9,
                10,
                11,
                12,
                13,
                14,
                15,
                16,
                17,
                18,
                19,
                20,
                21,
                22,
                23
            ]
        }
    ],
    "parsers": [
        {
            "name": "parser",
            "id": 0,
            "init_state": "start",
            "parse_states": [
                {
                    "name": "start",
                    "id": 0,
                    "parser_ops": [],
                    "transition_key": [],
                    "transitions": [
                        {
                            "type": "default",
                            "value": null,
                            "mask": null,
                            "next_state": "parse_ethernet"
                        }
                    ]
                },
                {
                    "name": "parse_ethernet",
                    "id": 1,
                    "parser_ops": [
                        {
                            "op": "extract",
                            "parameters": [
                                {
                                    "type": "regular",
                                    "value": "ethernet"
                                }
                            ]
                        }
                    ],
                    "transition_key": [
                        {
                            "type": "field",
                            "value": [
                                "ethernet",
                                "etherType"
                            ]
                        }
                    ],
                    "transitions": [
                        {
                            "type": "hexstr",
                            "value": "0x0800",
                            "mask": null,
                            "next_state": "parse_ipv4"
                        },
                        {
                            "type": "default",
                            "value": null,
                            "mask": null,
                            "next_state": null
                        }
                    ]
                },
                {
                    "name": "parse_ipv4",
                    "id": 2,
                    "parser_ops": [
                        {
                            "op": "extract",
                            "parameters": [
                                {
                                    "type": "regular",
                                    "value": "ipv4"
                                }
                            ]
                        }
                    ],
                    "transition_key": [],
                    "transitions": [
                        {
                            "type": "default",
                            "value": null,
                            "mask": null,
                            "next_state": "parse_color"
                        }
                    ]
                },
                {
                    "name": "parse_color",
                    "id": 3,
                    "parser_ops": [
                        {
                            "op": "extract",
                            "parameters": [
                                {
                                    "type": "regular",
                                    "value": "color"
                                }
                            ]
                        },
                        {
                            "op": "set",
                            "parameters": [
                                {
                                    "type": "field",
                                    "value": [
                                        "my_metadata",
                                        "color_total_len"
                                    ]
                                },
                                {
                                    "type": "field",
                                    "value": [
                                        "color",
                                        "total_len"
                                    ]
                                }
                            ]
                        },
                        {
                            "op": "set",
                            "parameters": [
                                {
                                    "type": "field",
                                    "value": [
                                        "my_metadata",
                                        "pid_count"
                                    ]
                                },
                                {
                                    "type": "expression",
                                    "value": {
                                        "type": "expression",
                                        "value": {
                                            "op": "-",
                                            "left": {
                                                "type": "expression",
                                                "value": {
                                                    "op": "/",
                                                    "left": {
                                                        "type": "field",
                                                        "value": [
                                                            "color",
                                                            "total_len"
                                                        ]
                                                    },
                                                    "right": {
                                                        "type": "hexstr",
                                                        "value": "0x4"
                                                    }
                                                }
                                            },
                                            "right": {
                                                "type": "hexstr",
                                                "value": "0x16"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    ],
                    "transition_key": [],
                    "transitions": [
                        {
                            "type": "default",
                            "value": null,
                            "mask": null,
                            "next_state": "parse_next_color_pid"
                        }
                    ]
                },
                {
                    "name": "parse_next_color_pid",
                    "id": 4,
                    "parser_ops": [],
                    "transition_key": [
                        {
                            "type": "field",
                            "value": [
                                "my_metadata",
                                "pid_count"
                            ]
                        }
                    ],
                    "transitions": [
                        {
                            "type": "hexstr",
                            "value": "0x0000",
                            "mask": null,
                            "next_state": null
                        },
                        {
                            "type": "default",
                            "value": null,
                            "mask": null,
                            "next_state": "parse_color_pid"
                        }
                    ]
                },
                {
                    "name": "parse_color_pid",
                    "id": 5,
                    "parser_ops": [
                        {
                            "op": "extract",
                            "parameters": [
                                {
                                    "type": "stack",
                                    "value": "pid"
                                }
                            ]
                        },
                        {
                            "op": "set",
                            "parameters": [
                                {
                                    "type": "field",
                                    "value": [
                                        "my_metadata",
                                        "pid_count"
                                    ]
                                },
                                {
                                    "type": "expression",
                                    "value": {
                                        "type": "expression",
                                        "value": {
                                            "op": "-",
                                            "left": {
                                                "type": "field",
                                                "value": [
                                                    "my_metadata",
                                                    "pid_count"
                                                ]
                                            },
                                            "right": {
                                                "type": "hexstr",
                                                "value": "0x1"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    ],
                    "transition_key": [],
                    "transitions": [
                        {
                            "type": "default",
                            "value": null,
                            "mask": null,
                            "next_state": "parse_next_color_pid"
                        }
                    ]
                }
            ]
        }
    ],
    "parse_vsets": [],
    "deparsers": [
        {
            "name": "deparser",
            "id": 0,
            "order": [
                "ethernet",
                "ipv4",
                "color",
                "pid[0]",
                "pid[1]",
                "pid[2]",
                "pid[3]",
                "pid[4]",
                "pid[5]",
                "pid[6]",
                "pid[7]",
                "pid[8]",
                "pid[9]",
                "pid[10]",
                "pid[11]",
                "pid[12]",
                "pid[13]",
                "pid[14]",
                "pid[15]",
                "pid[16]",
                "pid[17]",
                "pid[18]",
                "pid[19]"
            ]
        }
    ],
    "meter_arrays": [],
    "actions": [
        {
            "name": "rewrite_smac",
            "id": 0,
            "runtime_data": [
                {
                    "name": "smac",
                    "bitwidth": 48
                }
            ],
            "primitives": [
                {
                    "op": "modify_field",
                    "parameters": [
                        {
                            "type": "field",
                            "value": [
                                "ethernet",
                                "srcAddr"
                            ]
                        },
                        {
                            "type": "runtime_data",
                            "value": 0
                        }
                    ]
                }
            ]
        },
        {
            "name": "_drop",
            "id": 1,
            "runtime_data": [],
            "primitives": [
                {
                    "op": "drop",
                    "parameters": []
                }
            ]
        },
        {
            "name": "set_dmac",
            "id": 2,
            "runtime_data": [
                {
                    "name": "dmac",
                    "bitwidth": 48
                }
            ],
            "primitives": [
                {
                    "op": "modify_field",
                    "parameters": [
                        {
                            "type": "field",
                            "value": [
                                "ethernet",
                                "dstAddr"
                            ]
                        },
                        {
                            "type": "runtime_data",
                            "value": 0
                        }
                    ]
                }
            ]
        },
        {
            "name": "set_nport",
            "id": 3,
            "runtime_data": [
                {
                    "name": "port",
                    "bitwidth": 9
                }
            ],
            "primitives": [
                {
                    "op": "modify_field",
                    "parameters": [
                        {
                            "type": "field",
                            "value": [
                                "standard_metadata",
                                "egress_spec"
                            ]
                        },
                        {
                            "type": "runtime_data",
                            "value": 0
                        }
                    ]
                }
            ]
        },
        {
            "name": "push_new_pid",
            "id": 4,
            "runtime_data": [
                {
                    "name": "newpid",
                    "bitwidth": 32
                }
            ],
            "primitives": [
                {
                    "op": "modify_field",
                    "parameters": [
                        {
                            "type": "field",
                            "value": [
                                "pid[0]",
                                "pid"
                            ]
                        },
                        {
                            "type": "runtime_data",
                            "value": 0
                        }
                    ]
                },
                {
                    "op": "push",
                    "parameters": [
                        {
                            "type": "header_stack",
                            "value": "pid"
                        },
                        {
                            "type": "hexstr",
                            "value": "0x1"
                        }
                    ]
                },
                {
                    "op": "modify_field",
                    "parameters": [
                        {
                            "type": "field",
                            "value": [
                                "pid[0]",
                                "pid"
                            ]
                        },
                        {
                            "type": "hexstr",
                            "value": "0x0"
                        }
                    ]
                },
                {
                    "op": "add_to_field",
                    "parameters": [
                        {
                            "type": "field",
                            "value": [
                                "color",
                                "minpid"
                            ]
                        },
                        {
                            "type": "hexstr",
                            "value": "0x1"
                        }
                    ]
                },
                {
                    "op": "add_to_field",
                    "parameters": [
                        {
                            "type": "field",
                            "value": [
                                "color",
                                "total_len"
                            ]
                        },
                        {
                            "type": "hexstr",
                            "value": "0x4"
                        }
                    ]
                },
                {
                    "op": "add_to_field",
                    "parameters": [
                        {
                            "type": "field",
                            "value": [
                                "ipv4",
                                "totalLen"
                            ]
                        },
                        {
                            "type": "hexstr",
                            "value": "0x4"
                        }
                    ]
                }
            ]
        }
    ],
    "pipelines": [
        {
            "name": "ingress",
            "id": 0,
            "init_table": "rm_color_LSID_exact_nhop",
            "tables": [
                {
                    "name": "rm_color_LSID_exact_nhop",
                    "id": 0,
                    "match_type": "exact",
                    "type": "simple",
                    "max_size": 16384,
                    "with_counters": false,
                    "direct_meters": null,
                    "support_timeout": false,
                    "key": [
                        {
                            "match_type": "exact",
                            "target": [
                                "color",
                                "l_sid"
                            ],
                            "mask": null
                        }
                    ],
                    "actions": [
                        "set_nport",
                        "_drop"
                    ],
                    "next_tables": {
                        "set_nport": "rm_color_LSID_exact_push_next_pid",
                        "_drop": "rm_color_LSID_exact_push_next_pid"
                    },
                    "base_default_next": "rm_color_LSID_exact_push_next_pid"
                },
                {
                    "name": "rm_color_LSID_exact_push_next_pid",
                    "id": 1,
                    "match_type": "exact",
                    "type": "simple",
                    "max_size": 16384,
                    "with_counters": false,
                    "direct_meters": null,
                    "support_timeout": false,
                    "key": [
                        {
                            "match_type": "exact",
                            "target": [
                                "standard_metadata",
                                "egress_spec"
                            ],
                            "mask": null
                        }
                    ],
                    "actions": [
                        "push_new_pid",
                        "_drop"
                    ],
                    "next_tables": {
                        "push_new_pid": "forward",
                        "_drop": "forward"
                    },
                    "base_default_next": "forward"
                },
                {
                    "name": "forward",
                    "id": 2,
                    "match_type": "exact",
                    "type": "simple",
                    "max_size": 16384,
                    "with_counters": false,
                    "direct_meters": null,
                    "support_timeout": false,
                    "key": [
                        {
                            "match_type": "exact",
                            "target": [
                                "standard_metadata",
                                "egress_spec"
                            ],
                            "mask": null
                        }
                    ],
                    "actions": [
                        "set_dmac",
                        "_drop"
                    ],
                    "next_tables": {
                        "set_dmac": null,
                        "_drop": null
                    },
                    "base_default_next": null
                }
            ],
            "action_profiles": [],
            "conditionals": []
        },
        {
            "name": "egress",
            "id": 1,
            "init_table": "send",
            "tables": [
                {
                    "name": "send",
                    "id": 3,
                    "match_type": "exact",
                    "type": "simple",
                    "max_size": 16384,
                    "with_counters": false,
                    "direct_meters": null,
                    "support_timeout": false,
                    "key": [
                        {
                            "match_type": "exact",
                            "target": [
                                "standard_metadata",
                                "egress_port"
                            ],
                            "mask": null
                        }
                    ],
                    "actions": [
                        "rewrite_smac",
                        "_drop"
                    ],
                    "next_tables": {
                        "rewrite_smac": null,
                        "_drop": null
                    },
                    "base_default_next": null
                }
            ],
            "action_profiles": [],
            "conditionals": []
        }
    ],
    "calculations": [],
    "checksums": [],
    "learn_lists": [],
    "field_lists": [],
    "counter_arrays": [],
    "register_arrays": [],
    "force_arith": [
        [
            "standard_metadata",
            "ingress_port"
        ],
        [
            "standard_metadata",
            "packet_length"
        ],
        [
            "standard_metadata",
            "egress_spec"
        ],
        [
            "standard_metadata",
            "egress_port"
        ],
        [
            "standard_metadata",
            "egress_instance"
        ],
        [
            "standard_metadata",
            "instance_type"
        ],
        [
            "standard_metadata",
            "clone_spec"
        ],
        [
            "standard_metadata",
            "_padding"
        ]
    ]
}

**Comment by antoninbas** [comment]
I am not sure what you expect me to do with this JSON. Also, why do you have large numbers like `0x000102030405060708090a0b0c0d0e0f10111213` in your CLI commands.
Please follow the instructions to get a performance build of bmv2 (the most important things are compiling with O2 and disabling logging macros) and run your experiment again. Also make sure that the rate on the ingress interface is what you expect.

**Comment by antoninbas** [comment]
closing this as no update
