### ISSUE TITLE
Misbehavior (assertion error) when interpreting bool type 

### ISSUE THREAD

**Issue by Xingdao-Fan** [p4lang/behavioral-model#399]
simple_switch seems to misbehave when interpreting the bool type. I've used option `-v` to dump passes, as Mihai taught me, and it doesn't seem to be compiler-related, as the expressions in question are translated exactly as written by the final backend pass. 

## 1
I can write the following:
```C++
m.metafield = true;

if (m.metafield) {
  //something happens
}
```
and it works just fine.

## 2
However, if I move the statement `m.metafield = true;` to the parser, the program produces awkward behavior.
```C++
parser TopParser(packet_in b, out Parsed_packet p, inout Meta m,
    inout standard_metadata_t metadata) {

  state start {
    m.metafield = true;
    transition accept;
  }
}

control IngressP(inout Parsed_packet hdr,
                      inout Meta m,
                      inout standard_metadata_t standard_metadata) {
apply {
  if (!m.metafield) {
    //something happens
  }
}
```

An excerpt of the output switch log:
> [11:24:12.581] [bmv2] [D] [thread 4689] [38.0] [cxt 0] Parser set: setting field 'scalars.Meta.metafield' from expression, new value is 1
> [11:24:12.581] [bmv2] [T] [thread 4689] [38.0] [cxt 0] skeleton.p4(65) Condition "!m.metafieldfield" is true

## 3
If I replace `if (!m.metafield)` for `if (m.metafield == false)`, the switch doesn't even start, and the log shows:

> lt-simple_switch: P4Objects.cpp:293: void bm::P4Objects::build_expression(const Json::Value&, bm::Expression*, bm::P4Objects::ExprType*): Assertion `typeL == typeR' failed.

## Complete P4 program
```C++
#include <v1model.p4>

//------------------------------------------
header fixedLenHeader_h {
   bit<64> field;
}

//------------------------------------------
struct Meta {
   bool metafield;
}

struct Parsed_packet {
   fixedLenHeader_h h;
}

//------------------------------------------
parser TopParser(packet_in b, out Parsed_packet p, inout Meta m,
    inout standard_metadata_t metadata) {

  state start {
    m.metafield = true;
    transition accept;
  }
}

control VeryChecksum(in Parsed_packet hdr, inout Meta meta) { apply {} }

control IngressP(inout Parsed_packet hdr,
                      inout Meta m,
                      inout standard_metadata_t standard_metadata) {

  apply {
    if (m.metafield == false) {
      hdr.h.field = 64w5;
    }
  }
}

control EgressP(inout Parsed_packet hdr,
                     inout Meta meta,
                     inout standard_metadata_t standard_metadata) { apply {} }

control ChecksumComputer(inout Parsed_packet hdr,
                              inout Meta meta) { apply {} }

control TopDeparser(packet_out b, in Parsed_packet hdr) { apply {} }

V1Switch(TopParser(), VeryChecksum(), IngressP(), EgressP(), ChecksumComputer(),
    TopDeparser()) main;
```

**Comment by Xingdao-Fan** [comment]
UPDATE to the issue code: I erroneously wrote `if (m.metadata)` when it should read `if (!m.metadata)`.

**Comment by antoninbas** [comment]
As per the input JSON format documentation, implicit conversions between "bool" and "data", which are 2 types supported by bmv2, are not supported. The compiler needs to use the `b2d` (bool-to-data) and `d2b` (data-to-bool) cast operations. The compiler does this correctly in most places, but apparently you found a case where it is not introducing a `b2d` cast even though it should. I have confirmed that by looking at the generated JSON. So it is indeed a compiler bug.
