### ISSUE TITLE
Question: How to distinguish packet direction on bidirectional interfaces?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/behavioral-model#403]
This is in the context of examples where simple_switch is started with options like -i <port_num>@veth<number> for one or more ports bound to veth interfaces.

I realize that for P4 programs running on bmv2, there is no issue or problem here -- if some program sends a packet to an appropriate veth, simple_switch treats it as a received packet and sends it through the parser, ingress processing, packet buffer, egress processing, deparsing, and then (optionally) sends it out another port, which will be transmitted on the corresponding veth interface.

My question is this: Is there a recommended way from a process that is monitoring all of this from outside of the simple_switch process, only watching veth interface activity, e.g. via Scapy's sniff call, to distinguish whether a packet is one sent from outside, to simple_switch, vs. a packet sent by simple_switch, to the outside?  I can use programs like tcpdump, tshark, and Scapy's sniff to see all packets passing across a veth, but it shows packets in both directions, and I haven't seen a way to distinguish which 'direction' the packet is flowing.

If it isn't possible by only watching the veth interface activity, is there another way to observe all packets into and out of simple_switch that lets the observer know the packet direction?  Perhaps the nanomsg interface to simple_switch?

**Comment by antoninbas** [comment]
Well that's not really specific to bmv2 but the following should work:
- in tcpdump, you can use the `--direction=[in|out]` option. You can also use the `inbound|outbound` BPF filter. I don't know if there is a subtle difference between the 2, they both seem to work for me (using the BPF filter seems to drop the first packet for some reason, that may be a bug in libpcap, see https://github.com/the-tcpdump-group/libpcap/issues/405).
- scapy's sniff function supports arbitrary BPF filters as far as I know, so you should be able to use `inbound|outbound` there as well.
Note that according to the documentation (http://www.tcpdump.org/tcpdump_man.html, http://biot.com/capstats/bpf.html) these things may not be available on all platforms.

**Comment by jafingerhut** [comment]
Here is another answer I learned after sending out my earlier question: Use
the --use-files command line option to simple_switch.  If you have also
command line options to specify port/interface mappings like "-i 0@pcap0 -i
1@pcap1 -i 2@pcap2" etc., then simple_switch will read pcap files from the
file pcap0_in.pcap for input packets, and write packets to pcap0_out.pcap
for output packets.  These files can be created as named pipes instead of
normal files, if you want their contents to be generated 'live' while
simple_switch runs.  This is exactly what run-bmv2-test.py does today.

This technique also has the benefit of avoiding the IPv6 Neighbor Discovery
packets that Linux occasionally sends to virtual Ethernet interfaces, that
can make it more difficult to debug the packets you care about.

Andy
