### ISSUE TITLE
setForwardingPipelineConfig problem

### ISSUE THREAD

**Issue by dingrui37** [p4lang/behavioral-model#407]
I use simple_switch_grpc target,  read simple_router.proto.txt to build p4info and simple_router.json to build p4_device_config, but when I do setForwardingPipelineConfig RPC, it always throw an runtime exception and gives a message "INVALID ARGUMENT".
```
message ForwardingPipelineConfig {
  uint64 device_id = 1;
  config.P4Info p4info = 2;
  // Target-specific P4 configuration.
  bytes p4_device_config = 3;
}
```
 I start the target use the following command. when I try use grpc to set pipeline config from Opendaylight, it prints "P4Runtime SetForwardingPipelineConfig".
```
hll@hll:~$ simple_switch_grpc --no-p4
Thrift port was not specified, will use 9090
Calling target program-options parser
Server listening on 0.0.0.0:50051
P4Runtime SetForwardingPipelineConfig
P4Runtime SetForwardingPipelineConfig
P4Runtime SetForwardingPipelineConfig
P4Runtime SetForwardingPipelineConfig
P4Runtime SetForwardingPipelineConfig
P4Runtime SetForwardingPipelineConfig
```
when I start simple_switch_grpc with simple_router.json, and comment the p4_device_config relevant code,
then then runtime exception disappeared, but I still don't the RPC results, because the setForwardingPipelineConfig defination has no field. My java code is shown as below.
```
    public void setForwardingPipelineConfig() {
        P4Info.Builder p4InfoBuilder = P4Info.newBuilder();

        try {
            TextFormat.merge(new FileReader("simple_router.proto.txt"), p4InfoBuilder);
        } catch (IOException e) {
            LOG.info("simple_router.proto.txt file not found");
        }

        ForwardingPipelineConfig.Builder configBuilder = ForwardingPipelineConfig.newBuilder();
        configBuilder.setDeviceId(0);
        configBuilder.setP4Info(p4InfoBuilder.build());
        /*
        try {
            configBuilder.setP4DeviceConfig(ByteString.readFrom(new FileInputStream("simple_router.json")));
        } catch (IOException e) {
            LOG.info("simple_router.json file not found");
        }
        */
        SetForwardingPipelineConfigRequest request = SetForwardingPipelineConfigRequest.newBuilder()
                                                     .setAction(VERIFY_AND_COMMIT)
                                                     .addConfigs(configBuilder.build())
                                                     .build();
        SetForwardingPipelineConfigResponse response;

        try {
            response = blockingStub.setForwardingPipelineConfig(request);
        } catch (StatusRuntimeException e) {
            LOG.info("RPC failed: {}", e.getStatus());
        }
    }
```
Is the p4_device_config field not support now? I want to ask some other questions. what's the meaning of the device_id field?  I think it means the number of P4 chips,  a board may contains many P4 chips, but for bmv2 it must be 0, is it right?

In the demo(https://github.com/p4lang/behavioral-model/blob/master/targets/simple_switch_grpc/tests/test.cpp), it doesn't set the  p4_device_config field, where does the bmv2 run logical come from?  I think p4_device_config  and p4info  must be set when initialize bmv2.  What will happen when p4info  and p4_device_config come from different P4 source code?

**Comment by antoninbas** [comment]
The `p4_device_config` cannot be just the bmv2 JSON. It needs to be a serialization of this protobuf message: https://github.com/p4lang/PI/blob/master/proto/p4/tmp/p4config.proto#L22
I actually just pushed a big update to both this repo and the PI repo to clean-up the implementation of `SetForwardingPipelineConfig`, so I invite you to try again.
I also think you should take a look at example.cpp (https://github.com/p4lang/behavioral-model/blob/master/targets/simple_switch_grpc/tests/example.cpp) which is the updated version of test.cpp. In particular you'll notice that simple_router.json is now sent to the switch as part of the `SetForwardingPipelineConfigRequest`.

You are mostly correct about the device_id. The simple_switch_grpc design implies that in each process you have one gRPC server controlling a single device. However the device_id that you use in the P4Runtime messages should match the device id you choose when starting simple_switch_grpc. By default it is 0, but you can pick a different value with the `--device-id` command-line option. For example: `simple_switch_grpc --no-p4 --device-id 99`.

Once again, make sure you have the latest version of the PI repo installed and the latest version of this repo before trying again.

**Comment by dingrui37** [comment]
Thanks @antoninbas , I think I should ask quesitons in github , because many of my question are irrelevant to the P4 language.  By the way, is there any simple_switch_grp CLI?  In other words, how can I confirm the logic and the entries are actually in the simple_switch_grpc?  Thanks again.

**Comment by antoninbas** [comment]
There is no Thrift server running for `simple_switch_grpc`, no simple_switch_CLI will not work. Your option are:
- you can use the `Read` RPC in `P4Runtime` to retrieve table entries and verify them. You can either write a script to do that for you or use the `grpc_cli` (https://github.com/grpc/grpc/blob/master/doc/command_line_tool.md).
- you can modify your local version of `simple_switch_grpc` to start a Thrift server in addition to the gRPC server

**Comment by dingrui37** [comment]
Thanks, I will try again with the latest version of PI and bmv2.
