### ISSUE TITLE
compile p4 into json

### ISSUE THREAD

**Issue by Supreya1209** [p4lang/behavioral-model#424]
I am totally newbie to p4 and linux. I need to learn everything from zero, bear with me please.

I successfully install p4c-bmv2.
Now I try to test behavioral model.
I reached the step,

`p4c-bm --json <path to JSON file> <path to P4 file>`

My problem is that I dont know which json file to compile, (or create).

I try pointing to tcp_checksum.p4 in the provided directory, and I want to create json file in the same directory.

` $ p4c-bmv2 --json '/home/ck16700/p4c-bmv2/tests/p4_programs/tcp_checksum.p4' '/home/ck16700/p4c-bmv2/tests/p4_programs/tcp_checksum.json' `

Here is error (because there is no tcp_checksum.json)

```
Source file '/home/ck16700/p4c-bmv2/tests/p4_programs/tcp_checksum.json' could not be opened or does not exist.
Error while building HLIR
```

Next I tried to point to existed p4 file and json file

`$ p4c-bmv2 --json '/home/ck16700/behavioral-model/tests/testdata/header_stack.p4' '/home/ck16700/behavioral-model/tests/testdata/header_stack.json' `

there are 669 errors "illegal character" in header_stack.json file

Then I try creating empty document name serialize_test.json and run

`$ p4c-bmv2 --json '/home/ck16700/behavioral-model/tests/testdata/serialize.p4' '/home/ck16700/behavioral-model/tests/testdata/serialize_test.json' `

the result is 

```
parsing successful
Semantic error: P4 program does not define a start parse state
1 errors during semantic checking
Interrupting compilation
Error while building HLIR
```

and nothing happens.

This is may be a stupid question, but could please tell me how to compile a p4 file into json file?

Thank you in advance

**Comment by antoninbas** [comment]
Please start by looking at the examples and scripts in the tutorials repository: https://github.com/p4lang/tutorials
In all your attempts, you tries to pass the P4 source as the `--json` argument and the JSON destination as the positional argument to p4c-bmv2...
The syntax is `p4c-bmv2 --json <path to JSON file you want to create> <path to P4 source file>`, as you can see if you run `p4c-bmv2 --help`.

**Comment by antoninbas** [comment]
You even wrote in your answer that you reached the step `p4c-bm --json <path to JSON file> <path to P4 file>` and then went on to do the opposite.
