### ISSUE TITLE
Action profiles allow adding more members than their max_size attribute

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/behavioral-model#435]
I created a P4_16 program with 'implementation = action_profile(4)'.  Compiling it with p4c-bm2-ss caused a JSON file to be created that contains an action profile with "max_size" equal to 4, as expected.  While running simple_switch with this JSON file, and simple_switch_CLI to send commands to it via the Thrift API, I could successfully add over 10 members to this action profile, with no errors.  The command "act_prof_dump <act_profile_name>" showed all of the ones I added.

Is it expected that adding action profile members should fail when there are already the max_size members in it?

**Comment by antoninbas** [comment]
Yes, nothing of the sort is enforced by bmv2.
Note that the notion of max size for an action selector can be a little tricky IMO. In the case where one member is added to multiple groups, some targets may need to duplicate the member data, with one copy for each group that this member belongs to. If you think of an implementation that uses a single block of contiguous memory for all members and represents a group by the tuple (offset, size), replication would need to happen.
If this target also needs to allocate memory at compile-time, then the information provided by max_size is insufficient.

**Comment by jafingerhut** [comment]
OK, no worries.  I'm fine closing this issue -- just wanted to check that everything was working as intended, and this wasn't just an oversight.
