### ISSUE TITLE
simple_switch parses packet incorrectly when doing 'transition select' on 13-bit wide packet header field

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/behavioral-model#441]
[simple_switch-bug1.zip](https://github.com/p4lang/behavioral-model/files/1308962/simple_switch-bug1.zip)

This issue was verified using the latest versions of p4c-bm2-ss and simple_switch compiled from the p4lang/p4c and p4lang/behavioral-model repositories as of 2017-Sep-16.

The attached zip file contains a P4_16 source program demo14.p4, the demo14.json file I compiled it to using p4c-bm2-ss, and a single packet in the file 0_in.pcap that exhibits the bug.  That packet should cause the parser to reach state check_ipv4_frag_offset and from there transition to state check_ipv4_protocol, but the select statement is not implemented properly and instead the default transition to the accept state is taken.

The file demo14-log.txt shows the output produced from simple_switch using the command line options in the bash script demo14-ss-run.sh.  It has some extra debug log messages in it from simple_switch compiled with the patch behavioral-model-extra-debug.patch applied to p4lang/behavioral-model code.

My guess is that the match key for parse state check_ipv4_frag_offset is a 1-byte wide value 0xff, but the 13-bit wide hdr.ipv4.fragOffset field extracted from the header is padded up to 2 bytes wide 0x00ff, and the comparison "(key == input)" in method ParseSwitchCase::match() is returning false instead of true.  Probably the correct thing would be for the 1-byte wide "key" value to instead be a 2-byte wide "0x00ff", so the comparison returns true.

**Comment by antoninbas** [comment]
Looks like an issue I ran into a  while ago (I didn't open an issue right away so I forgot about it). The transition values need to be byte-padded in the JSON as indicated in the JSON doc:
```
For values and masks, make sure that you use the correct format. They need to be the concatenation (in the right order) of all byte padded fields (padded with 0 bits). For example, if the transition key consists of a 12-bit field and a 2-bit field, each value will need to have 3 bytes (2 for the first field, 1 for the second one). If the transition value is 0xaba, 0x3, the value attribute will be set to 0x0aba03.
```
If the value shows up as `0xff` in the JSON, it is incorrect. It should be `0x00ff`. Would you mind opening an issue in p4lang/p4c for this. It may actually be related to https://github.com/p4lang/p4c/issues/914.

**Comment by jafingerhut** [comment]
I have confirmed that by changing the "value" in the JSON file from `0xff` to `0x00ff`, simple_switch does parse the packet correctly.  I will start by adding a comment to https://github.com/p4lang/p4c/issues/914 since it is probably the same issue.

**Comment by antoninbas** [comment]
I'll leave this issue opened for now and try to add a check in the JSON parser to verify that the transition values have the correct width.

**Comment by antoninbas** [comment]
Added the check, closing this issue for bmv2
