### ISSUE TITLE
Ip fragmentation in p4 switch or host

### ISSUE THREAD

**Issue by x09326** [p4lang/behavioral-model#443]
Hi, I'm doing an experiment. I want to send a video from a host to another.
When I use "sudo mn" as original mininet, it works.
But when I use p4 switch and host to send the file, I found that the packet will do the fragmentation, I saw that from wireshark.

So I don't know why the original mininet switch works without ip fragmentation but p4 switch not.
Could you know about that? And how do I solve this problem?
I want the p4 switch works like original mininet switch, it won't do the ip fragmentation.
Thanks.

**Comment by antoninbas** [comment]
This is unlikely to be caused by bmv2, which does not do any fragmentation. If you observe IP fragmentation, it is because one of the links in your network requires it. You can try checking the MTU on all interfaces and compare it to the size of the packets you are sending.

**Comment by x09326** [comment]
Okay, thanks for your reply
