### ISSUE TITLE
Question: Does v1model provide a way for control block to read parser error_code?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/behavioral-model#446]
The behavioral-model code for simple_switch (and likely other variations -- I didn't check) does correctly set the error code to no error at the beginning of parsing: https://github.com/p4lang/behavioral-model/blob/master/src/bm_sim/parser.cpp#L969

It also records the error_code if a P4_16 verify() statement has a false condition, logs a message which I have seen with a small test P4 program, and terminates the parsing immediately: https://github.com/p4lang/behavioral-model/blob/master/src/bm_sim/parser.cpp#L978-L982

Is there a way to read this error code in the ingress or egress control blocks?  I haven't seen one yet, but I could be missing it.

**Comment by antoninbas** [comment]
If v1model.p4 is modified to include an error field in its standard metadata (https://github.com/p4lang/p4c/blob/master/p4include/v1model.p4#L32), then we can populate this field after the parser and it will be available in the pipeline. I've asked before that this change be made in v1model.p4: https://github.com/p4lang/p4c/issues/808. It is a backward-compatible change so I'm not sure there would be any issue.

**Comment by jafingerhut** [comment]
Related issue: https://github.com/p4lang/p4c/issues/808
