### ISSUE TITLE
Add Travis regression with gcc7

### ISSUE THREAD

**Issue by antoninbas** [p4lang/behavioral-model#455]
gcc7 has stricter warnings enabled by default

**Comment by antoninbas** [comment]
Alternatively we could stop using `-Werror` when shipping the code to be more future-proof.

**Comment by qin-nz** [comment]
#509

**Comment by antoninbas** [comment]
* we now run Travis regressions with gcc 7 and clang 6
 * we also no longer use `-Werror` by default (but we do use the flag for CI)
