### ISSUE TITLE
potential P4 bug: pop() in egress after push() in ingress doesn't seem to invalidate 

### ISSUE THREAD

**Issue by jrmcclurg** [p4lang/behavioral-model#456]
Hi, I'm seeing some strange behavior with push/pop. I'm on the 1.9.x branch of behavioral-model and p4c-bm.

I have a simple program that essentially "tags" a packet at the edge and forwards it between ports 1 and 2 in a network of 3 switches (see the following Gist). There is a header stack called `too`, and when I push/pop solely in the ingress, everything is fine. However, if I `push` in the ingress, and then `pop` in the egress, the pushed element still goes to the deparser, causing the packet to fail to "untag" properly.

In the following code, you can search for "NOTE", and see how I was able to make it work by manually calling `remove_header` on `too[0]`.

https://gist.github.com/jrmcclurg/1ac3a875fe00fb9fd2bbaf799b81715a

Is this a bug, or is it somehow expected behavior?
Thanks!
jed

**Comment by antoninbas** [comment]
I don't think this is the expected behavior.
Please provide the generated JSON file and an input packet so that we can reproduce the issue. Ideally you would provide the input packet in this format so I can import it in Python: `"\x01\x77\xb5..."`.

**Comment by jrmcclurg** [comment]
Sorry for the delay. I just updated the Gist with (hopefully) all the files needed to replicate the issue. On my machine, I do `make run`, which compiles `main.p4` if necessary, brings up Mininet with several `simple_switch` instances, and uses `sswitch_CLI` to populate the tables

The file `output.txt` contains the full output of `make run`, including commands sent to `sswitch_CLI`.

Once Mininet is running, I do `h1 ping h2`, and get no response (if I uncomment the line labeled with "NOTE" in `main.p4`, as mentioned above, the ping works just fine).

Here is the ping packet, exported from Wireshark (hopefully this is the correct format):

`"\x00\x00\x00\x00\x00\x22\x00\x00\x00\x00\x00\x11\x08\x00\x45\x00\x00\x54\x35\x0e\x40\x00\x40\x01\xf1\x98\x0a\x00\x00\x01\x0a\x00\x00\x02\x08\x00\xc3\x93\x46\xa5\x00\x01\x88\x85\xfe\x59\x00\x00\x00\x00\xa2\x13\x06\x00\x00\x00\x00\x00\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f\x20\x21\x22\x23\x24\x25\x26\x27\x28\x29\x2a\x2b\x2c\x2d\x2e\x2f\x30\x31\x32\x33\x34\x35\x36\x37"`

```
----
# Packet 187 from output.pcap
- 188
- 20.831870
- 10.0.0.1
- 10.0.0.2
- ICMP
- 98
- Echo (ping) request  id=0x46a5, seq=1/256, ttl=64 (no response found!)
```

**Comment by jrmcclurg** [comment]
BTW, if I change all `push(x, 1)` to `push(x, 1); add_header(x[0])` and all `pop(x, 1)` to `pop(x, 1); remove_header(x[0])`, is that something that's well-defined according to the 1.0.4 spec?

That appears to function like I thought push/pop should, but the following seems to indicate it might be problematic. I'm just trying to find a sensible hack to avoid this issue for now.

https://github.com/jafingerhut/p4-guide/blob/master/README-header-stacks.md

**Comment by jrmcclurg** [comment]
Thanks @antoninbas, this works great now!
