### ISSUE TITLE
Query: Support of thrift server in simple_switch_grpc implementation

### ISSUE THREAD

**Issue by manjurajv** [p4lang/behavioral-model#462]
Hello Team,

simple_switch_grpc as per README opens only grpc ports for listening. **Is it possible to support thrift port opening as well?** Because it is easy to use simple_switch_cli to visualize tables which uses thrift. 

root:$ simple_switch_grpc --device-id 1  --log-console -Ldebug **--thrift-port 40526** --no-p4 -- --cpu-port 255 --grpc-server-addr 0.0.0.0:52343
Calling target program-options parser
Server listening on 0.0.0.0:52343

**Comment by antoninbas** [comment]
This was a design choice. I didn't want to have two different RPC servers to do the same thing, given that the gRPC server actually stores state (the gRPC server stores information for every entry added, so if you add an entry through the Thrift server and tries to delete it through the gRPC server, there would definitely be some issues).
The P4 Runtime gRPC server can be used to `Read` tables. In the long term I am hoping we can have a P4 Runtime CLI that will be just as convenient to use as the Thrift CLI. But for now you can write your own scripts that connect to the gRPC server and read table contents.
If you still want to run both servers, you can modify the main.cpp of your local simple_switch_grpc copy to start the Thrift server. Check how it is done in simple_switch (https://github.com/p4lang/behavioral-model/blob/master/targets/simple_switch/main.cpp#L55) and you may need to edit Makefile.am to link with the Thrift library.

**Comment by manjurajv** [comment]
Thanks for your suggestions. I prefer writing my own scripts to read contents from gRPC server.
