### ISSUE TITLE
Simple_switch can't return from callee to caller (Control block) ?

### ISSUE THREAD

**Issue by MaoJianwei** [p4lang/behavioral-model#465]
Simple_switch can't return from callee to caller (Control block) ?

In the register `debuger`, I can see debuger[0] is increasing, but debuger[1] not...

The code looks like that:
```

control Go_to_first_indirect_neighbor(inout Mao_P4_WAN_Headers hdr, inout Mao_WAN_metadata meta, inout standard_metadata_t standard_metadata) {
    apply {
    }
}

control ingress(inout Mao_P4_WAN_Headers hdr, inout Mao_WAN_metadata meta, inout standard_metadata_t standard_metadata) {

    Go_to_first_indirect_neighbor() go_to_first_indirect_neighbor;
    register<bit<32>>(10) debuger;

    apply {
        bit<32> count;
        debuger.read(count, 0);
        debuger.write(0, count + 1);

        go_to_first_indirect_neighbor.apply(hdr, meta, standard_metadata);

        debuger.read(count, 1);
        debuger.write(1, count + 1);
    }
}
```

**Comment by antoninbas** [comment]
If this program is not working, it is probably an issue with the compiler. Please open an issue there with your P4 program & the generated JSON.

**Comment by jafingerhut** [comment]
[bmv2-issue465.p4.txt](https://github.com/p4lang/behavioral-model/files/1483332/bmv2-issue465.p4.txt)
[bmv2-issue465-console-log.txt](https://github.com/p4lang/behavioral-model/files/1483340/bmv2-issue465-console-log.txt)

@MaoJianwei I tried compiling a program that included your sample code (attached as bmv2-issue465.p4.txt) with a recent version of the p4c compiler p4c-bm2-ss to product a JSON file, then ran it on a recent version of simple_switch with the --log-console option, and I saw messages in the log indicating that both debuger.read and both debuger.write calls were being executed, before and after the call to the control block.  Search the attached file 'bmv2-issue465-console-log.txt' for occurrences of 'debuger' and you should see them.

As Antonin mentioned above, a full P4 program example attached to an issue for the compiler sounds appropriate, if you have such a program.
