### ISSUE TITLE
behavioral-model make error

### ISSUE THREAD

**Issue by gracehllee** [p4lang/behavioral-model#469]
I use the following link (https://github.com/p4lang/behavioral-model) to build the code.
And I run each command sequentially, "./autogen.sh", "./configure", "make"
After running "make", the errors thrown out are too many to fit in the screen.
The first error messages are shown below:

./third_party/spdlog -I../../../thrift_src/gen-cpp  -pthread -Wall -Werror -Wextra -g -O2 -std=c++11 -MT learn_client.o -MD -MP -MF $depbase.Tpo -c -o learn_client.o learn_client.cpp &&\
mv -f $depbase.Tpo $depbase.Po
/bin/bash ../../../libtool  --tag=CXX   --mode=link g++ -pthread -Wall -Werror -Wextra -g -O2 -std=c++11   -o learn_client learn_client.o ../../../src/bm_apps/libbmapps.la -lboost_thread -lpcap -lgmp -lJudy -lnanomsg
libtool: link: g++ -pthread -Wall -Werror -Wextra -g -O2 -std=c++11 -o .libs/learn_client learn_client.o  ../../../src/bm_apps/.libs/libbmapps.a /home/grace/bmv2/thrift_src/.libs/libruntimestubs.so -lthrift -lboost_thread -lpcap -lgmp -lJudy -lnanomsg -pthread
../../../src/bm_apps/.libs/libbmapps.a(learn.o): In function `bm_apps::LearnListener::start()':
/home/grace/bmv2/src/bm_apps/learn.cpp:107: undefined reference to `apache::thrift::transport::TSocket::TSocket(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int)'
collect2: error: ld returned 1 exit status
Makefile:365: recipe for target 'learn_client' failed
make[4]: *** [learn_client] Error 1
make[4]: Leaving directory '/home/grace/bmv2/targets/l2_switch/learn_client'
Makefile:472: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/home/grace/bmv2/targets/l2_switch'
Makefile:377: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/grace/bmv2/targets'
Makefile:450: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/grace/bmv2'
Makefile:380: recipe for target 'all' failed
make: *** [all] Error 2

Could anyone help me figure out what the problem is?

some information also has been checked 
$ sudo ldconfig -p | grep thrift
        libthriftz-0.9.2.so (libc6,x86-64) => /usr/local/lib/libthriftz-0.9.2.so
        libthriftnb-0.9.2.so (libc6,x86-64) => /usr/local/lib/libthriftnb-0.9.2.so
        libthrift-0.9.2.so (libc6,x86-64) => /usr/local/lib/libthrift-0.9.2.so
$ thrift --version
Thrift version 0.9.2

**Comment by antoninbas** [comment]
It's probably not that, but did you remember to run "sudo ldconfig" after installing libthrift?

**Comment by gracehllee** [comment]
I reinstall thrift 0.9.2 and run "sudo apt-get install thrift-compiler" ..
After that, I make and make install bmv2 sucessfuly.
