### ISSUE TITLE
make error in pcap_file.cpp

### ISSUE THREAD

**Issue by imaginezz** [p4lang/behavioral-model#480]
After `autogen` and  `configure`, I ran `make`
there's a make error
```
pcap_file.cpp:221:44: error: ‘earliest_time’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
                 PcapPacket::timevalToString(earliest_time));
```
in `src/bm_sim/pcap_file.cpp`

and I found earliest_time really don't have a initial value.

**Comment by antoninbas** [comment]
Hi,
I can take of fixing it, although for next time it is probably just as quick for you to open a pull request to fix this as it is to open an issue.
Also, which compiler version are you using?

**Comment by antoninbas** [comment]
I have opened PR https://github.com/p4lang/behavioral-model/pull/486 for this, but I haven't been able to verify that it fixes the issue since you haven't provided the compiler version.

**Comment by antoninbas** [comment]
No update on this, so I merged the PR

**Comment by antoninbas** [comment]
We do not compile with `Werror` by default anymore, so even in the unlikely case that this warning is still valid, this should not prevent the build from completing.
