### ISSUE TITLE
Question: configure simple_switch_grpc --with-sysrepo

### ISSUE THREAD

**Issue by dingrui37** [p4lang/behavioral-model#489]
I have read the introduction about simple_switch_grpc target. 
https://github.com/p4lang/behavioral-model/tree/master/targets/simple_switch_grpc
After updating all code to the  latest, I reconfigure simple_switch_grpc with `--with-sysrepo` and rebuild it, all the steps are successful. But when I start the target,  it doesn't work.
```
dr@dr:/home/opendaylight/P4/p4lang/behavioral-model/targets/simple_switch_grpc$ sudo simple_switch_grpc --no-p4 --log-console
Thrift port was not specified, will use 9090
Calling target program-options parser
I1211 16:21:48.215330507    5915 server_builder.cc:247]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2147483647, CQ timeout (msec): 1000
Server listening on 0.0.0.0:50051
[16:21:48.245] [bmv2] [E] [thread 5915] Error by sr_module_change_subscribe: Requested schema model is not known
dr@dr:/home/opendaylight/P4/p4lang/behavioral-model/targets/simple_switch_grpc$ simple_switch_grpc -v
1.9.0-0f53201b
```

**Comment by antoninbas** [comment]
Looks to me that either the sysrepo daemon is not running or you didn't install the openconfig-interfaces schema properly. Are you sure you followed all the instructions there: https://github.com/p4lang/PI/blob/master/proto/README.md
You can check if the openconfig-interfaces YANG schema was installed properly by running `sysrepoctl -l`. You can also run the sysrepo daemon in debug mode with `sudo sysrepod -d` which may help you troubleshoot the issue.

**Comment by dingrui37** [comment]
Thanks @antoninbas I forgot to run `sudo sysrepo/install_yangs.sh`, it works now.
