### ISSUE TITLE
p4c-bmv2 fails on big constants?

### ISSUE THREAD

**Issue by jrmcclurg** [p4lang/behavioral-model#498]
I'm running into an unexpected problem -- apparently `p4c-bmv2` won't let me use integer constants larger than 64-bit. For example, in the following "dummy" program, the compiler fails if I increase the large constant by 1.

```
header_type data__t {
    fields {
        wow : 128;
    }
}
header data__t data;

parser start {
    extract(data);
    return ingress;
}

control ingress {
    // changing the last digit to 8 in the following big
    // constant causes p4c-bmv2 to fail

    if(1 <= ((data.wow >> 64) & 9223372036854775807)) {

    } else {
        
    }
}
```

(1) Is this expected behavior?

(2) If so, are there any simple ways to get around this? I'm able to create fields larger than 64-bit, and I would like to be able to do bitwise operations (shifting, masking, etc.) on them.

(3) In the mean time, I will probably just restrict all my fields to be 64-bit or less.

**Comment by jafingerhut** [comment]
I haven't done extensive testing of variations of your program, but I tried
your program, also with the last '7' digit replaced with 8, and with that
entire constant replaced with the decimal representation of (1 << 64), and
the compiler p4c-bm2-ss compiles it without error (using the command line
options "--p4v 14" to indicate that the input source file is the P4_14
language, not the default of P4_16 that p4c-bm2-ss assumes).

I don't know what else you need to work, but that might be considered a
workaround for this issue.

I would guess that the behavior you see with p4c-bmv2 would be considered a
compiler bug, and could be filed as an issue on this repository:
https://github.com/p4lang/p4c-bm
But note that repository is, I believe, in 'maintenance mode', as compared
to p4lang/p4c, which is under active development.

Andy

**Comment by jrmcclurg** [comment]
Awesome, thanks for your help @jafingerhut!
