### ISSUE TITLE
Support the ability to specify key names

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/behavioral-model#500]
The name of the key should be decoupled from the "target" field. This is necessary to support @name annotations on key fields in P4-16. 

The JSON representation could be something like:

```
"key" : [{
              "match_type" : "exact",
              "name" : "hdr.x.add",
              "target" : ["x_0", "add"],
              "mask" : null
            }]
```

**Comment by antoninbas** [comment]
That should really not be an issue:
- in bmv2 itself: the name is only used for debugging messages
- in runtime stack: we usually rely on the order of the fields when creating entries
I'll give myself some time to think about potential issues, but if I can't think of anything I'll make the change tomorrow.
