### ISSUE TITLE
better log for register index out of range

### ISSUE THREAD

**Issue by qin-nz** [p4lang/behavioral-model#503]
I defined `register<bit<8>>(1) r;`  and I access it by `r.read(x,999);`.
I will get following line in log file.
```
simple_switch: ../../include/bm/bm_sim/stateful.h:117: const bm::Register& bm::RegisterArray::operator[](size_t) const: Assertion `idx < size()' failed.
```

https://github.com/p4lang/behavioral-model/blob/d742940270595c28c5caec5f711a63a2979e1b43/include/bm/bm_sim/stateful.h#L115-L119

**Comment by qin-nz** [comment]
After that, 
simple_switch was terminated by signal SIGABRT (Abort).

**Comment by antoninbas** [comment]
I believe this was fixed in https://github.com/p4lang/behavioral-model/pull/637
