### ISSUE TITLE
is P4 really device independent?

### ISSUE THREAD

**Issue by ali64Mon** [p4lang/behavioral-model#52]
Hi everyone,
I am new to P4. I was trying to understand how P4 works. So, I started reading the code as well some PDF files on the workshops. I found out that P4 is compiled by p4c-mbv2 and converted to a Json file. This Json file later is fed to bmv2 which is bunch of c++ codes. So whenever I want to run a P4 program,  I pick up a target, like simple_switch, and then I can run it through the following command: 
simple_switch test.json "some other parameters"
As a result, I guess P4 is just  a kind of data coding more comfortable for switch programmers which in deed gets converted to Json coding to be used later by bmv2. 
My question is now that how can we claim bmv2 is device independent since it is only bunch of c++ codes and we know c++ compiler is not machine independent? In other words, how is it possible to to run P4 simultaneously on CPUs , GPUs or even FPGAs since P4 compiler (bmv2) is written in c++?

Regards,
Alireza.

**Comment by antoninbas** [comment]
Hi,

I think the rest of the bullet point you are referring to pretty much explains what we mean by target independent:

>The new code is target independent. While the original p4c-behavioral assumed a fixed abstract switch model with 2 pipelines (ingress and egress), bmv2 makes no such assumption and can be used to represent many switch architectures. Three different -although similar- such architectures can be found in the targets/ directory. If you are a networking company interested in programming your device (parser, macth-action pipeline, deparser) with P4, you can use bmv2 to reproduce the behavior of your device.

What we mean by "bmv2 is target independent" is that the bmv2 library can be used to simulate many switch architectures, so long as these architectures follow the "P4 paradigm" (i.e. packet processing is essentially done by parser / match-action pipeline / deparser). It has nothing to do with the architecture on which you run the software switch. bmv2 is meant to be run on a x86 system but can be used to reproduce the behavior of a P4-programmable ASIC or NIC.

Your question shows some confusion on several points. The title is "is P4 really device independent?" but your question concerns bmv2. Our claim is that P4 is device independent: different devices such as an ASIC, a NIC, a FPGA or a software switch can be programmed using P4. However, for each of these devices, you need a P4 compiler to map the P4 code to a valid device configuration. bmv2 can be seen as one more software switch that can run P4 programs. It has its own compiler (p4c-bm) which compiles P4 programs to a JSON representation which is understood by bmv2. The two big differences about bmv2 are:
- it is supposed to be a "reference platform": speed is not a priority, but all P4 features should be supported, and supported correctly.
- it can simulate any hardware target (with some limited C++ coding)

I invite you to look at some of the 2nd P4 workshop presentations to find out more about the P4 ecosystem (http://p4.org/p4-workshop-2/). For example, Xilinx had a presentation on compiling P4 to FPGA. We look forward to being able to run P4 programs on GPUs, but somebody would have to contribute a P4 -> CUDA compiler.
