### ISSUE TITLE
Question:Is there any examples about how to use gNMI in bmv2?

### ISSUE THREAD

**Issue by dingrui37** [p4lang/behavioral-model#529]
Hi, @antoninbas, could you give me an example about how to use gNMI in bmv2, thanks

**Comment by antoninbas** [comment]
The support for gNMI is very experimental at this time. Please make sure that you read the relevant sections in both of these READMEs:
- https://github.com/p4lang/PI/tree/master/proto#tentative-gnmi-support-with-sysrepo
- https://github.com/p4lang/behavioral-model/tree/master/targets/simple_switch_grpc#tentative-gnmi-support-with-sysrepo
Make sure you install all the listed dependencies and that you `configure` both the PI and simple_switch_grpc with `--with-sysrepo`.

Right now we only support some of the nodes in the openconfig-interfaces model and most of them are stubbed out on bmv2, by which I mean they have no impact of the forwarding. Please refer to the README for details.

We support (under some conditions) the following gNMI operations:
- `Subscribe` (`ONCE` and `STREAM` modes)
- `Get` and `Set` on leaf nodes only
If you are not familiar with these, you should read the gNMI specification.

There are also some restrictions on the gNMI paths you can use. For example you can use `...` at the very end of the path but not in the middle of the path. Paths with `*` haven't been tested.

I checked-in an example Python script that does a `ONCE` gNMI subscription on the gNMI path "interfaces/interface/...": https://github.com/p4lang/behavioral-model/blob/master/targets/simple_switch_grpc/gnmi_sub_once.py. Just start `simple_switch_grpc` with a few interfaces (e.g. `simple_switch_grpc` -i 0@veth0 -i 1@veth2`) and then use this script to query all config & state values for these 2 interfaces.

You can look at these unit tests to see some examples of supported gNMI requests: https://github.com/p4lang/PI/blob/master/proto/tests/server/test_gnmi.cpp#L495

**Comment by dingrui37** [comment]
Thanks @antoninbas
