### ISSUE TITLE
connecting eth0 to bmv2

### ISSUE THREAD

**Issue by bijutalukdar** [p4lang/behavioral-model#53]
Hi  ,
I have attached a eth0 (real netdev interface of nic ) to the bmv2(c++) switch. I did that by passing the eth0 as a parameter along with the json file to the switch, while configuring the switch with the compiled p4 program. Now I want to know in which port in the bmv2 switch will receive the packets. I mean is there a mapping like the following. I assumed this kind of mapping as I saw something similar in one of the tutorial slide.

app switch(bmv2)
veth0-->veth1 (port0)
veth2-->veth3 (port1)
veth4-->veth5 (port2)
veth6-->veth7 (port3)

Also could someone point me to the source code file where veth1, veth3, veth5 are instantiated in the bmv2 switch.

**Comment by vgurevich** [comment]
Hello Biju,

You might find the following materials useful:

http://p4.org/wp-content/uploads/2015/12/Nov-2015-P4-Bootcamp-Labs-Guide.pdf
(especially slides #7 and #8)
https://youtu.be/xsEcGaQez14?t=8m59s

They are available through P4 Boot Camp page: http://p4.org/p4-bootcamp-1/

Happy hacking,
Vladimir

**Comment by bijutalukdar** [comment]
Hi Vladimir,
Great help , thanks a lot.
