### ISSUE TITLE
About simulate a datacenter network

### ISSUE THREAD

**Issue by fhowen** [p4lang/behavioral-model#530]
I want to simulate a datacenter network, and I need to assign different functions to different switchs. 
But I didn't see an example shows how to do this.

Thanks.

**Comment by antoninbas** [comment]
This is a fairly vague question.
I'll assume that by different functions you mean different P4 programs. I'll also assume that you want to use P4 Runtime to control your switches and that you will be using the simple_switch_grpc bmv2 binary.
You need to follow the following steps:
1. write the different P4 programs you need, preferably using P4_16
2. compile your P4 programs using the [bmv2 p4c compiler](https://github.com/p4lang/p4c)
For example: `p4c-bm2-ss --p4v 16 prog1.p4 -o prog1.json --p4runtime-file prog1.p4info.txt --p4runtime-format text`.
You will get one bmv2 JSON file for each P4 program.
3. start each simple_switch_grpc process (one per switch). Use a different device id and a different gRPC TCP port for each process.
For example:
```
simple_switch_grpc --no-p4 -i 0@veth0 -i 1@veth2 -i 2@veth4 --device-id 0 -- --grpc-server-addr 50050
simple_switch_grpc --no-p4 -i 0@veth6 -i 1@veth8 --device-id 1 -- --grpc-server-addr 50051
...
```
4. push the appropriate dataplane (progX.p4info.txt and progX.json) to each switch instance using the P4 Runtime SetForwardingPipelineConfig RPC.

Now if you want to emulate a datacenter network, you probably want to use some orchestrator like Mininet which will manage the interfaces and the simple_switch_grpc processes for you. The best place to get started is probably the P4D2_2017_Fall directory in the p4lang/tutorials repo: https://github.com/p4lang/tutorials/tree/master/P4D2_2017_Fall. It contains useful scripts to create a network topology of bmv2 processes with Mininet and push P4 dataplanes to each switch. You may want to look at these scripts and perhaps complete the exercises.

**Comment by fhowen** [comment]
@antoninbas Thanks a lot for your answer, it is very helpful.
I am currently study the code example in [https://github.com/p4lang/tutorials/tree/master/SIGCOMM_2017/exercises/basic](url) to get clear that how to combine the simple_switch model and Mininet network together.
But I am confused about p4app in the folder. I am not sure if it is using this [https://github.com/p4lang/p4app](url) tool.
