### ISSUE TITLE
extracting variable-size data makes them all zero

### ISSUE THREAD

**Issue by lomosewen** [p4lang/behavioral-model#538]
I'm trying to use the simple_switch to implement a 802.11 switch by P4_16. 
I tried to extract the radiotap header with a variable length from the 802.11 packets, then did nothing with the packets but forwarded them to another port. But after the packets come out of P4 switch, the variable-size field become all zero.
Here is the p4 code:
```
#include<core.p4>
#include <v1model.p4>

header RadioTap_h {
        bit<8>          headerVersion;
        bit<8>          headerPad;
        bit<16>         headerLength;
        bit<32>         presentFlags;
}

header RT_Options_h {
        varbit<400>     option;
}

struct myMetadata {
}

struct myHeader {
        RadioTap_h      radioTap;
        RT_Options_h    options;
}

parser MyParser(packet_in packet, out myHeader hdr, inout myMetadata meta, inout standard_metadata_t standard_metadata) {
        state start {
                transition parse_myheader;
        }
        state parse_myheader {
                packet.extract(hdr.radioTap);
                packet.extract(hdr.options, (bit<32>)(((hdr.radioTap.headerLength >> 8) - 8) * 8));
                transition accept;
        }
}

control MyVerifyChecksum(in myHeader hdr, inout myMetadata meta) {   
        apply {}
}

control MyIngress(inout myHeader hdr, inout myMetadata meta, inout standard_metadata_t standard_metadata) {
        apply {
                if(standard_metadata.ingress_port == 2) {
                        standard_metadata.egress_spec = 1;
                }
        }
}

control MyEgress(inout myHeader hdr, inout myMetadata meta, inout standard_metadata_t standard_metadata) {
        apply {}
}

control MyComputeChecksum(inout myHeader hdr, inout myMetadata meta) {
        apply {}
}

control MyDeparser(packet_out packet, in myHeader hdr) {
        apply {
                packet.emit(hdr.radioTap);
                packet.emit(hdr.options);
        }
}

V1Switch(
        MyParser(),
        MyVerifyChecksum(),
        MyIngress(),
        MyEgress(),
        MyComputeChecksum(),
        MyDeparser()
) main;
```

One of the two interfaces is a monitor interface of the wifi adapter, another is the monitor interface of a virtual wireless interface.

**Comment by antoninbas** [comment]
Hi @lomosewen could you provide the JSON file corresponding to this P4 program?

**Comment by antoninbas** [comment]
I've created a PR to fix this, it will be merged in master soon.

As a side-note, it seems that your radiotap extraction is only valid for radiotap headers whose length is less than 256 bytes. You can make it more general by splitting the length field into 2 `bit<8>` fields, `hl0` and `hl1` and then use the following to extract the VL options header:
```
bit<32> length = (hdr.radioTap.hl1 << 8) + hdr.radioTap.hl0;
packet.extract(hdr.options, (length - 8) * 8);
```

**Comment by jafingerhut** [comment]
I don't know the definition of radioTap headers, but if the submitted P4_16 program was correct, the radioTap header length does not depend upon the least significant 8 bits of headerLength at all, only on its most significant 8 bits.

**Comment by antoninbas** [comment]
@jafingerhut radiotap encodes all its header fields in little-endian, not network-byte order

**Comment by jafingerhut** [comment]
weirdos :-)

**Comment by antoninbas** [comment]
I agree, this is not very P4_16 friendly either :)
