### ISSUE TITLE
Program crashes simulator

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/behavioral-model#540]
The attached json program crashes the simulator at runtime with the following exception:
```
Assertion 'Default switch case should not be reachable' failed, file '../../include/bm/bm_sim/actions.h' line '318'.
```
The STF file which causes this to fail is:
```
packet 0 01 23456789 AB CDEFFEDC BA 98765432
```

[equality.zip](https://github.com/p4lang/behavioral-model/files/1666327/equality.zip)

**Comment by antoninbas** [comment]
This part of the JSON is wrong:
```
        {
          "op" : "assign",
          "parameters" : [
            {
              "type" : "header_stack",
              "value" : "tmp"
            },
            {
              "type" : "header_stack",
              "value" : "a"
            }
          ],
          "source_info" : {
            "filename" : "/home/mbudiu/git/p4c/testdata/p4_16_samples/equality-bmv2.p4",
            "line" : 41,
            "column" : 8,
            "source_fragment" : "tmp = hdr.a"
          }
        }
```
You cannot use `assign` to copy header stacks, you need to use `assign_stack`. This assert in the actions.h file usually mean that bmv2 couldn't reconcile the arg type with the expected parameter type.

**Comment by antoninbas** [comment]
I meant `assign_header_stack`.
