### ISSUE TITLE
std::out_of_range() exception thrown when egress_spec over 255

### ISSUE THREAD

**Issue by 4tXJ7f** [p4lang/behavioral-model#541]
When a packet has egress_spec > 255 after ingress, an `std::out_of_range()` exception gets thrown. It looks like this is because `egress_buffers` use a `max_port` of 256. In [`SimpleSwitch::enqueue()`](https://github.com/p4lang/behavioral-model/blob/master/targets/simple_switch/simple_switch.cpp#L276-L280) `push_front()` is called, which seems to lead to an out-of-bound access [here](https://github.com/p4lang/behavioral-model/blob/327a4029a0dc7ae505973d990bc4a29c9cc4c054/include/bm/bm_sim/queueing.h#L251). The special port 511 gets filtered out [here](https://github.com/p4lang/behavioral-model/blob/master/targets/simple_switch/simple_switch.cpp#L447). While this is not a critical issue, the [PSA Section 6.2](https://p4.org/p4-spec/docs/PSA.html#sec-after-ingress) does seem to say that packets with an invalid port should just get dropped (last else branch in pseudo code).

**Comment by jafingerhut** [comment]
And if simple_switch is enhanced to drop such packets, it would probably be nice to have a distinct message in the log, when logging is enabled, that gives a message similar to: "egress_spec 256 does not correspond to any port.  Dropping packet."

**Comment by antoninbas** [comment]
Fixed by #571
