### ISSUE TITLE
Build simple_switch_grpc error.

### ISSUE THREAD

**Issue by kevinbird61** [p4lang/behavioral-model#545]
Compiler:  `gcc version 7.2.0`
protoc: `3.5.0`
grpc: `v1.8.x`

After I compiler and install PI and bmv2 with guideline
( install `libyang` and `sysrepo`  for `PI` , and using `./configure --with-bmv2 --with-proto --with-sysrepo` to configure, and in `bmv2` using `./configure --enable-debugger --with-pi` )
Then I go to [`targets/simple_switch_grpc`](https://github.com/p4lang/behavioral-model/tree/master/targets/simple_switch_grpc) to build `simple_switch_grpc`

Build with command `make` after specified `./configure --with-sysrepo`
I found there have an error:

```
/home/kevin/tools/bmv2/targets/simple_switch_grpc/.libs/libbm_grpc_dataplane.so: undefined reference to `google::protobuf::Empty::~Empty()'
/home/kevin/tools/bmv2/targets/simple_switch_grpc/.libs/libbm_grpc_dataplane.so: undefined reference to `google::protobuf::Empty::Empty()'
/home/kevin/tools/bmv2/targets/simple_switch_grpc/.libs/libbm_grpc_dataplane.so: undefined reference to `protobuf_google_2fprotobuf_2fempty_2eproto::AddDescriptors()'
collect2: error: ld returned 1 exit status
make[2]: *** [simple_switch_grpc] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```
Does this problem occur because of my grpc or `protobuf` dependencies? 
I found in `PI` said need to use `grpc: v1.3.2` and `protobuf: v3.2.0`.

Thanks for any help.

**Comment by antoninbas** [comment]
It seems that in your environment, `google::protobuf::Empty` is not part of libprotobuf. I opened a PR to remove the dependency on `empty.proto` since it is not really important. It could be because of your version of protobuf or it could be because of some build flags.

Out of curiosity could you provide the output of this command: `nm /usr/local/lib/libprotobuf.so | c++filt | grep "google::protobuf::Empty"` (please make sure the library path is correct for your system)?

In this case there was a pretty simple workaround. However we do recommend using the advertised versions of protobuf and grpc as there is no guarantee that our code will always be compatible with the latest versions of protobuf / grpc.

**Comment by antoninbas** [comment]
Also please make sure that PR #546 fixes your issue, it could be that I'm wrong about the root cause of the issue.

**Comment by antoninbas** [comment]
According to this protobuf makefile (https://github.com/google/protobuf/blob/master/src/Makefile.am#L253), `Empty` should be part of libprotobuf so please provide the output of the `nm` command above and maybe the full linker invocation (what came before the error message).

**Comment by kevinbird61** [comment]
@antoninbas thanks for your help !
After I using the branch `origin/antonin/simple-switch-grpc-dp-proto-remove-empty-dep` 
Building process of `simple_switch_grpc`  succeed !

And I use command `nm /usr/local/lib/libprotobuf.so | c++filt | grep "google::protobuf::Empty"`
I found that after my building process of `grpc` and `protobuf`, I only have static library: `/usr/local/lib/libprotobuf.a` , `/usr/local/lib/libprotobuf.la`

So I change command `nm /usr/local/lib/libprotobuf.a | c++filt | grep "google::protobuf::Empty"`, and have the following message: 

```bash
00000000000004b0 T google::protobuf::Empty::descriptor()
0000000000000410 T google::protobuf::Empty::SharedCtor()
0000000000000420 T google::protobuf::Empty::SharedDtor()
0000000000000790 T google::protobuf::Empty::InternalSwap(google::protobuf::Empty*)
0000000000000830 T google::protobuf::Empty::UnsafeArenaSwap(google::protobuf::Empty*)
00000000000004d0 T google::protobuf::Empty::default_instance()
0000000000000400 T google::protobuf::Empty::InitAsDefaultInstance()
00000000000006f0 T google::protobuf::Empty::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*)
0000000000000990 T google::protobuf::Empty::Swap(google::protobuf::Empty*)
00000000000006d0 T google::protobuf::Empty::Clear()
0000000000000910 T google::protobuf::Empty::CopyFrom(google::protobuf::Message const&)
0000000000000950 T google::protobuf::Empty::CopyFrom(google::protobuf::Empty const&)
00000000000004a0 T google::protobuf::Empty::ArenaDtor(void*)
00000000000008b0 T google::protobuf::Empty::MergeFrom(google::protobuf::Message const&)
0000000000000850 T google::protobuf::Empty::MergeFrom(google::protobuf::Empty const&)
0000000000000580 T google::protobuf::Empty::Empty(google::protobuf::Arena*)
0000000000000660 T google::protobuf::Empty::Empty(google::protobuf::Empty const&)
00000000000004f0 T google::protobuf::Empty::Empty()
0000000000000580 T google::protobuf::Empty::Empty(google::protobuf::Arena*)
0000000000000660 T google::protobuf::Empty::Empty(google::protobuf::Empty const&)
00000000000004f0 T google::protobuf::Empty::Empty()
0000000000000480 T google::protobuf::Empty::~Empty()
0000000000000430 T google::protobuf::Empty::~Empty()
0000000000000430 T google::protobuf::Empty::~Empty()
0000000000000240 T google::protobuf::Empty::GetMetadata() const
0000000000000080 T google::protobuf::Empty::ByteSizeLong() const
0000000000000000 W google::protobuf::Empty::GetCachedSize() const
0000000000000010 T google::protobuf::Empty::IsInitialized() const
0000000000000000 T google::protobuf::Empty::SetCachedSize(int) const
0000000000000000 W google::protobuf::Empty::GetMaybeArenaPointer() const
0000000000000020 T google::protobuf::Empty::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const
0000000000000050 T google::protobuf::Empty::InternalSerializeWithCachedSizesToArray(bool, unsigned char*) const
00000000000005d0 T google::protobuf::Empty::New(google::protobuf::Arena*) const
0000000000000000 W google::protobuf::Empty::New() const
0000000000000000 W google::protobuf::Empty::GetArena() const
0000000000000000 V typeinfo for google::protobuf::Empty
0000000000000000 V typeinfo name for google::protobuf::Empty
0000000000000000 V vtable for google::protobuf::Empty
```

**Comment by antoninbas** [comment]
Do you happen to know why you only have the static library? How did you install protobuf?

**Comment by kevinbird61** [comment]
@antoninbas  
I just follow the [installation guideline of grpc](https://github.com/grpc/grpc/tree/master/src/cpp#build-from-source), and then go into its third party submodule: `protobuf`, then following the protobuf [installation guideline here](https://github.com/google/protobuf/tree/master/src) with default setting (not specify any options when using `./configure`).  

I have summarized some installation scripts ( About `bmv2`, `p4c`, `PI` ... etc ) I used in [this github repository](https://github.com/kevinbird61/P4-Play/tree/master/Installation).

**Comment by antoninbas** [comment]
Hmmm, maybe you should have installed protobuf separately first to get the dll.
In any case I don't mind merging #546 if it helps you out.
