### ISSUE TITLE
Understanding the l2_switch.p4 Program

### ISSUE THREAD

**Issue by FRuffy** [p4lang/behavioral-model#548]
Hello,
I am currently trying to run a P4 switch in Mininet, which consists of one switch and two hosts. However, instead of IPv4, I am using IPv6 and an MTU of 9000. I have been trying to run a simple forwarding switch, which does nothing else but broadcast packets it has received to the other ports. For that I am using l2_switch.p4 and the default configuration commands: 
> 	table_set_default smac mac_learn
> 	table_set_default dmac broadcast
> 	mc_mgrp_create 1
> 	mc_node_create 0 1
> 	mc_node_create 1 2
> 	mc_node_associate 1 0
> 	mc_node_associate 1 1

Unfortunately, l2_switch.p4 seems to crash as soon as it tries to process my 4096 byte packet. 
I can see the packet arriving on the interface, but not being forwarded. After the switch process terminates with 
<code> thrift.transport.TTransport.TTransportException: TSocket read 0 bytes  </code>
I am not exactly sure what might be going wrong, is there something I need to change?
I am also using <code>Host</code> instead of <code>P4host</code> in my Mininet environment. Otherwise it is the same setup as in the demo files.

**Comment by antoninbas** [comment]
Please share the exact steps you are using if you want help. Also what is l2_switch.py?

**Comment by FRuffy** [comment]
Sorry for the misunderstanding, I meant to say <code>l2_switch.p4</code>, which is in the <code>targets/l2_switch</code> folder. The steps I am running are pretty much as described in here:
https://github.com/p4lang/behavioral-model#integrating-with-mininet
The only difference is that I am running l2_switch instead of simple_router and I am sending a larger, slightly modified packet with a custom program.
I am using the CLI commands in the post above to set the switch up. Hosts are able to ping each other over IPv4 as well as IPv6. 
Once I send my custom packet of size 4158 byte, the switch crashes. I am not entirely sure what might be causing this.
Attached is a wireshark .pcapng file containing the packet I am sending, it is the UDP packet. 
[packet.txt](https://github.com/p4lang/behavioral-model/files/1704941/packet.txt)

**Comment by antoninbas** [comment]
For some historical reason the packet length is bounded to 2048 in the l2_switch implementation (https://github.com/p4lang/behavioral-model/blob/master/targets/l2_switch/l2_switch.cpp#L69). Feel free to replace that line by what is done in simple_switch: https://github.com/p4lang/behavioral-model/blob/master/targets/simple_switch/simple_switch.cpp#L134. You even a PR to fix it if you or your organization is a p4.org member.

On a side note, I would recommend not using l2_switch, but instead use simple_switch. l2_switch is a toy example while simple_switch is the actual implementation of the P4_14 abstract switch model (and of the P4_16 v1model.p4 architecture). simple_switch can do everything l2_switch can.

**Comment by FRuffy** [comment]
Thanks, that worked! Will try out simple_switch next. I am not part of any P4 related organization, can I still submit a PR?

**Comment by antoninbas** [comment]
We can only accept code contributions from p4.org members.

**Comment by FRuffy** [comment]
Okay, thank you for your help!
