### ISSUE TITLE
Unable to install bm to a custom location

### ISSUE THREAD

**Issue by agrml** [p4lang/behavioral-model#555]
I try to install bm to a custom location and get `libtool:   error: error: cannot install 'libbmp4apps.la' to a directory not ending in /usr/local/lib`. Upwards in the `make install` output I also get `libtool: warning: remember to run 'libtool --finish /usr/local/lib'`.

I'm installing P4-factory. As it's required in the Readme, I configure bm with `prefix=$HOME/install`, perform `make` and get the listed error on performing `make install`. If it matters, all the actions are performed from sudo.

What should be done to prevent the error?

**Comment by antoninbas** [comment]
AFAIK this only happens if you run `configure` with a new prefix value and don't do `make clean` before doing `make` and `make install`.
Doing the following will give you the error you are seeing:
```
./configure
make
make install
./configure --prefix=$HOME/install
make
make install
```
However, if you do `make clean` after the second configure, it should work fine.

**Comment by agrml** [comment]
Thanks!
