### ISSUE TITLE
I try to run simple_switch and got  `open: No such file or directory` error

### ISSUE THREAD

**Issue by wjf1993** [p4lang/behavioral-model#569]
root@ubuntu:/home/sdn/behavioral-model/targets/simple_switch# ./simple_switch --thrift-port 9091 -i 0@ens4 /home/sdn/test_my_p4_core/1.json/table_and_control.json  
Calling target program-options parser
Adding interface ens4 as port 0
Thrift server was started
open: No such file or directory
open: No such file or directory
open: No such file or directory

**Comment by antoninbas** [comment]
This happens when the interface name you provided stops being valid some time after you started simple_switch. That would typically happen if you are using a virtual interface (veth, tap,...) which gets deleted for some external reason.

**Comment by wjf1993** [comment]
@antoninbas Indeed, I was running simple_switch inside a virtual machine .But i  did not stop this interface name.How to solve this issue？

**Comment by wjf1993** [comment]
@antoninbas thanks,i solved this issue。
