### ISSUE TITLE
Unable to build simple_switch_grpc with --with-thrift option

### ISSUE THREAD

**Issue by coolvikas** [p4lang/behavioral-model#574]
Hi everyone,
I am unable to build simple_switch_grpc with --with-thrift option. I am attaching the log here in the file. Please help.
[logsimple_switch_grpc.txt](https://github.com/p4lang/behavioral-model/files/1866290/logsimple_switch_grpc.txt)

**Comment by antoninbas** [comment]
You seem to be using an incompatible version of PI. I don't think that has anything to do with the `--with-thrift` option, unless you can confirm it doesn't happen without this build option. The `GnmiMgr` was removed a while ago.

**Comment by coolvikas** [comment]
Thanks @antoninbas I was able to compile successfully. Now I have another issue that simple_switch_grpc always opens thrift port as 9090 I tried to run multiple instances of simple_switch_grpc by passing different thift ports 
`simple_switch_grpc -i 1@s1-eth1 -i 2@s1-eth2 --pcap --nanolog ipc:///tmp/bm-0-log.ipc --device-id 0 --no-p4 --log-console -- --grpc-server-addr 0.0.0.0:50051 -- --thrift-port 9876`

`simple_switch_grpc -i 1@s2-eth1 -i 2@s2-eth2 -i 3@s2-eth3 -i 4@s2-eth4 -i 5@s2-eth5 --pcap --nanolog ipc:///tmp/bm-1-log.ipc --device-id 1 --no-p4 --log-console -- --grpc-server-addr 0.0.0.0:50052 -- --thrift-port 9877`

P4 switch s2 did not start correctly.

When I checked the log of switch s1 I found 

> Thrift port was not specified, will use 9090
Calling target program-options parser
Adding interface s1-eth1 as port 1
[18:58:02.712] [bmv2] [D] [thread 3926] Adding interface s1-eth1 as port 1
Adding interface s1-eth2 as port 2
[18:58:02.742] [bmv2] [D] [thread 3926] Adding interface s1-eth2 as port 2
I0402 18:58:02.767079185    3926 server_builder.cc:247]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2147483647, CQ timeout (msec): 1000
Server listening on 0.0.0.0:50051
Thrift server was started

When I checked the log of switch s2 I found
 
> Thrift port was not specified, will use 9090
Calling target program-options parser
Adding interface s2-eth1 as port 1
[18:58:03.227] [bmv2] [D] [thread 3930] Adding interface s2-eth1 as port 1
Adding interface s2-eth2 as port 2
[18:58:03.254] [bmv2] [D] [thread 3930] Adding interface s2-eth2 as port 2
Adding interface s2-eth3 as port 3
[18:58:03.279] [bmv2] [D] [thread 3930] Adding interface s2-eth3 as port 3
Adding interface s2-eth4 as port 4
[18:58:03.303] [bmv2] [D] [thread 3930] Adding interface s2-eth4 as port 4
Adding interface s2-eth5 as port 5
[18:58:03.331] [bmv2] [D] [thread 3930] Adding interface s2-eth5 as port 5
I0402 18:58:03.359570279    3930 server_builder.cc:247]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2147483647, CQ timeout (msec): 1000
Thrift: Mon Apr  2 18:58:03 2018 TServerSocket::listen() BIND 9090
Server listening on 0.0.0.0:50052
Thrift server was started
Thrift returned an exception when trying to bind to port 9090
The exception is: Could not bind: Transport endpoint is not connected
You may have another process already using this port, maybe another instance of bmv2.


 seems like simple_switch_grpc thrift server always attempts to start at port 9090 as confirmed by 

> p4@p4:/tmp$netstat -an | grep 9090
tcp6       0      0 :::9090                 :::*                    LISTEN     
p4@p4:/tmp$ netstat -an | grep 9876
p4@p4:/tmp$

**Comment by antoninbas** [comment]
`--thrift-port` is a bmv2 generic command-line option, not a target-specific option
It should not appear after `--`, but along with the other generic command-line options, such as `--log-console`

**Comment by coolvikas** [comment]
I have tried again with `--thrift-port 9876` option 
`simple_switch_grpc -i 1@s1-eth1 -i 2@s1-eth2 --pcap --nanolog ipc:///tmp/bm-0-log.ipc --device-id 0 --no-p4 --log-console -- --grpc-server-addr 0.0.0.0:50051 --thrift-port 9876`

`simple_switch_grpc -i 1@s2-eth1 -i 2@s2-eth2 -i 3@s2-eth3 -i 4@s2-eth4 -i 5@s2-eth5 --pcap --nanolog ipc:///tmp/bm-1-log.ipc --device-id 1 --no-p4 --log-console -- --grpc-server-addr 0.0.0.0:50052 --thrift-port 9877`

Log of s1 is as follows  

> Thrift port was not specified, will use 9090
Calling target program-options parser
unrecognised option '--thrift-port'
Target parser returned an error
Adding interface s1-eth1 as port 1
[10:48:15.449] [bmv2] [D] [thread 7574] Adding interface s1-eth1 as port 1
Adding interface s1-eth2 as port 2
[10:48:15.477] [bmv2] [D] [thread 7574] Adding interface s1-eth2 as port 2
I0403 10:48:15.506830116    7574 server_builder.cc:247]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2147483647, CQ timeout (msec): 1000

Log of s2 is as follows

> Thrift port was not specified, will use 9090
Calling target program-options parser
unrecognised option '--thrift-port'
Target parser returned an error
Adding interface s2-eth1 as port 1
[10:48:16.008] [bmv2] [D] [thread 7581] Adding interface s2-eth1 as port 1
Adding interface s2-eth2 as port 2
[10:48:16.035] [bmv2] [D] [thread 7581] Adding interface s2-eth2 as port 2
Adding interface s2-eth3 as port 3
[10:48:16.061] [bmv2] [D] [thread 7581] Adding interface s2-eth3 as port 3
Adding interface s2-eth4 as port 4
[10:48:16.089] [bmv2] [D] [thread 7581] Adding interface s2-eth4 as port 4
Adding interface s2-eth5 as port 5
[10:48:16.114] [bmv2] [D] [thread 7581] Adding interface s2-eth5 as port 5
I0403 10:48:16.142701154    7581 server_builder.cc:247]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2147483647, CQ timeout (msec): 1000
Thrift: Tue Apr  3 10:48:16 2018 TServerSocket::listen() BIND 9090
Server listening on 0.0.0.0:50051
Thrift server was started
Thrift returned an exception when trying to bind to port 9090
The exception is: Could not bind: Transport endpoint is not connected
You may have another process already using this port, maybe another instance of bmv2.

However I have compiled simple_switch_grpc using --with-thrift option

> NUM_CORES=`grep -c ^processor /proc/cpuinfo`
git clone https://github.com/p4lang/PI.git
cd PI
#git submodule update --init --recursive
./autogen.sh
./configure --with-proto --without-internal-rpc --without-cli --without-bmv2
make -j${NUM_CORES}
sudo make install
sudo ldconfig
cd ..
git clone https://github.com/p4lang/behavioral-model.git
cd behavioral-model
tmpdir=`mktemp -d -p .`
cd ${tmpdir}
bash ../travis/install-thrift.sh
bash ../travis/install-nanomsg.sh
sudo ldconfig
bash ../travis/install-nnpy.sh
cd ..
sudo rm -rf $tmpdir
cd ..
cd behavioral-model
./autogen.sh
./configure --enable-debugger --with-pi --with-thrift
make -j${NUM_CORES}
sudo make install
sudo ldconfig
cd targets/simple_switch_grpc
./autogen.sh
./configure --with-thrift
make -j${NUM_CORES}
sudo make install
sudo ldconfig
cd ..
cd ..
cd ..

**Comment by coolvikas** [comment]
Thanks @antoninbas @jafingerhut finally it worked.
