### ISSUE TITLE
Can not make run

### ISSUE THREAD

**Issue by jw1park** [p4lang/behavioral-model#575]
When I run "make" command, There is some issue like below.

make[1]: *** [all-recursive] error1
make: *** [all[ Error 2

How cai I fix it??

**Comment by coolvikas** [comment]
Please run this script if you want to install simple_switch_grpc target with bmv2

git clone https://github.com/p4lang/behavioral-model.git
NUM_CORES=`grep -c ^processor /proc/cpuinfo`
cd behavioral-model
tmpdir=`mktemp -d -p .`
cd ${tmpdir}
bash ../travis/install-thrift.sh
bash ../travis/install-nanomsg.sh
sudo ldconfig
bash ../travis/install-nnpy.sh
cd ..
sudo rm -rf $tmpdir
cd ..
# Bmv2
cd behavioral-model
./autogen.sh
./configure --enable-debugger --with-pi
make -j${NUM_CORES}
sudo make install
sudo ldconfig
# Simple_switch_grpc target
cd targets/simple_switch_grpc
./autogen.sh
./configure
make -j${NUM_CORES}
sudo make install
sudo ldconfig
cd ..
cd ..
cd ..

**Comment by antoninbas** [comment]
@jw1park you do not provide enough information for us to help; including the rest of the logs would be great.

**Comment by jw1park** [comment]
I am sorry. I don;t know How can I see the log. Please Tell me the log command.
and After reply, I try 'make' again, I see the error massage like this.

Makefile:403: recipe for target 'server.lo' failed
make[3]: *** [server.lo] Error 1
make[3]: Leaving directory '/home/sds/share/bmv2/src/bm_runtime'
Makefile:541: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/sds/share/bmv2/src'
Makefile:451: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
Duplicate of 
Duplicate of ##
make[1]: Leaving directory '/home/sds/share/bmv2'
Makefile:381: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by antoninbas** [comment]
If you don't know what to look for, I suggest that you remove your current bmv2 directory, start from scratch and **provide us with all the bash logs**:
```
git clone https://github.com/p4lang/behavioral-model.git bmv2
cd bmv2
./autogen.sh
./configure
make
```

**Comment by antoninbas** [comment]
Closing this as no further information was provided, feel free to re-open it if needed.
