### ISSUE TITLE
Something broke with the deparser implementation for the stack of headers

### ISSUE THREAD

**Issue by gopchandani** [p4lang/behavioral-model#577]
We are using a statement which does a push_front in the stack of headers (like INT examples), it seems to work fine with the bm version (a83e2a37b0b4d595be1f4367e64bf449324e2aef), but the latest master branch version (d14bfb1beb4dcf298d846a228db5d6c7f885827b) is not pushing the header as expected (the next switch parses it and throws a PacketTooShort). It is definitely not there in the packet (as evident in the pcap).

The program we are running is here:

https://github.com/gopchandani/AquaFlow

If you wish to reproduce, then get the repo above and using the latest version of bm, follow these steps from the project root (AquaFlow/.):

1. sudo python experiment/experiment.py --type diversity -- payload 1024 --dev_mode

This will start a mininet shell.

2. From another terminal, start a tcpdump on s2-eth2

3. On the mininet shell run:

h1 python send_stream.py --npackets 2 --payload 1024

**Comment by jafingerhut** [comment]
A guess: this commit is the one that 'broke' your program's behavior: https://github.com/p4lang/behavioral-model/commit/9131ed9bc4f634e415d459e7d26e154396be1042

Before that commit, the default behavior in bmv2 for a P4_16 push_front(1) operation was to push 1 new _valid_ header at index 0 of the header stack, the way P4_14 push operation does.  However, that behavior does not conform with the P4_16 v1.0.0 language spec, which says that the newly pushed headers should be _invalid_.  See section 8.15 "Operations on header stacks" in the P4_16 language spec.

With the behavioral-model commit I linked above, the default behavior of P4_16 push_front now conforms with the language spec.

In your program, I believe this is the only call to the push_front method: https://github.com/gopchandani/AquaFlow/blob/master/templates/aqua_flow_template.p4#L530

If you add a new line of code immediately after that one like this: "hdr.switch_stats[0].setValid();" (it should be _before_ any assignments to fields in the header hdr.switch_stats[0]), likely your program will return to its former behavior.

**Comment by gopchandani** [comment]
That works. Thanks!
