### ISSUE TITLE
Ubuntu 'mktemp' package isn't needed, and maybe gone in Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/behavioral-model#578]
This line should probably be removed: https://github.com/p4lang/behavioral-model/blob/master/install_deps.sh#L22

In Ubuntu 14.04 and 16.04, the mktemp package only installs a documentation file in /usr/share/doc/mktemp, no executables or libraries needed for building.

In Ubuntu 18.04 beta, there is no mktemp Ubuntu package at all right now, and that line in the shell script causes the apt-get command to fail to install anything.

**Comment by antoninbas** [comment]
@jafingerhut Thanks. I'm surprised you didn't open a PR directly :)

**Comment by jafingerhut** [comment]
Sorry, I was being lazy :)
