### ISSUE TITLE
referencing the timestamp in BMv2

### ISSUE THREAD

**Issue by Pwniee** [p4lang/behavioral-model#580]
I'm writing a modified version of the basic.p4 program from the tutorials and despite my best efforts I still haven't managed to reference the ingress_global_timestamp field in order to have it correctly set by the BM (its always set zero).

Any ideas?

Here's my code:

`
/* -*- P4_16 -*- */
#include <core.p4>
#include <v1model.p4>

struct ingress_intrinsic_metadata_t {
    bit<1>  resubmit_flag;
    bit<48> ingress_global_timestamp;  // Always at zero :'(
    bit<16> mcast_grp;
    bit<1>  deflection_flag;
    bit<1>  deflect_on_drop;
    bit<2>  enq_congest_stat;
    bit<2>  deq_congest_stat;
    bit<13> mcast_hash;
    bit<16> egress_rid;
    bit<32> lf_field_list;
    bit<3>  priority;
    bit<3>  ingress_cos;
    bit<2>  packet_color;
    bit<5>  qid;
}

struct metadata {
    custom_metadata_t custom_metadata;
    ingress_intrinsic_metadata_t intrinsic_metadata;

}
`

Thank you all 👍

**Comment by antoninbas** [comment]
If you're using P4_16 with v1model, you cannot define your own version of the standard / intrinsic metadata fields, you need to use the ones defined in v1model.p4: https://github.com/p4lang/p4c/blob/master/p4include/v1model.p4#L55

For the ingress timestamp, the field is `standard_metadata.ingress_global_timestamp`.

**Comment by Pwniee** [comment]
Okay, got it. Thank you very much Antonin.

**Comment by ajayrahul97** [comment]
Hello ! 
I need to access the timestamp of every packet that arrives at my bmv2 switch.
I am unable to get any proper value, just by using standard_metadata.ingress_global_timestamp...i.e I am getting 0.
Infact, many other values under standard metadata are outputted as zero.
Is there any additional requirement to access the proper and correct values? Please help me out.Thanks you !

**Comment by jafingerhut** [comment]
With the latest versions of behavioral-model and p4c code, I see non-0 values for standard_metadata.ingress_global_timestamp at the beginning of ingress, and non-0 values for both that field and for standard_metadata.egress_global_timestamp at the beginning of egress, at least for a packet received from an input port and then sent via unicast to an egress port.

I do not know if there is a particular point in time when this was broken, and then was fixed, but are you able to use the latest versions?
