### ISSUE TITLE
thrift make failed

### ISSUE THREAD

**Issue by jw1park** [p4lang/behavioral-model#591]
I don't know how to fix it..
when I run the commane "make" to install thrift,
Error message happen below.

collect2: error: ld returned 1 exit status
Makefile:1168: recipe for target 'processor_test' failed
make[3]: *** [processor_test] Error 1
make[3]: Leaving directory '/home/thrift-0.10.0/lib/cpp/test'
Makefile:954: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/thrift-0.10.0/lib/cpp/test'
Makefile:646: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/thrift-0.10.0'
Makefile:560: recipe for target 'all' failed
make: *** [all] Error 2

what is the problem??

**Comment by antoninbas** [comment]
It seems to me that you are missing the important part of the error logs (before `collect2: error: ld returned 1 exit status`). If it is a Thrift build error, maybe you should ask for the help of the Thrift community as well?

**Comment by jafingerhut** [comment]
@jw1park These kinds of things can depend on all kinds of things, such as: what operating system are you running (including which version of that operating system)?  What C compiler do you have installed, and which version?  Which version of glibc?  etc. etc. etc.  It depends on all kinds of details you haven't mentioned in your question, and without those it is impossible for someone else to help you.

If you want (nearly) guaranteed success, install a new fresh clean copy of Ubuntu 16.04 Linux on a physical or virtual machine with an x86_64 processor (Intel or AMD) with at least 2 GB of RAM, and at least 10 GB of disk space.  You can get a copy of the install image here: https://www.ubuntu.com/download  You can install it as a virtual machine using free VirtualBox (virtualbox.org) running on a Windows, Mac, or Linux machine, as long as you have that much free disk space and unused RAM.

After it is installed, log in and do these commands, entering the admin password when asked:
```
sudo apt install git
git clone https://github.com/jafingerhut/p4-guide
./p4-guide/bin/install-p4dev.sh
```

That sequence of steps was obtained by me following the README instructions for the behavioral-model and p4c repositories, not from some special secret inside info I have.  I have used them multiple times on multiple Ubuntu 16.04 machines successfully.

If for some reason you really, really want to use a different version of Linux, or an OS other than Linux, then you will need to give more details, and perhaps expect more problems.

**Comment by jw1park** [comment]
Thank you for your help.
it works anyway. but there is some questions.
When I install p4c and try make,(like below)
root@~virtualBox:# make -j${MAX_PARALLEL_JOBS}
Does "-j${MAX_PARALLEL_JOBS}" need always??
or Is only "make" ok??

If I run command "make" with  -j${MAX_PARALLEL_JOBS} , Vm machine was rebooting automatically.

**Comment by jafingerhut** [comment]
The -j${MAX_PARALLEL_JOBS} is an optional speedup, enabling 'make' to run up to that many processes at a time.  If you leave it off, it should still work, using at most one process at a time.  It may take a little longer, but it should also require less RAM at one time, too.

**Comment by antoninbas** [comment]
Closing this issue. I'm assuming it was resolved since there was no update.
