### ISSUE TITLE
[question] `mirroring_add` on simple_switch_grpc target

### ISSUE THREAD

**Issue by pwkuan** [p4lang/behavioral-model#600]
Hello,

We can call `clone()` in P4 program via using `mirroring_add <mirror_id> <egress_port>` simple_switch_CLI's command line on simple_switch targets. I'd like to do this on simple_switch_grpc targets, however, this command line doesn't work on simple_switch_grpc targets. I saw 
[switch_runner.h](https://github.com/p4lang/behavioral-model/blob/master/targets/simple_switch_grpc/switch_runner.h#L71) this file has mirroring session API.
```
  // mirroring sessions
  int mirroring_mapping_add(int mirror_id,
                            bm::DevMgrIface::port_t egress_port);
```
How can I use it to set mirroring session on simple_switch_grpc targets?

Thanks!

**Comment by antoninbas** [comment]
Why do you say the command line doesn't work on simple_switch_grpc? What kind of error do you get?

**Comment by pwkuan** [comment]
Error Message:
```
$ simple_switch_CLI 
Could not connect to thrift client on port 9090
Make sure the switch is running and that you have the right port
```
Then, I saw these Information below:
1. [SimpleSwitchGrpc | FAQ ](https://github.com/p4lang/behavioral-model/tree/master/targets/simple_switch_grpc#enabling-the-thrift-server)
```
FAQ
I am using P4Runtime to program table entries, but I'd like to be able to use simple_switch_CLI to check the contents of my tables.
Refer to Enabling the Thrift server above. Use `--with-thrift` when configuring bmv2 and simple_switch_grpc.
```
2. “clone operation not working on simple_switch_grpc target” · [Issue #478 ] 
```
...
 If you want to support cloning to the CPU port, just add the following call to the runner's initialization routine: mirroring_mapping_add(1024, <your CPU port>)
...
```
If I don't enable Thrift server on  bmv2(simple_switch_grpc target), 
how can I add `mirroring_mapping_add(1024, <your CPU port>)` this call in the runner's initialization routine to support cloning to the CPU port? 
Are there some examples?

**Comment by antoninbas** [comment]
Just add the function call towards the end of `SwitchRunner::init_and_start`: https://github.com/p4lang/behavioral-model/blob/master/targets/simple_switch_grpc/switch_runner.cpp#L380
The parameters need to match the session id you want to use and the CPU port number you want to use.

**Comment by pwkuan** [comment]
Thanks a lot for replying! I will try it to take implement.
