### ISSUE TITLE
Can't get the multi-port queue length correctly and the queue length register is always 0

### ISSUE THREAD

**Issue by Wannabeperfect** [p4lang/behavioral-model#601]
according to @antoninbas method,I change the simple_switch.cpp file into this:
![2018-05-12 00 23 26](https://user-images.githubusercontent.com/38399275/39935169-afb2890c-5537-11e8-8756-b4e3f1790d7e.png)
And I also change v1model.p4 
I make clean && make in the bmv2 directory and rebulid the p4c
I write a P4 program to send packets to the port that has the shortest queue length.
In my program:
qlength_1_reg.write(0,standard_metadata.deq_qdepth_4);  
qlength_2_reg.write(0,standard_metadata.deq_qdepth_5);
qlength_3_reg.write(0,standard_metadata.deq_qdepth_6);
qlength_4_reg.write(0,standard_metadata.deq_qdepth_7);
I use qlength_1_reg,qlength_2_reg,qlength_3_reg,qlength_4_reg to record each link length.
The topology is like this:
![38780788-907e563e-410e-11e8-8888-2a496e73e388](https://user-images.githubusercontent.com/38399275/39935659-48988bf2-5539-11e8-895d-05059610cc21.png)

when I run this program and add entries:
I send iperf flow from h1 to h5,
I use this command    **./simple_switch_CLI --thrift-port 22222**
It shows like this:

```
Control utility for runtime P4 table manipulation
RuntimeCmd: register_read ingress.qlength_1_reg
register index omitted, reading entire array
ingress.qlength_1_reg= 0
RuntimeCmd: register_read ingress.qlength_2_reg
register index omitted, reading entire array
ingress.qlength_2_reg= 0
RuntimeCmd: register_read ingress.qlength_3_reg
register index omitted, reading entire array
ingress.qlength_3_reg= 0
RuntimeCmd: register_read ingress.qlength_4_reg
register index omitted, reading entire array
ingress.qlength_4_reg= 0
```
I also use `set_queue_rate` to constrain the rate to 40 like this: `set_queue_rate 40 5`,but the register is still 0.
I do not know what's wrong with that.
It doesn't get the queue length correctly.

Thanks:)

**Comment by antoninbas** [comment]
It's very impractical to help you when you just provide screenshots. It would help to have the output of `git diff` instead for your changes and for you to attach your P4 program.
One thing that comes to mind: your registers seem to be defined in ingress based on their names (`ingress.qlength_X_reg`). I'm therefore assuming that you update these registers in **ingress**: `qlength_X_reg.write(0,standard_metadata.deq_qdepth_Y);`. Based on your simple_switch.cpp code, you can see that the queue depths are written to fields `standard_metadata.deq_qdepth_Y` **after** the packet is dequeued and these values are therefore only available in **egress**. You cannot have access to the queue depth for a packet before the packet has even been enqueued...

**Comment by Wannabeperfect** [comment]
@antoninbas   I define the queue length registers in **ingress** and update them in **ingress**

I should update the values in **egress**.However,I need to choose the egress port for each packet according to the shortest queue length.But the queue length is stored in the egress processing.What should I do to get the right result?

Thanks :)

**Comment by antoninbas** [comment]
Since it's a software switch and you can do whatever you want, why not just move the code that sets the metadata fields to before the ingress control is executed: https://github.com/p4lang/behavioral-model/blob/master/targets/simple_switch/simple_switch.cpp#L335
BTW it seems to me that you don't really need these fields at all, you can just set the register values directly.

**Comment by Wannabeperfect** [comment]
@antoninbas  I need to get the queue length when a packet comes everytime.And choose the link that has the shortest egress queue length.I need to compare each link's queue length.If I just set the register values,How to do it?
Thanks :)

**Comment by Wannabeperfect** [comment]
@antoninbas  This is the original version of my code,what should I do to make it right? Thank you so much :)
[switch.p4.zip](https://github.com/p4lang/behavioral-model/files/1997172/switch.p4.zip)

**Comment by MohamadAlAdraa** [comment]
> @antoninbas This is the original version of my code,what should I do to make it right? Thank you so much :) [switch.p4.zip](https://github.com/p4lang/behavioral-model/files/1997172/switch.p4.zip)

Hi @Wannabeperfect,

It is too late I know, but I would like to ask if you were able to get it to work. If yes may you help me in this. I would like to do the exact same thing you were trying to do.

I highly appreciate your help.

Thank you.
