### ISSUE TITLE
gRPC Server doesn't stay at listening mode

### ISSUE THREAD

**Issue by j90332** [p4lang/behavioral-model#606]
Hi all
When I start the grpc server on localhost, it doesn't stay at listening mode. 
How can I fix this problem?
`p4@p4:~$ simple_switch_grpc --no-p4 --device-id 1 -- --grpc-server-addr localhost:50051
Calling target program-options parser
I0523 18:30:36.702621944   27100 server_builder.cc:247]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2147483647, CQ timeout (msec): 1000
Server listening on localhost:50051
p4@p4:~$ 
`

I think it should stay after showing "Server listening on localhost:50051" and wait for connection.
But instead it dosn't.

Thanks for answering my question.

**Comment by antoninbas** [comment]
Closing this since no additional information was provided.
