### ISSUE TITLE
Counter index validation is missing from method count

### ISSUE THREAD

**Issue by avinash23482** [p4lang/behavioral-model#609]
Hi,
I am trying counters in a P4 program.
Following is a snippet from the program,       

```
control Ingress(inout Headers hdr, inout MetaData meta,     
 inout standard_metadata_t smeta) {
    
    counter(1024,CounterType.packets) c1;

    action forward( MACAddr_t dstAddr, Port_t port){
        hdr.ethernet.dstAddr = dstAddr;
        smeta.egress_port = port;
        c1.count(2000);
    }
}
```

The index which is getting increment is greater than the maximum supported size for the counter c1.
Still the JSON output is getting generated without any validation.

**Comment by jafingerhut** [comment]
Did you run this compiled P4 program in simple_switch?

If so, was there was no error or warning message about the out-of-bounds index when you used the `--log-console` or `--log-file` options?

A run-time check and warning in the log seems reasonable to me for out-of-bounds indices for counters, meters, and registers, but going to the trouble of checking statically when loading the JSON file for constant indices that are out of range seems like something that would seldom find a problem.

**Comment by jafingerhut** [comment]
I tested myself and found that the behavioral model is not currently doing any run-time bounds checking when updating indexed counters, meters, and register arrays.

I created a proposed PR that will cause useful messages to be printed to the log (when you use the `--log-console` or `--log-file` command line options to simple_switch) to help you detect if your program is accessing out of bounds indices.

**Comment by avinash23482** [comment]
Andy,I just tried generating JSON output for bmv2. I didn't run the compiled program.

-Avinash

**Comment by jafingerhut** [comment]
@avinash23482 Now that PR #637 has been merged in, if you update to the latest version of source for p4lang/behavioral-model, compile, and install it again, if you run the JSON output with simple_switch and `--log-console` or `--log-file` enabled, you will get an error message in the log when c1.count(2000) is executed.  As far as the P4 program behavior goes, such out of bounds accesses will be treated as a no op.

At least in my opinion, it seems like too much work for too little gain to try to catch such things at compile time.

**Comment by antoninbas** [comment]
I agree with @jafingerhut that that kind of static verification seems like an overkill to do in bmv2 or in the compiler. It would be appropriate in a static code analyzer tool - which would need to be architecture-aware to analyze extern method calls.

**Comment by avinash23482** [comment]
Thanks Antonin and Andy !!!
