### ISSUE TITLE
simple_switch, simple_switch_CLI not able to connect.

### ISSUE THREAD

**Issue by MadhavChoudhary** [p4lang/behavioral-model#612]
When I run simple_switch_CLI, I get the output
```
 simple_switch_CLI
Could not connect to thrift client on port 9090
Make sure the switch is running and that you have the right port
```
I have tried with other ports, the no advantage.

On running simple_switch with any thrift port and a json file, the error message is like
```
Thrift port was not specified, will use 9090
Calling target program-options parser
Nanomsg returned a exception when trying to bind to address 'ipc:///tmp/bmv2-0-notifications.ipc'.
The exception is: Address already in use
This may happen if
1) the address provided is invalid,
2) another instance of bmv2 is running and using the same address, or
3) you have insufficent permissions (e.g. you are using an IPC socket on Unix, the file already exists and you don't have permission to access it)
```

I am trying to run SIGCOMM2017/source_routing tutorial, it gives error message
```
Entering build directory.
Extracting package.
Reading package manifest.
> p4c --std p4-16 "source_routing.p4" -o "source_routing.p4.json"
*** Log directory /home/vaddinenipavankumar/Documents/tutorials/SIGCOMM_2017/exercises/source_routing/build/logs
*** Pcap directory /home/vaddinenipavankumar/Documents/tutorials/SIGCOMM_2017/exercises/source_routing/build
> python2.7 "/home/vaddinenipavankumar/Documents/tutorials/SIGCOMM_2017/utils/mininet/multi_switch_mininet.py" --log-dir "/home/vaddinenipavankumar/Documents/tutorials/SIGCOMM_2017/exercises/source_routing/build/logs" --manifest "./p4app.json" --target "multiswitch" --auto-control-plane --behavioral-exe "simple_switch" --json "source_routing.p4.json" --cli-message "mininet_message.txt"
*** Creating network
*** Adding hosts:
h1 h2 h3 
*** Adding switches:
Cannot find required executable simple_switch.
Please make sure that it is installed and available in your $PATH:
(/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin)
```

I have made sure that it exists in path.
Note: SIGCOMM2015/source_routing tutorial is working on bmv2 simple switch.

**Comment by antoninbas** [comment]
The simple_switch_CLI error means simple_switch is not running which you can probably confirm by looking at running processes on your machine.
The "already in use" error means that simple_switch was previously run as root and you are now trying to run it without root privileges. You probably want to run it as root again. If you do want to run it without root privileges, you can try executing `sudo rm -rf ipc:///tmp/bmv2-0-notifications.ipc` before starting simple_switch. Keep in mind that running without root privileges will not let you access veth interfaces.
For the last error, you probably want to open an issue in the tutorials repository instead.

**Comment by MadhavChoudhary** [comment]
But those commands are working when I restart the computer. Even without sudo.

**Comment by jafingerhut** [comment]
Most (maybe all?) Linux distributions have boot time scripts that delete all files in the /tmp directory, which would remove the /tmp/bmv2-0-notifications.ipc file that Antonin mentioned, too.

If you want to be able to run simple_switch with the capability of sending packets to and receiving packets from veth interfaces, do these steps in this order:

Create veth interfaces desired (e.g. using veth_setup.sh shell script mentioned in another comment to you -- only needs to be done once after booting up the Linux system)

(The next command is unlikely to be needed as long as you run simple_switch as root, but it cannot hurt anything, either)
sudo rm -rf ipc:///tmp/bmv2-0-notifications.ipc
sudo simple_switch <desired cmd line options>
(Assuming simple_switch started up correctly, it is now listening on TCP port 9090 for control connections.  The simple_switch_CLI command below should successfully open a TCP connection to port 9090, as a TCP client.)
simple_switch_CLI
