### ISSUE TITLE
P4 Debugger

### ISSUE THREAD

**Issue by djshah19** [p4lang/behavioral-model#614]
Hello,

Even though debugger is enabled. When executing ./p4dbg.py I get error - "The debugger is not enabled on the switch". Please help me on this.
![image](https://user-images.githubusercontent.com/38405786/40857988-de815bb8-65aa-11e8-9750-df5ed90bc4b5.png)

Thanks,
Dhwani

**Comment by antoninbas** [comment]
Did you use the `--debugger` command-line flag when starting the switch?

**Comment by djshah19** [comment]
I am running P4D2_2017_Spring/ipv4_forward program. To execute program I run ./run.sh file which starts the switch. Where shall I use --debugger command-lie flag?

**Comment by antoninbas** [comment]
This stuff seems to be gone from the tutorials repo now.
I don't think there is a convenient way to do it by modifying p4app.json so you may have to edit the p4apprunner.py script to add the `--debugger` command-line flag to the list of simple_switch args.

**Comment by antoninbas** [comment]
You can probably just add it to the `switch_args` list

**Comment by djshah19** [comment]
Im still not able to enable debugger on switch. could you please tell where exactly I need to add the --debugger flag?

**Comment by djshah19** [comment]
I see below piece of code in p4_mininet.py    
    if self.enable_debugger:
            args.append("--debugger")
        if self.log_console:
            args.append("--log-console")

**Comment by djshah19** [comment]
I was able to start the debugger
![image](https://user-images.githubusercontent.com/38405786/40984921-f654e90e-68b0-11e8-8c46-904a3795f623.png)

Is it possible to open code in another box as shown in image below?
![image](https://user-images.githubusercontent.com/38405786/40985077-4ef859ba-68b1-11e8-8850-f044ebaf6319.png)

**Comment by antoninbas** [comment]
Everything that can be done with the debugger is included in the user guide (https://github.com/p4lang/behavioral-model/blob/master/docs/p4dbg_user_guide.md). That doesn't include displaying the code being executed (whether that's the P4 or the C++ code).

**Comment by afaheemp4** [comment]
@djshah19 Hello, 
Do you remember how the debugger problem solved by you?
