### ISSUE TITLE
Sending Packets to simple_switch

### ISSUE THREAD

**Issue by MadhavChoudhary** [p4lang/behavioral-model#616]
I tried to send packets to simple_switch (thrift-server on port 9090) with MoonGen packet generator. But it says no devices found. I also found that veth interfaces cannot be binded to dpdk. But I don't know what that means.

``sudo ./simple_switch -i 0@<iface0> -i 1@<iface1> <path to JSON file>``

Now, should we send packets to switch ports i.e 0,1 or to port 9090 of the server. I don't have proper knowledge about ports and interfaces. 

I ran p4benchmark.lua file in lua_config folder in p4benchmark.

**Comment by jafingerhut** [comment]
If you want to run simple_switch, and have it process packets as specified by your P4 program, you should send packets to one of the interfaces specified via a `-i <number>@<ifacename>` option on the `simple_switch` command line.  If you send a packet to interface `ifacename`, simple_switch should see it, and process it as if it was received on port number `<number>`.  If the P4 program sends a packet out to port number `<number>`, simple_switch should transmit that packet on the Unix interface `ifacename`.

There are examples of this using the Scapy library to send packets, and tcpdump to see what packets are going across the interfaces, that you can try out here if you want: https://github.com/jafingerhut/p4-guide/tree/master/demo1

That link is to one simple `demo` example P4 program in that git repo.  It contains others as well, but demo1 is the simplest one to start with.  The link to `README-using-bmv2.md` should be followed and read as well -- the document at that link contains example tcpdump commands for showing the contents of packets as they go across Linux network interfaces.

**Comment by antoninbas** [comment]
Closing this since no update. Feel free to re-open if you have additional questions.
