### ISSUE TITLE
Table miss when inserting entries via P4Runtime with priority 0

### ISSUE THREAD

**Issue by ccascone** [p4lang/behavioral-model#618]
I'm running simple_switch_grpc on rev 4e9a885 but I suspect the issue is present also on master.
When inserting entries for a table that includes a ternary match, if priority is set to 0 (default value), packets are not matched as expected. I've seen the issue when running `FabricL2UnicastTest` from fabric-p4test with table `FabricIngress.filtering.ingress_port_vlan`

**Comment by antoninbas** [comment]
What kind of behavior do you observe and do you have the bmv2 logs for the table add operation?

The P4Runtime spec currently says that:

> The priority field must be set to a non-zero value if the match key includes a ternary match, i.e. if the P4Info entry for the table indicates that one or more of its match fields has a TERNARY or RANGE match type, or to zero otherwise.

I believe that this is for consistency with the "Zero as reserved value section", but this may be an unnecessary restriction for priority.

**Comment by ccascone** [comment]
I see a table miss. I also confirm that the issue goes way when setting a non-zero priority.

Below are the log excerpts for the P4Runtime write operation, and table key lookup. You can replicate the issue with fabric-p4test,  BMv2 rev 4e9a885, PI rev 8588f60 (before v1 package rename), and ONOS master (for fabric.p4):

```
sudo ./ptf_runner.py --device bmv2 --p4info $ONOS_ROOT/pipelines/fabric/src/main/resources/p4c-out/bmv2/fabric.p4info --bmv2-json $ONOS_ROOT/pipelines/fabric/src/main/resources/p4c-out/bmv2/fabric.json --ptf-dir fabric.ptf --port-map ./port_map.veth.json test.FabricL2UnicastTest
```

If a restriction exists in the spec, then I'd expect the P4Runtime server to reject a write request with priority set to 0. Perhpas this check is not implemented in PI? I also believe this migh be an uneccesary restriction, since we could say that an unset priority (i.e. 0) means the lowest priority. Altough, the spec also says that:

> The match and priority fields are used to uniquely identify an entry within a table. Therefore, these fields cannot be modified after the entry has been inserted and must be provided for MODIFY and DELETE updates. 

I guess it helps with debugging to see the priority field explicitelly set when inspecting a MODIFY or DELETE message. But I can't think of any other usage that would justify reserving the value 0.

```
P4Runtime Write
updates {
  type: INSERT
  entity {
    table_entry {
      table_id: 33611649
      match {
        field_id: 1
        exact {
          value: "\000\001"
        }
      }
      match {
        field_id: 2
        exact {
          value: "\000"
        }
      }
      action {
        action {
          action_id: 16835546
          params {
            param_id: 1
            value: "\000\n"
          }
        }
      }
    }
  }
}
[21:57:39.630] [bmv2] [D] [thread 28142] Entry 0 added to table 'FabricIngress.filtering.ingress_port_vlan'
[21:57:39.630] [bmv2] [D] [thread 28142] Dumping entry 0
Match key:
* standard_metadata.ingress_port: EXACT     0001
* hdr.vlan_tag.is_valid         : EXACT     00
* hdr.vlan_tag.vlan_id          : TERNARY   0000 &&& 0000
Priority: 2147483647
```

```
[21:57:39.638] [bmv2] [D] [thread 28146] [0.0] [cxt 0] Looking up key:
* standard_metadata.ingress_port: 0001
* hdr.vlan_tag.is_valid         : 00
* hdr.vlan_tag.vlan_id          : 0000

[21:57:39.638] [bmv2] [D] [thread 28146] [0.0] [cxt 0] Table 'FabricIngress.filtering.ingress_port_vlan': miss
```
