### ISSUE TITLE
No digest received from nanomsg notifications

### ISSUE THREAD

**Issue by rosstex** [p4lang/behavioral-model#623]
Hello,

I am unable to receive digests from the nanomsg notifications channel (`ipc:///tmp/bmv2-<device-id>-notifications.ipc`) of the bmv2 switch.

It began as an issue with the p4c compiler that is now fixed: https://github.com/p4lang/p4c/issues/1352. You can find my p4 code there. Now, my program compiles and the bmv2 switch logs:
```
[03:59:45.628] [bmv2] [T] [thread 19143] Learning sample for list id 1
```
which I assume means the digest was sent.

However, the nanomsg notifications (`ipc:///tmp/bmv2-<device-id>-notifications.ipc`) are still empty when I connect to the socket.

Here's the Python code I am using, with the nanomsg-python library:
```
sub = Socket(SUB)
sub.connect('ipc:///tmp/bmv2-0-notifications.ipc')
sub.set_string_option(SUB, SUB_SUBSCRIBE, "")
msg = sub.recv()
```

I can receive from the nanolog properly, so the socket itself is not the issue.

**Comment by antoninbas** [comment]
If the bmv2 process is run as root, you need to make sure that your Python script runs as root too. Did you make sure that was the case?

**Comment by rosstex** [comment]
Good thought, but that is not the issue. My python script is running as root and I can receive from the --nanolog addr successfully. It's the --notifications-addr that I cannot receive from.

**Comment by antoninbas** [comment]
I gave it a try with your program and I'm receiving the notification just fine:
```
sudo simple_switch -i 0@veth0 --log-console ross_dfa_int.json
...
[15:04:36.513] [bmv2] [T] [thread 8742] Sending learning notification for list id 1 (buffer id 0)
```
```
antonin@ubuntu:~/Documents/p4lang/bmv2$ sudo python test.py 
LEA|<non ASCII>
```
```
cat test.py
import nnpy

sub = nnpy.Socket(nnpy.AF_SP, nnpy.SUB)
sub.connect('ipc:///tmp/bmv2-0-notifications.ipc')
sub.setsockopt(nnpy.SUB, nnpy.SUB_SUBSCRIBE, '')
msg = sub.recv()
print msg
```
I'm using the nnpy package, since this is the one I have installed at the moment. Seems to me that this is not a bmv2 problem but an issue with your nanomsg setup (maybe you are using a version of nanomsg which is not compatible with the Python package version you are using?).

**Comment by antoninbas** [comment]
Although I'm not sure why it would work with the logging socket and not the notifications socket... They both use pubsub. Maybe give it a try with nnpy...

**Comment by rosstex** [comment]
Can you receive any messages after that first one? I moved my socket code to a separate file like yours (I originally had it in a controller file that gets called from p4apprunner), and I can receive the first learn message. But no further messages.

**Comment by rosstex** [comment]
I see, thank you! That would be bm_learning_ack I presume. And I will follow the unpacking scheme as described in http://lists.p4.org/pipermail/p4-dev_lists.p4.org/2017-September/001379.html.

**Comment by antoninbas** [comment]
Looking at this code may help as well: https://github.com/p4lang/behavioral-model/blob/master/src/bm_apps/notifications.cpp
