### ISSUE TITLE
generate_digest only works on ingress

### ISSUE THREAD

**Issue by rosstex** [p4lang/behavioral-model#625]
I noticed that generate_digest has no effect when called from egress; only on ingress. Is this an intended behavior?

**Comment by antoninbas** [comment]
Yes that's the intended behavior. The generate_digest extern call actually just sets a flag. The actual digest is generated at the end of the ingress pipeline (https://github.com/p4lang/behavioral-model/blob/master/targets/simple_switch/simple_switch.cpp#L387), which means that the field values in the digest message are the ones at the end of ingress.

**Comment by jafingerhut** [comment]
@hanw @cc10512 I can create a separate issue if needed, but Antonin's answer made me wonder whether we think the intent in the PSA specification is that digests can only be created in ingress?  I believe the current PSA spec either doesn't restrict it explicitly, or perhaps explicitly says digests can be created in ingress and egress.

**Comment by rosstex** [comment]
The use case is collecting metrics about packets that satisfy certain queries. This might be "all cloned packets leaving port 2 on switch A", or the queue delta times/other data related to egress processing.

**Comment by rosstex** [comment]
From PSA:
"A PSA program can instantiate multiple Digest instances in the same IngressDeparser control
block, and make at most one pack call on each instance during a single execution of this control block. The same applies independently for the EgressDeparser control block."

**Comment by hanw** [comment]
Fixed PSA spec to be consistent with behavior-model, https://github.com/p4lang/p4-spec/pull/657

**Comment by antoninbas** [comment]
The right fix may not be to simply make PSA consistent with what bmv2/simple_switch does, but I think simple_switch inherited that behavior from P4_14. Also, note that bmv2 could easily accommodate digests in egress.

However IMO it probably makes sense to limit digests to ingress for an architecture like PSA, which aims at being the highest common denominator across switching ASICs. AFAIK, learning is most frequently used early in the pipeline for L2.
