### ISSUE TITLE
Implementation of Hash extern with CRC32

### ISSUE THREAD

**Issue by cristina-dominicini** [p4lang/behavioral-model#628]
I am trying to calculate the output value of CRC32 in a P4 program using the hash extern of the v1model:
extern void hash<O, T, D, M>(out O result, in HashAlgorithm algo, in T base, in D data, in M max);

I am running the simple switch. My test P4 code:

        bit<32> nbase=0;
        bit<64> nmax=4294967296*2;
        bit<32> nselect;
        bit<32> ninput = 123456789;
        hash(nselect, HashAlgorithm.crc32, nbase, {ninput},nmax);
 
As the result is (nbase + (hash_value % nmax)), I used nbase as 0 and nmax as a value greater than the maximum possible value for nselect (32 bits). In this way, I expect to get the CRC32 output without any modification.

For input 123456789, I expect to I get 3421780262 (int) or 0xcbf43926 (hex), as described here: http://crcmod.sourceforge.net/crcmod.predefined.html#predefined-crc-algorithms
 
I have already checked, and the behavioral model implementation of CRC32 (https://github.com/p4lang/behavioral-model/blob/master/src/bm_sim/calculations.cpp#L285) is producing the expected results. To that end, I executed the attached C++ code (testcrc.cpp).

But, when I run this P4 code, I get the result 3488836380 (int), and I was not able to understand this output.

Besides, if I change the algorithm to HashAlgorithm.crc32_custom (https://github.com/p4lang/behavioral-model/blob/master/src/bm_sim/calculations.cpp#L207), which provides a generic implementation of CRC32, the result is also 3488836380.

Please, find attached my test code. To facilitate tests, I modified the calc example from tutorials (https://github.com/p4lang/tutorials/tree/master/exercises/calc) to add a CRC32 operation as "input>base" (Example: "123456789>0" calculates the CRC32 for input=123456789 and base=0).

[test_crc.zip](https://github.com/p4lang/behavioral-model/files/2204000/test_crc.zip)

Thank you,
Cristina Klippel Dominicini

**Comment by antoninbas** [comment]
I believe 3488836380 (0xCFF36B1C) is the correct value and that's the value I'm getting with bmv2 and with online calculators. Your C++ test program is wrong by the way. You're using ASCII characters instead of a binary string in your test program, so there is no way you are going to get the same result using `bit<X>` in P4.
The C++ test program should read:
```
char databuf2[] = {0x07, 0x5b, 0xcd, 0x15} // 123456789 in hex
```
and not
```
char databuf2[9] = {'1', '2', '3', '4', '5', '6','7','8','9'};
```

**Comment by cristina-dominicini** [comment]
Thank you for the information, Antonin. You are right, I was misunderstanding the input format.

**Comment by Justin860215** [comment]
This is my code, and I have a same question as cristina-dominicini. My answer is 3421780262 (int) or 0xcbf43926 (hex). I do not know why it has to be like this. Please help me.

[testcrc.zip](https://github.com/p4lang/behavioral-model/files/5660908/testcrc.zip)

**Comment by Justin860215** [comment]
I want to know how to cinvert 123456789 to {0x07, 0x5b, 0xcd, 0x15}, please help me. Thank you!

**Comment by jafingerhut** [comment]
> I want to know how to convert 123456789 to {0x07, 0x5b, 0xcd, 0x15}, please help me. Thank you!

Are you asking how to convert an integer from decimal to hexadecimal?  There are many free calculator programs that can do this, or some hand-held calculators, etc.  You can do it in Python like this:

```
$ python3
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> print("%x" % (123456789))
75bcd15
```
