### ISSUE TITLE
Generate one packet for each WCMP member in BMv2

### ISSUE THREAD

**Issue by konne-google** [p4lang/behavioral-model#641]
I'm moving a conversation between me and Antonin into a bug here for better visibility and tracking.

Konstantin:
I'm wanting to use BMv2 to test out switches, by predicting how they will handle a packet. The big problem with that idea is that we may not know the hash function that's used by the switch, and so BMv2 may predict that a packet will be sent out through a different port that it will actually be sent out by the switch due to WCMP.

What do you think would be the easiest way to deal with this problem? Could we add a flag to BMv2, maybe call it --multicast_wcmp, where BMv2's behavior would be modified in such a way that instead of choosing one WCMP member via the hash, it would clone the packet for each member. In our test, we could then verify that the packet generated by the hardware switch is one of the packets generated by BMv2.

Antonin:
As we discussed today, it would not be trivial to do this. However, it would be trivial to use a hash function that iterates over all the members in a round-robin fashion. You would then simply need to send enough packets to wrap around and you would get the set of all possible packets. Since hash functions in bmv2 are functors that can hold state, this is very easy to do.

They are 2 open questions though:
- if there are multiple selectors in a given packet path, then doing round-robin for each hash function may not give you the set of all possible packets (but maybe you are only interested in doing since scheme for a single hash). We may be able to find a workaround for this by using some static state in the functor.
- we need to tell bmv2 to use this hash function for a given selector. So the easiest solution (that doesn't involve modifying the P4 program) would be for you to do a search/replace on the compiler-produced JSON before feeding it to bmv2.

Konstantin:
How will round robin interact with WCMP, i.e. if there are 32 members, but the sum of their weights will be 1024, will round robin go through the 1024 members, or the 32? 

What is the name of the round robin hash function? I should be able to simply modify the p4 program. I don't think multiple selectors in a row will be a problem for my use case.

**Comment by antoninbas** [comment]
@konne-google I can add this round-robin hash function today. There is no notion of weight in bmv2's action profiles so unfortunately (or fortunately?) it will iterate through the 1024 members.

Note that currently there is no support for the `weight` attribute in the reference P4Runtime implementation for bmv2 (https://github.com/p4lang/PI/blob/master/proto/frontend/src/action_prof_mgr.cpp#L162). Feel free to open an issue in the PI repo if this is important to you.

**Comment by konne-google** [comment]
Since there is no support for weights in bmv2's P4Runtime implementation, wouldn't that mean that it would iterate through the 32 members (which is what we want), not the 1024 members?

**Comment by antoninbas** [comment]
When the P4Runtime server supports weights, it will call the "add_member" bmv2 API repeatedly so in practice if you have 32 members with a sum of weights of 32, you will have 1024 "distinct" members in bmv2.

I have opened a PR to add the round-robin hash function. They are 2 variants: "round_robin" and "round_robin_consistent". "round_robin_consistent" ensure that packets belong to the same flow yield the same hash result.

**Comment by konne-google** [comment]
I saw that PR, thanks! I think I'll only need "round_robin".

Right now my approach assumes that all the members perform different actions. This allows me to keep sending the same exact packet to BMv2 until I get an output packet that I've already seen. Once that happens I know that I've seen all the members in the group. If we replicate members by weights, that assumption will be violated. 

Could we add a flag to P4Runtime server to ignore the weights, i.e. it would only add one member no matter the weight?

**Comment by antoninbas** [comment]
I'm not a big fan of adding flags for the sake of testing only (like in https://github.com/p4lang/behavioral-model/issues/642). Maybe you can define an upper bound for the sum of weights in a group and iterate that number of time? You will be guaranteed to see all possible outputs.

**Comment by konne-google** [comment]
In my usecase, I think I should be able to rewrite all the weights to 1 before sending to bmv2, which should fix the problem, even without a flag.

Unfortunately, I think that the upper bound would be infeasible from a performance perspective. It's not just that we would have to simulate order of magnitude more packets that hit wcmp, but we'd also have to do order of magnitude more simulations for packets that don't hit wcmp.

**Comment by antoninbas** [comment]
My understanding was that there would be ~10x difference in the number of packets for the wcmp hit case. I am not sure I understand why the wcmp miss case would be impacted? Is it because you don't know in advance when generating the packets if it's going to be hit or miss? Wouldn't you know after sending the first packet if it's hit / miss (and if it's miss you don't need more iterations)?

**Comment by konne-google** [comment]
I'm using your round robin function and it works.  Thanks!
