### ISSUE TITLE
UDP header not properly deparsed after inserting INT headers

### ISSUE THREAD

**Issue by alikashmar** [p4lang/behavioral-model#647]
I'm running into this issue with INT over UDP where the UDP header is not deparsed correctly, or at least that's what appears to be the case. 

Here's what the packet looks like when it enters the switch:
![screen shot 2018-08-27 at 9 01 24 am](https://user-images.githubusercontent.com/9664455/44661292-31e63280-a9d8-11e8-84a3-c2f2609c49b5.png)

and here's what it looks like when it's processed:

![screen shot 2018-08-27 at 9 02 08 am](https://user-images.githubusercontent.com/9664455/44661317-49252000-a9d8-11e8-8e26-c767a78c56a8.png)
The UDP header length appears to be 256 but that is in fact the beginning of the INT header.

Any help on this would be greatly appreciated! I can provide the code if necessary

**Comment by antoninbas** [comment]
Yes you should share the P4 program with us.

**Comment by alikashmar** [comment]
Here you go: [int_router.txt](https://github.com/p4lang/behavioral-model/files/2324288/int_router.txt)

**Comment by alikashmar** [comment]
Here you go: [int_router.txt](https://github.com/p4lang/behavioral-model/files/2324297/int_router.txt)

**Comment by antoninbas** [comment]
Did you see anything strange in the bmv2 console logs? Could you share that as well so that I can see the packet path?
Also is this switch a source node or a transit node?

**Comment by alikashmar** [comment]
@antoninbas I don't see any errors during processing. Here's the log from the switch processing that packet in the pcap: [p4s.lf1.log](https://github.com/p4lang/behavioral-model/files/2324398/p4s.lf1.log)

The switch is a source node.

**Comment by antoninbas** [comment]
The packet is TCP in the log file, but you mentioned an issue with UDP packets? Did you mean to share something else or do you also observe the issue with TCP packets?

**Comment by alikashmar** [comment]
@antoninbas my apologies. Here's the proper log file: [p4s.lf1.log](https://github.com/p4lang/behavioral-model/files/2324435/p4s.lf1.log)

**Comment by jafingerhut** [comment]
@alikashmar According to Wireshark, that IPv4 header has an IHL field value of 6, specifying an IPv4 header length of 6 4-byte words.  Your P4 program only parses IPv4 headers with the base no-options IHL value of 5 4-byte words.  Probably what is happening is that the 4 bytes of IPv4 options are being parsed by your P4 program as the first 4 bytes of the UDP header.

If you send in a packet with IHL=5 and no IPv4 options, you may get better results.

**Comment by alikashmar** [comment]
@jafingerhut you are 100% correct. I checked the test program I was using to send the packet and it was inserting IPv4 options but my program wasn't parsing it. I removed the options header and ran the test again and it was parsed properly. Thank you so much!
