### ISSUE TITLE
Passing header stacks to actions

### ISSUE THREAD

**Issue by maborghe** [p4lang/behavioral-model#649]
Hi everybody,

I'm running the following P4 code:

```
header my_hs_t {
    bit<2> field_1;
}

struct metadata {
    my_hs_t[10] my_hs;
}

...

    action bar(inout my_hs_t[10] stack) {
	stack.push_front(1);
	stack[0].field_1 = 3;
    }

    action foo() {
	bar(meta.my_hs);
	meta.my_hs.push_front(1);	
	meta.my_hs[0].field_1 = 2;
    }
```
Now, after foo() is called it turns out that my_hs only contains the header pushed by bar(). The same happens if bar() is called in the last line of foo() or if bar() is called twice (my_hs only contains one header).
Is it intended to work so (I wouldn't say that, by reading "6.7. Calling convention" in the specs) or is there some problem with the reference? 

Thanks,
Matteo

**Comment by antoninbas** [comment]
I assume that you tried to inline `bar` inside of `foo` and it worked (i.e. you get 2 headers)?
It would be useful to have a full P4 program that can be compiled as well as the generated JSON file. Once I have the JSON I can take a look but it is possible it is an issue with the compiler.

**Comment by maborghe** [comment]
Hi Antonin,
Yes, doing everything as inline in ```foo``` works as expected. 
Here are the P4 and the JSON files:
[hs_test.zip](https://github.com/p4lang/behavioral-model/files/2343623/hs_test.zip)

**Comment by jafingerhut** [comment]
One thing that looks a little suspicious is that my_hs_t is only 2 bits long.  I thought that in several places, p4c and/or behavioral-model code were restricted to headers that were a multiple of 8 bits long?

**Comment by jafingerhut** [comment]
Another thing that might not be as you expect: In P4_16, push_front() does _not_ make the new pushed headers valid automatically for you.  You must do that with a separate operation _after_ the push_front, _before_ you start initializing the contents of those headers, e.g.:
```
    action bar(inout my_hs_t[10] stack) {
	stack.push_front(1);
        stack[0].setValid();
	stack[0].field_1 = 3;
    }

    action foo() {
	bar(meta.my_hs);
	meta.my_hs.push_front(1);
        meta.my_hs[0].setValid();
	meta.my_hs[0].field_1 = 2;
    }
```
This is _different_ than it was in P4_14.  The primary reason for this difference is that P4_16 has header_union, and you can have a header stack consisting of header_union, and in such a case push_front() automatically making the new pushed elements valid would leave open the question "which element of the header_union should be made valid?".

**Comment by jafingerhut** [comment]
Also, there was a bug in p4c for passing header stacks as parameters, that was fixed some time back.  If you are using a version of p4c source code from before 2018-Jan-18, you may still be experiencing that bug: https://github.com/p4lang/p4c/commit/d98328ac6dcd5f6f298ee379180ce078a1ef6493

In general, it is always a good idea when reporting bugs to try out the latest p4c and behavioral-model versions available, if you can.

**Comment by jafingerhut** [comment]
I will stop adding new comments soon, don't worry :-)

I note that your example P4_16 program only parses an Ethernet header, and only emits an Ethernet header.  It never emits your header stack in the output packet, so it isn't clear to me how you come to the conclusion about which headers have been pushed and which have not?

**Comment by jafingerhut** [comment]
Attached is a zip file with your original program, and also a slightly edited version that has changes I've suggested or hinted at above:

+ change the header to be 8 bits long, not 2.  It works without this change, but p4c adds 6 bits of padding after each 2-bit header.

+ move the header stack into the header struct, rather than the metadata struct, so that it can be emitted in the deparser, and add the statement to emit it in the deparser.

+ Add two setValid() calls, one after each push_front() call, before initializing the fields in the pushed header.

I tried compiling that with p4c and running a simple test packet through simple_switch, and it pushed both headers and emitted them as I would expect.
[hs_test.zip](https://github.com/p4lang/behavioral-model/files/2343702/hs_test.zip)

**Comment by antoninbas** [comment]
@jafingerhut makes some good points. His point in https://github.com/p4lang/behavioral-model/issues/649#issuecomment-417954511 in particular explains why you are seeing different behaviors when inlining `bar` manually / non-inlining `bar`.
The compiler is not doing copy-elimination for some reason, so when it inlines `bar` inside `foo`, the code looks like this (you can check the JSON) - in pseudocode:
```
my_hs_t[10] stack_tmp;
stack_tmp.push_front(1);
stack_tmp[0].field_1 = 3;
meta.my_hs = stack_tmp; 
meta.my_hs.push_front(1);
meta.my_hs[0].field_1 = 2;
```
Notice the copy from the temporary stack variable to your metadata variable. Because you do not call `setValid` (as pointed out by @jafingerhut) after `push_front`, bmv2 considers your stack empty and doesn't copy anything (see https://github.com/p4lang/behavioral-model/blob/master/src/bm_sim/core/primitives.cpp#L68).

**Comment by antoninbas** [comment]
I'm closing this issue. The behavior observed is consistent with 1) the copy-in / copy-out semantics of P4 and 2) the (limited) guarantees made by the spec regarding copying invalid header stack elements.

**Comment by maborghe** [comment]
Thanks to both of you for your replies and for your cues.

Not validing the header was definitely my fault and the program posted by @jafingerhut https://github.com/p4lang/behavioral-model/issues/649#issuecomment-417955649 works as expected. Yet, headers pushed after ```bar``` has been called - either by calling it again or by doing it in ```foo``` - don't show up in the header stack.

In hs_test.mod2 in the attachment you can see what I mean; I'm using the latest BMv2 and p4c.
[hs_test.zip](https://github.com/p4lang/behavioral-model/files/2351872/hs_test.zip)

**Comment by jafingerhut** [comment]
So quick response for now, before I have delved through the compiled JSON file, but when I run simple_switch with your JSON file, and a JSON file compiled with the most recent version of p4c, when I send in a packet with this sequence of bytes:
```
	0x0000:  0000 0000 beef 0000 0000 dead 0000 ffff
	0x0010:  ffff 0000 0000 0000 0000 0000
```
the packet that comes out is:
```
	0x0000:  0000 0000 beef 0000 0000 dead 0000 0203
	0x0010:  03ff ffff ff00 0000 0000 0000 0000 0065
	0x0020:  736b 746f 702e 4442 7573 0000 00
```
The 14-byte Ethernet header ends on the first line with `dead 0000`.  You can see the output packet has the 3 bytes inserted `0203 03` just after that, followed by the `ff ffff ff` that was in the Ethernet payload of the input packet.

Do you get different results when running your compiled program with simple_switch?  If so, what are you getting?

**Comment by jafingerhut** [comment]
From looking at the compiled JSON, I agree that it is doing extra 'assign' operations to copy the main header stack into and out of temporary header stacks, but that is a correct implementation of the P4 source code behavior as far as I can tell.  The p4c compiler doesn't do a lot of optimizations yet, so one should not expect to see optimized code in the BMv2 JSON file (yet).

If you are expecting something different, please describe what that is.

**Comment by jafingerhut** [comment]
OK, I do not know exactly when that code you added to simple_switch.cpp is being executed, relative to the ingress control block P4 code in your program, so I have no comment on why it might be different than what you expect.

If the only reason you added that code to simple_switch.cpp was for debugging of what is going on, I would recommend instead adding a "debug table" to your P4 code.  Such a "debug table" is simply a normal P4 table in your P4 program, where the keys are any and all fields you want to see the value of at that point of the P4 program execution where you call apply() on the table.  If you run simple_switch with the `--log-console` or `--log-file` command line option, it will include messages containing the values of all table search key fields whenever they are applied, in hex.  There is no "print" in P4 right now (it might be useful to add such a debug-only print statement for such debugging purposes), but until then, such a 'debug table' is the next best thing.

**Comment by jafingerhut** [comment]
In particular, perhaps a useful debug table for your program would be as in the attached modified version of your hs_test.mod3.p4 program (same as your hs_test.mod2.p4, with the new debug_table_1 and an apply call for it).  Here is the output from simple_switch with the `--log-console` option enabled, when it reaches the new debug_table_1.apply() call:
```
[15:11:34.579] [bmv2] [T] [thread 7003] [0.0] [cxt 0] Applying table 'MyIngress.debug_table_1'
[15:11:34.579] [bmv2] [D] [thread 7003] [0.0] [cxt 0] Looking up key:
* hdr.my_hs[0].$valid$: 01
* hdr.my_hs[0].field_1: 02
* hdr.my_hs[1].$valid$: 01
* hdr.my_hs[1].field_1: 03
* hdr.my_hs[2].$valid$: 01
* hdr.my_hs[2].field_1: 03
* hdr.my_hs[3].$valid$: 00
* hdr.my_hs[3].field_1: 00
* hdr.my_hs[4].$valid$: 00
* hdr.my_hs[4].field_1: 00
```
[hs_test.zip](https://github.com/p4lang/behavioral-model/files/2354732/hs_test.zip)
