### ISSUE TITLE
How does the dp-grpc-server inject packet into the pipeline?

### ISSUE THREAD

**Issue by dingrui37** [p4lang/behavioral-model#653]
Hi @antoninbas , sorry for trouble you again. I want to know how `dp_grpc_server`  inject a packet into the pipeline? For the packet-out using the P4runtime server, it will call `_pi_packetout_send` (pi_imp.cpp)  at last, I think it will push packet to the pipeline. I don't understand the implementation principle of `DataplaneInterfaceServiceImpl`. who will set `pkt_handler`?  The inject packet will come from which port in the view of the switch? Could you give me some guidance?

**Comment by antoninbas** [comment]
The DP gRPC service is a way to inject dataplane traffic in the switch model without requiring interfaces (whether virtual or physical). This is convenient for writing unit tests for example. It is *completely orthogonal* to the P4Runtime gRPC service and the PacketIn / PacketOut P4Runtime messages. PacketIn / PacketIO is typically used to exchange control packets with the controller (ARP, BGP, etc) and to punt specific packets to the controller (e.g. if a specific ACL rule is hit in the P4 pipeline). The DP gRPC service is not meant to talk to the control-plane at all and is not something that is used in production. When injecting a packet though the DP service, you specify the port on which the switch should receive that packet (take a look at the Protobuf definition for the service) and when receiving a packet through the DP service, you know the egress port set by the switching logic.

Most of the simple_switch_grpc unit tests use the DP service to send & receive dataplane packets, so you can refer to them. When running simple_switch_grpc, you do *not* need to use this service if you prefer to use veth interfaces (for example).

**Comment by dingrui37** [comment]
Thanks @antoninbas
