### ISSUE TITLE
Additional simple_switch docs desired?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/behavioral-model#654]
Wondering if adding to this file: https://github.com/p4lang/behavioral-model/blob/master/docs/simple_switch.md

some more docs about other P4_16 v1model metadata fields, such as found at the link below, would be considered useful additions:

https://github.com/jafingerhut/p4-guide/tree/master/v1model-special-ops#standard-metadata-for-p4_16--v1model-architecture-in-p4c-and-behavioral-model

**Comment by antoninbas** [comment]
@jafingerhut I think it's a good idea. Feel free to open a PR to add more information to simple_switch.md (also maybe we should have a link to simple_switch.md in the README somewhere).

**Comment by jafingerhut** [comment]
PR created here: https://github.com/p4lang/behavioral-model/pull/655

**Comment by jafingerhut** [comment]
Closing this issue since #655 was merged.
