### ISSUE TITLE
Oneshot Action Selector support in BMv2

### ISSUE THREAD

**Issue by konne-google** [p4lang/behavioral-model#658]
Can we extend BMv2 with Oneshot Action Selector programming? We've started using it internally, and it would be great if there was also support in BMv2.

**Comment by jafingerhut** [comment]
Just for my own education, the primary thing missing in BMv2 is the ability to interpret the new P4Runtime messages being defined for Oneshot Action Selectors?

I would guess so, since as presented the P4 syntax and data plane behavior is the same as for the existing action selectors.

**Comment by antoninbas** [comment]
I opened an issue in p4lang/PI (https://github.com/p4lang/PI/issues/405) since everything will be contained in that repo. I'll try to get it to it soon.
