### ISSUE TITLE
Accessing Switch Internals

### ISSUE THREAD

**Issue by Pwniee** [p4lang/behavioral-model#670]
Hello, I am currently benchmarking the BMv2 to discover how fast I can obtain the information stored in its registers by my P4 program. I would like to know if measuring the thrift server response time by timing the simple_switch_CLI such as 

`time simple_switch_CLI <<< "register_read test 0"`

would give me an accurate estimation of the time a controller would take to get this information from a real P4 switch through the CPU-Link. Am I right to assume that the thrift server is similar to an OpenFlow agent running on p4 switches? is there a more legitimate manner of accessing a p4 switch internals?

Thank you all very much!

**Comment by antoninbas** [comment]
No, this is not at all representative of the performance of control-plane operations on a hardware switch. A hardware switch would probably have to do a DMA read to query the value, and performance can vary significantly across implementations. For an accurate estimate, you will need to get your hands on an actual P4 switch.
If you are new to P4, I suggest you take a look at the P4Runtime specification on p4.org (https://p4.org/specs/). P4Runtime is meant to be the OpenFlow "replacement" for P4-programmable devices.
If you are reading a single cell from a single register (e.g. with `register_read test 0`), the time to completion is likely to be dominated by the RPC overhead, so maybe that number wouldn't change much between bmv2 and a hardware target. However, things may be very different for wildcard reads on an entire register or if you batch register reads together (which P4Runtime lets you do).

**Comment by Pwniee** [comment]
Hi Antonin, thank you for taking the time.
My P4Runtime build fails with 
`error: ‘class bm_runtime::standard::StandardClient’ has no member named ‘bm_mt_reset_default_entry’` 
Can you please point me to a VM you would recommend for running P4Runtime and bmv2?

Thanks again.

**Comment by antoninbas** [comment]
You should follow instructions in this README: https://github.com/p4lang/behavioral-model/tree/master/targets/simple_switch_grpc
You can also use the tutorials VM, although the software in it is a bit out-dated: https://github.com/p4lang/tutorials

**Comment by Pwniee** [comment]
I installed the tutorials VM and managed to configure the P4Runtime for the bmv2, but I cannot find a register_read or equivalent on the PI_CLI, and I tried counter_read on my test register but got Invalid counter name error. Can you tell me what I am doing wrong?

Thanks a lot, Antonin!

**Comment by antoninbas** [comment]
P4Runtime supports reading from registers but it has not been implemented yet for bmv2. The PI CLI pre-dates P4Runtime and is a separate project. It is in maintenance mode now and doesn't support reading from registers. So if you are specifically interested in reading stateful registers for a P4 program running in bmv2, you have no choice but to use the Thrift RPC service. My assumption was that your original question was more general than that and that you were using registers as an example, but looks like I may have been wrong.

**Comment by Pwniee** [comment]
No problems, Antonin, at least I got my bearings on many concepts that were fuzzy to me, all thanks to you. The Thrift server will serve as an approximation for now.

Thank you very much for your patience! We can close this now.
