### ISSUE TITLE
Question:How does the gRPC server receive a packet from data-plane?

### ISSUE THREAD

**Issue by dingrui37** [p4lang/behavioral-model#674]
Hi @antoninbas I want to know how does the gRPC server receive a packet from data-plane? I think there will be a thread listening on the CPU_PORT(veth), when receiving a packet, it will parse and filter first, then send the packet to gRPC server, is it right? Where is the source code?

**Comment by antoninbas** [comment]
If you are using simple_switch_grpc, a custom transmit function is provided to intercept the CPU packets and send them to the server code: https://github.com/p4lang/behavioral-model/blob/master/targets/simple_switch_grpc/switch_runner.cpp#L326
The server code then extracts the metadata fields before sending everything to the client on the gRPC stream.
