### ISSUE TITLE
Packet goes to egress pipeline after being marked to drop in ingress pipeline

### ISSUE THREAD

**Issue by alikashmar** [p4lang/behavioral-model#677]
I've written a P4 program that checks if a table has a given entry, and if it does, it drops the packet. The packet for some reason still goes through, even though I see primitive mark_to_drop being called in the log. Can someone please help me figure this out?

I've attached the log from the source switch.
[p4s.lf1.log](https://github.com/p4lang/behavioral-model/files/2526771/p4s.lf1.log)

**Comment by jafingerhut** [comment]
After your code calls mark_to_drop, it later assigns a value to egress_spec
of 4 before the end of ingress.  The later assignment overwrites the drop.
With P4_16 + v1model, and with P4_14, mark_to_drop() is implemented by
writing a special 'drop' value to egress_spec that is not a valid port
number.

Andy

**Comment by jafingerhut** [comment]
See the documentation for egress_spec and drop, and what happens to a packet at the end of ingress processing, here: https://github.com/p4lang/behavioral-model/blob/master/docs/simple_switch.md

**Comment by alikashmar** [comment]
Thank you, that explains it. I did read that document but I didn't know mark_to_drop was setting the egress_spec value.

**Comment by rst0git** [comment]
The following is the output of `simple_switch_grpc --help` describing the `--drop-port` option:

```
  --drop-port arg                 Choose a numerical value for the drop port 
                                  (default is 511). When using standard 
                                  v1model.p4, this value must fit within 9 
                                  bits. You will need to use this command-line 
                                  option when you wish to use port 511 as a 
                                  valid dataplane port or as the CPU port.
```
