### ISSUE TITLE
packet scheduling algorithm

### ISSUE THREAD

**Issue by longlongman** [p4lang/behavioral-model#694]
Hi,
In this mail http://lists.p4.org/pipermail/p4-dev_lists.p4.org/2016-May/002045.html, I noticed that the only packet scheduling algorithm in simple_switch was strict priority scheduling. I wonder whether there is any other algorithm available right now? And if I want to implement my own scheduling algorithm e.g. deficit round robin in simple_switch, where should I start from?

**Comment by antoninbas** [comment]
Hi,
The strict priority scheduling algorithm is actually not the default and needs to be selected at compile time. The process of using your own scheduling algorithm involves some manual work. You can look at https://github.com/p4lang/behavioral-model/blob/master/include/bm/bm_sim/queueing.h for the current implementation. You can then either modify this file directly or define your own implementation in simple_switch.cpp. Then you need some minor changes to simple_switch.cpp to use your own algorithm (look for calls to push and pop).

Note that simple_switch is an emulator and the throughput / accuracy you will be able to achieve is limited. The P4 TM SubWG (sub working group of the P4 Architecture WG) is working on integrating bmv2 with ns3 to use bmv2 as a cycle-accurate simulator (https://github.com/PIFO-TM/ns3-bmv2), which will be more appropriate to evaluate scheduling algorithms. You can reach out to them on the Github repo if you have questions or if you're interested in contributing.
