### ISSUE TITLE
I believe there are two mistakes in queueing.h.

### ISSUE THREAD

**Issue by longlongman** [p4lang/behavioral-model#700]
When I try to modify the file https://github.com/p4lang/behavioral-model/blob/master/include/bm/bm_sim/queueing.h, I find there are might be two mistakes in it. 
1) In https://github.com/p4lang/behavioral-model/blob/master/include/bm/bm_sim/queueing.h#L521, there should have a `w_info.size--;`, isn't it?
2) In https://github.com/p4lang/behavioral-model/blob/master/include/bm/bm_sim/queueing.h#L551, the `return q_info.size;` should be replaced by `return q_info_pri.size;`.
I believe these two are mistakes, but if not pls let me know. Thank you.

**Comment by antoninbas** [comment]
I think you are correct in both cases. If you or your organization is a p4.org member, please let me know and feel free to submit a patch. If you are not a member, I will have to fix these myself.

**Comment by longlongman** [comment]
I am not a member.
