### ISSUE TITLE
What should instance_type be for a packet resubmitted on ingress, then sent to egress?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/behavioral-model#706]
I have a test program I am trying on BMv2 simple_switch, where the packet is recirculated on ingress, so after that it starts ingress with instance_type=6 (PKT_INSTANCE_TYPE_RESUBMIT) for a resubmitted packet.  That is what I expected, so far.

On that next pass in ingress, the packet is sent to egress (i.e. no resubmit operation this time, no multicast, no clone).

If the packet had not been resubmitted, it would start egress processing with instance_type=0 (PKT_INSTANCE_TYPE_NORMAL).

But since it started ingress with instance_type=6, and didn't go through any special cases, the instance_type=6 was preserved through the packet buffer until the packet started egress processing.

I would have expected it to be 0 (NORMAL) at start of egress.

What would you expect?

**Comment by antoninbas** [comment]
I tend to agree that the instance type should be NORMAL for the resubmitted packet once it reaches ingress, although I guess at this point it is pretty much up to us :P. It should be a trivial fix. What about recirculate? I guess the same logic should apply.
