### ISSUE TITLE
Thoughts on transitioning to Python 3?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/behavioral-model#709]
I get this ominous-looking message when running `pip install ...` commands based on Python 2.7 on my Ubuntu Linux 16.04 machine now:

```
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020.
Please upgrade your Python as Python 2.7 won't be maintained after that date.
A future version of pip will drop support for Python 2.7.
```

I am sure this issue is shared by many other projects, and I suspect a lot of them will simply continue using Python 2.7 after it is no longer maintained by whoever is doing it now (and perhaps maintenance might be taken up by some other organization), but the writing seems to be on the wall.

**Comment by cc10512** [comment]
It is actually quite easy to transition if you run `2to3` followed by a bit of manual cleanup.

**Comment by antoninbas** [comment]
I would be happy to accept a contribution updating all of the Python scripts to support both Python 2.7 and Python 3+
Unfortunately we don't really test the Python scripts comprehensively in the CI system like we do the C++ code, so a lot of manual testing may be involved

**Comment by jafingerhut** [comment]
If anyone works on transitioning Python2 to Python3 for programs that use the Scapy library for creating and parsing packets, I would recommend avoiding the "kamene" fork of Scapy, and instead using the "main branch/original" version of Scapy, which as of 2018 has finally started supporting Python3 officially.

Reason: I expect that there are subtle differences between kamene and Scapy since they forked, and continuing to use the "main branch/original" Scapy will likely lead to fewer bugs.

The only tricky part here is that some packaged versions of kamene have names that include "scapy" in them, so it can be a bit confusing to avoid kamene if you are not aware of it.  Gory details are documented here, if you are curious, and/or making such Python2->Python3 translations: https://github.com/jafingerhut/p4-guide/blob/master/README-scapy.md

**Comment by huaixiaohuai** [comment]
> 如果运行`2to3`后再进行一些手动清理，实际上过渡非常容易。

I tried. It's very difficult!
