### ISSUE TITLE
--load-modules option for simple_switch_grpc

### ISSUE THREAD

**Issue by awstuff** [p4lang/behavioral-model#719]
Are there any plans to add the --load-modules option to simple_switch_grpc as well? At the moment, it is only available for simple_switch.
Judging by the [original pull request](https://github.com/p4lang/behavioral-model/pull/605), the amount of code that would have to be changed looks relatively small, and the option is really useful.

**Comment by antoninbas** [comment]
I pushed a patch for this. In the future, providing the organization (company or university) you belong to us a p4.org member (https://p4.org/members/), don't hesitate to submit a patch yourself for new features you care about.

**Comment by awstuff** [comment]
Thank you. Neither I nor my organization is a p4.org member.
