### ISSUE TITLE
error: reference to ‘shared_ptr’ is ambiguous

### ISSUE THREAD

**Issue by IMxbo** [p4lang/behavioral-model#723]
I got an error when compiler simple_switch_grpc, Could you tell me how to fix it?  my thrift version is 0.12.0
#508 

> vagrant@p4:~/P4/behavioral-model/targets/simple_switch_grpc$ make -j4
/usr/bin/protoc /home/vagrant/P4/behavioral-model/targets/simple_switch_grpc/p4/bm/dataplane_interface.proto --cpp_out ./cpp_out -I/home/vagrant/P4/behavioral-model/targets/simple_switch_grpc
/usr/bin/protoc /home/vagrant/P4/behavioral-model/targets/simple_switch_grpc/p4/bm/dataplane_interface.proto --grpc_out ./grpc_out --plugin=protoc-gen-grpc=/usr/local/bin/grpc_cpp_plugin -I/home/vagrant/P4/behavioral-model/targets/simple_switch_grpc
/usr/bin/protoc /home/vagrant/P4/behavioral-model/targets/simple_switch_grpc/p4/bm/dataplane_interface.proto --python_out ./py_out -I/home/vagrant/P4/behavioral-model/targets/simple_switch_grpc --grpc_out ./py_out --plugin=protoc-gen-grpc=/usr/local/bin/grpc_python_plugin
make  all-recursive
make[1]: Entering directory '/home/vagrant/P4/behavioral-model/targets/simple_switch_grpc'
Making all in .
make[2]: Entering directory '/home/vagrant/P4/behavioral-model/targets/simple_switch_grpc'
depbase=`echo switch_runner.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I.  -I./../../include -I./../simple_switch -I./../../PI -isystem./../../third_party/spdlog  -DWITH_THRIFT -Icpp_out -Igrpc_out -I./cpp_out -I./grpc_out  -Wall -Wextra -pthread -g -O2 -MT switch_runner.lo -MD -MP -MF $depbase.Tpo -c -o switch_runner.lo switch_runner.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
make[2]: *** No rule to make target '../../PI/libbmpi.la', needed by 'libsimple_switch_grpc.la'.  Stop.
make[2]: *** Waiting for unfinished jobs....
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I./../../include -I./../simple_switch -I./../../PI -isystem./../../third_party/spdlog -DWITH_THRIFT -Icpp_out -Igrpc_out -I./cpp_out -I./grpc_out -Wall -Wextra -pthread -g -O2 -MT switch_runner.lo -MD -MP -MF .deps/switch_runner.Tpo -c switch_runner.cpp  -fPIC -DPIC -o .libs/switch_runner.o
In file included from switch_runner.cpp:55:0:
./../../include/bm/bm_runtime/bm_runtime.h:29:17: error: reference to ‘shared_ptr’ is ambiguous
                 shared_ptr<Iface> handler) {
                 ^~~~~~~~~~
In file included from /usr/include/boost/throw_exception.hpp:42:0,
                 from /usr/include/boost/thread/pthread/mutex.hpp:12,
                 from /usr/include/boost/thread/mutex.hpp:16,
                 from /usr/include/boost/thread/pthread/shared_mutex.hpp:13,
                 from /usr/include/boost/thread/shared_mutex.hpp:22,
                 from ./../../include/bm/bm_sim/switch.h:70,
                 from ./../simple_switch/simple_switch.h:27,
                 from switch_runner.cpp:45:
/usr/include/boost/exception/exception.hpp:19:44: note: candidates are: template<class T> class boost::shared_ptr
 namespace boost { template <class T> class shared_ptr; };
                                            ^~~~~~~~~~
In file included from /usr/include/c++/7/bits/shared_ptr.h:52:0,
                 from /usr/include/c++/7/memory:81,
                 from ./../../third_party/spdlog/bm/spdlog/common.h:30,
                 from ./../../third_party/spdlog/bm/spdlog/spdlog.h:32,
                 from ./../../include/bm/bm_sim/logger.h:36,
                 from switch_runner.cpp:22:
/usr/include/c++/7/bits/shared_ptr_base.h:347:11: note:                 template<class _Tp> class std::shared_ptr
     class shared_ptr;
           ^~~~~~~~~~
In file included from switch_runner.cpp:55:0:
./../../include/bm/bm_runtime/bm_runtime.h:29:17: error: ‘shared_ptr’ has not been declared
                 shared_ptr<Iface> handler) {
                 ^~~~~~~~~~
./../../include/bm/bm_runtime/bm_runtime.h:29:27: error: expected ‘,’ or ‘...’ before ‘<’ token
                 shared_ptr<Iface> handler) {
                           ^
./../../include/bm/bm_runtime/bm_runtime.h: In function ‘int bm_runtime::add_service(const string&, int)’:
./../../include/bm/bm_runtime/bm_runtime.h:31:5: error: reference to ‘shared_ptr’ is ambiguous
     shared_ptr<TProcessor>(new Processor(handler)));
     ^~~~~~~~~~
In file included from /usr/include/boost/throw_exception.hpp:42:0,
                 from /usr/include/boost/thread/pthread/mutex.hpp:12,
                 from /usr/include/boost/thread/mutex.hpp:16,
                 from /usr/include/boost/thread/pthread/shared_mutex.hpp:13,
                 from /usr/include/boost/thread/shared_mutex.hpp:22,
                 from ./../../include/bm/bm_sim/switch.h:70,
                 from ./../simple_switch/simple_switch.h:27,
                 from switch_runner.cpp:45:
/usr/include/boost/exception/exception.hpp:19:44: note: candidates are: template<class T> class boost::shared_ptr
 namespace boost { template <class T> class shared_ptr; };
                                            ^~~~~~~~~~
In file included from /usr/include/c++/7/bits/shared_ptr.h:52:0,
                 from /usr/include/c++/7/memory:81,
                 from ./../../third_party/spdlog/bm/spdlog/common.h:30,
                 from ./../../third_party/spdlog/bm/spdlog/spdlog.h:32,
                 from ./../../include/bm/bm_sim/logger.h:36,
                 from switch_runner.cpp:22:
/usr/include/c++/7/bits/shared_ptr_base.h:347:11: note:                 template<class _Tp> class std::shared_ptr
     class shared_ptr;
           ^~~~~~~~~~
In file included from switch_runner.cpp:55:0:
./../../include/bm/bm_runtime/bm_runtime.h:31:26: error: expected primary-expression before ‘>’ token
     shared_ptr<TProcessor>(new Processor(handler)));
                          ^
./../../include/bm/bm_runtime/bm_runtime.h:31:42: error: ‘handler’ was not declared in this scope
     shared_ptr<TProcessor>(new Processor(handler)));
                                          ^~~~~~~
./../../include/bm/bm_runtime/bm_runtime.h:31:42: note: suggested alternative: ‘rand_r’
     shared_ptr<TProcessor>(new Processor(handler)));
                                          ^~~~~~~
                                          rand_r
switch_runner.cpp: At global scope:
switch_runner.cpp:58:5: error: reference to ‘shared_ptr’ is ambiguous
     shared_ptr<SimpleSwitchIf> get_handler(SimpleSwitch *sw);
     ^~~~~~~~~~
In file included from /usr/include/boost/throw_exception.hpp:42:0,
                 from /usr/include/boost/thread/pthread/mutex.hpp:12,
                 from /usr/include/boost/thread/mutex.hpp:16,
                 from /usr/include/boost/thread/pthread/shared_mutex.hpp:13,
                 from /usr/include/boost/thread/shared_mutex.hpp:22,
                 from ./../../include/bm/bm_sim/switch.h:70,
                 from ./../simple_switch/simple_switch.h:27,
                 from switch_runner.cpp:45:
/usr/include/boost/exception/exception.hpp:19:44: note: candidates are: template<class T> class boost::shared_ptr
 namespace boost { template <class T> class shared_ptr; };
                                            ^~~~~~~~~~
In file included from /usr/include/c++/7/bits/shared_ptr.h:52:0,
                 from /usr/include/c++/7/memory:81,
                 from ./../../third_party/spdlog/bm/spdlog/common.h:30,
                 from ./../../third_party/spdlog/bm/spdlog/spdlog.h:32,
                 from ./../../include/bm/bm_sim/logger.h:36,
                 from switch_runner.cpp:22:
/usr/include/c++/7/bits/shared_ptr_base.h:347:11: note:                 template<class _Tp> class std::shared_ptr
     class shared_ptr;
           ^~~~~~~~~~
switch_runner.cpp: In member function ‘int sswitch_grpc::SimpleSwitchGrpcRunner::init_and_start(const bm::OptionsParser&)’:
switch_runner.cpp:362:45: error: ‘get_handler’ is not a member of ‘sswitch_runtime’
           "simple_switch", sswitch_runtime::get_handler(simple_switch.get()));
                                             ^~~~~~~~~~~
Makefile:791: recipe for target 'switch_runner.lo' failed
make[2]: *** [switch_runner.lo] Error 1
make[2]: Leaving directory '/home/vagrant/P4/behavioral-model/targets/simple_switch_grpc'
Makefile:885: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/vagrant/P4/behavioral-model/targets/simple_switch_grpc'
Makefile:544: recipe for target 'all' failed
make: *** [all] Error 2
###

**Comment by antoninbas** [comment]
Which version of bmv2 are you using? I submitted a patch 2 weeks ago that should have fixed this issue: https://github.com/p4lang/behavioral-model/pull/718

**Comment by IMxbo** [comment]
> Which version of bmv2 are you using? I submitted a patch 2 weeks ago that should have fixed this issue: #718
@antoninbas  I used the tutorials/vm/user-bootstrap.sh to build the environment in a new 18.04 Ubuntu system, but failed. it's compatible with 18.04?

**Comment by antoninbas** [comment]
The tutorials use an old version of bmv2. You can either use a more recent bmv2 version or roll-back your Thrift version to 0.9.2.
Basically, either you use the same versions as the tutorials for everything (that includes bmv2, PI, p4c and all the dependencies such as Thrift) or you are on your own. If you just upgrade bmv2, other things may break.
You may be able to use one of @jafingerhut's installation scripts, which I think have been tested on Ubuntu 18.04 and use more recent versions of the dependencies (such as Thrift 0.11.0): https://github.com/jafingerhut/p4-guide/tree/master/bin

**Comment by IMxbo** [comment]
> The tutorials use an old version of bmv2. You can either use a more recent bmv2 version or roll-back your Thrift version to 0.9.2.
> Basically, either you use the same versions as the tutorials for everything (that includes bmv2, PI, p4c and all the dependencies such as Thrift) or you are on your own. If you just upgrade bmv2, other things may break.
> You may be able to use one of @jafingerhut's installation scripts, which I think have been tested on Ubuntu 18.04 and use more recent versions of the dependencies (such as Thrift 0.11.0): https://github.com/jafingerhut/p4-guide/tree/master/bin

@antoninbas  ok I will try it, thank you !
