### ISSUE TITLE
Assigning header union stacks

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/behavioral-model#725]
I have the following JSON fragment:
```
          "parser_ops" : [
            {
              "op" : "primitive",
              "parameters" : [
                {
                  "parameters" : [
                    {
                      "type" : "header_union_stack",
                      "value" : "tcp_options_vec"
                    },
                    {
                      "type" : "header_union_stack",
                      "value" : "vec_0"
                    }
                  ],
                  "op" : "assign_union_stack"
                }
              ]
            }
         ]
```

BMv2 complains when parsing this JSON file:
```
Parameter type 'header_union_stack' not supported
bad json:
{
   "type" : "header_union_stack",
   "value" : "tcp_options_vec"
}
```

Is the JSON incorrect?
I am attaching the full file.

[issue561-bmv2.txt](https://github.com/p4lang/behavioral-model/files/2921587/issue561-bmv2.txt)

**Comment by antoninbas** [comment]
I pushed a fix (https://github.com/p4lang/behavioral-model/pull/726). I think it was just an oversight in the JSON parsing code since the rest of the bmv2 code supports unions and union stacks fine. Your JSON file is loaded correctly now, hopefully your STF test will pass as well :)

**Comment by mbudiu-vmw** [comment]
I have pulled the bmv2 again, but now I can't run older programs.
```
Running /home/mbudiu/git/behavioral-model/targets/simple_switch/simple_switch --log-file switch.log --log-flush --use-files 0 --thrift-port 10053 --device-id 963 ../bmv2/testdata/p4_16_samples/action_profile-bmv2.json
Error while parsing command line arguments
Usage: SWITCH_NAME [options] <path to JSON config file>
Options:
...
```

The help message shown does not list the --thrift-port command-line argument. This should break the p4c testing scripts.

**Comment by mbudiu-vmw** [comment]
Maybe it's because configure forgot my previous configuration. Let me see if that's why.

**Comment by antoninbas** [comment]
I did some changes to configure recently, so it's possible. Let me know if it doesn't fix the issue and I'll look into it.

**Comment by mbudiu-vmw** [comment]
It probably was configure; once I passes the --with flags parsing command-line options worked again.
The PR seems to fix this program. Do you plan to merge it? I want to submit a PR against p4c which uses union stack assignment.

**Comment by antoninbas** [comment]
I'll merge it right away. Thanks for testing it.

**Comment by mbudiu-vmw** [comment]
There's no STF test for the stack assignment yet, but my PR will test quite a few combinations of union stack operations using stf files. Will work on adding more. Thank you.
