### ISSUE TITLE
packet.advance

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/behavioral-model#727]
The p4-16 spec has a method on packet_in called advance which takes a 32-bit number. If the value is compile-time constant it's easy to implement this, but if it is variable we have to implement a parser loop. Should we consider adding it as a primitive to bmv2 instead?

**Comment by antoninbas** [comment]
I can improve the "shift" parser primitive operation to support arbitrary expressions.

**Comment by mbudiu-vmw** [comment]
What is the constraint today on the argument of shift?

**Comment by mbudiu-vmw** [comment]
It looks like it must be a constant.

**Comment by antoninbas** [comment]
Correct. It will be easy to support an expression. I'll see if I can alias it to "advance" as well, to make the bmv2 logs easier to decipher.

**Comment by mbudiu-vmw** [comment]
The answer should probably depend on whether this is something that hardware will support easily.
If not, maybe it has to be done by the compiler in software.

**Comment by mbudiu-vmw** [comment]
But it does look like the easiest way to implement it is allowing expressions in bmv2. Thank you.

**Comment by antoninbas** [comment]
I opened a PR for this. In your case, you are more likely to use the "field" parameter type I think (or an "expression" parameter which just loads a field value).
For example, `pkt.advance(pkt.lookahead<bit<32>>() + 32w16)` will need to be transformed to:
```
bit<32> tmp;
tmp = pkt.lookahead<bit<32>>();  // "set" operation from a lookahead value
tmp = tmp + 32w16;  // "set" operation from an expression
pkt.advance(tmp);  // "advance" operation from field
```
or
```
bit<32> tmp;
tmp = pkt.lookahead<bit<32>>();  // "set" operation from a lookahead value
pkt.advance(tmp + 32w16);  // "advance" operation from expression
```
Creating a temporary field is only required when the input expression includes a lookahead operation, because the bmv2 expression evaluation engine doesn't support lookahead. This is the same as for variable-length extraction BTW.

**Comment by mbudiu-vmw** [comment]
Yes, the compiler can do these rewrites easily.

**Comment by mbudiu-vmw** [comment]
I have created a sample program that uses advance, but it does not seem to have any effect on the packet. I am attaching the P4 and JSON.

[issue1755-bmv2.txt](https://github.com/p4lang/behavioral-model/files/2942643/issue1755-bmv2.txt)

[issue1755-bmv2.json.txt](https://github.com/p4lang/behavioral-model/files/2942646/issue1755-bmv2.json.txt)

**Comment by antoninbas** [comment]
It works for me:
```
antonin@ubuntu:~/Documents/p4lang/bmv2$ sudo ./targets/simple_switch/simple_switch --log-console issue1755-bmv2.json.txt -i 0@veth0 -i 2@veth2 --dump-packet-data 64
Calling target program-options parser
Adding interface veth0 as port 0
[10:13:45.212] [bmv2] [D] [thread 24432] Adding interface veth0 as port 0
Adding interface veth2 as port 2
[10:13:45.246] [bmv2] [D] [thread 24432] Adding interface veth2 as port 2
[10:13:45.294] [bmv2] [I] [thread 24432] Starting Thrift server on port 9090
[10:13:45.294] [bmv2] [I] [thread 24432] Thrift server was started
[10:13:49.651] [bmv2] [I] [thread 24450] Received packet of length 34 on port 0: ffffffffffff0000000000000800450000140001000040007ce77f0000017f000001
[10:13:49.651] [bmv2] [D] [thread 24451] [0.0] [cxt 0] Processing packet received on port 0
[10:13:49.651] [bmv2] [D] [thread 24451] [0.0] [cxt 0] Parser 'parser': start
[10:13:49.651] [bmv2] [D] [thread 24451] [0.0] [cxt 0] Parser 'parser' entering state 'start'
[10:13:49.651] [bmv2] [D] [thread 24451] [0.0] [cxt 0] Advancing by 8 bytes
[10:13:49.651] [bmv2] [D] [thread 24451] [0.0] [cxt 0] Parser state 'start' has no switch, going to default next state
[10:13:49.651] [bmv2] [T] [thread 24451] [0.0] [cxt 0] Bytes parsed: 8
[10:13:49.651] [bmv2] [D] [thread 24451] [0.0] [cxt 0] Parser 'parser': end
[10:13:49.651] [bmv2] [D] [thread 24451] [0.0] [cxt 0] Pipeline 'ingress': start
[10:13:49.651] [bmv2] [D] [thread 24451] [0.0] [cxt 0] Pipeline 'ingress': end
[10:13:49.651] [bmv2] [D] [thread 24451] [0.0] [cxt 0] Egress port is 0
[10:13:49.651] [bmv2] [D] [thread 24452] [0.0] [cxt 0] Pipeline 'egress': start
[10:13:49.651] [bmv2] [D] [thread 24452] [0.0] [cxt 0] Pipeline 'egress': end
[10:13:49.651] [bmv2] [D] [thread 24452] [0.0] [cxt 0] Deparser 'deparser': start
[10:13:49.651] [bmv2] [D] [thread 24452] [0.0] [cxt 0] Deparser 'deparser': end
[10:13:49.651] [bmv2] [D] [thread 24456] [0.0] [cxt 0] Transmitting packet of size 26 out of port 0
[10:13:49.651] [bmv2] [I] [thread 24456] Sending packet of length 26 on port 0: 000000000800450000140001000040007ce77f0000017f000001
```
I see the correct log message and the packet "loses" the first 8 bytes.

**Comment by mbudiu-vmw** [comment]
the count is in bytes, not in bits?
I sent a short packet and it didn't lose anything.
Maybe because it didn't have 8 bytes...

**Comment by jafingerhut** [comment]
The P4_16 spec says that in the source code, the argument to advance() is in units of bits.

While it mentions that some implementations may restrict headers to be multiple of 8 bits (and BMv2 is an implementation with this restriction today), the spec I think today does not mention that implementations may restrict arguments to advance to be a multiple of 8 bits.  Perhaps it should explicitly allow implementations to make that restriction, and then BMv2 could be one implementation with that restriction?

**Comment by antoninbas** [comment]
The count is in bytes. Bmv2 requires all headers to start and end at a byte boundary, and this restriction transferred to advance.
I will change it to bits though, since it is bits in the P4 spec and there is no way for the compiler to enforce that the expression evaluates to a multiple of 8.
BTW, what do you think of extending error in v1model to include a `ParserInvalidAlignment` error.

**Comment by jafingerhut** [comment]
Hmmm.  It seems perhaps a similar issue exists for 2-argument extract into a header with a varbit?

**Comment by jafingerhut** [comment]
So is a perhaps reasonable way to explain the restriction that some implementations (perhaps including BMv2) are allowed to impose, as follows?

P4_16 implementation are allowed to impose the following restriction:

Every call to extract (both 1-argument and 2-argument variants), advance, lookahead, and emit must occur when the packet "cursor" is currently at a multiple of 8 bits from the start of the packet, and must end with the packet "cursor" at a multiple of 8 bits from the start of the packet.

?

**Comment by antoninbas** [comment]
@jafingerhut I think the restriction can simply be "the cursor must always be a byte boundary", if one assumes that for an extract operation, the cursor is only incremented once, at the end (which is consistent with the extract pseudocode in the spec).

@mbudiu-vmw I opened a PR to switch the amount to bits: https://github.com/p4lang/behavioral-model/pull/731. It would be great if you could reject programs in the backend when the advance amount is a constant expression and not a multiple of 8. Having a new parser error for v1model would also be pretty neat IMO.

**Comment by jafingerhut** [comment]
@antoninbas So I have a local change I am working on to added error.ParserInvalidArgument to the core.p4 include file for p4c, and I am writing an STF test case for it.  Right now that STF test case causes BMv2 simple_switch to crash with an assert if extract's second argument is not a multiple of 8.

I am guessing that you would want error.ParserInvalidArgument to be added to p4c's core.p4 first, and only then would you be able to change simple_switch/simple_switch_grpc to assign this new parser error value when advance or extract have a number of bits not a multiple of 8?

**Comment by antoninbas** [comment]
Yes, you will need to have 2 PRs for p4c.
Feel free to update the bmv2 parser.cpp code to use the new error as well. It should be very straightforward as the code already uses other error members (e.g. PacketTooShort).

**Comment by jafingerhut** [comment]
Created this PR: https://github.com/p4lang/behavioral-model/pull/757
