### ISSUE TITLE
Cannot install simple_switch_grpc.

### ISSUE THREAD

**Issue by Pfeifenjoy** [p4lang/behavioral-model#742]
I want to install the simple_switch_grpc,
however when I compile it, I always get the following error:

```
/usr/bin/ld: ./.libs/libsimple_switch_grpc.a(switch_runner.o): undefined reference to symbol 'pi_p4info_table_id_from_name'                                                                                                                  
/usr/bin/ld: /usr/local/lib/libpip4info.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

The librarary /usr/local/lib/libpip4info.so.0 exists on my machine and
I am using gcc (GCC) 8.2.1 20181127.
Also I ran ldconfig before the compilation.

Does anybody know how this issue is caused?

**Comment by jafingerhut** [comment]
I do not know how it is caused.

I know at least one way to avoid it, though.  If you have a freshly installed Ubuntu 16.04 or 18.04 Linux machine, you can install simple_switch_grpc and all other open source packages that it depends upon using this bash script: https://github.com/jafingerhut/p4-guide/blob/master/bin/install-p4dev-p4runtime.sh

I test it out every month or so with the latest versions of p4c, behavioral-model, and other P4 repositories.  It last ran successfully 12 days ago.

**Comment by jafingerhut** [comment]
As a wild guess, though, if you have a .so file installed on your system, but the 'ld' command is not finding it, you may have missed a `sudo ldconfig` step from the installation instructions (or such a step might be missing from the instructions).

**Comment by antoninbas** [comment]
I have seen this issue before and the easiest solution is to do a clean build & install of PI and bmv2 (from fresh clones). Is it possible that you tried to re-build bmv2 with different configure flags (such as `--with-pi`) without cleaning your build directory first?

**Comment by Pfeifenjoy** [comment]
I have fixed the issue by checking out an older commit.
As said before ldconfig did not work. Also a clean install did not work.

My guess is that the issue is due to my OS. I am using Arch Linux not Ubuntu.

**Comment by sayasree** [comment]
Yes, Andy Fingerhut's script:  https://github.com/jafingerhut/p4-guide/blob/master/bin/install-p4dev-p4runtime.sh got executed on Ubuntu 18.04. I tried to build simple_switch_grpc, but could not do it. Executing this script created it without any hiccups!
Thanks to Andy for developing, sharing and maittaining the script! It saved my time and I don't have to go through the frustration of making multiple version of the open sources pieces work together!
