### ISSUE TITLE
Configurable max_port

### ISSUE THREAD

**Issue by stefanheule** [p4lang/behavioral-model#743]
Currently, BMv2 limits ports to be between 0 and 512 (https://github.com/p4lang/behavioral-model/blob/6700f6d072b0c42228ef0dbaf872461b991cbe95/targets/simple_switch_grpc/switch_runner.h#L54, or concretely https://github.com/p4lang/behavioral-model/blob/6700f6d072b0c42228ef0dbaf872461b991cbe95/targets/simple_switch_grpc/main.cpp#L85 where it is set).  In our use-case we need larger port numbers, and we would find it useful if this value was configurable.

**Comment by jafingerhut** [comment]
When you configure a larger max_port, if you use the v1model architecture, you will probably also want the magic value 511 written to standard_metadata.egress_spec that indicates a drop to change, too.

If you do not use the v1model architecture, that may not be an issue for you.

**Comment by konne-google** [comment]
Thanks for pointing that out Andy!
Thankfully, we are using the port space very sparsely, and 511 happens to be a port id that we don't use.

**Comment by stefanheule** [comment]
Though it might be nice if that value is configurable, too, so that people who do use that port have options.

**Comment by jafingerhut** [comment]
How large do you want to go?

A full 32-bit value, for example, would be bad for memory footprint if the BMv2 implementation ever creates an array indexed by the port number.  I know such things could be changed to sparse hash tables indexed by the 32-bit value, only populating the port numbers you actually want to be valid for a particular run.  I suspect the current command line argument for simple_switch `-i <port_number>@<interface_name>` will run out of room on a Linux command line before you can get to tens of thousands of ports specified in that way.

Another implementation detail: If you want to use p4c, its v1model.p4 include file at https://github.com/p4lang/p4c/blob/master/p4include/v1model.p4 would need to be changed, at least to increase the bit width of these fields:

+ ingress_port
+ egress_spec
+ egress_port

Note that `recirculate_port` is not used by BMv2 at all, as comments in that file indicate, and thus there is no reason to use it, ever, let alone change it for this reason.

There may be other changes in the Thrift API for configuring clone/mirror sessions and multicast groups, if they are currently limited in the bit width of port sizes they allow.  (but unnecessary if one is not using the Thrift API)

**Comment by stefanheule** [comment]
Thanks for all the info, Andy, this is super useful.  Right now I think we wouldn't need more than 4096.

It's not totally clear to me if you are saying that BMv2 does create such an array (which would obviously bad for very large number of ports), or only saying one would need to look into this as a possible source of problems.  Can you clarify?

**Comment by antoninbas** [comment]
It's on my TODO list to support arbitrary uint32 port values throughout the code. This requires me to change a few data structures (mostly vectors indexed by the port number).

**Comment by antoninbas** [comment]
I have opened PR #747 for this. I'll open a different one later for configuring an arbitrary drop port number.
Note that v1model.p4 hardcodes the port fields' bitwidth to 9, so the burden is on you to change that if you want to use port numbers outside of the [0, 511] range.
In theory one could use P4Runtime translation support to circumvent that (and this PR would not really be needed), but translation is not supported yet by the bmv2 P4Runtime implementation and would require much more work than this PR. And of course, the bmv2 logs would show the untranslated (device-specific) port numbers (or more precisely port index, if we reserve port number / port id to designate SDN ports).

**Comment by antoninbas** [comment]
FYI, I added the ability to provide a custom drop port with `--drop-port` (https://github.com/p4lang/behavioral-model/pull/750).
