### ISSUE TITLE
get_time_since_epoch_us() is wrong in simple_switch.cpp

### ISSUE THREAD

**Issue by IMxbo** [p4lang/behavioral-model#749]
I modified the source to get the real time in my INT application ,
 
> if(phv->has_field("intrinsic_metadata.ingress_global_timestamp")) {
phv->get_field("intrinsic_metadata.ingress_global_timestamp").set(get_time_since_epoch_us());

And, the real timestamp is 1554121270150922 but I got something wrong  like 146745507757117.
I checked the src code and the original packet , they are all right. I am so confused about this.

**Comment by jafingerhut** [comment]
ingress_global_timestamp and egress_global_timestamp are defined to be 48 bits in size here: https://github.com/p4lang/p4c/blob/master/p4include/v1model.p4#L64-L65

The number 1554121270150922 decimal = 585770E3EC70A hex, which does not fit in 48 bits.

146745507757117 decimal = 8576D9DCBC3D hex, which does fit in 48 bits.  Most likely you tried to store a value with non-0 bits outside of the least significant 48 bits, and all but the least significant 48 bits were discarded.

Any finite size timestamp will wrap around eventually.  You can decide for yourself if for some reason you think 48 bit is enough, or not, and if not, one experiment you could try would be to change the size of those fields in the v1model.p4 of a local copy of the p4c compiler that you clone, and then build the compiler from source code after making that change, then recompile your program.

**Comment by IMxbo** [comment]
> ingress_global_timestamp and egress_global_timestamp are defined to be 48 bits in size here: https://github.com/p4lang/p4c/blob/master/p4include/v1model.p4#L64-L65
> 
> The number 1554121270150922 decimal = 585770E3EC70A hex, which does not fit in 48 bits.
> 
> 146745507757117 decimal = 8576D9DCBC3D hex, which does fit in 48 bits. Most likely you tried to store a value with non-0 bits outside of the least significant 48 bits, and all but the least significant 48 bits were discarded.
> 
> Any finite size timestamp will wrap around eventually. You can decide for yourself if for some reason you think 48 bit is enough, or not, and if not, one experiment you could try would be to change the size of those fields in the v1model.p4 of a local copy of the p4c compiler that you clone, and then build the compiler from source code after making that change, then recompile your program.

Thank your so much, I got it and solved my problem!
