### ISSUE TITLE
BMV2 installation issues

### ISSUE THREAD

**Issue by Juniortheone** [p4lang/behavioral-model#752]
I am installing the bmv2 but I have gotten a lot of errors. Most of them have to deal with missing packages which I have installed but I've gotten this error and I can't seem to find a solution,
`prince@prince-VirtualBox:~/baby/sysrepo/build$ cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug ..
-- Preparing developer's build of sysrepo v. 0.7.5
-- sysrepo repository location: /etc/sysrepo
-- Could NOT find ev (missing:  EV_LIBRARY EV_INCLUDE_DIR) 
-- Could NOT find redblack (missing:  REDBLACK_LIBRARY REDBLACK_INCLUDE_DIR) 
-- libavl will be used for binary tree manipulations.
CMake Warning at CMakeLists.txt:244 (find_package):
  By not providing "FindCMOCKA.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "CMOCKA", but
  CMake did not find one.

  Could not find a package configuration file provided by "CMOCKA" with any
  of the following names:

    CMOCKAConfig.cmake
    cmocka-config.cmake

  Add the installation prefix of "CMOCKA" to CMAKE_PREFIX_PATH or set
  "CMOCKA_DIR" to a directory containing one of the above files.  If "CMOCKA"
  provides a separate development package or SDK, be sure it has been
  installed.

CMake Warning at CMakeLists.txt:250 (MESSAGE):
  CMocka not found, tests are disabled.

-- Found SWIG: /usr/bin/swig3.0 (found version "3.0.8") 
-- Lua version 5.1 was selected
-- Could NOT find Lua51 (missing:  LUA_LIBRARIES LUA_INCLUDE_DIR) 
CMake Warning at swig/CMakeLists.txt:26 (message):
  Did not found Lua version 5.1

-- Sysrepo supports Lua 5.1, Lua 5.2 and Lua 5.3
-- Python version 2 was selected
-- Could NOT find PythonLibs (missing:  PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS) (Required is at least version "2")
-- Found PythonInterp: /usr/bin/python (found version "2.7.12") 
CMake Warning at swig/CMakeLists.txt:57 (message):
  Did not found Python version 2.x

-- Sysrepo supports Python 2.x and Python 3.x
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
EV_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/prince/baby/sysrepo
   used as include directory in directory /home/prince/baby/sysrepo
   used as include directory in directory /home/prince/baby/sysrepo
   used as include directory in directory /home/prince/baby/sysrepo
   used as include directory in directory /home/prince/baby/sysrepo
   used as include directory in directory /home/prince/baby/sysrepo
   used as include directory in directory /home/prince/baby/sysrepo
   used as include directory in directory /home/prince/baby/sysrepo/src
   used as include directory in directory /home/prince/baby/sysrepo/src
   used as include directory in directory /home/prince/baby/sysrepo/src
   used as include directory in directory /home/prince/baby/sysrepo/src
   used as include directory in directory /home/prince/baby/sysrepo/src
   used as include directory in directory /home/prince/baby/sysrepo/src
   used as include directory in directory /home/prince/baby/sysrepo/src
   used as include directory in directory /home/prince/baby/sysrepo/src
   used as include directory in directory /home/prince/baby/sysrepo/src
   used as include directory in directory /home/prince/baby/sysrepo/src
   used as include directory in directory /home/prince/baby/sysrepo/src
   used as include directory in directory /home/prince/baby/sysrepo/src
   used as include directory in directory /home/prince/baby/sysrepo/src
   used as include directory in directory /home/prince/baby/sysrepo/src
   used as include directory in directory /home/prince/baby/sysrepo/src
   used as include directory in directory /home/prince/baby/sysrepo/swig
   used as include directory in directory /home/prince/baby/sysrepo/swig
   used as include directory in directory /home/prince/baby/sysrepo/swig
   used as include directory in directory /home/prince/baby/sysrepo/swig
   used as include directory in directory /home/prince/baby/sysrepo/swig
   used as include directory in directory /home/prince/baby/sysrepo/swig
   used as include directory in directory /home/prince/baby/sysrepo/swig
   used as include directory in directory /home/prince/baby/sysrepo/swig/cpp/examples
   used as include directory in directory /home/prince/baby/sysrepo/swig/cpp/examples
   used as include directory in directory /home/prince/baby/sysrepo/swig/cpp/examples
   used as include directory in directory /home/prince/baby/sysrepo/swig/cpp/examples
   used as include directory in directory /home/prince/baby/sysrepo/swig/cpp/examples
   used as include directory in directory /home/prince/baby/sysrepo/swig/cpp/examples
   used as include directory in directory /home/prince/baby/sysrepo/swig/cpp/examples
   used as include directory in directory /home/prince/baby/sysrepo/swig/cpp/examples
   used as include directory in directory /home/prince/baby/sysrepo/swig/cpp/examples
   used as include directory in directory /home/prince/baby/sysrepo/swig/cpp/examples
   used as include directory in directory /home/prince/baby/sysrepo/swig/cpp/examples
   used as include directory in directory /home/prince/baby/sysrepo/swig/cpp/examples
   used as include directory in directory /home/prince/baby/sysrepo/swig/cpp/examples
   used as include directory in directory /home/prince/baby/sysrepo/swig/cpp/examples
EV_LIBRARY (ADVANCED)
    linked by target "sysrepo" in directory /home/prince/baby/sysrepo/src
    linked by target "sysrepo_a" in directory /home/prince/baby/sysrepo/src
    linked by target "sysrepo-plugind" in directory /home/prince/baby/sysrepo/src

-- Configuring incomplete, errors occurred!
See also "/home/prince/baby/sysrepo/build/CMakeFiles/CMakeOutput.log".
See also "/home/prince/baby/sysrepo/build/CMakeFiles/CMakeError.log".
prince@prince-VirtualBox:~/baby/sysrepo/build$ make install
make: *** No rule to make target 'install'.  Stop.
prince@prince-VirtualBox:~/baby/sysrepo/build$ cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug ..
-- Preparing developer's build of sysrepo v. 0.7.5
-- sysrepo repository location: /etc/sysrepo
-- Could NOT find ev (missing:  EV_LIBRARY EV_INCLUDE_DIR) 
-- Could NOT find redblack (missing:  REDBLACK_LIBRARY REDBLACK_INCLUDE_DIR) 
-- libavl will be used for binary tree manipulations.
CMake Warning at CMakeLists.txt:244 (find_package):
  By not providing "FindCMOCKA.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "CMOCKA", but
  CMake did not find one.

  Could not find a package configuration file provided by "CMOCKA" with any
  of the following names:

    CMOCKAConfig.cmake
    cmocka-config.cmake

  Add the installation prefix of "CMOCKA" to CMAKE_PREFIX_PATH or set
  "CMOCKA_DIR" to a directory containing one of the above files.  If "CMOCKA"
  provides a separate development package or SDK, be sure it has been
  installed.

CMake Warning at CMakeLists.txt:250 (MESSAGE):
  CMocka not found, tests are disabled.

-- Lua version 5.1 was selected
-- Could NOT find Lua51 (missing:  LUA_LIBRARIES LUA_INCLUDE_DIR) 
CMake Warning at swig/CMakeLists.txt:26 (message):
  Did not found Lua version 5.1

-- Sysrepo supports Lua 5.1, Lua 5.2 and Lua 5.3
-- Python version 2 was selected
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable version "2.7.12", minimum required is "2") 
-- Found PythonInterp: /usr/bin/python2.7 (found version "2.7.12") 
-- Found SWIG: /usr/bin/swig3.0 (found suitable version "3.0.8", minimum required is "3.0.5") 
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
EV_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/prince/baby/sysrepo
   used as include directory in directory /home/prince/baby/sysrepo
   used as include directory in directory /home/prince/baby/sysrepo
   used as include directory in directory /home/prince/baby/sysrepo
   used as include directory in directory /home/prince/baby/sysrepo
   used as include directory in directory /home/prince/baby/sysrepo
   used as include directory in directory /home/prince/baby/sysrepo
   used as include directory in directory /home/prince/baby/sysrepo/src
   used as include directory in directory /home/prince/baby/sysrepo/src
   used as include directory in directory /home/prince/baby/sysrepo/src
   used as include directory in directory /home/prince/baby/sysrepo/src
   used as include directory in directory /home/prince/baby/sysrepo/src
   used as include directory in directory /home/prince/baby/sysrepo/src
   used as include directory in directory /home/prince/baby/sysrepo/src
   used as include directory in directory /home/prince/baby/sysrepo/src
   used as include directory in directory /home/prince/baby/sysrepo/src
   used as include directory in directory /home/prince/baby/sysrepo/src
   used as include directory in directory /home/prince/baby/sysrepo/src
   used as include directory in directory /home/prince/baby/sysrepo/src
   used as include directory in directory /home/prince/baby/sysrepo/src
   used as include directory in directory /home/prince/baby/sysrepo/src
   used as include directory in directory /home/prince/baby/sysrepo/src
   used as include directory in directory /home/prince/baby/sysrepo/swig
   used as include directory in directory /home/prince/baby/sysrepo/swig
   used as include directory in directory /home/prince/baby/sysrepo/swig
   used as include directory in directory /home/prince/baby/sysrepo/swig
   used as include directory in directory /home/prince/baby/sysrepo/swig
   used as include directory in directory /home/prince/baby/sysrepo/swig
   used as include directory in directory /home/prince/baby/sysrepo/swig
   used as include directory in directory /home/prince/baby/sysrepo/swig/cpp/examples
   used as include directory in directory /home/prince/baby/sysrepo/swig/cpp/examples
   used as include directory in directory /home/prince/baby/sysrepo/swig/cpp/examples
   used as include directory in directory /home/prince/baby/sysrepo/swig/cpp/examples
   used as include directory in directory /home/prince/baby/sysrepo/swig/cpp/examples
   used as include directory in directory /home/prince/baby/sysrepo/swig/cpp/examples
   used as include directory in directory /home/prince/baby/sysrepo/swig/cpp/examples
   used as include directory in directory /home/prince/baby/sysrepo/swig/cpp/examples
   used as include directory in directory /home/prince/baby/sysrepo/swig/cpp/examples
   used as include directory in directory /home/prince/baby/sysrepo/swig/cpp/examples
   used as include directory in directory /home/prince/baby/sysrepo/swig/cpp/examples
   used as include directory in directory /home/prince/baby/sysrepo/swig/cpp/examples
   used as include directory in directory /home/prince/baby/sysrepo/swig/cpp/examples
   used as include directory in directory /home/prince/baby/sysrepo/swig/cpp/examples
   used as include directory in directory /home/prince/baby/sysrepo/swig/python
   used as include directory in directory /home/prince/baby/sysrepo/swig/python
   used as include directory in directory /home/prince/baby/sysrepo/swig/python
   used as include directory in directory /home/prince/baby/sysrepo/swig/python
   used as include directory in directory /home/prince/baby/sysrepo/swig/python
   used as include directory in directory /home/prince/baby/sysrepo/swig/python
   used as include directory in directory /home/prince/baby/sysrepo/swig/python
EV_LIBRARY (ADVANCED)
    linked by target "sysrepo" in directory /home/prince/baby/sysrepo/src
    linked by target "sysrepo_a" in directory /home/prince/baby/sysrepo/src
    linked by target "sysrepo-plugind" in directory /home/prince/baby/sysrepo/src

-- Configuring incomplete, errors occurred!
See also "/home/prince/baby/sysrepo/build/CMakeFiles/CMakeOutput.log".
See also "/home/prince/baby/sysrepo/build/CMakeFiles/CMakeError.log".` 

The most troublesome are the CMAKE and cmocka errors. I installed cmocka and I went though the cmake files in each directory to see where was NOT FOUND but I can't figure it out.

**Comment by Juniortheone** [comment]
This is the error log from CMakeError.log;
`Determining if the function getpeereid exists failed with the following output:
Change Dir: /home/prince/baby/sysrepo/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_c27d8/fast"
/usr/bin/make -f CMakeFiles/cmTC_c27d8.dir/build.make CMakeFiles/cmTC_c27d8.dir/build
make[1]: Entering directory '/home/prince/baby/sysrepo/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_c27d8.dir/CheckFunctionExists.c.o
/usr/bin/cc    -Wall -Wpedantic -std=gnu11 -Wno-language-extension-token -Wno-strict-aliasing -DCHECK_FUNCTION_EXISTS=getpeereid   -o CMakeFiles/cmTC_c27d8.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.5/Modules/CheckFunctionExists.c
Linking C executable cmTC_c27d8
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_c27d8.dir/link.txt --verbose=1
/usr/bin/cc   -Wall -Wpedantic -std=gnu11 -Wno-language-extension-token -Wno-strict-aliasing -DCHECK_FUNCTION_EXISTS=getpeereid    CMakeFiles/cmTC_c27d8.dir/CheckFunctionExists.c.o  -o cmTC_c27d8 -rdynamic -lpthread 
CMakeFiles/cmTC_c27d8.dir/CheckFunctionExists.c.o: In function `main':
CheckFunctionExists.c:(.text+0x15): undefined reference to `getpeereid'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_c27d8.dir/build.make:97: recipe for target 'cmTC_c27d8' failed
make[1]: *** [cmTC_c27d8] Error 1
make[1]: Leaving directory '/home/prince/baby/sysrepo/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_c27d8/fast' failed
make: *** [cmTC_c27d8/fast] Error 2


Determining if the function getpeerucred exists failed with the following output:
Change Dir: /home/prince/baby/sysrepo/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_596cc/fast"
/usr/bin/make -f CMakeFiles/cmTC_596cc.dir/build.make CMakeFiles/cmTC_596cc.dir/build
make[1]: Entering directory '/home/prince/baby/sysrepo/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_596cc.dir/CheckFunctionExists.c.o
/usr/bin/cc    -Wall -Wpedantic -std=gnu11 -Wno-language-extension-token -Wno-strict-aliasing -DCHECK_FUNCTION_EXISTS=getpeerucred   -o CMakeFiles/cmTC_596cc.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.5/Modules/CheckFunctionExists.c
Linking C executable cmTC_596cc
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_596cc.dir/link.txt --verbose=1
/usr/bin/cc   -Wall -Wpedantic -std=gnu11 -Wno-language-extension-token -Wno-strict-aliasing -DCHECK_FUNCTION_EXISTS=getpeerucred    CMakeFiles/cmTC_596cc.dir/CheckFunctionExists.c.o  -o cmTC_596cc -rdynamic -lpthread 
CMakeFiles/cmTC_596cc.dir/CheckFunctionExists.c.o: In function `main':
CheckFunctionExists.c:(.text+0x15): undefined reference to `getpeerucred'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_596cc.dir/build.make:97: recipe for target 'cmTC_596cc' failed
make[1]: *** [cmTC_596cc] Error 1
make[1]: Leaving directory '/home/prince/baby/sysrepo/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_596cc/fast' failed
make: *** [cmTC_596cc/fast] Error 2


Determining if files ucred.h exist failed with the following output:
Change Dir: /home/prince/baby/sysrepo/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_80623/fast"
/usr/bin/make -f CMakeFiles/cmTC_80623.dir/build.make CMakeFiles/cmTC_80623.dir/build
make[1]: Entering directory '/home/prince/baby/sysrepo/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_80623.dir/CheckIncludeFiles.c.o
/usr/bin/cc    -Wall -Wpedantic -std=gnu11 -Wno-language-extension-token -Wno-strict-aliasing    -o CMakeFiles/cmTC_80623.dir/CheckIncludeFiles.c.o   -c /home/prince/baby/sysrepo/build/CMakeFiles/CMakeTmp/CheckIncludeFiles.c
/home/prince/baby/sysrepo/build/CMakeFiles/CMakeTmp/CheckIncludeFiles.c:2:19: fatal error: ucred.h: No such file or directory
compilation terminated.
CMakeFiles/cmTC_80623.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_80623.dir/CheckIncludeFiles.c.o' failed
make[1]: *** [CMakeFiles/cmTC_80623.dir/CheckIncludeFiles.c.o] Error 1
make[1]: Leaving directory '/home/prince/baby/sysrepo/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_80623/fast' failed
make: *** [cmTC_80623/fast] Error 2

Source:
/* */
#include <ucred.h>


int main(void){return 0;}

`

**Comment by jafingerhut** [comment]
If you want a script that on an Ubuntu 16.04 or 18.04 Linux system (a fresh install, at least) will install p4c, BMv2, and P4Runtime support, and is periodically verified to work even as those projects are updated, you can find it here: https://github.com/jafingerhut/p4-guide/blob/master/bin/install-p4dev-p4runtime.sh

There are some troubleshooting tips here that should maximize your chances of success: https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md

**Comment by Juniortheone** [comment]
Thank you @jafingerhut
