### ISSUE TITLE
Nanomsg returned a exception when trying to bind to address 'ipc:///tmp/bmv2-0-notifications.ipc'. The exception is: Address already in use

### ISSUE THREAD

**Issue by ShiJinYu2017** [p4lang/behavioral-model#759]
I want to install the latest version（1.13） of bmv2，so I removed the old folder named behavioral model. And now it was reinstalled as follows[https://github.com/p4lang/behavioral-model](url),but
there is a when I execute the `make check`
```
PASS: test_periodic_tasks
FAIL: test_switch
PASS: test_target_parser
PASS: test_runtime_iface
PASS: test_bm_apps
PASS: test_stateful
PASS: test_enums
PASS: test_core_primitives
PASS: test_control_flow
============================================================================
Testsuite summary for bm 1.13.0-84e7ff14
============================================================================
# TOTAL: 35
# PASS: 34
# SKIP: 0
# XFAIL: 0
# FAIL: 1
# XPASS: 0
# ERROR: 0
============================================================================
See tests/test-suite.log
Please report to antonin@barefootnetworks.com
============================================================================
Makefile:1681: recipe for target 'test-suite.log' failed
make[4]: *** [test-suite.log] Error 1
make[4]: Leaving directory '/home/myp4/P4/behavioral-model/tests'
Makefile:1787: recipe for target 'check-TESTS' failed
make[3]: *** [check-TESTS] Error 2
make[3]: Leaving directory '/home/myp4/P4/behavioral-model/tests'
Makefile:2123: recipe for target 'check-am' failed
make[2]: *** [check-am] Error 2
make[2]: Leaving directory '/home/myp4/P4/behavioral-model/tests'
Makefile:1574: recipe for target 'check-recursive' failed
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory '/home/myp4/P4/behavioral-model/tests'
Makefile:453: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1
```
I opened the file test-suite.log ,it says:
```
# FAIL: 1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test_switch
=================

[==========] Running 12 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 12 tests from Switch
[ RUN ] Switch.GetConfig
[ OK ] Switch.GetConfig (0 ms)
[ RUN ] Switch.ConfigOptions
[ OK ] Switch.ConfigOptions (0 ms)
[ RUN ] Switch.InitObjectsEmpty
[ OK ] Switch.InitObjectsEmpty (2008 ms)
[ RUN ] Switch.GetP4Objects
[ OK ] Switch.GetP4Objects (6 ms)
[ RUN ] Switch.SerializeState1
[ OK ] Switch.SerializeState1 (11 ms)
[ RUN ] Switch.SerializeState2
[ OK ] Switch.SerializeState2 (188 ms)
[ RUN ] Switch.ForceArithNone
[ OK ] Switch.ForceArithNone (0 ms)
[ RUN ] Switch.ForceArithField
[ OK ] Switch.ForceArithField (0 ms)
[ RUN ] Switch.ForceArithHeader
[ OK ] Switch.ForceArithHeader (0 ms)
[ RUN ] Switch.ExternSafeAccess
[ OK ] Switch.ExternSafeAccess (0 ms)
[ RUN ] Switch.MyDevMgr
Nanomsg returned a exception when trying to bind to address 'ipc:///tmp/bmv2-0-notifications.ipc'.
The exception is: Address already in use
This may happen if
1) the address provided is invalid,
4) another instance of bmv2 is running and using the same address, or
3) you have insufficent permissions (e.g. you are using an IPC socket on Unix, the file already exists and you don't have permission to access it)
FAIL test_switch (exit status: 1)
```

**Comment by jafingerhut** [comment]
When you run simple_switch, it attempts to create a file `/tmp/bmv2-0-notifications.ipc`.  If you run it as the superuser (i.e. user 'root'), it creates that file with 'root' as the owner.  Later if you try to run simple_switch as a normal user, which the automated build and/or testing steps likely do, they will fail to remove that file since it is owned by 'root'.

Could you try running this command, and then repeat the build/test steps that failed for you, to see if they succeed afterwards?

```
$ sudo rm /tmp/bmv2-0-notifications.ipc
```

**Comment by ShiJinYu2017** [comment]
I tried this way, but it doesn't seem to work. then I removed the folder named behavioral model. but It still works when I execute simple_switch.

**Comment by ShiJinYu2017** [comment]
now I have reinstall the bmv2，but when I execute `make`  in the project `/P4/tutorials/exercises/basic`, It says :
```
mkdir -p build pcaps logs
p4c-bm2-ss --p4v 16 --p4runtime-file build/basic.p4info --p4runtime-format text -o build/basic.json basic.p4
sudo python ../../utils/run_exercise.py -t topology.json -b simple_switch_grpc
[sudo] password for myp4: 
Traceback (most recent call last):
  File "../../utils/run_exercise.py", line 33, in <module>
    import p4runtime_lib.simple_controller
  File "/home/myp4/P4/tutorials/utils/p4runtime_lib/simple_controller.py", line 22, in <module>
    import bmv2
  File "/home/myp4/P4/tutorials/utils/p4runtime_lib/bmv2.py", line 15, in <module>
    from switch import SwitchConnection
  File "/home/myp4/P4/tutorials/utils/p4runtime_lib/switch.py", line 20, in <module>
    from p4 import p4runtime_pb2
ImportError: cannot import name p4runtime_pb2
../../utils/Makefile:28: recipe for target 'run' failed
make: *** [run] Error 1
```
and I can find the file p4runtime_pb2 at `myp4@myp4-VM:~/P4/p4c/build/control-plane/p4$ ls
config  p4runtime_pb2.py  p4runtime.pb.cc  p4runtime.pb.h`

**Comment by frederic-loui** [comment]
Hi,
Depending in the protobuf/grpc version you use you might have to tweak python scripts in p4runtime_lib folder. In the issue you raised, you face a python loading module error.

switch.py in folder /home/myp4/P4/tutorials/utils/p4runtime_lib/ cannot find a python library name in the PYTHONPATH or in library path defined in the script.

This is done using this line:

```
sys.path.append(
    os.path.join(os.path.dirname(os.path.abspath(__file__)),
        '../../utils/'))
```

So you should try to find a file name p4runtime_pb2.py in your python library path.
User `find` or `locate` in ubuntu and you normally should find this file under:
/usr/local/lib/python2.7/site-packages/ or /usr/lib/python2.7/dist-packages/
Depending on the method you use for P4 installation.
Please note that this is a pure python problem.
If you don't find the file, it means that there is something wrong in you P4lang installation.

One final note, if you using recent software version and/or use simple_switch_grpc you might have to use a modified switch.py in p4runtime_lib as it is mentioned in this [thread](http://lists.p4.org/pipermail/p4-dev_lists.p4.org/2018-July/003591.html) 

Or in this [issue](https://github.com/p4lang/tutorials/issues/184)

Hope this help.
Frederic.

PS: Don't hesitate to search in P4lang various mailing list or github past issues. (Or simply google it)
       You'll find various tips. These scripts are subject to change from time to time as the dev integrate 
       new features, improve the code that might "break" existing test/tutorial code.

**Comment by jafingerhut** [comment]
If you are willing to start with a new freshly installed Ubuntu 16.04 or 18.04 Linux system, and install BMv2 and the open source P4 compiler p4c, with P4Runtime support, you can run this bash shell script, which I have run successfully over the last several months on the latest version of the P4 source code: https://github.com/jafingerhut/p4-guide/blob/master/bin/install-p4dev-p4runtime.sh

It might also work on an Ubuntu Linux system that is not a fresh install, but no guarantees there -- the script does not attempt to detect any kinds of Ubuntu package conflicts with any packages installed earlier.

**Comment by ShiJinYu2017** [comment]
@frederic-loui @jafingerhut  Thanks for your help .I am willing to install the lastest version of the P4 source code, The reason for this problem may be that I have only updated the behavioral-model.

**Comment by antoninbas** [comment]
I'm closing this. The fix given by Andy (https://github.com/p4lang/behavioral-model/issues/759#issuecomment-483721826) is the correct fix for this issue.
