### ISSUE TITLE
symbol lookup error: _pi_act_prof_api_support

### ISSUE THREAD

**Issue by Pfeifenjoy** [p4lang/behavioral-model#776]
I am using the current stable version of the PI runtime.
My behavioral model is version 1.13.0.

As a target I run the simple_switch_grpc.
When I want to connect to the switch via grpc I get the following error.

`/usr/local/bin/simple_switch_grpc: symbol lookup error: /usr/local/lib/libpi.so.0: undefined symbol: _pi_act_prof_api_support`

The debug_error_string is:

```
"{"created":"@1557318835.921928951","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"Socket closed","grpc_status
":14}"
```

I am assuming that I run incompatible versions.
Does anybody know what could cause this issue?

**Comment by antoninbas** [comment]
You can check if `_pi_act_prof_api_support` is implemented in the version of bmv2 you are using, but as far as I can tell it is available in 1.13.0: https://github.com/p4lang/behavioral-model/blob/1.13.0/PI/src/pi_act_prof_imp.cpp#L267
My guess would be that you are using an old `libbmpi` library version (the code under behavioral-model/PI). I would recommend doing a clean build of bmv2 (either from a fresh clone or by removing all untracked files with `git clean -fX`), and making sure you use the `--with-pi` flag when running configure.

**Comment by Pfeifenjoy** [comment]
Hmm, when I try to build the simple_switch_grpc then I get:

```
make  all-recursive
make[1]: Entering directory '/home/vagrant/behavioral-model/targets/simple_switch_grpc'
Making all in .
make[2]: Entering directory '/home/vagrant/behavioral-model/targets/simple_switch_grpc'
/bin/bash ./libtool  --tag=CXX   --mode=link g++ -Wall -Wextra -pthread -g -O2 -std=c++11 -Wl,--no-as-needed,-lgrpc++_reflection,--as-needed  -o simple_switch_grpc main.o libsimple_switch_grpc.la
libtool: link: g++ -Wall -Wextra -pthread -g -O2 -std=c++11 -Wl,--no-as-needed -Wl,-lgrpc++_reflection -Wl,--as-needed -o .libs/simple_switch_grpc main.o  ./.libs/libsimple_switch_grpc.a -lboost_system -l
thrift -lboost_program_options -lboost_filesystem /home/vagrant/behavioral-model/PI/.libs/libbmpi.so -ldl -lpcap -lgmp /home/vagrant/behavioral-model/targets/simple_switch_grpc/.libs/libbm_grpc_dataplane.
so -L/usr/local/lib /usr/local/lib/libpigrpcserver.so /usr/local/lib/libpifeproto.so /usr/local/lib/libpifecpp.so /usr/local/lib/libpiconvertproto.so -lboost_thread /usr/local/lib/libpiprotogrpc.so /usr/l
ocal/lib/libpiprotobuf.so /usr/local/lib/libpi.so /usr/local/lib/libpip4info.so -lnanomsg -lreadline -lJudy -lgrpc++ -lgrpc /usr/local/lib/libprotobuf.so -lz -lpthread -pthread
/usr/local/lib/libpi.so: undefined reference to `_pi_learn_config_set'
/usr/local/lib/libpi.so: undefined reference to `_pi_act_prof_api_support'
/usr/local/lib/libpi.so: undefined reference to `_pi_table_entry_get_remaining_ttl'
/usr/local/lib/libpi.so: undefined reference to `_pi_clone_session_reset'
/usr/local/lib/libpi.so: undefined reference to `_pi_act_prof_grp_set_mbrs'
/usr/local/lib/libpi.so: undefined reference to `_pi_clone_session_set'
/usr/local/lib/libpi.so: undefined reference to `_pi_table_idle_timeout_config_set'
collect2: error: ld returned 1 exit status
Makefile:717: recipe for target 'simple_switch_grpc' failed
make[2]: *** [simple_switch_grpc] Error 1
make[2]: Leaving directory '/home/vagrant/behavioral-model/targets/simple_switch_grpc'
Makefile:885: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/vagrant/behavioral-model/targets/simple_switch_grpc'
Makefile:544: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by jafingerhut** [comment]
I do not know why that is occurring, but I do know that if you start with a freshly installed Ubuntu 16.04 or 18.04 Desktop Linux system with enough memory (e.g. 4 GB) and disk space (15 GB or more), and Internet access, this bash script can install a working simple_switch_grpc and p4c: https://github.com/jafingerhut/p4-guide/blob/master/bin/install-p4dev-p4runtime.sh

If nothing else, you could look at the script and see if you missed any steps.

**Comment by antoninbas** [comment]
@Pfeifenjoy That means your PI version is very old, since all the functions that were added "recently" (in the last few months_ are missing. I'm positive that the PI stable branch has all of these.

**Comment by Pfeifenjoy** [comment]
@antoninbas I reinstalled PI now multiple times with either the master or stable branched and tried different versions of the bm.

When I search the PI folder I do find the missing methods, mainly under `targets/*/pi_learn_config_set.cpp, ...`.

I have removed all shared libraries under `/usr/local/lib/libpi*`, reinstalled it and called `sudo ldconfig`.

However I still get the linker error.

Do you have an idea what I missed?

**Comment by Pfeifenjoy** [comment]
After the virtual machine and installing everything from scratch it works now.

No idea why it did not work before.
