### ISSUE TITLE
Choice of veths cause packets to be sent to different output port

### ISSUE THREAD

**Issue by aatish17varma** [p4lang/behavioral-model#781]
Hello,

I was testing my P4 program using a BMv2 switch with 8 ports. I checked it with two different switches. 

1) sudo simple_switch --log-console -i 0@veth2 -i 1@veth4 -i 2@veth6 -i 3@veth8 -i 4@veth10 -i 5@veth12 -i 6@veth14 -i 7@veth16 basic_demo8.json

2) sudo simple_switch --log-console -i 0@veth0 -i 1@veth1 -i 2@veth2 -i 3@veth3 -i 4@veth4 -i 5@veth5 -i 6@veth6 -i 7@veth7 basic_demo8.json

In 1) -  packets are forwarded to veth10 (output port)
In 2) - packets are forwarded to veth4 and veth5 (output port)

This is the program I was using: https://github.com/aatish17varma/P4-BugFinder/blob/master/Program_Pairs/basic_demo8.p4

Do you know why this in-congruency may be occurring? 

Thanks

**Comment by jafingerhut** [comment]
Assuming you are using the veth_setup.sh script included in the behavioral-model repo, or something similar that has lines like these: https://github.com/p4lang/behavioral-model/blob/master/tools/veth_setup.sh#L6-L8

veth interfaces are being created in pairs, with names of the pairs being such that veth(2*i) is paired with veth(2*i+1).  Any packet sent to one of the interfaces of a pair is forwarded to the other interface of the pair.

**Comment by antoninbas** [comment]
Closing this issue, it doesn't make sense to connect both ends of a veth to bmv2, as packets would "show up" on both ports
