### ISSUE TITLE
mesure P4 switch performance

### ISSUE THREAD

**Issue by washburn125** [p4lang/behavioral-model#785]
Hello!
A question from a beginner:  I am running some simple P4 programs for ipv6 packets on P4 switch using bmv2. How can I mesure its performance? I read the issues about using 'sudo python stress_test_ipv4.py', but if I try it I get 'file not found', and I don't understand what should I install/download  to make it work. Is there a version for ipv6 forwarding?

P.S. I am working on studying project and I need something to prove that P4 is preferable to use also for its performance. 

If you have any ideas, I will be REALLY happy to here from you!

**Comment by antoninbas** [comment]
I think the stress test script has to be run directly from the mininet directory.
More importantly,:
 * "P4 is preferable to use also for its performance" -> that's not an accurate statement, there is no correlation between a target being P4 programmable and the bandwidth that the target can sustain. P4 programmability and performance are two orthogonal dimensions. I imagine that when programming certain classes of run-to-completion programmable targets (maybe NPUs?) it is possible that programming the target with P4 gives better throughput results than programming it in generic C, P4 being a DSL (therefore simplifying the job of the compiler). But even that is a risky statement and highly dependent on the target and its compiler.
 * the behavioral-model (bmv2) is not at all representative of the performance of P4-programmable packet-processing hardware in general. As hinted by its name, it is meant to be development tool for P4 data planes and associated control planes. It is not a production virtual switch.

**Comment by antoninbas** [comment]
Closing this old issue. A lot of relevant information is also available in https://github.com/p4lang/behavioral-model/blob/master/docs/performance.md, if anyone were to stumble here.
