### ISSUE TITLE
Installing bmv2 on Raspberry PI..

### ISSUE THREAD

**Issue by castilhorosa** [p4lang/behavioral-model#786]
Hello everyone! Is it possible to install bmv2 in a physical device like Raspberry PI, for example? As far as I know, bmv2 has not been created to be executed direcly in hardware and to have good performance as well.. but I just wanted to know the feasibility of turning a Raspberry PI into a P4 capable device. Thanks.

**Comment by antoninbas** [comment]
There should be no issue when building / running bmv2 on the Raspberry PI, unless the C++ compilation fails for some portability reason. bmv2 uses libpcap to send / receive packets, so bmv2 can work with any Linux interface.

**Comment by antoninbas** [comment]
Closing this issue because it is inactive. Feel free to re-open it if you have further questions.
