### ISSUE TITLE
Configure Switch  

### ISSUE THREAD

**Issue by Fengww2014** [p4lang/behavioral-model#798]
How should I configure the switch to support p4?How do I install bmv2 on the switch?Are there any requirements for switch hardware?At the moment I can only run simulations on Linux, but I'd like to try it on an actual switch, so what should i do.

**Comment by jafingerhut** [comment]
This repository p4lang/behavioral-model is only intended for an implementation of a software switch that runs on general purpose CPU systems, e.g. Intel, AMD, etc.  Except for development, debugging, and testing, it cannot directly help you run P4 code on a real switch.

You need to acquire or borrow the use of real switch hardware (and/or a NIC, if that suits your needs) that is P4 programmable.  There is a partial list of vendors here, but note that it is _not_ intended to be complete.

https://github.com/hesingh/p4-info/blob/master/README.md

There is some discussion of that list, and some vendors and devices not listed there, in the email discussion threads linked below:

http://lists.p4.org/pipermail/p4-dev_lists.p4.org/2019-May/003944.html
http://lists.p4.org/pipermail/p4-dev_lists.p4.org/2019-June/003953.html

**Comment by antoninbas** [comment]
Closing this issue since it is inactive.
