### ISSUE TITLE
How to build docker image

### ISSUE THREAD

**Issue by bijutalukdar** [p4lang/behavioral-model#80]
I need to  build a docker image of bmv2 .Could someone help me.

Hi Vladimir,
I have a question, hope you will be able to answer. I want to run many docker containers of a p4 switch in a multi core server.My aim is to distribute the traffic(say real traffic from a 10 G NIC) to all these containers so that the processing is faster. Say I have calculating some hash values on the incoming traffic and I want to do it faster by running many instances of the p4 switch and distribute the traffic to all these containers. 
Do you think it can be done ? I am looking forward for your reply.

**Comment by antoninbas** [comment]
Closing this issue which is independent of this repo
