### ISSUE TITLE
behavioral-model command not found

### ISSUE THREAD

**Issue by prince901** [p4lang/behavioral-model#801]
I installed bmv2 and tried to run the targets but I get
`p4c-bm: command not found`
`p4c-bmv2: command not found`
I followed the instructions and I added the contents of p4setup.bash to .bashrc. I also exported the path but it is still not working. Please, I'm I missing something? 

My system: freshly installed ubuntu 16.04.

**Comment by jafingerhut** [comment]
You mention a file named p4setup.bash.  Am I correct in guessing that means you ran this script to build and install some P4 tools?  https://github.com/jafingerhut/p4-guide/blob/master/bin/install-p4dev-p4runtime.sh

If yes, then note that script does not install p4c-bm nor p4c-bmv2 commands.  It does install p4c and p4c-bm2-ss commands, and running the command `source p4setup.bash` should put them into your command PATH environment variable.  Look in the directory $HOME/p4c/build to see several of the p4 compiler executable names, but p4c should be the only one you need.

**Comment by prince901** [comment]
Thank you @jafingerhut for the clarification. I read more on it and found out the discrepancies. I am trying to run the `simple_switch` target. My understanding is to first compile the `.p4` file which generates a `.json` file which will be used by the bmv2. I realized that in the `simple_switch` target folder, there is no `simple_switch.p4` file and subsequent running of the process did not work. This is the command to generate the `.json` file:
`p4c --simple_switch bmv2 --arch v1model --std p4-16 simple_switch.p4`.
This is the error message
`unrecognized arguments: --simple_switch simple_switch.p4`
I managed however to run `l2_switch` successfully.

**Comment by prince901** [comment]
I was able to run both `l2_switch` and `simple_router`. Both are P14 which I run using `p4c-bmv2` but for the `simple_switch` and `simple_switch_grpc`; I tried using p4c-bm2-ss instead but it does not work.

**Comment by jafingerhut** [comment]
You can find recommended commands near the beginning of the README for the p4c compiler, here: https://github.com/p4lang/p4c#p4c

In particular, you should replace `--simple_switch` in your command with `--target`

**Comment by prince901** [comment]
Thank you

**Comment by prince901** [comment]
@jafingerhut I did what you advised. One more thing please. I tried compiling the `basic.p4` file in the p4 tutorial to generate its `json` file. This was the command `p4c --target bmv2 --arch v1model basic.p4
` but I'm getting this error `basic.p4(90): [--Werror=legacy] error: mark_to_drop: Passing 1 arguments when 0 expected
        mark_to_drop(standard_metadata);
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
`. I changed the `mark_to_drop` to `mark_to_drop(standard_metadata);` as suggested but I'm still getting the same error. Here is the section from the `basic.p4` file `action drop() {
        mark_to_drop(standard_metadata);`. I searched online and I found your article on how to troubleshoot this. The first I think is related to the above and the second was to update the p4c. I tried using `sudo apt-get upgrade p4c` but I got `Unable to locate package p4c`.
1. How can I update `p4c`?
2. In the p4 tutorial basic folder, the `json` files for the network topology and switch runtime are already available. My understanding is to first compile the `.p4` file which generates the `json` file so my question is this; how do I add hosts to the `simple_switch`? Do I define that in the `.p4` file or in a separate file like `topology.json` as done in the p4 tutorial?

**Comment by jafingerhut** [comment]
One option you have is to continue using the older version of p4c you have, and to change every mark_to_drop call to have no arguments.

Updating p4c is another possibility.  p4c is not published as any kind of package, so apt-get will not help to do so.

I would recommend the first choice above for now.  If you really, really want to update p4c, it will be a somewhat more involved process, but I can give instructions.

**Comment by antoninbas** [comment]
All instructions on how to install the latest p4c version are in the p4c README (https://github.com/p4lang/p4c#getting-started). I'm closing this issue, since it is no longer about bmv2.
