### ISSUE TITLE
How to auto-generate flow entries for bmv2 with spec P4 program

### ISSUE THREAD

**Issue by Polly2014** [p4lang/behavioral-model#804]
Here we go again, assume that I have create a P4 program(just like basic.p4), and compiled it to basic.json, basic.p4info.
Now I make a custom topology (with multi switch and host like classic fattree topo, 10 switches, 8 hosts), Then I should use thrift-based or gRPC-based method to populate the flow entries to switches.
***Question comes***:
How can I automic create flow entries(like tutorial's ```sX-runtime.json``` or ```commands.txt```) for each switches and add to them, Need I write the flow entries one by one, or there's other way to automic achieve it.
Hope for guide or sugguestion, thanks

**Comment by antoninbas** [comment]
The flow entries you can install depend on the P4 program you are running on the switch. So if you want to auto-generate flow entries, the tool you use need to be aware of your program. If you just want to install a large number of flow entries for a given P4 program, you can write a script to generate `sX-runtime.json` or `commands.txt` with appropriate entries (randomly generated with the correct format). But if you find yourself writing a script, it is probably better to just establish a P4Runtime / Thrift connection and install the entries directly; there is no need for the `sX-runtime.json` / `commands.txt` step. **In the case of P4Runtime, your script can even consume the P4Info message generated by the compiler and generate arbitrary valid entries for any P4 program**. So you can keep your script generic. This can be useful if your end goal is to do fuzz testing on a P4 program or a set of P4 programs.

**Comment by antoninbas** [comment]
Closing this, since no update.
