### ISSUE TITLE
Problem with recirculate primitive 'std::out_of_range'

### ISSUE THREAD

**Issue by andreyqg** [p4lang/behavioral-model#807]
Hello, dears.

I'm using bmv2 simple_switch and I am trying to use **Primitive recirculate<headers>(hdr)** for recirculating a packet with a personalized header added,  so adding into a set of address, reading from a register. I am trying using a stack of headers for to copy from register to added header, like this:

struct headers {
    ethernet_t   ethernet;
    ipv4_t       ipv4;
    personalized_t      personalized;
    info_t[100] info;
}
  
After the egress pipeline and deparser end, in the first time, switch log shows this error below:

[16:49:19.817] [bmv2] [D] [thread 9650] [64.0] [cxt 0] Deparser 'deparser': end
[16:49:19.817] [bmv2] [D] [thread 9650] [64.0] [cxt 0] Recirculating packet
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at

I would know what means this error in this case, and the possible solution to this problem.

**Comment by jafingerhut** [comment]
I haven't seen that before, and have written small P4 programs to test recirculating of test packets within bmv2 simple_switch, but not ones that added headers before doing so.

Do you have a P4 program, whatever table entries you needed to add to cause a packet to be recirculated, and a sample packet, that exhibits this problem?

Do you know what version of p4lang/behavioral-model source code your simple_switch program was compiled from?

**Comment by andreyqg** [comment]
I solved this only using **_recirculate(meta)_**, I think than headers are included in packet recirculation, so only need recirculating and maintaining metadata values, for each packet recirculation. Now, recirculate primitive is working

**Comment by antoninbas** [comment]
It would still be helpful to have the P4 program (or even better the bmv2 JSON file) that caused the issue in the first place, since the bmv2 process is not supposed to crash and since is something we should investigate and fix.

**Comment by antoninbas** [comment]
Unfortunately @andreyqg never submitted the program, so I'm closing this issue. Let's re-open it if more information is provided.

**Comment by andreyqg** [comment]
Hi @antoninbas, unfortunately, I didn't save the JSON containing this error, however, here is my P4 program for possible helpful about clone and recirculate primitives used.

https://github.com/andreyqg/ddosmitigation
