### ISSUE TITLE
When installing p4c, make -j4 check has an error. If ebpf is already installed, what is the reason? If you ignore these errors, does it affect the normal use of p4c?

### ISSUE THREAD

**Issue by chenjy9581** [p4lang/behavioral-model#809]
The following tests FAILED:
	 17 - ebpf/testdata/p4_16_samples/valid_ebpf.p4 (Failed)
	 18 - ebpf/testdata/p4_16_samples/issue870_ebpf.p4 (Failed)
	 19 - ebpf/testdata/p4_16_samples/key-issue-1020_ebpf.p4 (Failed)
	 20 - ebpf/testdata/p4_16_samples/switch_ebpf.p4 (Failed)
	 21 - ebpf/testdata/p4_16_samples/action_call_ebpf.p4 (Failed)
	 22 - ebpf/testdata/p4_16_samples/two_ebpf.p4 (Failed)
	 23 - ebpf/testdata/p4_16_samples/lpm_ebpf.p4 (Failed)
	 24 - ebpf/testdata/p4_16_samples/bool_ebpf.p4 (Failed)
	 25 - ebpf/testdata/p4_16_samples/init_ebpf.p4 (Failed)
	 26 - ebpf/testdata/p4_16_samples/count_ebpf.p4 (Failed)
	 27 - ebpf/testdata/p4_16_samples/test_ebpf.p4 (Failed)
	 28 - ebpf/testdata/p4_16_samples/hit_ebpf.p4 (Failed)
	 29 - ebpf/testdata/p4_16_samples/key_ebpf.p4 (Failed)
	 30 - ebpf/testdata/p4_16_samples/stack_ebpf.p4 (Failed)
	 31 - ebpf/testdata/p4_16_samples/action_call_table_ebpf.p4 (Failed)
Errors while running CTest
CMakeFiles/check-all.dir/build.make:57: recipe for target 'CMakeFiles/check-all' failed
make[3]: *** [CMakeFiles/check-all] Error 8
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/check-all.dir/all' failed
make[2]: *** [CMakeFiles/check-all.dir/all] Error 2
CMakeFiles/Makefile2:170: recipe for target 'CMakeFiles/check.dir/rule' failed
make[1]: *** [CMakeFiles/check.dir/rule] Error 2
Makefile:212: recipe for target 'check' failed
make: *** [check] Error 2

**Comment by antoninbas** [comment]
These are the ebpf tests for the p4c compiler, so these failures are not related to this repository (p4lang/behavioral-model). I suggest that you re-open this issue in the appropriate repository: https://github.com/p4lang/p4c.

The ebpf tests are probably failing because of some missing dependencies, but ideally if the dependencies were not met in the first place these tests should not be run by `make check`...
