### ISSUE TITLE
Update googletest to a more recent version

### ISSUE THREAD

**Issue by antoninbas** [p4lang/behavioral-model#811]
We have been using the same version (currently checked-in under third-party) for 3+ years.

**Comment by redone9211** [comment]
i would like to contribute to this issue , can you let me know how i can solve it.

**Comment by antoninbas** [comment]
We use a copy of the googletest code in https://github.com/p4lang/behavioral-model/tree/main/third_party/gtest. It needs to be updated to a recent version. As part of this update, some changes may be required to existing bmv2 unit tests.

**Comment by OSdakrory** [comment]
if this issue is open, I'd like to contribute to this issue
