### ISSUE TITLE
Update grpc and protobuf versions

### ISSUE THREAD

**Issue by pkotikal** [p4lang/behavioral-model#812]
Hi @antoninbas,

Hope you are doing good.

Can we please update protobuf and grpc to the below versions?

grpc++ 1.17.0
grpc 7.0.0
protobuf 3.6.1

Thanks,
Prathima

**Comment by antoninbas** [comment]
I Prathima,

I'm fine with making these the officially supported versions of Protobuf / gRPC. There is really not much to do: you just need to 1) update the p4lang/third-party master & stable branches to install the correct dependencies in the base docker, and 2) update the necessary READMEs (PI and p4c come to mind, might be other places).

I actually tested some of the p4lang code with gRPC 1.17.2 and Protobuf 3.6.1 earlier this year. I even created a branch in p4lang/third-party which installs these versions (https://github.com/p4lang/third-party/tree/grpc-v1.17.2) so you just need to merge it into master & stable. After that, the docker images published to dockerhub and used for CI will include the desired versions. Ideally you would make sure that all the p4lang downstream projects can build & pass tests before merging. You may also want to check with @jnfoster as it may impact the tutorials repo.

**Comment by pkotikal** [comment]
Thanks a lot, @antoninbas. I will check with Nate before the merge.

**Comment by antoninbas** [comment]
See https://github.com/p4lang/third-party/pull/21
