### ISSUE TITLE
Is bmv2 support mcast_grp？

### ISSUE THREAD

**Issue by kphf1995cm** [p4lang/behavioral-model#813]

**Comment by jafingerhut** [comment]
Yes, it works.  See the description of mcast_grp on this page: https://github.com/p4lang/behavioral-model/blob/master/docs/simple_switch.md

Before your control plane software configures simple_switch, assigning a value of X to mcast_grp before the end of ingress processing will cause the packet to be dropped at the end of ingress.

If you use simple_switch_CLI to configure simple_switch, for example, there is detailed documentation on how to use its commands to configure multicast groups here: https://github.com/p4lang/behavioral-model/blob/master/docs/runtime_CLI.md#mc_dump-mc_mgrp_create-mc_mgrp_destroy-mc_node_associate-mc_node_create-mc_node_destroy-mc_node_dissociate

If you use P4Runtime to configure the switch, I would recommend reading the P4Runtime specification, the part focused on multicast groups.

**Comment by kphf1995cm** [comment]
Thanks for your suggestion!
