### ISSUE TITLE
Data plane notify control plane do something in bmv2?

### ISSUE THREAD

**Issue by kphf1995cm** [p4lang/behavioral-model#814]
For example, when implement Mac Learn Table in data plane,  require control plane forward mac and port flow table to bmv2.

**Comment by jafingerhut** [comment]
I have not gone through this example myself, but I have seen it recommended by others when this was asked about.  Here is how they described it:

"an example that implements l2 learning with copy to cpu and digest. The only problem is that uses the old controller API and not the P4Runtime:"
https://github.com/nsg-ethz/p4-learning/tree/master/exercises/04-L2_Learning
