### ISSUE TITLE
Some question about function clone_ingress_pkt_to_egress

### ISSUE THREAD

**Issue by liuhycn** [p4lang/behavioral-model#815]
Hello, I am a new P4 coder.
As we all know, after function `clone_ingress_pkt_to_egress`  , the `bmv2` switch will generate a cloned packet and send it to a specific egress pipeline. 
We can distinguish the origin packet and cloned packet by the value of `instance_type` in `standard_metadata`.
But I do not know the `instance_type` value of a `normal` packet , `ingressclone` packet and `egressclone` packet.
Could someone help me? Thx!!

**Comment by jafingerhut** [comment]
Search for the string instance_type on this page of documentation, and you will find the list of names, and a link to a snippet of code that you can copy and paste into your program that matches what is used by BMv2 simple_switch.
https://github.com/p4lang/behavioral-model/blob/master/docs/simple_switch.md
I would recommend bookmarking that page for the other potentially useful info it contains.
