### ISSUE TITLE
onos and BMV2

### ISSUE THREAD

**Issue by 1760947562** [p4lang/behavioral-model#827]
I installed onos2.2.0 and soft P4 switches respectively. Soft P4 switches include BMV2, P4c, protobuf, etc. How can I use onos to control BMV2? What command should I use to complete the connection between onos and BMV2? Do I need to start BMV2 before connecting?

**Comment by jafingerhut** [comment]
These questions seem best directed towards some forum for ONOS software.  They have very little to do with the behavioral-model code or program itself, and almost everything to do with how ONOS works.

**Comment by ccascone** [comment]
@jafingerhut is right, @1760947562 you should reach out to the onos-dev mailing list or Slack channels: https://onosproject.org/tools/

Also, a good place to learn how to use ONOS with BMv2 is this tutorial:
https://github.com/opennetworkinglab/ngsdn-tutorial

The tutorial uses stratum_bmv2, a version of the BMv2 simple_switch target with the [Stratum](https://github.com/stratum/stratum) agent on top to provide support for P4Runtime and gNMI (required by ONOS).
