### ISSUE TITLE
topology building using multiple simple_switch

### ISSUE THREAD

**Issue by sanooprajan** [p4lang/behavioral-model#828]
i couldn't find any argument with "simple_switch" command to instantiate multiple switches and connecting them. Couldn't find any dcoumentation as well.can someone help

**Comment by antoninbas** [comment]
Each bmv2 `simple_switch` process corresponds to one switch instance. So to create a topology with multiple switches (on Linux), you need to:
 * create as many veth pairs as you need links
 * start as many `simple_switch` processes as you need switches, with the correct command-line arguments for each one. For example, if you have a veth pair `(veth0, veth1)` and you want to use it to connect switchA to switchB, then you need to start one `simple_switch` process (switchA) with `-i veth0` and the other one (switchB) with `-i veth1`.

This all very tedious so we usually rely on Mininet to create topologies for us. There are multiple examples in the tutorials repository (https://github.com/p4lang/tutorials) that you can look at. I believe this is the script which takes care of creating the desired Mininet topology for each tutorial exercise: https://github.com/p4lang/tutorials/blob/master/utils/run_exercise.py. The script uses as input a JSON script describing the desired topology. Each exercise as its own topology, such as this one: https://github.com/p4lang/tutorials/blob/master/exercises/basic_tunnel/topology.json

**Comment by sanooprajan** [comment]
Thanks for your response. I am trying to make it work in my environment. There are a lot of places where tweaking is needed.

**Comment by antoninbas** [comment]
Closing this since no update. Please feel free to re-open if you have new updates or suggestions.
