### ISSUE TITLE
Error Running Make For simple_switch_grpc

### ISSUE THREAD

**Issue by mike2151** [p4lang/behavioral-model#829]
When I try to run the `make` command to build simple_switch_grpc, I get the following error:
`In file included from switch_runner.cpp:22:0:
./../../include/bm/bm_sim/logger.h:36:10: fatal error: bm/config.h: No such file or directory`

I am trying to do this with Docker and I currently use Docker Base Image in the repo. Any idea what is going wrong?

**Comment by jafingerhut** [comment]
I do not know what is going wrong.  I do know that at least on a freshly installed Ubuntu 16.04 or 18.04 Linux machine, without docker, the scripts described at the link below can compile and install simple_switch_grpc just fine.  I suspect it might be straightforward to adapt them for use with docker by someone more familiar with docker than I am, but have not tried: https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md
