### ISSUE TITLE
Error in Make while building simple_switch_grpc and thrift

### ISSUE THREAD

**Issue by anandakella** [p4lang/behavioral-model#830]
Im trying to build my own vagrant and docker images for the behavioral model. The build is failing due to the following reason 

switch_runner.cpp: In constructor ‘sswitch_grpc::SimpleSwitchGrpcRunner::SimpleSwitchGrpcRunner(bool, std::__cxx11::string, bm::DevMgrIface::port_t, std::__cxx11::string, bm::DevMgrIface::port_t)’:
switch_runner.cpp:509:22: warning: ‘static void pi::fe::proto::DeviceMgr::init(size_t)’ is deprecated [-Wdeprecated-declarations]
   DeviceMgr::init(256);
                      ^
In file included from switch_runner.cpp:28:0:
/usr/local/include/PI/frontends/proto/device_mgr.h:93:15: note: declared here
   static void init(size_t max_devices);
               ^~~~
Makefile:794: recipe for target 'switch_runner.lo' failed
make[2]: *** [switch_runner.lo] Error 1
make[2]: Leaving directory '/tmp/behavioral-model/targets/simple_switch_grpc'
Makefile:888: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/behavioral-model/targets/simple_switch_grpc'
Makefile:547: recipe for target 'all' failed
make: *** [all] Error 2

Here is the code I used for building simple_switch_grpc

cd targets/simple_switch_grpc
 ./autogen.sh
 ./configure --with-thrift
  make -j${NUM_CORES}
  sudo make install
  sudo ldconfig

Im using latest Ubuntu18.04 images. I build grpc from the master branch and installed python modules using pip for grpcio.

**Comment by jafingerhut** [comment]
Starting with a freshly installed Ubuntu 18.04 Linux system, the two shell scripts linked from the instructions below install behavioral-model simple_switch and simple_switch_grpc, and also the p4c compiler, and all other software that they depend upon: https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md

**Comment by antoninbas** [comment]
@anandakella it seems that the version of bmv2 you are trying to build is less recent than the version of PI you have installed. I suggest that you clone the latest version of bmv2 and try again. 

I'm surprised this causes the build to fail though, we are not supposed to treat warnings as errors by default. Could you share the full `g++` command-line (it should appear a couple of lines earlier in the logs)? Is there no other error in the logs?

**Comment by anandakella** [comment]
Im trying with latest master branch of bmv2, I was hitting the same issue as reported earlier. Let me try it again and get back to you

**Comment by jafingerhut** [comment]
I tested again (without using vagrant or docker, just Ubuntu 18.04 Linux) with the shell script mentioned in my earlier comment, and it works with latest versions of PI, behavioral-model, and p4c as of yesterday (plus the particular versions of protobuf, graph, etc. that it installs).

**Comment by anandakella** [comment]
Andy I'm going through your script to see where things went wrong. Will use your script run it on my virtual machine and let you know.

**Comment by antoninbas** [comment]
No update for a while, closing the issue.

**Comment by bhullarsukh96** [comment]
i am also facing the same issue. please help me to resolve this issue.
![image](https://user-images.githubusercontent.com/3541469/163574282-f1aba103-8c80-4f27-b73f-630f1e9726d6.png)

**Comment by jfingerh** [comment]
Copying and pasting a comment I made 3 years ago, which is still relevant today, as I still test my scripts every month and make changes so they keep working: Starting with a freshly installed Ubuntu 18.04 or 20.04 Linux system, the two shell scripts linked from the instructions below install behavioral-model simple_switch and simple_switch_grpc, and also the p4c compiler, and all other software that they depend upon: https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md
