### ISSUE TITLE
Adding arithmetic operation with runtime index fails simple_switch testing

### ISSUE THREAD

**Issue by hesingh** [p4lang/behavioral-model#846]
One would need the p4c code with support for runtime index to reproduce this issue.  Use the following repo and P4 program.

1. p4 compiler:  https://github.com/hesingh/p4c
2. P4 program - see attached file.  Add the file to p4c/testdata/p4_16_samples/ and then run cmake. Build p4c and test. 
3. Copy `runtime-index.stf` from https://github.com/hesingh/p4c/testdata/p4_16_samples/

[runtime-index-bmv2-p4.txt](https://github.com/p4lang/behavioral-model/files/4081514/runtime-index-bmv2-p4.txt)

This is how I test as shown in a test log below.  I have an arrow "<===" included below to see the failure. 

```
hemant@ubuntu:/tmp/p4c/build$ bmv2/testdata/p4_16_samples/runtime-index-bmv2.p4.test -v
Writing temporary files into  ./tmp7vc0av7e
Executing  ./p4c-bm2-ss -o bmv2/testdata/p4_16_samples/runtime-index-bmv2.json /tmp/p4c/testdata/p4_16_samples/runtime-index-bmv2.p4
Exit code  0
Check for  /tmp/p4c/testdata/p4_16_samples/runtime-index-bmv2.stf
Running model
Running simple_switch --log-file switch.log --log-flush --use-files 0 --thrift-port 10087 --device-id 997 -i 0@pcap0 ../bmv2/testdata/p4_16_samples/runtime-index-bmv2.json
Calling target program-options parser
Adding interface pcap0 as port 0 (files)
Running simple_switch_CLI --thrift-port 10087
STF Command: packet 0 ca0107fc001c1111111111110800 02 010203 040404
STF Command: expect 0 CA0107FC001C1111111111110800 02 050203 040405 $
STF Command: packet 0 ca0107fc001c1111111111110800 00 010203 040404
STF Command: expect 0 CA0107FC001C1111111111110800 00 050203 050404 $
Obtaining JSON from switch...
Error when requesting JSON config from switch  <===
*** simple_switch died with return code -11
*** CLI process failed with exit code 1
Execution completed
Removing ./tmp7vc0av7e
*** Test failed
```

Alternatively, generate json using `p4c-bms-ss` as shown below:

`hemant@ubuntu:/tmp/p4c/build$ ./p4c-bm2-ss --std p4-16 ../testdata/p4_16_samples/runtime-index-bmv2.p4 -o tmp.json`

Then the json output can be used with simple_switch.  Using simple_switch, I don't see any obvious error. See test log below.

```
hemant@ubuntu:/tmp/p4c/build$ simple_switch tmp.json --log-console
Calling target program-options parser
[11:04:19.367] [bmv2] [D] [thread 32435] Set default default entry for table 'tbl_runtimeindexbmv2l67': runtimeindexbmv2l67 - 
[11:04:19.367] [bmv2] [I] [thread 32435] Starting Thrift server on port 9090
[11:04:19.368] [bmv2] [I] [thread 32435] Thrift server was started

```

If one comments out the code on line 73 of the P4 program, then test (`bmv2/testdata/p4_16_samples/runtime-index-bmv2.p4.test -v`) goes past obtaining JSON from the switch.

**Comment by hesingh** [comment]
Also see 

https://github.com/p4lang/p4c/pull/2139#issuecomment-575936744

**Comment by antoninbas** [comment]
I'm not sure what you expect from this issue. As you noted in https://github.com/p4lang/p4c/pull/2139#issuecomment-575936744, the JSON you generated is invalid, as it includes a malformed "expression" node. You should fix your p4c-bmv2 backend patch to handle this case properly.

I understand that it may be a bit tricky to handle both cases (static index and dynamic index) in a uniform manner in the backend code, since they translate to very different bmv2 JSON objects. When accessing a field in a header stack / a header in a header union stack, you have to determine whether the stack reference is static or dynamic. If static, you have to use `access_field` / `access_union_header`.

I think the 2 cases `stack[hdr.field]` vs `stack[hdr.field + 1]` should be treated uniformly. I don't see anything preventing it. It's the same thing as handling an operand for any binary expression.

**Comment by hesingh** [comment]
It's not an issue with static vs. dynamic index into a header.  The issue is when outer JSON has binary operations such as "+' or "&", the JSON format is 

```
"type" : "expression",
 "value" : {
       "op" : "&",
 "left" : {
"type" : "expression",
"value" : {
     "op" : "&",
"left" : {
```

As one can see above there is only one (type, value)

But when access_field is added as inner JSON, one has two (type, value)'s.  There should be only one and then simple_switch accepts the JSON.

```
 "type" : "expression",
 "value" : {
 "type" : "expression",
 "value" : {
  "op" : "access_field",
 "left" : {
```

The reason runtime index has two (type, value) in JSON is because when there is only runtime index to generate in JSON (no outer JSON), then the format uses two (type, value) as shown in your runtime_index_LV.json.

Changing bmv2 backend code is tricky, because, first, the runtime index JSON is generated and then the outer binary operation JSON is generated.  So, it's too late to remove one (type, value) from the innder runtime index.

**Comment by antoninbas** [comment]
I don't understand what is outer JSON vs inner JSON.

I think the JSON format is pretty consistent. The outer most "operator" node needs to be wrapped in an extra type-value "expression" object (for legacy reasons) but that's the only surprise:
```
{
    "op" : "assign",
    "parameters" : [
        {
            "type" : "expression",
            "value": {
                "type": "expression",
                "value": {
                    "op": "access_field",
                    "left": {
                        "type": "expression",
                        "value": {
                            "op": "dereference_header_stack",
                            "left": {
                                "type": "header_stack",
                                "value": "h2"
                            },
                            "right": {
                                "type": "field",
                                "value": ["h1", "idx"]
                            }
                        }
                    },
                    "right": 0
                }
            }
        },
        {
            "type" : "expression",
            "value": {
                "type": "expression",
                "value": {
                    "op": "+",
                    "left": {
                        "type" : "field",
                        "value" : ["h1", "v"]
                    },
                    "right": {
                        "type" : "hexstr",
                        "value" : "0x0000004d"
                    }
                }
            }
        }
    ]
}
```
Honestly, I think the example above says it all.

I really don't understand why generating "the runtime index JSON" as you put it is a special case at all. When you generate it, it should *not* be wrapped.

**Comment by hesingh** [comment]
This is the output from the PR with arrows showing outer and inner JSON.  I understand what you are saying.   I will have to change bmv2 backend code.

```
{
              "type" : "expression",  
              "value" : {
                "type" : "expression", <=== outer JSON 
                "value" : {
                  "op" : "&",
                  "left" : {
                    "type" : "expression",  <=== outer JSON 
                    "value" : {
                      "op" : "+",
                      "left" : {
                        "type" : "expression",  <===  inner JSON
                        "value" : {
                          "type" : "expression", <=== inner JSON
                          "value" : {
                            "op" : "access_field",
                            "left" : {
                              "type" : "expression",
                              "value" : {
                                "op" : "dereference_header_stack",
                                "left" : {
                                  "type" : "header_stack",
                                  "value" : "pool"
                                },
                                "right" : {
                                  "type" : "field",
                                  "value" : ["ml", "idx"]
                                }
                              }
                            },
                            "right" : 0
                          }
                        }
                      },
                      "right" : {
                        "type" : "hexstr",
                        "value" : "0x01"
                      }
                    }
                  },
                  "right" : {
                    "type" : "hexstr",
                    "value" : "0xff"
                  }
                }
              }
            }
```

**Comment by hesingh** [comment]
Regarding "The outer most "operator" node needs to be wrapped in an extra type-value "expression" object (for legacy reasons)"

Would you know what code in `p4c/backends/bmv2/` adds the extra type-value "expressions".   I looked in `common/expression.cpp` but don't find anything obvious to me.

**Comment by hesingh** [comment]
It would really help if you could find the P4 program that generated this json you pointed to me in the past.

https://github.com/p4lang/behavioral-model/blob/master/tests/testdata/unions_e2e_options_count.json#L312

**Comment by antoninbas** [comment]
@hesingh there is no P4 program, I wrote it by hand to test my bmv2 implementation. This is why there is the `"compiler": "HAND_WRITTEN"` metadata tag at the top. But the expression you pointed to in the file would correspond to the following P4 assignment (in a parser state):
```
my_metadata.option_counter = my_metadata.option_counter - 1;
```

The `wrap` boolean parameter for the `convert` function determines whether the "top-level" expression node gets wrapped: https://github.com/p4lang/p4c/blob/master/backends/bmv2/common/expression.cpp#L705. In retrospect, I wish I had not called both types of nodes "expression" since they are not the same... Notice how the top one doesn't have an "op" field in the "value" object.

There is a comment that explains the "wrapping": https://github.com/p4lang/p4c/blob/master/backends/bmv2/common/expression.cpp#L731. The comment says that stack fields also have to be wrapped. I'm a bit surprised by this comment, it doesn't match my understanding of the bmv2 code, but anyway you can ignore that.

**Comment by hesingh** [comment]
@antoninbas Thanks much.  I thought since the bmv2 backend JSON code was checked in, some P4 test program would exist in p4_16_samples.  Poking around some -bmv2.p4 programs, I couldn't find any.  However, with your guidance above, I am all set.
