### ISSUE TITLE
simple_switch causes std::out_of_range exception with runtime index stack processing

### ISSUE THREAD

**Issue by hesingh** [p4lang/behavioral-model#849]
The bottom of this note includes P4 and STF programs, and p4c repo used to reproduce this issue.

The line of P4 code that causes the problem is:

`  hdr.pool[hdr.ml.idx].val = hdr.vector[0].e;`

Specifically, the left-hand side of the assignment statement above causes the problem.  `pool` is a header stack of size 3 and used in `headers`.   The STF packet has set hdr.ml.idx to 2.  Note `val` in header `pool` has an offset of 8 from header start. 

I added debugged code to src/bm_sim/expressions.cpp in `eval_()` where `get_field` is used.  These are the diffs for debugged code:

```
diff --git a/src/bm_sim/expressions.cpp b/src/bm_sim/expressions.cpp
index 8c22de4..9674445 100644
--- a/src/bm_sim/expressions.cpp
+++ b/src/bm_sim/expressions.cpp
@@ -30,6 +30,7 @@
 #include <algorithm>  // for std::max
 
 #include <cassert>
+#include <iostream>
 
 namespace bm {
 
@@ -514,6 +515,7 @@ Expression::eval_(const PHV &phv,
     const auto &op = ops[i];
     switch (op.opcode) {
       case ExprOpcode::LOAD_FIELD:
+        std::cout << "LOAD_FIELD: " << op.field.header << " offset " << op.field.field_offset << std::endl;
         temps->push_data(
             &phv.get_field(op.field.header, op.field.field_offset));
         break;
@@ -527,6 +529,7 @@ Expression::eval_(const PHV &phv,
         break;
 
       case ExprOpcode::LOAD_LAST_HEADER_STACK_FIELD:
+        std::cout << "LOAD_LAST_HEADER_STACK_FIELD: \n";
         temps->push_data(
             &phv.get_header_stack(op.stack_field.header_stack).get_last()
               .get_field(op.stack_field.field_offset));
@@ -563,6 +566,7 @@ Expression::eval_(const PHV &phv,
 
       case ExprOpcode::ACCESS_FIELD:
         rh = temps->pop_header();
+        std::cout << "ACCESS_FIELD: " << rh->get_name() << " offset " << op.field_offset << std::endl;
         temps->push_data(&rh->get_field(op.field_offset));
         break;
```

Then I ran `bmv2/testdata/p4_16_samples/runtime-index-bmv2.p4.test -v`.  A portion of the simple_switch log is included below.  After the "ACCESS_FIELD" debugged message is printed, the `std::out_of_range exception` occurs.  Clearly header stack size of 3 is not correctly matched for std::vector size.

```
[14:38:58.435] [bmv2] [T] [thread 111942] [0.0] [cxt 0] /tmp/p4c/testdata/p4_16_samples/runtime-index-bmv2.p4(77) Primitive hdr.pool[hdr.ml.idx].val = hdr.vector[0].e
LOAD_FIELD: 3 offset 0
ACCESS_FIELD: pool[2] offset 8
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 8) >= this->size() (which is 3)
```

Please use this repo to build p4c.

https://github.com/hesingh/p4c

The p4 and stf programs used to test are attached. Copy the two files to p4c/testdata/p4_16_samples/ and then run `cmake ..` and build p4c. 

[runtime-index-bmv2-p4.txt](https://github.com/p4lang/behavioral-model/files/4088265/runtime-index-bmv2-p4.txt)
[runtime-index-bmv2-stf.txt](https://github.com/p4lang/behavioral-model/files/4088267/runtime-index-bmv2-stf.txt)

**Comment by antoninbas** [comment]
Based on your program, `val` has offset 1 (it is the second field in the `aggregator_t` header type), not offset 8.

**Comment by antoninbas** [comment]
@jafingerhut explained to you what the offset was in this comment: https://github.com/p4lang/p4c/pull/2139#issuecomment-575302589

**Comment by hesingh** [comment]
Ah, sorry, I missed that offset is not in bits but in bytes.  Let me change my p4c code and re-test - thanks!

**Comment by antoninbas** [comment]
It's neither in bits not in bytes.
It's the **index** of the field in the field list.

**Comment by hesingh** [comment]
Ah, right, I saw Andy's comment and changed the code.  Sorry about bits and bytes too.
