### ISSUE TITLE
Testing arithmetic expression with runtime index causes crash in simple_switch

### ISSUE THREAD

**Issue by hesingh** [p4lang/behavioral-model#850]
I have attached a json file and the P4 program that generated the JSON. The P4 code is testing only one line of code in the ingress apply block.  The p4c code being used is new changes over what exists at

https://github.com/hesingh/p4c

Anyway, if the private changes generated correct JSON, then the issue is with behavioral-model software.  If not, I have to fix the JSON. 

I get std::out_of_range exception with a bogus value.

```
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 18446744073709551615) >= this->size() (which is 8)
```

[tmp-json.txt.txt](https://github.com/p4lang/behavioral-model/files/4099810/tmp-json.txt.txt)
[runtime-index-2-bmv2-p4.txt.txt](https://github.com/p4lang/behavioral-model/files/4099816/runtime-index-2-bmv2-p4.txt.txt)
[runtime-index-2-bmv2.stf.txt](https://github.com/p4lang/behavioral-model/files/4099856/runtime-index-2-bmv2.stf.txt)

**Comment by jafingerhut** [comment]
What packet are you testing with?

If the value of the expression `hdr.ml.idx2 ^ 0x07` is not in the range 0 to 7, then an out of range exception is expected from simple_switch.

**Comment by hesingh** [comment]
I just attached the STF file which includes the packet.

**Comment by jafingerhut** [comment]
I will double check that STF file.  I had no way to test it before, so would not be surprised if there are mistakes in there that could lead to an out of range header stack index at run time.

**Comment by hesingh** [comment]
Also, I commented out the first packet and still get the same error.   Let me try to check in my latest code changes which pass runtime index tests without arithmetic expressions but is supposed to support arithmetic expressions as well.

**Comment by hesingh** [comment]
I just checked in new code.  Please grab latest code from https://github.com/hesingh/p4c.  thanks.

**Comment by antoninbas** [comment]
You are computing `(int<8>) 0xb8 ^ 0x07`, which according to the P4 spec is a negative number. I think you should try to do a little bit more investigation before opening issues like this.
