### ISSUE TITLE
How to debug stratum_bmv2 using eclipse

### ISSUE THREAD

**Issue by drobinkent** [p4lang/behavioral-model#853]
I am using the bmv2 as p4 switch simulator. I have followed the steps described here [https://github.com/stratum/stratum/blob/master/stratum/hal/bin/bmv2/README.md](url) .

Whenever I try to debug a bmv2 switch (running as mininet switch) using eclipse it never succeeds. threads of the bmv2 switch can be seen in Eclipse. But I can not actually debug the bmv2 codes. I tried to attach the stratum_bmv2 binary as remote process to be debugged in eclipse. 

Seems I am missing something. Is there any other way to debug the bmv2? Or any other better way can be used to debug it?

**Comment by jafingerhut** [comment]
I suspect the answer to your question is pretty much completely dependent upon how the stratum project starts the simple_switch / simple_switch_grpc process, i.e. what command line options it gives, whether it directs simple_switch_grpc to write to log files or not, what directory and file name it specifies for them to be written into, etc.  simple_switch_grpc does not mandate where these things go -- it follows whatever it is told to do, which can vary from environment to environment.

I would recommend creating an issue on this project asking your question: https://github.com/stratum/stratum

**Comment by jafingerhut** [comment]
Are you trying to debug the C++ code used to implement bmv2, or a P4 program running on it?  My answer was assuming you were trying to debug a P4 program running on bmv2.

**Comment by antoninbas** [comment]
I'm going to close this since there is no update. `stratum_bmv2` includes a lot of code besides bmv2, and unless you are also having issues with the `simple_switch` or `simple_switch_grpc` binaries, I think this is out-of-scope of this repo.
