### ISSUE TITLE
What part of value_set control plane API implemented, both Thrift and P4Runtime?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/behavioral-model#854]
There is no urgency on this.  Mainly curious due to some recent bug fixing in p4c bmv2 back end related to value_set.

Is there an already-implemented Thrift API to add/delete entries in a parser value set?

Same question for P4Runtime API.

If it is partial, any quick description of what parts should be there, and which are not yet?

Also it appears that BMv2 JSON files have no mechanism to indicate the number of entries declared in the P4 program for a parser value set, but there is such a field defined in P4Info files.  Is that an oversight?  By design somehow?

It also seems that the only info in the BMv2 JSON file when there are multiple fields in a struct as the type of element in the value_set, is the total width in bits, not the names and widths of individual fields, so that would imply to me that unless the Thrift API is reading the P4Info file (I think it does not?), there isn't enough information to represent those kinds of parser value sets for the Thrift API.

**Comment by antoninbas** [comment]
P4Runtime is easy: there is no support for value sets in the p4lang/PI implementation of P4Runtime. Any attempt to write / read a value set entry will get you the `UNIMPLEMENTED` error code.

There is a Thrift API (https://github.com/p4lang/behavioral-model/blob/master/thrift_src/standard.thrift#L661) and it is implemented correctly. It only supports exact matching for the values included in the value set, so the following example included in the spec is not supported:
```
struct vsk_t {
    @match(ternary)
    bit<16> port;
}
value_set<vsk_t>(4) pvs;
select (p.tcp.port) {
    pvs: runtime_defined_port;
    _: other_port;
}
```
It does support a static mask, so in theory the following example should be supported, though I am not actually sure it is valid P4_16 (if you have some cycles and want to check, I would love to know):
```
typedef bit<16> vsk_t;
value_set<vsk_t>(4) pvs;
select (p.tcp.port) {
    pvs &&& 0xF0F0: runtime_defined_port;
    _: other_port;
}
```
You may have noticed however that **the runtime_CLI does not integrate with the Thrift API**, which makes it harder to test the functionality. I can take a look at adding support.

Finally, your last 2 questions:
 * the number of entries is not represented in the JSON: bmv2 will let you grow your PVS as much as your memory allows. I agree we should change that to make it consistent with match tables.
 * PVS with multiple-fields: they are supported; the Thrift API indeed uses compressed values (and so will the CLI) for ease of implementation (which I agree is a bit tedious for the user) but we can split these values inside bmv2 by looking at the type of the expression being selected on in the parser state.

**Comment by jafingerhut** [comment]
Regarding your question about P4_16 code like this:
```
    value_set<bit<32>>(4) pvs;

    state start {
        b.extract(p.data);
        transition select(p.data.da) {
            pvs &&& 0x0000_00f0 : accept;
            0x810 : foo;
        }
    }
```
I tried out a test program (attached) and the command `p4test pvs-bitstring-with-mask-bmv2.p4`, which includes no p4c back end code at all, gives this error message:
```
$ p4test pvs-bitstring-with-mask-bmv2.p4
pvs-bitstring-with-mask-bmv2.p4(23): [--Werror=type-error] error: &&&: cannot be applied to pvs of type set<bit<32>>
            pvs &&& 0x0000_00f0 : accept;
            ^^^
```

I did a quick scan through some parts of the P4_16 language spec related to value_set and key select expressions in parser select expressions, and it does appear from what is written there that `pvs &&& 0x1` is not defined to have any meaning in the language.

Section 12.6 "Select expressions" says: "Given a type T for the type parameter of the value set, the type of the value set is set<T>."

For example, Section 8.12.3 "Masks" says: "The infix operator &&& takes two arguments of type bit<W>, and creates a value of type set<bit<W>>."

So it appears to me that code is undefined, and an error message should be given.

**Comment by jafingerhut** [comment]
Attaching a test P4 program mentioned in my previous comment here, since I forgot to attach it there.

[pvs-bitstring-with-mask-bmv2.p4.txt](https://github.com/p4lang/behavioral-model/files/4145882/pvs-bitstring-with-mask-bmv2.p4.txt)

**Comment by jafingerhut** [comment]
@antoninbas I do not see any test P4_14 programs that contain a parser that uses `my_parser_value_set &&& 0xf0 : next_parser_state`, nor with `&&&` replaced by `&`.

I also do not see that syntax mentioned as legal in the P4_14 language spec, version 1.0.5.

Might this be an extension added in the implementation that never got into the specs?

Do you have a P4_14 test program handy, or would be willing to cook up a tiny one for testing purposes, that compiles using p4c?

**Comment by jafingerhut** [comment]
I tried similar syntax in a P4_14 program with lines like `pvs &&& 0x0ff0 : next_parser_state` and `pvs & 0x0ff0 : next_parser_state` in the parser, and both give errors from `p4test --std p4-14 file.p4`.

I even tried with the old p4c-bm code, and it gave syntax errors for both of those as well.

Maybe only implemented in some proprietary P4_14 compiler somewhere?

**Comment by antoninbas** [comment]
In P4_14 syntax, it would have been `pvs mask 0x0ff0` IIRC.

That being said, it doesn't seem to be supported by the p4-hlir / p4c-bm toolchain, so unless I made it up, it may indeed have been a proprietary extension to P4_14. I doubt I made it completely up - I would not have gone through the trouble of implementing it in bmv2 for nothing :). It is also a very convenient way to keep PVS sizes small, for targets which implement parser transitions using TCAMs.

**Comment by jafingerhut** [comment]
`p4c --std p4-14 --target bmv2 --arch v1model file.p4` accepts the syntax `pvs mask 0x0ff0 : next_parser_state`, but produces a BMv2 JSON file exactly the same as when you write `pvs : next_parser_state`.

Using the command `p4test --std p4-14 file.p4 --pp file_p416.p4` accepts both, but produces a P4_16 program that is identical in both cases.

So it seems that either p4c accepts it but silently ignores it, or it accepts it, pays attention to it for some part of the compiler's transformation, but then forgets it before producing a BMv2 JSON file or P4_16 translated program.  I haven't looked at the compiler internals to try to figure out why or where it is getting lost, but would not be surprised if it was very early after reading the P4_14 code.

I can file an issue for this with p4c to see if anyone thinks it ought to behave differently.

**Comment by jafingerhut** [comment]
https://github.com/p4lang/p4c/issues/2188

**Comment by hesingh** [comment]
> In P4_14 syntax, it would have been `pvs mask 0x0ff0` IIRC.
> 
> That being said, it doesn't seem to be supported by the p4-hlir / p4c-bm toolchain, so unless I made it up, it may indeed have been a proprietary extension to P4_14. I doubt I made it completely up - I would not have gone through the trouble of implementing it in bmv2 for nothing :). It is also a very convenient way to keep PVS sizes small, for targets which implement parser transitions using TCAMs.

Sorry, I don't understand what work was done in bmv2 backend to support  P4-14 code in `pvs mask 0x0ff0`.  The reason is because the code is converted to `pvs` by the time the backend receives the IR.  I am trying to understand where did the p4-14 `mask 0x0ff0` get inserted in any IR or is it skipped?

**Comment by jafingerhut** [comment]
@hesingh That is a question for the p4c compiler writers.  It is irrelevant to the behavioral-model code how it gets into the BMv2 JSON file.

**Comment by jafingerhut** [comment]
Sorry, not trying to cut off your questions.  Just that it seems like first we may want to understand what the behavior of this language construct even is (which is the point of questions/comments on this issue: https://github.com/p4lang/p4c/issues/2188

and also perhaps in parallel, understand how a non-null mask on a pvs in the BMv2 JSON file is handled internally inside of bmv2, by digging into what behavioral-model code already does today with a non-null mask for a pvs.

I say that, because it is at least possible that those two things might not even match up with each other.  They probably do, but in case not, the time when you are adding support for something is a good time to verify that their behaviors match up.

**Comment by hesingh** [comment]
@jafingerhut Understood, no apologies needed.  I am digging into p4-14 p4c code right now.

**Comment by antoninbas** [comment]
I'm closing this. The discussion has diverged from the original topic and now belongs to https://github.com/p4lang/p4c/issues/2188 as Andy pointed out.
