### ISSUE TITLE
Enforce parser value set size limit in bmv2

### ISSUE THREAD

**Issue by antoninbas** [p4lang/behavioral-model#856]
When declaring a `value_set` in P4_16, one must specify a maximum number of entries. We should include this number in the bmv2 JSON and enforce it, like we do for the match table implementation. If the JSON attribute is missing, we will keep implementing the default behavior.

**Comment by hesingh** [comment]
I didn't want p4c to be behind.  At this public repo, I added "size" to parse_vset JSON.

https://gitlab.com/hemant_mnkcg/p4c-valueset

This is a snippet to generated JSON.

```
"parse_vsets" : [
    {
      "name" : "MyParser.pvs",
      "id" : 0,
      "compressed_bitwidth" : 32,
      "size" : 4
    }
  ],
```

The repo also includes the fix to compute bitwidth for struct used by parse_vset.  Also included is the fix to have parse_vset mask set to null.
