### ISSUE TITLE
Support non-exact matches for value_sets

### ISSUE THREAD

**Issue by antoninbas** [p4lang/behavioral-model#857]
As per the P4_16 specification, the `@match` annotation can be used when declaring a struct to be used as the type for a `value_set`:
> If the value_set takes a struct as type parameter, the runtime API can use the struct field names to name the objects in the value set. The match type of the struct field is specified with the `@match` annotation. If the `@match` annotation is not specified on a struct field, by default it is assumed to be `@match(exact)`. A single non-exact field must be placed into a struct by itself, with the desired `@match` annotation.

We should try to support this in the bmv2 implementation. At the moment we only support exact matches. This is probably a significant change however, which will require a JSON format update.

**Comment by jafingerhut** [comment]
I have no near-term plans to tackle this, but wanted to point out that there is significant similarity between parser value sets and P4 tables, when the `@match` annotation is supported.

+ Both can have any number of match fields, where each match field has an independent name, width in bits, and match_kind.
+ Both support the ability to add and remove entries at run time, via a control plane API.  I do not know whether anyone cares to support modify of an existing entry in a parser value set, but I do not see any fundamental reason why it could not be supported, if someone wanted to implement it.

The primary difference is that unlike a P4 table, the entries in a parser value set have no action, nor action parameters.

So it seems there is an opportunity to share at least some code that implements these capabilities in P4 tables, when implementing parser value sets.
