### ISSUE TITLE
Error when making behavioral-model 

### ISSUE THREAD

**Issue by JWQQ** [p4lang/behavioral-model#868]
When I execute the following instruction：

> cd behavioral-model
   ./antogen.sh
   ./configure 
   sudo make -j1
I just got the following result：
![image](https://user-images.githubusercontent.com/53334584/75166317-a8dfc100-575e-11ea-877d-cf3b6e46fa9b.png)
What can I do to solve this problem?
I would appreciate it if you could solve my problem.

**Comment by jafingerhut** [comment]
There are several other software packages that must be installed on a system before you can install behavioral-model, as described in its README instructions, and some of those prerequisites also have their own list of steps required to install them.  A while ago I carefully went through and created a bash script that installs all of p4c, behavioral-model, PI, mininet, and all of their prerequisites.  You can follow the instructions here to use that script, if you start from a freshly installed Ubuntu 16.04 or 18.04 Linux system: https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md

Sorry, I do not know every error message that results from missing each of the possible steps you may have skipped.  There are too many ways to do it wrong, and only a few to do it correctly, hence the script above.

**Comment by JWQQ** [comment]
Thank you very much anyway, I will try your solution on a new system, thanks again!

**Comment by antoninbas** [comment]
Closing this. Feel free to re-open if you are still facing issues.

(The complete list of dependencies is also included in the README).

**Comment by JWQQ** [comment]
I tried reloading the dependencies and re-compiling, but the error still existed.

**Comment by jafingerhut** [comment]
Did you try the shell script I linked above, but not on your existing system, but instead starting from a new freshly installed Ubuntu 16.04 or 18.04 Linux system?  That script works for a freshly installed system, and probably for a system with _some_ other software installed on it, but I cannot test that script with all possible combinations of software preinstalled on it, any of which might conflict with what it installs.

**Comment by JWQQ** [comment]
I just updated the dependencies without replacing the existing system, then I will try to install it again on a freshly installed system.Thank you.
