### ISSUE TITLE
how to control pck enter into specfic queue of one port.

### ISSUE THREAD

**Issue by zqz-net** [p4lang/behavioral-model#875]
one of port of simple switch has 8 priority queue?
I want my p4 program to control the pck enter into specific queue.
for example, pck 1 to queue 1, pck 2 to queue 8.Is there any way to use p4 to achieve this?

**Comment by antoninbas** [comment]
Input ports don't have priority queues in simple_switch.

Priority queueing can be enabled for simple_switch (https://github.com/p4lang/behavioral-model/blob/master/targets/simple_switch/simple_switch.h#L37) for the queueing logic between the ingress & egress pipelines. In which case, you need to can select a specific priority queue by setting the `standard_metadata.priority` field in ingress: https://github.com/p4lang/p4c/blob/master/p4include/v1model.p4#L122

**Comment by Crystal-wxy** [comment]
> Input ports don't have priority queues in simple_switch.
> 
> Priority queueing can be enabled for simple_switch (https://github.com/p4lang/behavioral-model/blob/master/targets/simple_switch/simple_switch.h#L37) for the queueing logic between the ingress & egress pipelines. In which case, you need to can select a specific priority queue by setting the `standard_metadata.priority` field in ingress: https://github.com/p4lang/p4c/blob/master/p4include/v1model.p4#L122

i replace two file in P4 Tutorial 2019-04-25.ova but it doesn`t work
p4c-bm2-ss --p4v 16 "s_edge.p4" -o "s_edge.p4.json"
s_edge.p4(141): [--Werror=type-error] error: Field priority is not a member of structure struct standard_metadata;
what should i do to make it work

**Comment by antoninbas** [comment]
`standard_metadata.priority` was added to v1model.p4 on April 25th 2019 (https://github.com/p4lang/p4c/pull/1704): your tutorial OVA image may not include this change. You can locate the v1model.p4 file and check.
