### ISSUE TITLE
How to print the Table contents, Meter in Real time when running the emulation using mininet

### ISSUE THREAD

**Issue by chagnti** [p4lang/behavioral-model#876]
Hello,

This might be silly question to ask as i have started exploring recently and would be needing to monitor the table contents for simple experiment.

I would see there may be two ways to do that by looking at the code modules.one is, running thrift server and use runtime_CLI.py and other way is using nanomsg_client.py. However, I have not been succeeded any of these two ways so far. Can you please throw some light on ways to perform this?

I am trying to look at the P4 program flow by running the nanomsg_client.py script when the experiment is running. But, I would not be able to see any messages printed in the console. Did i miss something? I know i am just giving very high level description of my issues. But, would like to provide more details if needed. thanks.

Raj

**Comment by jafingerhut** [comment]
When you say "monitor the table contents", do you mean one of these things?

(a) You want some automated program that reads the contents of the table periodically, e.g. every 1 second, and shows that on the screen in a terminal window, until you force it to stop.

(b) You want to be able to type a command to show the contents of table "T1" right now, and then not do anything else until you type another command.  The later commands might be to again run a command that shows the contents of table "T1", or it might be a different command.

(c) Something else?

If you want (b), then the program `simple_switch_CLI` can do that, and a command you can do is, if I remember correctly `table_dump T1`

If you want (a), then you need to write your own program to do that, using either the Thrift API or the P4Runtime API to send the appropriate request messages to the `simple_switch` or `simple_switch_grpc` process.  Such a program could be written in Python, or C++, or Golang, Java, etc.  Sorry I am giving you lots of possibilities when you likely want to narrow it down to a few, but feel free to reply with your preference.

**Comment by antoninbas** [comment]
Closing this issue. Helpful answer from @jafingerhut and no update since.
