### ISSUE TITLE
Does simple_switch_grpc support priority queue ?

### ISSUE THREAD

**Issue by apathy72115** [p4lang/behavioral-model#877]
I know if I need to enable priority queue in `simple_switch` , I need to uncomment  the flag `// #define SSWITCH_PRIORITY_QUEUEING_ON ` in `simple_switch.h` this file and compile behavioral-model again.
When I use Iperf send UDP datagram for the priority queue test , it works successfully.
From my understanding, `simple_switch_grpc` is based on the `simple_switch` target. So I create a switch by using `simple_switch_grpc` to do the same test, but it doesn't work.

So , I would like to know how `simple_switch_grpc` enable priority queue. Does it support or not?

Here is my p4 code in Ingress which I use for this test.
>    
    action send_outport(bit<9>port) {
		standard_metadata.egress_spec = port;
    }
    action priority_set(bit<3>queue) {
        standard_metadata.priority = queue;
    }
    apply {
	if(standard_metadata.ingress_port == 1){
		priority_set(7);
		send_outport(3);
	    }
	if(standard_metadata.ingress_port == 2){
		priority_set(0);
		send_outport(3);
	    }
	}

**Comment by antoninbas** [comment]
AFAIK this should work. You need to uncomment the `#define`, re-build simple_switch, re-build simple_switch_grpc. Maybe it would help if you could provide the exact steps you used.

**Comment by apathy72115** [comment]
Thanks for your help ! 
After re-build simple_switch, re-build simple_switch_grpc again , It works now.
