### ISSUE TITLE
configure error for check boost/multiprecision/gmp.hpp fail

### ISSUE THREAD

**Issue by lxlmummy** [p4lang/behavioral-model#879]
I'm compiling bmv2 with a third party cross-compiler toolchain, Bmv2 relies on the boost library and the libpcap library and P4lang/PI library. I had the boost library installed, but It still reported an error while running the bmv2 configure script, error happen：couldn't find the boost gmp.hpp header. Here are the log details:
cd behavioral-model-9ef324838b29419040b4f677a3ff65bc72405c44 &&./autogen.sh
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:124: installing './compile'
configure.ac:7: installing './missing'
PI/Makefile.am: installing './depcomp'
cd behavioral-model-9ef324838b29419040b4f677a3ff65bc72405c44 &&./configure CPPFLAGS="-isystem/home/jamescook/tmp/pi-install/include -I/home/jamescook/tmp/boost_1_72_0/boost-install/include" --without-nanomsg --without-thrift --with-pi --prefix=/home/jamescook/tmp/bmv2_install
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for a Python interpreter with version >= 2.7... python2
checking for python2... /usr/bin/python2
checking for python2 version... 2.7
checking for python2 platform... linux2
checking for python2 script directory... ${prefix}/lib/python2.7/site-packages
checking for python2 extension module directory... ${exec_prefix}/lib/python2.7/site-packages
configure: WARNING: Cannot use elogger without nanomsg
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether /home/jamescook/project/build/project/customtoolchain/host/usr/bin/x86_64-unknown-linux-gnu-g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of /home/jamescook/project/build/project/customtoolchain/host/usr/bin/x86_64-unknown-linux-gnu-g++... gcc3
checking for gcc... /home/jamescook/project/build/OS/customtoolchain/host/usr/bin/x86_64-unknown-linux-gnu-gcc
checking whether we are using the GNU C compiler... yes
checking whether /home/jamescook/project/build/OS/customtoolchain/host/usr/bin/x86_64-unknown-linux-gnu-gcc accepts -g... yes
checking for /home/jamescook/project/build/OS/customtoolchain/host/usr/bin/x86_64-unknown-linux-gnu-gcc option to accept ISO C89... none needed
checking whether /home/jamescook/project/build/OS/customtoolchain/host/usr/bin/x86_64-unknown-linux-gnu-gcc understands -c and -o together... yes
checking dependency style of /home/jamescook/project/build/OS/customtoolchain/host/usr/bin/x86_64-unknown-linux-gnu-gcc... gcc3
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by /home/jamescook/project/build/OS/customtoolchain/host/usr/bin/x86_64-unknown-linux-gnu-gcc... /home/jamescook/project/build/OS/customtoolchain/host/usr/bin/x86_64-unknown-linux-gnu-ld
checking if the linker (/home/jamescook/project/build/OS/customtoolchain/host/usr/bin/x86_64-unknown-linux-gnu-ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /home/jamescook/project/build/OS/customtoolchain/host/usr/bin/x86_64-unknown-linux-gnu-nm
checking the name lister (/home/jamescook/project/build/OS/customtoolchain/host/usr/bin/x86_64-unknown-linux-gnu-nm) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /home/jamescook/project/build/OS/customtoolchain/host/usr/bin/x86_64-unknown-linux-gnu-ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @file support... @
checking for strip... /home/jamescook/project/build/OS/customtoolchain/host/usr/bin/x86_64-unknown-linux-gnu-strip
checking for ranlib... /home/jamescook/project/build/OS/customtoolchain/host/usr/bin/x86_64-unknown-linux-gnu-ranlib
checking command to parse /home/jamescook/project/build/OS/customtoolchain/host/usr/bin/x86_64-unknown-linux-gnu-nm output from /home/jamescook/project/build/OS/customtoolchain/host/usr/bin/x86_64-unknown-linux-gnu-gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... /home/jamescook/project/build/OS/customtoolchain/host/usr/bin/x86_64-unknown-linux-gnu-gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if /home/jamescook/project/build/OS/customtoolchain/host/usr/bin/x86_64-unknown-linux-gnu-gcc supports -fno-rtti -fno-exceptions... no
checking for /home/jamescook/project/build/OS/customtoolchain/host/usr/bin/x86_64-unknown-linux-gnu-gcc option to produce PIC... -fPIC -DPIC
checking if /home/jamescook/project/build/OS/customtoolchain/host/usr/bin/x86_64-unknown-linux-gnu-gcc PIC flag -fPIC -DPIC works... yes
checking if /home/jamescook/project/build/OS/customtoolchain/host/usr/bin/x86_64-unknown-linux-gnu-gcc static flag -static works... yes
checking if /home/jamescook/project/build/OS/customtoolchain/host/usr/bin/x86_64-unknown-linux-gnu-gcc supports -c -o file.o... yes
checking if /home/jamescook/project/build/OS/customtoolchain/host/usr/bin/x86_64-unknown-linux-gnu-gcc supports -c -o file.o... (cached) yes
checking whether the /home/jamescook/project/build/OS/customtoolchain/host/usr/bin/x86_64-unknown-linux-gnu-gcc linker (/home/jamescook/project/build/OS/customtoolchain/host/usr/bin/x86_64-unknown-linux-gnu-ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... /home/jamescook/project/build/OS/customtoolchain/host/usr/bin/x86_64-unknown-linux-gnu-g++ -E
checking for ld used by /home/jamescook/project/build/OS/customtoolchain/host/usr/bin/x86_64-unknown-linux-gnu-g++... /home/jamescook/project/build/OS/customtoolchain/host/usr/bin/x86_64-unknown-linux-gnu-ld -m elf_x86_64
checking if the linker (/home/jamescook/project/build/OS/customtoolchain/host/usr/bin/x86_64-unknown-linux-gnu-ld -m elf_x86_64) is GNU ld... yes
checking whether the /home/jamescook/project/build/OS/customtoolchain/host/usr/bin/x86_64-unknown-linux-gnu-g++ linker (/home/jamescook/project/build/OS/customtoolchain/host/usr/bin/x86_64-unknown-linux-gnu-ld -m elf_x86_64) supports shared libraries... yes
checking for /home/jamescook/project/build/OS/customtoolchain/host/usr/bin/x86_64-unknown-linux-gnu-g++ option to produce PIC... -fPIC -DPIC
checking if /home/jamescook/project/build/OS/customtoolchain/host/usr/bin/x86_64-unknown-linux-gnu-g++ PIC flag -fPIC -DPIC works... yes
checking if /home/jamescook/project/build/OS/customtoolchain/host/usr/bin/x86_64-unknown-linux-gnu-g++ static flag -static works... yes
checking if /home/jamescook/project/build/OS/customtoolchain/host/usr/bin/x86_64-unknown-linux-gnu-g++ supports -c -o file.o... yes
checking if /home/jamescook/project/build/OS/customtoolchain/host/usr/bin/x86_64-unknown-linux-gnu-g++ supports -c -o file.o... (cached) yes
checking whether the /home/jamescook/project/build/OS/customtoolchain/host/usr/bin/x86_64-unknown-linux-gnu-g++ linker (/home/jamescook/project/build/OS/customtoolchain/host/usr/bin/x86_64-unknown-linux-gnu-ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether /home/jamescook/project/build/OS/customtoolchain/host/usr/bin/x86_64-unknown-linux-gnu-g++ supports C++11 features by default... yes
checking PI/pi.h usability... yes
checking PI/pi.h presence... yes
checking for PI/pi.h... yes
checking PI/target/pi_imp.h usability... yes
checking PI/target/pi_imp.h presence... yes
checking for PI/target/pi_imp.h... yes
checking PI/p4info.h usability... yes
checking PI/p4info.h presence... yes
checking for PI/p4info.h... yes
checking algorithm usability... yes
checking algorithm presence... yes
checking for algorithm... yes
checking array usability... yes
checking array presence... yes
checking for array... yes
checking cassert usability... yes
checking cassert presence... yes
checking for cassert... yes
checking cmath usability... yes
checking cmath presence... yes
checking for cmath... yes
checking queue usability... yes
checking queue presence... yes
checking for queue... yes
checking cstdio usability... yes
checking cstdio presence... yes
checking for cstdio... yes
checking string usability... yes
checking string presence... yes
checking for string... yes
checking for sys/stat.h... (cached) yes
checking for sys/types.h... (cached) yes
checking ctime usability... yes
checking ctime presence... yes
checking for ctime... yes
checking tuple usability... yes
checking tuple presence... yes
checking for tuple... yes
checking for unistd.h... (cached) yes
checking unordered_map usability... yes
checking unordered_map presence... yes
checking for unordered_map... yes
checking utility usability... yes
checking utility presence... yes
checking for utility... yes
checking vector usability... yes
checking vector presence... yes
checking for vector... yes
checking whether /home/jamescook/project/build/OS/customtoolchain/host/usr/bin/x86_64-unknown-linux-gnu-gcc is Clang... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking whether more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking for Judy1Next in -lJudy... yes
checking for __gmpz_init in -lgmp... yes
checking for pcap_create in -lpcap... yes
checking for pcap_set_immediate_mode in -lpcap... yes
checking for compiler atomic support... yes
checking for dlopen()... checking for dlfcn.h... (cached) yes
checking for library containing dlopen... -ldl
checking boost/thread.hpp usability... yes
checking boost/thread.hpp presence... yes
checking for boost/thread.hpp... yes
checking for boost::thread in -lboost_thread... yes
checking boost/multiprecision/gmp.hpp usability... no
checking boost/multiprecision/gmp.hpp presence... no
checking for boost/multiprecision/gmp.hpp... no
configure: error: Missing boost Multiprecision headers

I confirm that gmp.hpp exist in the following path:

root@jamescook-VirtualBox:/home/jamescook/tmp/boost_1_72_0/boost-install# find ./ -name "gmp.hpp"
./include/boost/multiprecision/gmp.hpp
root@jamescook-VirtualBox:/home/jamescook/tmp/boost_1_72_0/boost-install#

So, How can I fix it？and It is strange why "checking for boost/thread.hpp... yes" but " checking boost/multiprecision/gmp.hpp usability fail " ?

**Comment by lxlmummy** [comment]
I found the reason.The reason is that gmp.hpp contains gmp.h, and gmp.h requires the libgmp library to be installed.
It is recommended that the author add a check for gmp.h in configure.ac, otherwise it is easy to mislead.

**Comment by lxlmummy** [comment]
just close this issue.

**Comment by antoninbas** [comment]
@lxlmummy we already check for the presence of libgmp in configure.ac. You can see it from the logs you pasted in your issue comment, just a couple lines above the error:
```
checking for __gmpz_init in -lgmp... yes
```
I am not sure how this check can pass without the gmp.h header. The check itself does not require gmp.h per se, but it does require the gmp library to be installed since it needs to link against it. Is it possible that you had an incorrect search path for headers?

If the issue is in our configure.ac, please feel free to submit a patch.

**Comment by lxlmummy** [comment]
@antoninbas ，Thanks, I went over the environment configuration. I find that When the above error occurs, an old version of gmp.so library has been installed before, but this old version of gmp.h header file does not exist. So happens the above strange error. Now, this isn't a configure.ac problem.
