### ISSUE TITLE
building gr-iio error

### ISSUE THREAD

**Issue by jovanny26** [p4lang/behavioral-model#881]
hi, I'm a  newbie. I was trying to install/build plutosdr in my gnu radio but this error appear.
What should I do?

/home/jovanny/gr-iio/lib/device_source_impl.cc: In static member function ‘static gr::iio::device_source::sptr gr::iio::device_source::make(const string&, const string&, const std::vector<std::__cxx11::basic_string<char> >&, const string&, const std::vector<std::__cxx11::basic_string<char> >&, unsigned int, unsigned int)’:
/home/jovanny/gr-iio/lib/device_source_impl.cc:45:9: error: could not convert ‘gnuradio::get_initial_sptr(T*) [with T = gr::iio::device_source_impl]()’ from ‘std::shared_ptr<gr::iio::device_source_impl>’ to ‘gr::iio::device_source::sptr {aka boost::shared_ptr<gr::iio::device_source>}’
       return gnuradio::get_initial_sptr
              ~~~~~~~~~~~~~~~~~~~~~~~~~~
         (new device_source_impl(device_source_impl::get_context(uri), true,
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     device, channels, device_phy,
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     params, buffer_size, decimation));
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/jovanny/gr-iio/lib/device_source_impl.cc: In static member function ‘static gr::iio::device_source::sptr gr::iio::device_source::make_from(iio_context*, const string&, const std::vector<std::__cxx11::basic_string<char> >&, const string&, const std::vector<std::__cxx11::basic_string<char> >&, unsigned int, unsigned int)’:
/home/jovanny/gr-iio/lib/device_source_impl.cc:58:9: error: could not convert ‘gnuradio::get_initial_sptr(T*) [with T = gr::iio::device_source_impl]()’ from ‘std::shared_ptr<gr::iio::device_source_impl>’ to ‘gr::iio::device_source::sptr {aka boost::shared_ptr<gr::iio::device_source>}’
       return gnuradio::get_initial_sptr
              ~~~~~~~~~~~~~~~~~~~~~~~~~~
         (new device_source_impl(ctx, false, device, channels, device_phy,
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     params, buffer_size, decimation));
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
lib/CMakeFiles/gnuradio-iio.dir/build.make:73: recipe for target 'lib/CMakeFiles/gnuradio-iio.dir/device_source_impl.cc.o' failed
make[2]: *** [lib/CMakeFiles/gnuradio-iio.dir/device_source_impl.cc.o] Error 1
CMakeFiles/Makefile2:135: recipe for target 'lib/CMakeFiles/gnuradio-iio.dir/all' failed
make[1]: *** [lib/CMakeFiles/gnuradio-iio.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jafingerhut** [comment]
Is this Github repository in any way related to your question?  Perhaps there is a different project that would be much more appropriate for this question?  As far as I can tell, your questions are about SDR (Software Defined Radio), which while it is related to communications, that is a pretty thin correspondence to this repository's code.

**Comment by antoninbas** [comment]
Seems unrelated to this repo as pointed out by Andy.
