### ISSUE TITLE
simple_switch died with return code -6

### ISSUE THREAD

**Issue by fruffy** [p4lang/behavioral-model#887]
I have a couple of programs that crash simple switch with return code -6 at runtime when I perform a stf test. However, I am not sure  what the source issue is or if that even is a bug.

The command I used to run the command is:

`python p4c/backends/bmv2/run-bmv2-test.py p4c -v -b -bd p4c/build/ return_in_action.p4`

[return_in_action.p4.txt](https://github.com/p4lang/behavioral-model/files/4604061/return_in_action.p4.txt)
[return_in_action.stf.txt](https://github.com/p4lang/behavioral-model/files/4604062/return_in_action.stf.txt)

[switch.log.txt](https://github.com/p4lang/behavioral-model/files/4604057/switch.log.txt)

**Comment by antoninbas** [comment]
Thanks for reporting this. It was indeed an issue with the bmv2 implementation, and not with the JSON generated by the compiler. I am surprised we didn't catch it sooner. Hopefully you can add your program to the p4c test suite.
