### ISSUE TITLE
New conditionals for simple_switch

### ISSUE THREAD

**Issue by hesingh** [p4lang/behavioral-model#892]
This is a question.

Do I understand correctly that an if-statement in apply block of a control is emitted as `conditionals` in JSON output when compiling a P4 program?

See https://github.com/p4lang/p4c/issues/644#issuecomment-629279026

If I have a  new feature in while loop to add to p4c, is the while considered a conditional?  If yes, how does the while get added to behavioral-model?  Do we define a new `conditionals-while`?  Any other ideas?

**Comment by hesingh** [comment]
@antoninbas Could you please reply when you get a chance, thanks.

**Comment by antoninbas** [comment]
It would depend on whether you want to support loops inside actions or at the control level.
* in actions: you should be able to use the `_jump` and `_jump_if_zero` operators to support loops. I don't know if these operators support negative offsets for the jumps, but it should be easy to check and it can be changed if needed.
* in controls: I don't think you need to introduce any new object in the JSON. The bmv2 table graph representation should be able to support loops actually. Even though this representation has limitations (https://github.com/p4lang/behavioral-model/issues/599), this is probably one of the rare case in which we can support multiple invocations of the same table.

In this examples:
```
while (C) {
    my_table.apply()
}
other_table.apply()
```
The "true" pointer for `C` would point to `my_table`. The "false" pointer for C would point to `other_table`. The "next_tables" pointer for `my_table` would point to C. Refer to the JSON documentation for more details.

**Comment by hesingh** [comment]
Thanks @antoninbas 

I already read the JSON doc for _jump and while loop inside action is fine with behavioral-model.   Appreciate the clarification on while inside apply block.  I am all set.
