### ISSUE TITLE
stratum_bmv2 crashes because of "Assertion `is_valid_mbr(mbr)' failed"

### ISSUE THREAD

**Issue by ccascone** [p4lang/behavioral-model#893]
I'm using `stratum_bmv2` but I believe the issue belongs to the `simple_switch` part of the process. The `stratum_bmv2` build is based on the following commits:

* PI 1539ecd8a50c159b011d9c5a9c0eba99f122a845
* bmv2 9ef324838b29419040b4f677a3ff65bc72405c44

I also tried building with the most recent ones, but the issue persists:

* PI 0fbdac256151eb1537cd5ebf19101d5df60767fa`
* bmv2 9a331b900cb04195807f63d2e5f436b8785fc7cd

The issue is also tracked here with full logs and instructions to reproduce it:
https://github.com/opennetworkinglab/fabric-p4test/issues/72

In a nutshell, I run two PTF tests that:

- Insert 1 action profile group with 2 members (and other P4Runtime entities)
- Send many packets (to test ECMP-like distribution), all good, test pass
- Remove all P4Runtime entities, including the action profile group and 2 members
- Insert 1 action profile group with 1 member
- Send packet, assertion error

Here's a relevant excerpt from the stratum_bmv2 log:
```
...
[00:11:15.415] [bmv2] [D] [thread 106] Added member 0 to action profile 'FabricIngress.next.hashed_selector'
[00:11:15.417] [bmv2] [D] [thread 101] Added member 1 to action profile 'FabricIngress.next.hashed_selector'
[00:11:15.420] [bmv2] [D] [thread 106] Created group 0 in action profile 'FabricIngress.next.hashed_selector'
[00:11:15.420] [bmv2] [D] [thread 106] Added member 0 to group 0 in action profile 'FabricIngress.next.hashed_selector'
[00:11:15.421] [bmv2] [D] [thread 106] Added member 1 to group 0 in action profile 'FabricIngress.next.hashed_selector'
[00:11:15.424] [bmv2] [D] [thread 101] Entry 0 added to table 'FabricIngress.next.hashed'
[00:11:15.424] [bmv2] [D] [thread 101] Dumping entry 0
Match key:
* next_id             : EXACT     0000012c
Index: group(0)
Group members:
  mbr 0: FabricIngress.next.routing_hashed - 2,aa01,2,
  mbr 1: FabricIngress.next.routing_hashed - 3,aa01,3,

...

[00:11:22.986] [bmv2] [D] [thread 106] Entry 0 removed from table 'FabricIngress.next.hashed'
[00:11:22.986] [bmv2] [D] [thread 106] Removed group 0 from action profile 'FabricIngress.next.hashed_selector'
[00:11:22.987] [bmv2] [D] [thread 106] Removed member 1 from action profile 'FabricIngress.next.hashed_selector'
[00:11:22.988] [bmv2] [D] [thread 106] Removed member 0 from action profile 'FabricIngress.next.hashed_selector'

...

[00:11:23.095] [bmv2] [D] [thread 101] Added member 0 to action profile 'FabricIngress.next.hashed_selector'
[00:11:23.099] [bmv2] [D] [thread 107] Created group 0 in action profile 'FabricIngress.next.hashed_selector'
[00:11:23.100] [bmv2] [D] [thread 107] Added member 0 to group 0 in action profile 'FabricIngress.next.hashed_selector'
[00:11:23.110] [bmv2] [D] [thread 101] Entry 16777216 added to table 'FabricIngress.next.hashed'
[00:11:23.111] [bmv2] [D] [thread 101] Dumping entry 16777216
Match key:
* next_id             : EXACT     00000064
Index: group(0)
Group members:
  mbr 0: FabricIngress.next.routing_hashed - 2,aa01,2,

...

[00:11:23.150] [bmv2] [D] [thread 84] [52.0] [cxt 0] Looking up key:
* next_id             : 00000064

[00:11:23.150] [bmv2] [D] [thread 84] [52.0] [cxt 0] Choosing member 1 from group 0
stratum_bmv2: action_profile.cpp:182: const bm::ActionEntry& bm::ActionProfile::lookup(const bm::Packet&, const bm::ActionProfile::IndirectIndex&) const: Assertion `is_valid_mbr(mbr)' failed.
*** Aborted at 1590106283 (unix time) try "date -d @1590106283" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x50) received by PID 80 (TID 0x7ff37a2df700) from PID 80; stack trace: ***
    @     0x7ff37d4910e0 (unknown)
    @     0x7ff37cefcfff gsignal
    @     0x7ff37cefe42a abort
    @     0x7ff37cef5e67 (unknown)
    @     0x7ff37cef5f12 __assert_fail
    @     0x7ff37df6ef4f bm::ActionProfile::lookup()
    @     0x7ff37e0087c4 bm::MatchTableIndirect::lookup()
    @     0x7ff37e009c93 bm::MatchTableIndirectWS::lookup()
    @     0x7ff37e005b5c bm::MatchTableAbstract::apply_action()
    @     0x7ff37e0ddd7e bm::MatchActionTable::operator()()
    @     0x7ff37e0afb77 bm::Pipeline::apply()
    @     0x7ff37ded37f4 SimpleSwitch::ingress_thread()
    @     0x7ff37def03ae std::__invoke_impl<>()
    @     0x7ff37def02b3 std::__invoke<>()
    @     0x7ff37def01f0 _ZNKSt12_Mem_fn_baseIM12SimpleSwitchFvvELb1EEclIJPS0_EEEDTcl8__invokedtdefpT6_M_pmfspcl7forwardIT_Efp_EEEDpOS6_
    @     0x7ff37def016f _ZNSt12_Bind_simpleIFSt7_Mem_fnIM12SimpleSwitchFvvEEPS1_EE9_M_invokeIJLm0EEEEvSt12_Index_tupleIJXspT_EEE
    @     0x7ff37deefef3 std::_Bind_simple<>::operator()()
    @     0x7ff37deefdc0 std::thread::_State_impl<>::_M_run()
    @     0x7ff37e863e6f (unknown)
    @     0x7ff37d4874a4 start_thread
    @     0x7ff37cfb2d0f clone
    @                0x0 (unknown)

```

**Comment by antoninbas** [comment]
That's pretty confusing, the entry dump shows that the membership is correct, yet somehow it ends up picking a member that does not exist:
```
[00:11:23.111] [bmv2] [D] [thread 101] Dumping entry 16777216
Match key:
* next_id             : EXACT     00000064
Index: group(0)
Group members:
  mbr 0: FabricIngress.next.routing_hashed - 2,aa01,2,
```

I'm working on reproducing this outside of the docker image. So far no luck with just a unit test. I have built stratum_bmv2 locally and I hope to run it under gdb. Do you have any instructions on how I can run the PTF tests outside of the docker using my local stratum_bmv2 binary?

I also have a bmv2 branch with some additional log statements. If you have an easy way to build statum_bmv2 and run the tests, and you could share the new logs, that would be useful. The branch is here: https://github.com/p4lang/behavioral-model/tree/antonin/ap-debug.

**Comment by ccascone** [comment]
Thanks a lot @antoninbas  for looking into this.

Assuming `stratum_bmv2` is running on `localhost:28000` with flags, veths, and chassis_config file like in this script:
https://github.com/opennetworkinglab/fabric-p4test/blob/fix-travis/travis/run_stratum_bmv2.sh

Clone ONOS branch `onos-2.2` to obtain the bmv2.json and p4info.txt (generated with a quite old version of the compiler, keep reading): 
https://github.com/opennetworkinglab/onos/tree/onos-2.2

Install P4Runtime's Python bindings, [scapy-vxlan](https://github.com/p4lang/scapy-vxlan), and [ptf](https://github.com/p4lang/ptf).

Finally, from fabric-p4test, branch `fix-travis`, you should be able run:
```
cd fabric-p4test/tests/ptf
python -u ptf_runner.py --port-map port_map.veth.json --ptf-dir fabric.ptf --cpu-port 255 --device-id 1 --grpc-addr localhost:28000 --device bmv2 --p4info /onos/pipelines/fabric/impl/src/main/resources/p4c-out/fabric/bmv2/default/p4info.txt --bmv2-json /onos/pipelines/fabric/impl/src/main/resources/p4c-out/fabric/bmv2/default/bmv2.json bug
https://github.com/opennetworkinglab/onos/tree/onos-2.2
```

I also tried running the same test with bmv2.json and p4info.txt generated with the latest p4c master and stratum_bmv2 based on bmv2 latest master., but the issue persists.

I will build stratum_bmv2 based on your debug branch and will let you know.

**Comment by ccascone** [comment]
I've attached below the logs from stratum_bmv2 built with:
- PI 0fbdac256151eb1537cd5ebf19101d5df60767fa
- bmv2 8e2ac109e32d9d07ad25e49fda1416d5581c20b1

If you're interested, I built the mn-stratum container (which contains stratum_bmv2) off of this commit:
https://github.com/ccascone/stratum-1/commit/2bdee062ce12419ab346fbb6fe9f2bdb4b3b514b

```
docker build --build-arg JOBS=4 -t stratumproject/build:build -f Dockerfile.build . 
docker build -t mn-stratum-debug -f tools/mininet/Dockerfile .
```

I've also simplified the test cases to the bare minimum to reproduce the issue:
https://github.com/opennetworkinglab/fabric-p4test/commit/9ad39e308719e2cd471bda4562c4f74ca31962e1

Here are the logs. Strangely, I see lines with `*** handle` but not with `*** get_from_hash()`.
I've also attached the bmv2.json and p4info.txt used in the test and generated with the latest p4c.

[bmv2.json.txt](https://github.com/p4lang/behavioral-model/files/4671115/bmv2.json.txt)
[p4info.txt](https://github.com/p4lang/behavioral-model/files/4671116/p4info.txt)
[switch.log](https://github.com/p4lang/behavioral-model/files/4671117/switch.log)
[write-reqs.log](https://github.com/p4lang/behavioral-model/files/4671118/write-reqs.log)

**Comment by antoninbas** [comment]
>  Strangely, I see lines with `*** handle` but not with `*** get_from_hash()`.

Actually that's great info. That reminded me that there was a different implementation for `simple_switch_grpc` / `stratum_bmv2` in order to support watch ports. The implementation is here: https://github.com/p4lang/behavioral-model/blob/master/PI/src/group_selection.cpp. I'm hoping that knowing this, it won't take long to find the issue.

**Comment by ccascone** [comment]
Thanks @antoninbas , I confirm that fixed it.
