### ISSUE TITLE
multicast group

### ISSUE THREAD

**Issue by kphf1995cm** [p4lang/behavioral-model#894]
Is bmv2 support multicast group?

**Comment by jafingerhut** [comment]
Yes, it does.  See these two files in some documentation files included in this repository to see if they answer your questions, and if not, add another comment with your question.

https://github.com/p4lang/behavioral-model/blob/master/docs/simple_switch.md   If you do not want to read the whole thing, search for occurrences of 'multicast' and 'mcast_grp'

https://github.com/p4lang/behavioral-model/blob/master/docs/runtime_CLI.md   This is only relevant if you want to use the simple_switch_CLI tool for configuring multicast groups.  Search for mc_dump and related commands, all documented together.

If you want to use the P4Runtime API, look at the P4Runtime API specification instead for occurrences of 'multicast'.

**Comment by kphf1995cm** [comment]
Thanks a lot !

--
 况鹏
    Peng Kuang
 清华大学 网络科学与网络空间研究院
    Tel： +86 18292886592
    E-mail: kp18@mails.tsinghua.edu.cn


发件人: Andy Fingerhut
发送时间: 2020年5月22日 11:55
收件人: p4lang/behavioral-model
抄送: echorez; Author
主题: Re: [p4lang/behavioral-model] multicast group (#894)

Yes, it does. See these two files in some documentation files included in this repository to see if they answer your questions, and if not, add another comment with your question.
https://github.com/p4lang/behavioral-model/blob/master/docs/simple_switch.md If you do not want to read the whole thing, search for occurrences of 'multicast' and 'mcast_grp'
https://github.com/p4lang/behavioral-model/blob/master/docs/runtime_CLI.md This is only relevant if you want to use the simple_switch_CLI tool for configuring multicast groups. Search for mc_dump and related commands, all documented together.
If you want to use the P4Runtime API, look at the P4Runtime API specification instead for occurrences of 'multicast'.
