### ISSUE TITLE
Egress pipeline doesn't work

### ISSUE THREAD

**Issue by Hoangttrieu** [p4lang/behavioral-model#897]
Hello, I use the simple switch with grpc amd b1 model. When i send a packet with gtp header to switch, the packet was processed in the Ingress pipeline, then it was fowarded to the egress port. The Egress pipeline and the Deparser does not start, but the switch starts to process new packet. Do you know how can i fix it cause when i send the packet without gtp header, everything works normal.

**Comment by antoninbas** [comment]
The "egress pipeline doesn't work" is a serious accusation :) Did you actually look at the bmv2 console logs? If yes, can you paste them here and point out what's the expected vs actual behavior?

You should also provide the bmv2 JSON file produced by the compiler for your program (make sure you do not share proprietary information), along with a packet template that can be used to reproduce the issue.

**Comment by Hoangttrieu** [comment]
Below is a part of the log file i got. I need it the egress pipeline start ,end, Deparser my packet and send to port 2. But actual, the packet is not deparser and sent to port 2 correctly.
Match key:
* fabric_metadata.spgw.teid: EXACT     00000001
Action entry: FabricIngress.forwarding.gtpu_egress - 5254001ad05f,2,

[09:01:29.293] [bmv2] [D] [thread 12782] [7.0] [cxt 0] Action entry is FabricIngress.forwarding.gtpu_egress - 5254001ad05f,2,
[09:01:29.293] [bmv2] [T] [thread 12782] [7.0] [cxt 0] Action FabricIngress.forwarding.gtpu_egress
[09:01:29.293] [bmv2] [T] [thread 12782] [7.0] [cxt 0] upf.p4(255) Primitive standard_metadata.egress_spec = port
[09:01:29.293] [bmv2] [T] [thread 12782] [7.0] [cxt 0] upf.p4(256) Primitive hdr.ethernet.src_addr = hdr.ethernet.dst_addr
[09:01:29.293] [bmv2] [T] [thread 12782] [7.0] [cxt 0] upf.p4(257) Primitive hdr.ethernet.dst_addr = dst_addr
[09:01:29.293] [bmv2] [T] [thread 12782] [7.0] [cxt 0] upf.p4(258) Primitive hdr.ipv4.ttl = hdr.ipv4.ttl - 1
[09:01:29.293] [bmv2] [T] [thread 12782] [7.0] [cxt 0] Applying table 'tbl_forwarding_spgw_ingress_gtpu_decap'
[09:01:29.293] [bmv2] [D] [thread 12782] [7.0] [cxt 0] Looking up key:

[09:01:29.293] [bmv2] [D] [thread 12782] [7.0] [cxt 0] Table 'tbl_forwarding_spgw_ingress_gtpu_decap': miss
[09:01:29.293] [bmv2] [D] [thread 12782] [7.0] [cxt 0] Action entry is FabricIngress.forwarding.spgw_ingress.gtpu_decap -
[09:01:29.293] [bmv2] [T] [thread 12782] [7.0] [cxt 0] Action FabricIngress.forwarding.spgw_ingress.gtpu_decap
[09:01:29.293] [bmv2] [T] [thread 12782] [7.0] [cxt 0] upf.p4(223) Primitive hdr.gtpu_ipv4.setInvalid()
[09:01:29.293] [bmv2] [T] [thread 12782] [7.0] [cxt 0] upf.p4(224) Primitive hdr.gtpu_udp.setInvalid()
[09:01:29.293] [bmv2] [T] [thread 12782] [7.0] [cxt 0] upf.p4(225) Primitive hdr.gtpu.setInvalid()
[09:01:29.293] [bmv2] [D] [thread 12782] [7.0] [cxt 0] Pipeline 'ingress': end
[09:01:29.293] [bmv2] [D] [thread 12782] [7.0] [cxt 0] **Egress port is 2
[09:01:29.293] [bmv2] [D] [thread 12782] [8.0] [cxt 0] Processing packet received on port 1**
[09:01:29.293] [bmv2] [D] [thread 12782] [8.0] [cxt 0] Parser 'parser': start
[09:01:29.293] [bmv2] [D] [thread 12782] [8.0] [cxt 0] Parser 'parser' entering state 'start'
[09:01:29.293] [bmv2] [D] [thread 12782] [8.0] [cxt 0] Extracting header 'ethernet'

Below is a part of the json file created by p4c compiler:

 "pipelines" : [
    {
      "name" : "ingress",
      "id" : 0,
      "source_info" : {
        "filename" : "file.p4",
        "line" : 423,
        "column" : 8,
        "source_fragment" : "FabricIngress"
      },
      "init_table" : "node_2",
      "tables" : [
        ..........
          
        {
          "name" : "FabricIngress.forwarding.teid_exact",
          "id" : 5,
          "source_info" : {
            "filename" : "upf.p4",
            "line" : 274,
            "column" : 10,
            "source_fragment" : "teid_exact"
          },
          "key" : [
            {
              "match_type" : "exact",
              "name" : "fabric_metadata.spgw.teid",
              "target" : ["scalars", "fabric_metadata_t._spgw_teid6"],
              "mask" : null
            }
          ],
          "match_type" : "exact",
          "type" : "simple",
          "max_size" : 1024,
          "with_counters" : false,
          "support_timeout" : false,
          "direct_meters" : null,
          "action_ids" : [2, 1],
          "actions" : ["FabricIngress.forwarding.gtpu_egress", "FabricIngress.forwarding.drop"],
          "base_default_next" : "tbl_forwarding_spgw_ingress_gtpu_decap",
          "next_tables" : {
            "FabricIngress.forwarding.gtpu_egress" : "tbl_forwarding_spgw_ingress_gtpu_decap",
            "FabricIngress.forwarding.drop" : "tbl_forwarding_spgw_ingress_gtpu_decap"
          },
          "default_entry" : {
            "action_id" : 1,
            "action_const" : false,
            "action_data" : [],
            "action_entry_const" : false
          }
        },
        {
          "name" : "tbl_forwarding_spgw_ingress_gtpu_decap",
          "id" : 6,
          "source_info" : {
            "filename" : "file.p4",
            "line" : 234,
            "column" : 12,
            "source_fragment" : "gtpu_decap()"
          },
          "key" : [],
          "match_type" : "exact",
          "type" : "simple",
          "max_size" : 1024,
          "with_counters" : false,
          "support_timeout" : false,
          "direct_meters" : null,
          "action_ids" : [0],
          "actions" : ["FabricIngress.forwarding.spgw_ingress.gtpu_decap"],
          "base_default_next" : null,
          "next_tables" : {
            "FabricIngress.forwarding.spgw_ingress.gtpu_decap" : null
          },
          "default_entry" : {
            "action_id" : 0,
            "action_const" : true,
            "action_data" : [],
            "action_entry_const" : true
          }
        }
      ],
      "action_profiles" : [],
      "conditionals" : [
        {
          "name" : "node_2",
          "id" : 0,
          "source_info" : {
            "filename" : "file.p4",
            "line" : 433,
            "column" : 5,
            "source_fragment" : "hdr.gtpu.isValid()"
          },
          "expression" : {
            "type" : "expression",
            "value" : {
              "op" : "d2b",
              "left" : null,
              "right" : {
                "type" : "field",
                "value" : ["gtpu", "$valid$"]
              }
            }
          },
          "true_next" : "tbl_act",
          "false_next" : "node_7"
        },
        {
          "name" : "node_4",
          "id" : 1,
          "source_info" : {
            "filename" : "upf.p4",
            "line" : 324,
            "column" : 12,
            "source_fragment" : "inner_udp.isValid()"
          },
          "expression" : {
            "type" : "expression",
            "value" : {
              "op" : "d2b",
              "left" : null,
              "right" : {
                "type" : "field",
                "value" : ["inner_udp", "$valid$"]
              }
            }
          },
          "true_next" : "tbl_act_0",
          "false_next" : "tbl_act_1"
        },
        {
          "name" : "node_7",
          "id" : 2,
          "source_info" : {
            "filename" : "upf.p4",
            "line" : 287,
            "column" : 12,
            "source_fragment" : "hdr.gtpu.isValid()"
          },
          "expression" : {
            "type" : "expression",
            "value" : {
              "op" : "d2b",
              "left" : null,
              "right" : {
                "type" : "field",
                "value" : ["gtpu", "$valid$"]
              }
            }
          },
          "true_next" : "tbl_act_2",
          "false_next" : "tbl_act_3"
        },
        {
          ............
          },
          "expression" : {
           .........
              }
            }
          },
          "false_next" : null,
          "true_next" : "FabricIngress.forwarding.teid_exact"
        }
      ]
    },

**Comment by Hoangttrieu** [comment]
The packet template is the GTP packet: 

header gtpu_t {
    bit<3>  version;    
    bit<1>  pt;        
    bit<1>  spare;      
    bit<1>  ex_flag;   
    bit<1>  seq_flag;   
    bit<1>  npdu_flag;  
    bit<8>  msgtype;    
    bit<16> msglen;   
    bit<32> teid;      
}


struct headers_t {
    ethernet_t ethernet;
    ipv4_t gtpu_ipv4;
    udp_t gtpu_udp;
    gtpu_t gtpu;
    ipv4_t inner_ipv4;
    udp_t inner_udp;
    ipv4_t ipv4;
    udp_t udp;
}

**Comment by jafingerhut** [comment]
Ingress and egress might be executing in different threads, and so if packets are arriving quickly enough, it is possible that the ingress logs of two packets might appear before the egress log of the 1st packet appears.  If you look through the entire log after this line:
```
[09:01:29.293] [bmv2] [D] [thread 12782] [7.0] [cxt 0] Egress port is 2
```
to see if there are other lines containing the string "[7.0]", are there any?  I suspect there might be.

**Comment by Hoangttrieu** [comment]
Thanks a lot. I found this line at the end of the file.
