### ISSUE TITLE
make check:   FAIL: test_queueing

### ISSUE THREAD

**Issue by Schweik7** [p4lang/behavioral-model#900]
i install most of libs by using "apt install xxx-dev" ,not from source.And after "make check",only 1 test failed:test_queueing.
this is the result of "cat tests/test-suite.log":

...
FAIL: test_queueing
===================

[==========] Running 6 tests from 5 test cases.
[----------] Global test environment set-up.
[----------] 1 test from QueueingTest/0, where TypeParam = bm::QueueingLogic<std::unique_ptr<int, std::default_delete<int> >, WorkerMapper>
[ RUN      ] QueueingTest/0.ProducerConsummer
[       OK ] QueueingTest/0.ProducerConsummer (110 ms)
[----------] 1 test from QueueingTest/0 (110 ms total)

[----------] 1 test from QueueingTest/1, where TypeParam = bm::QueueingLogicRL<std::unique_ptr<int, std::default_delete<int> >, WorkerMapper>
[ RUN      ] QueueingTest/1.ProducerConsummer
test_queueing.cpp:141: Failure
      Expected: expected_queue_id
      Which is: 2
To be equal to: queue_id
      Which is: 0
...

How to fix it?

**Comment by antoninbas** [comment]
I have also seen these tests fail on some machines. I'm planning to look into this in the near future, but in the meantime I think it is safe for you to just ignore the failing queueing tests.

**Comment by Schweik7** [comment]
@antoninbas Thanks your watching
