### ISSUE TITLE
Query Regarding queue rate and depth 

### ISSUE THREAD

**Issue by drobinkent** [p4lang/behavioral-model#907]
In bmv2, when we work with the priority queues and set rate using set_queue_rate command of simple_switch_CLI -- does that set same rate for all the queues of a port? Or there is mechanism to set queue rate for each of the priority queue for a port? Also, what happens when we use set_queue_depth command from simple_switch_CLI? In case of priority queue based shceduler implementation, does that set the depth for each of the queue?

**Comment by antoninbas** [comment]
Given that there is no `priority` parameter for these commands, yes it applies to all priority queues for a given egress port.

Feel free to submit a patch to enable selecting a single priority queue.
