### ISSUE TITLE
Include hex sequence of received and transmitted packets in simple_switch log

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/behavioral-model#911]
If it is already possible to enable this in simple_switch log output, please let me know how to enable it.

If it isn't, it seems like a very useful thing to have for debugging purposes.  Right now one can see the length of received and transmitted packets, but can only infer parts of their contents based upon whatever other log messages happen to print.

It seems to me that even if a packet is 1500 bytes, it is worth printing the entire thing in one long log line, rather than trying to guess how much of it someone wants to see.  The typical number of characters added to the log for a packet being processed is usually far more than that, anyway.

**Comment by antoninbas** [comment]
Did you try this:
```
  --dump-packet-data arg      Specify how many bytes of packet data to dump 
                              upon receiving & sending a packet. We use the 
                              logger to dump the packet data, with log level 
                              'info', so make sure the log level you have set 
                              does not exclude 'info' messages; default is 0, 
                              which means that nothing is logged.
```
It should handle cases where the packet length is shorter than `arg` gracefully. If not, please file a bug.

**Comment by jafingerhut** [comment]
I am having a hard time believing that I never noticed this capability before.  Works like a charm.  Thanks, Antonin!
