### ISSUE TITLE
Problems to parse a variable number of headers ...

### ISSUE THREAD

**Issue by castilhorosa** [p4lang/behavioral-model#915]
Hi there,

I've been using the V1Model and simple_switch to create a P4 application in which I can encapsulate a variable number of headers through a header stack. I've been using a field (bit<4>) in the packet itself to represent the number of headers (at most 16 headers) that a particular packet contains. My question is, how can I parses all the headers in the header stack taking into account the field that represents the number of headers? I tried to use the header stack example below (MPLS stack), from P4 specification, but in my case the parse needs to be done taking into account the number of headers extract from a field in the packet and not from a specific bit.

Example of MPLS processing, from P4 specification:
`
struct Pkthdr {
   Ethernet_h ethernet;
   Mpls_h[3] mpls;
   // other headers omitted
}

parser P(packet_in b, out Pkthdr p) {
    state start {
        b.extract(p.ethernet);
        transition select(p.ethernet.etherType) {
           0x8847: parse_mpls;
           0x0800: parse_ipv4;
        }
    }
    state parse_mpls {
         b.extract(p.mpls.next);
         transition select(p.mpls.last.bos) {
            0: parse_mpls; // This creates a loop
            1: parse_ipv4;
         }
    }
    // other states omitted
}
`

My simplified code:
`
header block_t {
       bit<48> block;
}

header customized_pdu {
       bit<2> tag1;
       bit<2> tag2;
       bit<4> number_blocks;
}

struct headers {
       customized_pdu      pdu;
       block_t[16]               blocks; 
}

parser My_Parser(packet_in packet, out headers hdr, inout metadata meta, inout standard_metadata_t standard_metadata) {
        
         state start {
                           transition parse_customized_pdu;
         }

         state parse_customized_pdu {
                           packet.extract(hdr.pdu);
                           transition select (hdr.pdu.tag1) {
                                        1  :   parse_blocks;
                           }
         }

         state parse_blocks {
                 packet.extract(hdr.blocks.next);
                 if(hdr.blocks.nextIndex < hdr.pdu.number_blocks) {
                       transition parse_blocks;  //I want this loop, based on hdr.pdu.number_blocks. However, I'm getting a compile error
                                                              // (Unexpected TRANSITION, expecting { or CONST)
                 }
                 transition accept;  //I want to go to this state after all hdr.pdu.number_blocks blocks are parsed
         }

}
`
It could be a silly question but I'm a begginer in P4..

Thanks in advance.

**Comment by jafingerhut** [comment]
You can create local variables inside of the parser, before the parser state definitions, and assign values to those local variables, e.g. copied from header fields in headers you have extracted.  After parsing the header that contains the `bit<4>` field with the count, you can assign to it like this: `my_remaining_count = hdr.some_hdr.my_count;`.  You can do a `transition select (my_remaining_count)` with a case for 0 that transitions to a state indicating you are done with the stack parsing, which could go to accept if you are done, or to some other parser state if there might be other headers after the stack.  The non-0 case would be default, transitioning to a state that extracts one element of the header stack, and also does the assignment `my_remaining_count = my_remaining_count - 1`, and transitions back to the parser state that does `transition select (my_remaining_count)`.

**Comment by castilhorosa** [comment]
I got it @jafingerhut . It's working now using a local variable. Thanks.
