### ISSUE TITLE
How to use varbit fields or header stack as key in match tables?

### ISSUE THREAD

**Issue by castilhorosa** [p4lang/behavioral-model#916]
Hi there,

I need to use a variable bit field, either using varbit or header stack, as a key in match tables using lpm. I'm trying to do that but I'm getting the following error:

[--Werror=type-error] error: Key hdr.variable field type must be a scalar type; it cannot be header variable_field.

I'm using v1model and simple_switch.

What should I do to solve that? Is that possible?

Thanks in advance.

**Comment by antoninbas** [comment]
I don't know what would be the semantics of an LPM match on a variable-length field. Note that the P4_16 spec greatly limits the operations that are supported by varbits: https://p4.org/p4-spec/docs/P4-16-v1.2.1.html#sec-varbit-string.

An issue like this one probably does not belong in this repository. The error you quote is emitted by the p4c compiler.

**Comment by jafingerhut** [comment]
Good places for questions on how to achieve things in P4:

+ The p4-dev email list, which you can join here: http://lists.p4.org/mailman/listinfo/p4-dev_lists.p4.org
+ The P4 language Slack community, for interactive chatting: Go to the p4.org home page, near top right click on the "Community" menu, and select "Slack" in the menu that appears.
