### ISSUE TITLE
Netcat does not accept packets from bmv2

### ISSUE THREAD

**Issue by simoelazzab** [p4lang/behavioral-model#919]
I have two namespaces srv1 and srv2, interconnected with veth pairs via bmv2 running within the plang/behavioral-model container. The p4 program does just match on DMAC and simple forwarding.  The veth interfaces inside the namespaces have IP addresses assigned to them (respectively 192.168.1.1 and 192.168.1.2). I could ping between the two namespaces using those IP addresses, but netcat does not work even though I see the packet received on the interface of the listening server.

```
sudo ip netns exec srv1 ping 192.168.1.2
PING 192.168.1.2 (192.168.1.2) 56(84) bytes of data.
64 bytes from 192.168.1.2: icmp_seq=1 ttl=64 time=1.03 ms
64 bytes from 192.168.1.2: icmp_seq=2 ttl=64 time=1.04 ms
but when I try netcat I dont receive messages on the server side:
```
I used necat as follows:
client:

```
sudo ip netns exec srv1 netcat 192.168.1.2 80 -u
 hello!
```
server:

`sudo ip netns exec srv2 netcat -l 80 -u`

The interface receives the packets with proper format .I verified with tcpdump on on both namespaces and I saw the packets being sent and received properly, and that the sent packet is exactly the same as the received one :

client:
```

sudo ip netns exec srv1  tcpdump -XXvv -i srv1p
[sudo] password for simo: 
tcpdump: listening on srv1p, link-type EN10MB (Ethernet), capture size 262144 bytes
^C06:09:41.088601 IP (tos 0x0, ttl 64, id 14169, offset 0, flags [DF], proto UDP (17), length 35)
    192.168.1.1.55080 > 192.168.1.2.http: [bad udp cksum 0x8374 -> 0x5710!] UDP, length 7
    0x0000:  00aa bbcc dd02 00aa bbcc dd01 0800 4500  ..............E.
    0x0010:  0023 3759 4000 4011 801d c0a8 0101 c0a8  .#7Y@.@.........
    0x0020:  0102 d728 0050 000f 8374 6865 6c6c 6f21  ...(.P...thello!
    0x0030:  0a                                       .

1 packet captured
1 packet received by filter
0 packets dropped by kernel
```
server:

```
sudo ip netns exec srv2  tcpdump -XXvv -i srv2p
tcpdump: listening on srv2p, link-type EN10MB (Ethernet), capture size 262144 bytes
^C06:09:41.089232 IP (tos 0x0, ttl 64, id 14169, offset 0, flags [DF], proto UDP (17), length 35)
    192.168.1.1.55080 > 192.168.1.2.http: [bad udp cksum 0x8374 -> 0x5710!] UDP, length 7
    0x0000:  00aa bbcc dd02 00aa bbcc dd01 0800 4500  ..............E.
    0x0010:  0023 3759 4000 4011 801d c0a8 0101 c0a8  .#7Y@.@.........
    0x0020:  0102 d728 0050 000f 8374 6865 6c6c 6f21  ...(.P...thello!
    0x0030:  0a                                       .

1 packet captured
1 packet received by filter
0 packets dropped by kernel
```
I added on srv2 iptable rules to ACCEPT udp packets on port 80 and to LOG:

```
sudo ip netns exec srv2 iptables -t filter -A INPUT -p udp --dport 80 -j ACCEPT
sudo ip netns exec srv2 iptables -I INPUT -p udp --dport 80 -j LOG --log-prefix " IPTABLES " --log-level=debug
```

I could see the stats increasing on the entry and the packets being logged on /var/log/kern.log, but the message never reaches the netcats listening socket.

```
sudo ip netns exec srv2 iptables -L -n -v
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    1    33 LOG        udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:80 LOG flags 0 level 7 prefix " IPTABLES "
    4   133 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:80

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination 
```

kernel logs:

`kernel: [581970.306032]  IPTABLES IN=srv2p OUT= MAC=00:aa:bb:cc:dd:02:00:aa:bb:cc:dd:01:08:00 SRC=192.168.1.1 DST=192.168.1.2 LEN=33 TOS=0x00 PREC=0x00 TTL=64 ID=51034 DF PROTO=UDP SPT=48784 DPT=80 LEN=13 `

The weird thing is that when I replace the bmv2 with a linux bridge the netcat works. I thought maybe the bmv2 corrputs the packets but the tcpdump shows that packet sent is the same as the received one. The UDP checksum is not correct but it is generated like that from the source server, and it is the same thing anyways when using the linux bridge which  works. Can it be something related to CRC? any ideas ?

**Comment by antoninbas** [comment]
It is definitely a checksum issue. You have several options here:

1. disable all offloads on your veth interfaces
2. set the UDP checksum to 0 unconditionally in your P4 program
3. compute and set the UDP checksum in your P4 program

When you use the Linux bridge the packet stays in the kernel during bridging and the kernel keeps track of checksum validity / whether the checksum has been computed / whether a checksum is needed (google `CHECKSUM_UNNECESSARY`). This is not what happens with bmv2. The packet is read by a userspace application (simple_switch) using libpcap. It is then re-injected back, but all these checksum flags have been lost, and the kernel will just drop the packet on the receiver's side because of the invalid checksum (which was never valid to begin with).

Option 1 above is probably your best choice.
```
        TOE_OPTIONS="rx tx sg tso ufo gso gro lro rxvlan txvlan rxhash"
        for TOE_OPTION in $TOE_OPTIONS; do
           /sbin/ethtool --offload $intf "$TOE_OPTION" off
        done
```

Repeat for all veths...

**Comment by mohammedelazzab** [comment]
That solved the problem. Thank you
