### ISSUE TITLE
Error while parsing fe80::0:1 - Invalid IPv6 address

### ISSUE THREAD

**Issue by guimvmatos** [p4lang/behavioral-model#924]
Hi, 

I'm trying to implement a program that I already test in mininet with sucess. But when I try to run in BMV2 I'm getting an error. 

When I try to config a table with runtime_cli, I get this: 

RuntimeCmd: table_add ipv6_outer_lpm ipv6_forward fe80::1/128 => 00:00:00:00:00:01 1
Invalid match key: Error while parsing fe80::1 - Invalid IPv6 address

I already try a lot of combinations of ipv6, like: 
::
1::1
fe80:0:0:0:0:0:0:1
and probably other that I don't remember now. 

Someone can help me?

**Comment by antoninbas** [comment]
I need to update the code, but it will give this error if `ipaddr` (https://pypi.org/project/ipaddr/) cannot be imported. You may want to try installing it with pip in the meantime.

**Comment by guimvmatos** [comment]
It worked! thanks!

**Comment by guimvmatos** [comment]
I think if you just put a new line with "pip install ipaddr" in some travis script, it will solve this problem in the future.

Again, thanks for helping me.

**Comment by antoninbas** [comment]
Thanks for confirming. I'll update the code since there is built in support in Python for this now IIRC (Python 3 but also backported to Python 2). I'll close this issue after I do this.
