### ISSUE TITLE
Support configuring log rotation for bmv2 switch logs

### ISSUE THREAD

**Issue by drobinkent** [p4lang/behavioral-model#930]
When I activate the logger in bmv2 software switches, the system only keeps  last 4 log files. But I want to keep more than 4 log files. 

Can someone kindly help me about,  How to configure (where is the configuration) the system to increase the number of log files.

**Comment by antoninbas** [comment]
bmv2 currently hardcodes it (3 log files of 5MB each): https://github.com/p4lang/behavioral-model/blob/master/src/bm_sim/logger.cpp#L45

It should be very easy for someone to expose new command-line options so this can be configured at runtime. So I am going to rename your issue and tag it as a "good first issue". @drobinkent if you want to take a stab at implementing this, it would be much appreciated!

As option names, I would suggest `--log-max-files` and `--log-max-file-size`.

**Comment by drobinkent** [comment]
@antoninbas , I will certainly work on this after sometime.

**Comment by antoninbas** [comment]
This issue should not be closed. It's a valid feature request which has bot been implemented yet.

**Comment by drobinkent** [comment]
Sorry. My mistake. The closing was really not intentional.

**Comment by PreritO** [comment]
Can I take this issue?

**Comment by antoninbas** [comment]
sure thing
