### ISSUE TITLE
Hash table 5-tuple

### ISSUE THREAD

**Issue by guimvmatos** [p4lang/behavioral-model#932]
Hi guys, I'm here again. 

I think maybe this is not the best place to share my question, but I think you can help me.

I need to create a hash table to match different flows using 5 tuples, but I haven't found any documentation on this or how it works. I also have some difficulties in understanding the 'external' functions and tables.

What am I doing? I am developing a device that will extend the ipv6 header with srv6 to some flows. This already works with GTP headers, extending ipv6 based on a table with the teid field as the key

Can someone help me? I just need a good explanation or some links to help understand how 'extern' works and how I can implement it in my project. Maybe, some code examples or projects would be good too.

**Comment by guimvmatos** [comment]
I found a project in tutorial called load balance that implement that five tuple hash table that I need, but unfortunately, I don't understand. I'll paste the code with my doubts in bold

    action set_ecmp_select(bit<16> ecmp_base, bit<32> ecmp_count) {
        hash(meta.ecmp_select,       *****how does this function hash work? what are its inputs?**
	    HashAlgorithm.crc16,       *****what this line means?**
	    ecmp_base,                     **** I see that ecmp_base was declared on code, but what's its function here?
	    { hdr.ipv4.srcAddr,
	      hdr.ipv4.dstAddr,
              hdr.ipv4.protocol,
              hdr.tcp.srcPort,
              hdr.tcp.dstPort },
	    ecmp_count);

**Comment by antoninbas** [comment]
Hi - if you are asking for advice on how to write P4 programs, this is not the best place to do so. I encourage you to look at available documentation:
* [P4_16 specification](https://p4.org/p4-spec/docs/P4-16-v1.2.1.html)
* [v1model.p4](https://github.com/p4lang/p4c/blob/master/p4include/v1model.p4), which includes some comments about each extern
* [simple_switch documentation](https://github.com/p4lang/behavioral-model/blob/master/docs/simple_switch.md), simple_switch being the bmv2 implementation of the v1model architecture

If you still have questions after this, I encourage you to ask the on the P4.org [Slack](https://join.slack.com/t/p4-lang/shared_invite/enQtODA0NzY4Mjc5MTExLTRlMWVmN2I5ZTY4MTAzMDI3MGQ1OTZjM2ZmM2Q1MWE2YzZjYTQ2ZWMyMGUyYjQ2ZmIxMjFjZDE4ZThiN2ZkZWI) to get quicker and more interactive answers.

**Comment by guimvmatos** [comment]
Thanks @antoninbas for doc indications and P4 Slack link.
