### ISSUE TITLE
Copying a varbit field into a fixed-bit metadata..

### ISSUE THREAD

**Issue by castilhorosa** [p4lang/behavioral-model#941]
Hello everyone!

I have the following piece of code in my P4 application:

```
header my_varbit_header {
	varbit<32> field1;
}
...
struct headers {
	my_varbit_header mvh;
}
...
struct metadata {
	bit<32> temp;
}
```

After I parsed the header "mvh" I'd like to copy it into a metadata and padding all the remaining bits with 0's up to 32 bits.
I'm trying to do it as follows:

```
state parse_myvarbit {
	packet.extract(hdr.mvh, (bit<32>)n);    //n is a fixed-length field parsed previously from the packet
	transition padding;	
}
...
state padding {
	meta.temp = (bit<32>) hdr.mvh; //I got the error message "cast: Cannot unify header my_varbit_header to bit<32>" How could I fix it?
        //Let's suppose the bits in the packets are 01010101. At the end of this statement I want something like this:
        //meta.temp = 0b0101010100000000000000000000000000000000;	
}
```

To sum up, my question is: Is it possible to copy a varbit field into a fixed-bit metadata and padding the remaining bits with 0's?
If not, are there other ways to do this?

Thanks in advance!

**Comment by jafingerhut** [comment]
The P4_16 language does not currently provide any ability to copy varbit fields to anything other than another varbit field.  This is enough to extract it into a header, and either remove that header completely, or preserve the header in the output packet, but not enough to do anything else with it.

There is an article I've written here describing these limitations in more detail, and proposing a workaround, which is to use multiple different fixed-length headers, one for each length you care about.  https://github.com/jafingerhut/p4-guide/tree/master/variable-length-header

Using that approach might lead to repetitive code for each of the cases.  If so, there is another article giving a simple example of using tiny Python programs to generate repetitive P4 source code here which can save you some work in such cases: https://github.com/jafingerhut/p4-guide/tree/master/code-generation
