### ISSUE TITLE
about latest tag release

### ISSUE THREAD

**Issue by sequoiar** [p4lang/behavioral-model#948]
the last tag release is about one year ago. can we do a tag release with latest codes ? thx.

**Comment by antoninbas** [comment]
Thanks for opening this. I have been meaning to do this for a while, but kept postponing. I'll create one this week.

**Comment by antoninbas** [comment]
Done: https://github.com/p4lang/behavioral-model/releases/tag/1.14.0. Thanks for the reminder.
