### ISSUE TITLE
where can we find the error message"StatusCode.INVALID_ARGUMENT, Invalid P4 id"

### ISSUE THREAD

**Issue by lyupengpublish** [p4lang/behavioral-model#952]
Hi  @jafingerhut  do you know where we can find the message "StatusCode.INVALID_ARGUMENT, Invalid P4 id" ?

**Comment by jfingerh** [comment]
@lyupengpublish There is an error message like that in this repository that you can search through the source files to find it: https://github.com/p4lang/PI

**Comment by lyupengpublish** [comment]
thank you 😀

**Comment by lyupengpublish** [comment]
can you help me? @antoninbas

**Comment by jafingerhut** [comment]
@lyupengpublish Sorry, I did not notice your message a few days ago.

Have you made a copy of all of the p4lang repositories, or at least p4c, behavioral-model, PI?

If so, a command on Linux or macOS like the following can search the code very quickly on your local system.  The command below was run from the root directory of my local copy of the behavioral-model repository.  This is pretty standard software developer technique here that I would recommend becoming experienced at using:
```
$ grep -r 'Invalid match key' *
targets/l2_switch/runtime_CLI:            print("Invalid match key:", e)
targets/simple_switch/runtime_CLI:            print("Invalid match key:", e)
targets/psa_switch/runtime_CLI:            print("Invalid match key:", e)
targets/simple_router/runtime_CLI:            print("Invalid match key:", e)
tools/runtime_CLI.py:            print("Invalid match key:", e)
```

**Comment by lyupengpublish** [comment]
thanks
