### ISSUE TITLE
Calling BMv2 simple_switch periodic externs inside P4 code

### ISSUE THREAD

**Issue by harshgondaliya** [p4lang/behavioral-model#953]
Commit [1ac93d8](https://github.com/p4lang/behavioral-model/commit/1ac93d8f55a645537e03623c57e650e1d7d3f004) added support for periodic externs to BMv2 simple_switch target.
I want to use BMv2 simple_switch target and v1model architecture to use these periodic externs.
Is there any documentation that describes how these externs can be used in my P4 code? Like the syntax, naming, etc. 
Please shed some light on this.

P.S. Sorry for the wrong link. Updated the link and commit number.

**Comment by jafingerhut** [comment]
The commit you link to adds a paragraph of documentation about the v1model architecture, not any externs.

I am not sure what periodic externs you are referring to, so finding the correct commit might help jog the memory.

**Comment by harshgondaliya** [comment]
I have updated the link.

**Comment by antoninbas** [comment]
The PR description includes an example: https://github.com/p4lang/behavioral-model/pull/665

But I think there is a misunderstanding as to what this functionality is for. It is a convenience feature for folks who want to implement new extern types in bmv2. It is not used for any extern which is part of the v1model architecture. It is meant to perform asynchronous / periodic tasks, independently of P4 packet processing. One basic example would be if you want to define a new `CounterWithReset` extern type (different from the `counter` extern type which is part of v1model), which resets itself to 0 every 10 seconds, you could implement the reset functionality by leveraging `REGISTER_PERIODIC_ACTION`, introduced in #665. The reset frequency could be exposed as an extern constructor parameter, in which case you would specify it when instantiating the extern in the P4 program. But the reset implementation would execute independently of P4 packet processing.

There are multiple discussion threads available online about how to extend v1model to implement custom extern types. However this is not very well documented and most people consider it not to be very straightforward.

**Comment by harshgondaliya** [comment]
Thanks Antonin! I have understood the convenience feature that the above commit added.

I am looking for a BMv2 feature/function that can help me generate packets and send them into the pipeline.
I want to invoke that `generatePkt()` function periodically using `REGISTER_PERIODIC_ACTION` so that I am able to periodically generate and send packets into the ingress pipeline.

If such a feature/function is available, can you please point me to its code?

**Comment by antoninbas** [comment]
You can define your extern as in the https://github.com/p4lang/behavioral-model/pull/665 example, with a `generatePacket` static method that will be called periodically. The you have to solve these 2 issues:

 1. injecting packets in the data pane. I think the right way to do it is:
    - Modify the `SimpleSwitch::InputBuffer` to support your generated packets
https://github.com/p4lang/behavioral-model/blob/50f017865bcf0e204a37e26aa4a1f9e78b040332/targets/simple_switch/simple_switch.cpp#L122
    - Add a public method to `SimpleSwitch`, e.g. `inject_generated_packet`. This method will in turn call `SimpleSwitch::InputBuffer::push_front`, with your new packet type as an argument.
    - In your implementation of `generatePacket` in the extern type, make sure you can grab the pointer to the `SimpleSwitch` object so you can call the public method defined above
https://github.com/p4lang/behavioral-model/blob/50f017865bcf0e204a37e26aa4a1f9e78b040332/targets/simple_switch/main.cpp#L33

 2. supporting your extern in P4 / p4c. You'll have to do some digging here but the main steps should be these:
    - define your extern type in P4, with a constructor (no other methods required); the constructor could take the period as a parameter if you want to be fancy
    - instantiate your extern at the top-level of the P4 program
    - call `p4c-bm2-ss` with `--emit-externs` to compile your program for bmv2; this should ensure that the generated JSON will include your extern, but you will probably want to check manually that this is the case

For 1, there is a simpler solution that doesn't involve modifying `SimpleSwitch` or `SimpleSwitch::InputBuffer`. You can directly call the `receive` method on the `Switch` object. It depends on whether you want to treat these packets differently from regular traffic (e.g. prioritize them differently) or not. You can look at the code and decide. https://github.com/p4lang/behavioral-model/blob/50f017865bcf0e204a37e26aa4a1f9e78b040332/include/bm/bm_sim/switch.h#L114

That's pretty much the extent of the help I can provide for this, so hopefully it will be enough to point you in the right direction.

**Comment by harshgondaliya** [comment]
Yes Antonin, that is really helpful. I will work in that direction. 
I am closing this thread as the original issue is solved now.
