### ISSUE TITLE
Should scripts like simple_switch_CLI use `/usr/bin/env python3` instead of `/usr/bin/env python` ?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/behavioral-model#958]
Given all the recent updates to use Python3 in various p4 packages, I tried creating a variant of my bash install script to see if I could install and test all open source P4 dev tools on Ubuntu 20.04, where Python2 was never installed.

It turns out that the current way it installs the mininet software does cause Python2 to be installed, but I'm sure I can figure out how to disable that, and that happens near the very end of my script, anyway, after all other open source P4 tools are built and installed.  So far, so good!

I end up with a system that has a `/usr/bin/python3` executable, but no `python` executable anywhere in the command path.

Several Python programs in the behavioral-model repo are installed with this line first `#! /usr/bin/env python`.  Those fail on this system.

I see a couple of possible approaches, at least:

+ recommend that people install a Python3 executable as `/usr/bin/python`
+ change those scripts to use `/usr/bin/env python3` instead

There might be other good ideas besides those that I'm not thinking of.

Thoughts?

**Comment by rst0git** [comment]
[PEP 394](https://www.python.org/dev/peps/pep-0394/) recommends using `python3` instead of `python`

**Comment by antoninbas** [comment]
That sounds good to me. If we decide to drop support for Python2 altogether (which I think we should do) we can probably clean-up some of the scripts to remove the code that was introduced to support both versions simultaneously.

**Comment by jafingerhut** [comment]
This PR should do at least some of the job.  We'll see what Travis does with it.  I have never installed on macOS before, only Linux, and don't plan to start trying macOS builds any time soon.  The commit comment lists a few places that might still need updating.

**Comment by jafingerhut** [comment]
Perhaps this issue can be closed, since this commit in 2020-Dec probably addressed it?  https://github.com/p4lang/behavioral-model/commit/a6330594486261b87560881ad2fd7db35f13ddfd
