### ISSUE TITLE
Error during flow rules isntallation 

### ISSUE THREAD

**Issue by Dscano** [p4lang/behavioral-model#964]
Hi,

Today I installed bmv2 in a new virtual machine that have as OS Ubuntu 16.04. When I try to use this command `simple_switch_CLI --thrift-port 9090 --json main.json < Commands_s1` I get this error:
`Error when requesting config md5 sum from switch`.  But if I use `simple_switch_CLI --thrift-port 9090` I can insert the flow rules in the switch.
Can you help me?

**Comment by antoninbas** [comment]
Thanks for reporting this and sorry for the delay. I was able to reproduce the issue and I submitted a patch.

Note that using `--json main.json` will not buy you much: the JSON configuration can be retrieved from the switch by the CLI. When you provide your own, it just makes sure that the JSON you provide and the one currently used by the switch do indeed match by comparing their md5 checksum.
