### ISSUE TITLE
thrift/Thrift.h not found

### ISSUE THREAD

**Issue by BYGX-wcr** [p4lang/behavioral-model#968]
Hi,

I just wanted to install p4 behavioral-model in my Ubuntu 20.04 VM. I have successfully installed the Apache Thrift but when I run *./configure* script, it still persistently output an error "configure: error: Thrift headers not found. Install Thrift from http://thrift.apache.org/docs/install/". Can you provide any hint to solve this problem?
Here is the snapshot
![image](https://user-images.githubusercontent.com/30227319/101502190-a1b33800-39ab-11eb-8c75-58e55f8d0e69.png)

Plus, I have tried manually copying the thrift headers to the *include/bm/thrift* directory under behavioral-model repo. It didn't work. Where should these headers are?

**Comment by rst0git** [comment]
Hi @BYGX-wcr, you can find installation steps for Thrift in the following script:
https://github.com/p4lang/behavioral-model/blob/master/travis/install-thrift.sh

The are a few other dependencies that you might need to install as well. A complete BMv2 installation script is available in
https://github.com/p4lang/tutorials/blob/master/vm/user-bootstrap.sh

**Comment by BYGX-wcr** [comment]
Thanks for your reply. In fact, I used the script that you mention to install the thrift. But after the installation succeed, the configure script still reported that error.

I also tried the user-bootstrap.sh, but it seems that it contains extra gRPC dependency and when the script installed gRPC, there are always some compliation errors. Is gPRC neccessary? Your README document of behavioral-model didn't mention it.

**Comment by jafingerhut** [comment]
There is a different (still experimental) bash script to install many of the open source P4 development tools on an Ubuntu 20.04 system if you follow the instructions here: https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md

NOTE: the name of the script recommended in those instructions is install-p4dev-v2.sh, which has been well tested on Ubuntu 16.04 and 18.04, but does not work with Ubuntu 20.04.  Replace the `v2` with `v4` to get the experimental version of the script that I have tested on Ubuntu 20.04 and seen some decent success.  If you want to use the p4lang/tutorials code with such an installation, you will need to update the p4lang/tutorials Python code from Python2 to Python3, which this patch is a _start_ at, but may very well be incomplete:

https://github.com/jafingerhut/p4-guide/blob/master/bin/patches/tutorials-python3-changes1.patch

e.g. you can apply those patches using these commands:

```bash
git clone https://github.com/jafingerhut/p4-guide
git clone https://github.com/p4lang/tutorials
cd tutorials
patch -p1 < ../p4-guide/bin/patches/tutorials-python3-changes1.patch
```

**Comment by BYGX-wcr** [comment]
@jafingerhut Thanks for your help! I have successfully installed the p4 suite in Ubuntu 16.04 and after that I tried reinstalling thrift in Ubuntu 20.04. Then it worked... Yet, I think your experience and scripts are very useful for developers who want to use the p4 suite in newer OS.
