### ISSUE TITLE
Does BMv2 switch also support SNMP stats?

### ISSUE THREAD

**Issue by sbibek** [p4lang/behavioral-model#970]
Hi,

Wanted to know if the BMv2 switch supports SNMP statistics for my project.

Thanks
B.

**Comment by jafingerhut** [comment]
If by "supports SNMP statistics" you mean: "Can I use a client program to read stats via the SNMP protocol, and use it to communicate directly with the simple_switch or simple_switch_grpc processes to read statistics?", I am pretty sure the answer is "no".

If you mean "Can I write my own P4 controller software that communicates with a P4-programmable switch, reads statistics using the Thrift or P4Runtime API protocols that simple_switch and simple_switch_grpc supports, and if I wish and go to the effort myself, develop code in my controller software that lets other processes read statistics from my controller software using SNMP?", then the answer is "yes, if you develop the SNMP server side software yourself, or adapt it from some other software project you have access to".

**Comment by sbibek** [comment]
Thanks, that answers my question.
