### ISSUE TITLE
Setting parameters in default action..

### ISSUE THREAD

**Issue by castilhorosa** [p4lang/behavioral-model#972]
Hi folks,

I have the following table and actions in my P4 program:

```
action action1(bit<8> param_from_control_plane) {
	//I want to execute this action when a hit occurs
	//It seems ok here
}

action action2(bit<8> param_from_control_plane) {
	//I'd like to use the parameter from control plane to to something here when the matching results in a miss 
}

table my_table {
	key = {
		hdr.my_field.f1 : exact;
	}
	actions = {
		action1;
		action2;
	}
	size = 512;
	default_action = action2;
}
```

In my understanding, when the apply operation on my_table results in a miss, action2 is going to be executed, right? Is the control plane software able to dynamically add entries into my_table in a way that I can capture these parameters in action2, when a miss occurs? I'd like to execute some operations with such parameters in a case of a "miss". How can I do that, if it is possible at all?

When I try to compile the code above I get the following error:

```
my_program.p4(267): [--Werror=type-error] error: param_from_control_plane: parameter should be assigned in call action2
   action action2(bit<8> param_from_control_plane) {
                         ^^^^^^^^^^^^^^^^^^^^^^^^
my_program.p4(308)
 default_action = action2;
                  ^^^^^^^
```

Among other things, the document in [https://github.com/jafingerhut/p4-guide/blob/master/docs/p4-table-behaviors.md](url) says:

> There are two kinds of modifications that control plane software can make to the contents of a table at run time:

> Add, remove, or modify table entries, each entry with its own key, action name, and action parameters.

> Modify the action name and action parameters that are the default action of the table.

The last statement is making me to believe (I may be misinterpreting) that is possible to have default action with parameters.

Thanks.

**Comment by antoninbas** [comment]
This is not the right place to open such an issue, as it's not related to this repository, but more to the P4 language and compiler toolchain.

In your case, the error message indicates that line 308 is incorrect. You are trying to set `action2` as the default action in your P4 program, without providing a value for `param_from_control_plane`. So what will happen if a miss occurs before you get a chance to set that value from the control-plane? You need to provide a placeholder value until you can change it from the control-plane. For example: `default_action = action2(8w0)`. Or you can omit the `default_action` property altogether, in which case the default action will default to `NoActiom` (no-op) until you change it from the control-plane.

**Comment by castilhorosa** [comment]
> This is not the right place to open such an issue, as it's not related to this repository, but more to the P4 language and compiler toolchain.
> 
> In your case, the error message indicates that line 308 is incorrect. You are trying to set `action2` as the default action in your P4 program, without providing a value for `param_from_control_plane`. So what will happen if a miss occurs before you get a chance to set that value from the control-plane? You need to provide a placeholder value until you can change it from the control-plane. For example: `default_action = action2(8w0)`. Or you can omit the `default_action` property altogether, in which case the default action will default to `NoActiom` (no-op) until you change it from the control-plane.

I got it. Thanks @antoninbas
