### ISSUE TITLE
Can bmv2 pause a flow?

### ISSUE THREAD

**Issue by ymj0808** [p4lang/behavioral-model#973]
I want implement some congestion control rules on bmv2 switch， but I don't konw how to pause a flow or keep packets in the buffer? Thanks!

**Comment by jafingerhut** [comment]
As far as I know, bmv2 has no feature built into it today that would cause a particular queue in the packet buffer to stop scheduling packets.  Such a feature could be implemented by appropriate changes to the C++ code implementing BMv2, of course.

**Comment by ymj0808** [comment]
> As far as I know, bmv2 has no feature built into it today that would cause a particular queue in the packet buffer to stop scheduling packets. Such a feature could be implemented by appropriate changes to the C++ code implementing BMv2, of course.

Thank you, and I have another question,  how can I get the BMv2's system time?

**Comment by jafingerhut** [comment]
Does this section of the simple_switch documentation answer your question?  (the entire document is worth a read if you are writing P4 code for the v1model architecture): https://github.com/p4lang/behavioral-model/blob/master/docs/simple_switch.md#bmv2-timestamp-implementation-notes

**Comment by ymj0808** [comment]
> Does this section of the simple_switch documentation answer your question? (the entire document is worth a read if you are writing P4 code for the v1model architecture): https://github.com/p4lang/behavioral-model/blob/master/docs/simple_switch.md#bmv2-timestamp-implementation-notes

I have read this before,  I mean to how to get current time in my P4 program.

**Comment by jafingerhut** [comment]
When you say 'get the current time', realize that there are about 17 different ways of getting time in different programming languages, Linux APIs, the Linux kernel, etc.  So being precise helps.

When you say 'get the current time', do you mean something like the Linux system call gettimeofday?   https://man7.org/linux/man-pages/man2/gettimeofday.2.html

Something else?

In any case, the only thing implemented _today_ in BMv2's C++ code are the ingress and egress timestamp intrinsic metadata values in the link that I mentioned above.  Nothing else is currently implemented.

Could you implement other notions of getting time in BMv2?  Sure, if you modify the appropriate C++ code in the p4lang/behavioral-model repository.

Will changing BMv2 change the behavior of any real hardware switches that are P4-programmable?  No, it will not.  It will only change the behavior of the BMv2 software switch.

**Comment by ymj0808** [comment]
I'm clear about it, thank you for your help and patience.
