### ISSUE TITLE
bmv2 does not support psa checksum

### ISSUE THREAD

**Issue by sunbin21** [p4lang/behavioral-model#974]
I'm trying to use bmv2 to compile a psa code with checksum. however, it semms that behavioral-model can not deal with psa checksum. I'm confused because I don't konw whether behavioral-model can'suppoet this checksum or something was wrong in my code. Currently if I comple my code, I got these following error message:
```
parser IngressParserImpl(packet_in buffer,
                         out headers parsed_hdr,
                         inout metadata user_meta,
                         in psa_ingress_parser_input_metadata_t istd,
                         in empty_t resubmit_meta,
                         in empty_t recirculate_meta)
{
    CommonParser() p;
    Checksum<bit<16>>(PSA_HashAlgorithm_t.CRC16) ck;
    state start {
        p.apply(buffer, parsed_hdr, user_meta);

	ck.clear();
	ck.update({ parsed_hdr.ipv4.version,
	      parsed_hdr.ipv4.ihl,
              parsed_hdr.ipv4.diffserv,
              parsed_hdr.ipv4.totalLen,
              parsed_hdr.ipv4.identification,
              parsed_hdr.ipv4.flags,
              parsed_hdr.ipv4.fragOffset,
              parsed_hdr.ipv4.ttl,
              parsed_hdr.ipv4.protocol,
              parsed_hdr.ipv4.srcAddr,
              parsed_hdr.ipv4.dstAddr });
	parsed_hdr.ipv4.hdrChecksum = ck.get();
	ck.clear();

        transition accept;
    }
}
```
```
forwarding_task_psa_untilnow.p4(93): [--Werror=unsupported] error: ck.clear: not supported in parser on this target
 ck.clear();
 ^^^^^^^^^^
forwarding_task_psa_untilnow.p4(94): [--Werror=unsupported] error: ck.update: not supported in parser on this target
 ck.update({ parsed_hdr.ipv4.version,
 ^
In file: /home/myp4/p4/p4c/backends/bmv2/common/expression.cpp:97
Compiler Bug: forwarding_task_psa_untilnow.p4(105): ck_0/ck;: could not convert to Json
 parsed_hdr.ipv4.hdrChecksum = ck.get();
                               ^^
```

what's more, my Compilation options are "p4c-bm2-psa" because "p4c --arch psa" cannot run correctly and compiler shows that "arch psa not implement"
` sudo p4c-bm2-psa forwarding_task_psa_untilnow.p4 -o success.json`

**Comment by antoninbas** [comment]
The PSA `Checksum` extern is not implemented (yet) in PSA, so the message from the compiler is accurate. See https://github.com/p4lang/behavioral-model/tree/master/targets/psa_switch/externs for implemented externs.

I have no plans in the near future to improve the bmv2 PSA implementation. Whatever limited time I have to work on P4 software, I typically use it to maintain existing bmv2 / P4Runtime code and fix bugs. We welcome contributions to the PSA implementation.

**Comment by jafingerhut** [comment]
The implementation of the PSA architecture in both the open source p4lang/behavioral-model and p4lang/p4c repositories is definitely only partial today.  A few volunteers did make some progress in making more things work during 2020, and we have not had meetings in a while to keep up with status of those (very part time volunteer) efforts, but I believe the document at the link below might be close to the current status of passing test cases for the PSA architecture that work:

https://github.com/jafingerhut/p4-guide/tree/master/psa-test-info
