### ISSUE TITLE
Question about bmv2's internal behavior when setInvalid() and clone() is called.

### ISSUE THREAD

**Issue by GordonWuCn** [p4lang/behavioral-model#975]
Hi,

The question I have is related to how bmv2 manages header fields internally. The situation is: first, `hdr1.setInvalid()` is called. Then `clone()` is called in the egress. For the cloned packet, is it possible that I restore hdr1 by calling `hdr1.setValid()`? I was wondering how `clone()` handles header copying. Will `clone()` copy headers that have been set to invalid? Or `clone()` only copies headers that are valid when the packet approaches the end of the egress(Assuming `clone()` is called in egress.) Thanks!

**Comment by jafingerhut** [comment]
Note: I have not tried this.  I am giving my best educated guesses here.  If it is important to you, I would recommend creating a small test program that tries the behavior you are interested in, and test it with a few packets to see if you understand the behavior, and ask questions about any behavior that seems wrong.

"For the cloned packet, is it possible that I restore hdr1 by calling hdr1.setValid()?"   You can call `hdr1.setValid()` on a header where `hdr1.setInvalid()` was called earlier, yes, but this does not restore the original values of all of the fields (except perhaps by a lucky accident).   After the `hdr1.setInvalid()` call, all field values are uninitialized garbage, and must be initialized by your program, if you care what their values are.  That is true for P4_16 in general, whether you are doing clone operations or not.

The rest of this is specific to the v1model architecture.  If you are using a different architecture, consult its documentation.  If you are using the v1model architecture, I would recommend reading everything it has to say about clone operations and see if it answers any of your questions: https://github.com/p4lang/behavioral-model/blob/master/docs/simple_switch.md

When you do a clone operation in egress, the clone copy is _not created immediately_.  The full egress control code continues executing on the original packet after the clone operation is invoked until egress processing is complete, then the deparser executes, which takes all currently valid headers, and emit's them in the order the emit calls appear in your deparser.

When the deparser is finished, the clone packet(s) are created, and a separate decision is made to send the original packet to its output port or drop it.  For the clone(s), 0 of them are created if you have not configured the mirror session yet, or 1 of them if you've configured it for a single port, or 0 or more clones if you have configured the mirror session to use a multicast group to replicate the cloned packet multiple times.  Just as any other packets that are put into a queue in the traffic manager/packet buffer, it might be arbitrarily long before those cloned copies begin egress processing, or it might be very soon.

The v1model architecture does not have an egress parser like the PSAarchitecture does, so it isn't 100% clear to me exactly which headers will be valid/invalid when the clones begin egress processing again.  I believe they will be exactly the headers that were valid / invalid at the time the oroginal packet finished its egress processing.  The precise behavior is not well documented, that I know of.  Perhaps you can help clarify it with some experiments?
