### ISSUE TITLE
Runtime Index - No packets received

### ISSUE THREAD

**Issue by fruffy** [p4lang/behavioral-model#976]
Sourced from https://github.com/p4lang/p4c/pull/2661. 
I have several test programs, which use runtime indices and header stacks. Unfortunately, they do not seem to work on simple switch. The received packets are not sent back out. Some of the packets may have an out-of-bounds header stack access. Is there something wrong with the way these programs are structured? 

This is the message for `gauntlet_index_1-bmv2.p4` for example:
```bash
STF Command: packet 0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 20 00 00 00 00 00 00 00 00 0
*** Invalid packet data 00000000000000000000000000002000000000000000000
STF Command: expect 0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 20 00 00 00 00 00 00 00 00 1
STF Command: packet 0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 10 00 00 00 00 00 00 00 00 0
*** Invalid packet data 00000000000000000000000000001000000000000000000
STF Command: expect 0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 10 00 00 00 00 00 00 00 00 1
STF Command: packet 0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 1
*** Invalid packet data 00000000000000000000000000000000000000000000001
STF Command: expect 0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 10 00 00 00 1
Obtaining JSON from switch...
Done
Control utility for runtime P4 table manipulation
RuntimeCmd: 
simple_switch exit code -15
Execution completed
Comparing outputs
*** Expected 3 packets on port 0 got 0
*** Full list of 3 expected packets on port 0:
***     packet # 1: 00000000000000000000000000002000000000000000001
***     packet # 2: 00000000000000000000000000001000000000000000001
***     packet # 3: 00000000000000000000000000000000000000100000001
```

[gauntlet_index_1-bmv2.stf.txt](https://github.com/p4lang/behavioral-model/files/5905630/gauntlet_index_1-bmv2.stf.txt)
[gauntlet_index_1-bmv2.p4.txt](https://github.com/p4lang/behavioral-model/files/5905631/gauntlet_index_1-bmv2.p4.txt)
[gauntlet_index_3-bmv2.p4.txt](https://github.com/p4lang/behavioral-model/files/5905622/gauntlet_index_3-bmv2.p4.txt)
[gauntlet_index_3-bmv2.stf.txt](https://github.com/p4lang/behavioral-model/files/5905627/gauntlet_index_3-bmv2.stf.txt)
[gauntlet_index_7-bmv2.p4.txt](https://github.com/p4lang/behavioral-model/files/5905623/gauntlet_index_7-bmv2.p4.txt)
[gauntlet_index_7-bmv2.stf.txt](https://github.com/p4lang/behavioral-model/files/5905628/gauntlet_index_7-bmv2.stf.txt)
[gauntlet_index_8-bmv2.stf.txt](https://github.com/p4lang/behavioral-model/files/5905629/gauntlet_index_8-bmv2.stf.txt)
[gauntlet_index_8-bmv2.p4.txt](https://github.com/p4lang/behavioral-model/files/5905624/gauntlet_index_8-bmv2.p4.txt)

This one simply crashes simple_switch:
[gauntlet_index_10-bmv2.p4.txt](https://github.com/p4lang/behavioral-model/files/5905625/gauntlet_index_10-bmv2.p4.txt)
[gauntlet_index_10-bmv2.stf.txt](https://github.com/p4lang/behavioral-model/files/5905626/gauntlet_index_10-bmv2.stf.txt)

**Comment by antoninbas** [comment]
This seems to be a duplicate of https://github.com/p4lang/behavioral-model/issues/978. As far as I can tell, all you rinput packets are invalid, as reported by the STF framework.

**Comment by fruffy** [comment]
Ah I was a bit too hasty with blaming simple_switch, apologies. Fixed up the issues on my end, but there are still two tests that crash with exit code -6. What could cause this? 

```bash
Running simple_switch_CLI --thrift-port 9148                                                                         
STF Command: packet 0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 40                                             
STF Command: expect 0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 40                                             
STF Command: packet 0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00                                             
STF Command: expect 0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ** 00 00                                             
STF Command: packet 0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 20                                             
STF Command: expect 0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ** 20                                             
*** simple_switch died with return code -6                                                                           
*** CLI process failed with exit code 1    
```


[gauntlet_index_3-bmv2.p4.txt](https://github.com/p4lang/behavioral-model/files/5907554/gauntlet_index_3-bmv2.p4.txt)
[gauntlet_index_3-bmv2.stf.txt](https://github.com/p4lang/behavioral-model/files/5907556/gauntlet_index_3-bmv2.stf.txt)

[gauntlet_index_10-bmv2.p4.txt](https://github.com/p4lang/behavioral-model/files/5907552/gauntlet_index_10-bmv2.p4.txt)
[gauntlet_index_10-bmv2.stf.txt](https://github.com/p4lang/behavioral-model/files/5907553/gauntlet_index_10-bmv2.stf.txt)

**Comment by antoninbas** [comment]
Is there any chance you can provide the generated JSON files for these?

**Comment by fruffy** [comment]
Attached. 
[gauntlet_index_3-bmv2.json.txt](https://github.com/p4lang/behavioral-model/files/5907758/gauntlet_index_3-bmv2.json.txt)
[gauntlet_index_10-bmv2.json.txt](https://github.com/p4lang/behavioral-model/files/5907759/gauntlet_index_10-bmv2.json.txt)

**Comment by antoninbas** [comment]
I looked at the first one, the crash is because of an out-of-bound access:
```
[19:58:56.748] [bmv2] [D] [thread 988856] [0.0] [cxt 0] Table 'tbl_act': miss
[19:58:56.748] [bmv2] [D] [thread 988856] [0.0] [cxt 0] Action entry is act - 
[19:58:56.748] [bmv2] [T] [thread 988856] [0.0] [cxt 0] Action act
[19:58:56.748] [bmv2] [T] [thread 988856] [0.0] [cxt 0] Primitive (no source info)
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 2) >= this->size() (which is 2)
Aborted
```
I purposefully crash the bmv2 process in that case, mostly to ensure it doesn't go unnoticed. Maybe an error log would make more sense (plus returning an undefined value), but then folks may miss that something is wrong with their program / test packets.

**Comment by fruffy** [comment]
So the out-of-bounds access in these programs is intentional as part of the test. Unfortunately, there does not seem to be a way to check for crashes with stf. I can restrict the index of these programs, but then we would never test for invalid access in the bmv2 models.

The spec says
`Accessing a header stack hs with an index less than 0 or greater than hs.size results in an undefined value. See Section 8.22 for more details. `

p4c should probably warn (if it not already does) about values that can potentially be out-of-bounds?

**Comment by jafingerhut** [comment]
So thinking of bmv2 as a debug/development tool for P4, the default behavior of crashing on out-of-bounds access definitely seems reasonable.

At least for this kind of 'does it meet the spec' kinds of corner case tests that @fruffy is developing, would it be reasonable if there was a command line option when starting simple_switch/simple_switch_grpc that would cause not a crash/exit on out-of-bounds access, but a warning/error in the log, and always reading some value like 0?   It seems a bit overboard to have it return some randomly generated value, if this is a non-default explicitly-requested mode intended for corner case spec testing.

**Comment by jafingerhut** [comment]
@fruffy I thought that p4c already gave a compile-time error if a header stack index was a compile-time known value that was out of bounds, but a quick test seemed to show that it does not.  I will double check that with latest version of p4c, and file an issue on that if there is no compile-time error with latest.

For index expressions that are not compile-time known values, in general it isn't knowable whether the index is in range or not, e.g. if the run-time index comes from a header field of an input packet.

**Comment by jafingerhut** [comment]
@fruffy FYI, for compile-time known value headers stack indexes, if they are out of range then p4c does give a compile-time error, e.g. this test case just added to p4c: https://github.com/p4lang/p4c/pull/2666

**Comment by fruffy** [comment]
Thanks for checking, @jafingerhut! p4c, however, does not complain if a runtime index could potentially be out of range, right? 

So, I actually have a question on the validity of these accesses:

Considering an assignment like the one in this program:

```p4
header ethernet_t {
    bit<48> dst_addr;
    bit<48> src_addr;
    bit<16> eth_type;
}

header H {
    bit<8> a;
}

struct Headers {
    ethernet_t eth_hdr;
    H[2]  h;
}

parser p(packet_in pkt, out Headers hdr) {
    state start {
        transition parse_hdrs;
    }
    state parse_hdrs {
        transition accept;
    }
}

control ingress(inout Headers h) {
    apply {
        h.h[h.eth_hdr.eth_type] = {2};
    }
}
```
Will the entire `h.h` now be undefined? What about `h.h[h.eth_hdr.eth_type].a = 2`? Will the entire `h.h` be again undefined?

**Comment by mbudiu-vmw** [comment]
There is a discussion in the spec about "blast radius" of using invalid values, but I don't think it mentions stacks.

**Comment by fruffy** [comment]
```
If any of these kinds of writes are performed:

    a write to a field in a currently invalid header, either a regular header or an element of a header stack with an index that is in range, and that header is not part of a header_union
    a write to a field in an element of a header stack, where the index is out of range
    a method call of setValid() or setInvalid() on an element of a header stack, where the index is out of range 

then that write must not change any state that is currently defined in the system, neither in header fields nor anywhere else. In particular, if an invalid header is involved in the write, it must remain invalid. 
```
I guess the implication is that nothing happens?

**Comment by mbudiu-vmw** [comment]
Yes, the implication seems to be that accessing an invalid index will not modify any of the existing elements.

**Comment by jafingerhut** [comment]
@fruffy In the example code snippet you gave, there appears to be no initialization of `h.eth_hdr.eth_type`, which is then used as an index to `h.h`.  I believe that a careful reading of the spec says that an implementation can read any value of type `bit<16>` when reading `h.eth_hdr.eth_type`, so any value in the range [0, 65535].

If that value happens to be in the range [0, 1], then it is in range of your example header stack with 2 elements, and might change the state of the header stack in a way that you would expect for an in-range access.

If that value happens to be out of the range [0, 1], then as the parts of the spec you quoted indicate, no currently-defined state should be changed.  (undefined values can change unpredictably at any time, not just when such assignments occur)

I could imagine a compiler warning if it can statically determine that a run-time variable header index expression might be out of range, but I am not sure that is on the top 50 list of things to change in p4c :-)

It would be good if simple_switch could correctly implement the spec behavior, as Antonin mentions above in this comment: https://github.com/p4lang/behavioral-model/issues/976#issuecomment-772156671

**Comment by jafingerhut** [comment]
I am marking this as a good first issue if someone was interested in implementing a command line option for simple_switch / simple_switch_grpc such that it could behave in one of two modes:

+ the current one, where an out-of-bounds header stack index caused bmv2 to print a descriptive error message and abort execution immediately
+ the more spec-compliant behavior, which is to make no change to any header fields at all, and continue execution normally.  It would be very good to print a warning message in the log file with the line of code where this happened, and what the out of bounds index value was, for those who want to be notified of this and potentially change their P4 programs not to do so any longer.
