### ISSUE TITLE
Question about expected output when all headers are invalid

### ISSUE THREAD

**Issue by fruffy** [p4lang/behavioral-model#977]
Sourced from p4lang/p4c#2661.

I have a test in which all headers are set to invalid. I would expect there to be no packet output. However, when I run STF tests I receive 
`0 02000000`
What does this mean? Do STF tests require Ethernet headers to always be valid?

[gauntlet_invalid_hdr_short_circuit-bmv2.stf.txt](https://github.com/p4lang/behavioral-model/files/5905546/gauntlet_invalid_hdr_short_circuit-bmv2.stf.txt)
[gauntlet_invalid_hdr_short_circuit-bmv2.p4.txt](https://github.com/p4lang/behavioral-model/files/5905547/gauntlet_invalid_hdr_short_circuit-bmv2.p4.txt)

**Comment by jafingerhut** [comment]
I don't have full details/knowledge here, but many physical Ethernet ports do not permit sending packets shorter than a 64-byte minimum frame length, and/or if you try to do so, they pad them up to that minimum length.

The veth interfaces in Linux, as far as I have seen, DO allow sending packets shorter than 64 bytes, and pass them along to the other side without any padding.

I have never tried to send a 0-byte packet on a veth before, though.  I wouldn't be surprised if veth interfaces have a different support minimum frame length shorter than 64 bytes, e.g. perhaps 14 bytes?

**Comment by fruffy** [comment]
Right, that is probably the reason. What is the best way to resolve this? Never write tests that have zero output or implement a check that drops packets with zero length?

**Comment by antoninbas** [comment]
You should check the packets received and sent by bmv2 using the `--dump-packet-data 64` command line argument. This will tell you if there is an issue with your P4 program / p4c / bmv2, or if this is normal Linux behavior.

I would recommend using a minimum packet size of 20 or so bytes. I am not sure what sending a 0-byte packet means. I would actually expect libpcap to complain if you try to send an empty packet, but maybe it doesn't.

**Comment by jafingerhut** [comment]
I had a small test program in Python3 using the Scapy library to determine whether the Linux kernel version one is running had a certain bug where it added 14 bytes to packets sent on veth interfaces, and it was quick to make a new test program from its code that tries using Scapy to send packets to veth interfaces on Linux that are several different sizes, some shorter than 14 bytes.  The results are here, in case anyone is curious: https://github.com/jafingerhut/p4-guide/tree/master/linux-veth-bug#what-do-linux-veth-interfaces-combined-with-scapy-do-with-short-packets

Summary: It seems that packets shorter than 14 bytes cause the Scapy `Ether()` method to fail with an exception, unless they are 0 bytes long, in which case it seems to pad them up to 60 bytes on the veth interface.  Packets at least 14 bytes long, but less than 60 bytes long, are _not_ padded.

**Comment by fruffy** [comment]
Thank you for looking into this. I changed the p4c test to include a fixed packet header.
