### ISSUE TITLE
Cloned packets are dumped into "in" pcap files

### ISSUE THREAD

**Issue by danushkam** [p4lang/behavioral-model#980]
I used the following command line to start the switch.

`sudo simple_switch_grpc -i 1@enp6s0f2 -i 2@enp6s0f1 -i 3@enp6s0f0 -i 4@enp4s0f0 --pcap pcaps/ build/switch.json --log-console --thrift-port 9090 -- --grpc-server-addr 0.0.0.0:50051 --cpu-port 192`

**Comment by jafingerhut** [comment]
Are clone packets any different in this regard from other output packets?  If clone packets and other output packets are in the same file, then things might be working as intended here, albeit perhaps with confusing file names.

**Comment by antoninbas** [comment]
Thanks, I have confirmed that this is indeed happening. Not just for cloned packets, the "in" and "out" files are swapped because of a typo.
