### ISSUE TITLE
Support enums in bmv2

### ISSUE THREAD

**Issue by konne88** [p4lang/behavioral-model#982]
I'd like to assign a hash algorithm to a variable, and then use it later in a hash computation. Unfortunately, this fails with:

```
type not yet handled on this target

enum HashAlgorithm {
     ^^^^^^^^^^^^^
```

would it be easy to add support for this?

**Comment by antoninbas** [comment]
Andy is correct. Typically the hash algorithm has to be known at compile time. This is unrelated to enum support in general.
Unfortunately this is not always clear when using the v1model architecture:
```
extern void hash<O, T, D, M>(out O result, in HashAlgorithm algo, in T base, in D data, in M max);
```

In PSA, hash algorithms (`PSA_HashAlgorithm_t` enum members) are passed to extern *constructors*, and the language ensures that these are compile-time values. There is no such guarantees for extern function parameters, but this is really a failing of the v1model architecture.

bmv2 supports runtime-configurable CRCs, when selecting `crc32_custom` or `crc16_custom` as the compile-time algorithm. But these are only configurable through the runtime CLI at the moment, not P4Runtime.

**Comment by konne88** [comment]
Very interesting, I didn't realize that the HashAlgorithm had to be a compile time constant.

Marking this bug a closed.
