### ISSUE TITLE
Can't run Iperf between two containers with BMV2 switch in between

### ISSUE THREAD

**Issue by vetletm** [p4lang/behavioral-model#986]
Hi,

I'm working on a setup using [FOP4](https://github.com/ANTLab-polimi/FOP4) to deploy two containers connected with a BMV2 switch. I'm using the basic forwarding example in [p4lang/tutorials](https://github.com/p4lang/tutorials/tree/master/exercises/basic), but simplified to use just one switch instead of four. 

The containers can ping each other just fine, but running iperf3 results in a connection that times out. PCAPs from the switch shows a lot of TCP retransmissions. When running TCPDump on the iperf server, the TCP packets arrive, but it does not seem to reply. If I run a similar setup using OVS, iperf works just fine so I have reason to suspect that BMV2 is at fault here. 

Command used by FOP4 to start and configure BMV2: `simple_switch_grpc --device-id 1 -i 2@s1-eth2 -i 3@s1-eth3 --thrift-port 55563 --log-console --pcap --dump-packet-data 80 -Ldebug ./basic.json -- --cpu-port 255 --grpc-server-addr 0.0.0.0:50467`

simple_switch version: `1.14.0-62a013a1`

The host machine is a VM running Ubuntu 18.04.5 with 4.15.0-137-generic kernel. 

Any help would be greatly appreciated, thanks in advance.

**Comment by jafingerhut** [comment]
Try using Wireshark to capture the packets as they arrive at the iperf server in the xperiment where it does not reply again, and enable the options for Wireshark to check the IPv4 header and TCP/UDP payload checksums, and see if they are correct or not.  If they are incorrect, then even though they are arriving at the container where the iperf server is running, the application will not be receiving them as they will be dropped by the kernel networking code.

**Comment by jafingerhut** [comment]
More important than whether they are the same or changed is whether they are _correct_ at the receiver.  Wireshark can help you determine this pretty quickly, if you enable the correct parsing options for IPv4 and TCP headers to enable checksum checking.  I don't recall if tcpdump checks them and reports whether they are correct or not.

**Comment by vetletm** [comment]
I ran Tshark with `tcp.check_checksum:TRUE`, and it's as you say that the TCP checksum is incorrect at the iperf server. 

I guess the next step would be to implement a proper TCP parser into the basic P4 program to rectify this?

**Comment by vetletm** [comment]
I solved the issue by disabling checksum offloading using ethtool. I figured out that this is done for each host when running the mininet code used by the tutorials in p4lang/tutorials. Using the same approach for the containers resulted in a successful iperf test.
