### ISSUE TITLE
Performance decrease in latest version

### ISSUE THREAD

**Issue by mohammedelazzab** [p4lang/behavioral-model#990]
Hello, 
I was using the flowing flags to compile the simple_switch_grpc to have better performance according to the comments from a discussion thread about bmv2 peformance:
```
CXXFLAGS=-g 'CFLAGS=-g -03' --disable-logging-macros --disable-elogger
```
That indeed incresed the performance and my p4 code could process up to 20000 pps instead of 2000pps. But after I pulled the latest behavioral-model code and recompiled using the same flags the performance went back to around 2000pps.
 Is there any new features that can be disabled to increase performance ? 
 The latest version I am using correspond to the commit on date Mar 17:` Fix simple_swiitch_grpc tests after PI update`

Thanks
  `

**Comment by Itwaits** [comment]
I have the same problem. How do you solve it finally?
