### ISSUE TITLE
HashAlgorithm - xor16

### ISSUE THREAD

**Issue by machadoatz** [p4lang/behavioral-model#995]
Hi,

I was playing with the Hash algorithms defined in [v1model.p4](https://github.com/p4lang/p4c/blob/master/p4include/v1model.p4) and I noticed that I could not use the `xor16`

`enum HashAlgorithm {
    crc32,
    crc32_custom,
    crc16,
    crc16_custom,
    random,
    identity,
    csum16,
    xor16
}`

I was trying to run this piece of code:

` hash(xor_value, HashAlgorithm.xor16,(bit<32>) MIN, {hdr.ipv4.srcAddr,hdr.tcp.srcPort,meta.originalPort},(bit<32>)MAX); `

I did not test crc16_custom and crc32_custom but all the others algorithms seem to be working fine. The reported errors are a mininet message saying: 

> "P4 switch s1 did not start correctly. Check the switch log file."

 and the log message saying 

> "Unknown hash algorithm: xor16"

I tried with multiple versions of the behavior model, including 1.14.0. I am using the repository from [ETH Zurique](https://github.com/nsg-ethz/p4-learning).

**Comment by machadoatz** [comment]
Additionally I found that at the time of this [comment](https://github.com/p4lang/behavioral-model/issues/570#issuecomment-376249477) (March 2018), the xor algorithm was not implemented in bmv2.

**Comment by antoninbas** [comment]
I tagged this as a good first issue. If someone wants to take care of this, it should probably be quite straightforward to implement.

**Comment by KenCox94** [comment]
Can I take this issue?

**Comment by antoninbas** [comment]
> Can I take this issue?

Of course, let me assign it to you. Thanks!

**Comment by Jithin-K-Sojan** [comment]
It looks like this issue has not been resolved yet. Can I take it?

**Comment by jafingerhut** [comment]
@Jithin-K-Sojan I would say go for it!  It would be highly unlikely that the person who claimed it before is just about ready to create a PR now, if they claimed it last May with no further communication since then.

**Comment by antoninbas** [comment]
Done in https://github.com/p4lang/behavioral-model/pull/1081
