### ISSUE TITLE
Are there any clear steps to implement custom hash Algorithms besides CRC16, CRC32, XOR16?

### ISSUE THREAD

**Issue by gogamid** [p4lang/behavioral-model#999]
I want to have for example a simple custom hash function written in C++:

```
struct h1 {
  uint32_t operator()(const char *buf, size_t s) const {
    uint32_t hash = 27;
    
    return hash;
  }
};
```
Where should I input so that I can use it in Firewall example?
https://github.com/p4lang/tutorials/tree/master/exercises/firewall

**Comment by antoninbas** [comment]
I would suggest copying this PR to add your hash algorithm: https://github.com/p4lang/behavioral-model/pull/645
Notice the call to `REGISTER_HASH`. After that, the JSON that you feed to bmv2 can refer to your new hash function by name. I believe you will need to add the name of your hash function to the `HashAlgorithm` enum defined in v1model.p4 if you want to be able to refer to your hash function in your P4 program, e.g. when calling the `hash` extern function: https://github.com/p4lang/p4c/blob/f47980b20a9622c97f97f909e18579fad87866fd/p4include/v1model.p4#L403

**Comment by gogamid** [comment]
Hello,
I am using vagrant vm provided in website. 
I made changes to these files:
```
sudo gedit /home/vagrant/behavioral-model/targets/simple_switch/simple_switch.cpp
sudo gedit /home/vagrant/behavioral-model/src/bm_sim/calculations.cpp 
sudo gedit /home/vagrant/p4c/backends/bmv2/common/extern.cpp
sudo gedit /home/vagrant/p4c/backends/bmv2/simple_switch/simpleSwitch.cpp
sudo gedit /home/vagrant/p4c/frontends/p4/fromv1.0/programStructure.cpp
sudo gedit /home/vagrant/p4c/frontends/p4/fromv1.0/v1model.h 
sudo gedit /home/vagrant/p4c/p4include/v1model.p4
sudo gedit  /usr/local/share/p4c/p4include/v1model.p4 


```
![image](https://user-images.githubusercontent.com/36050790/117225844-9a397300-ae13-11eb-8338-cfd6dd5a94e7.png)
![image](https://user-images.githubusercontent.com/36050790/117225912-ba693200-ae13-11eb-8060-65f2783fdf23.png)
![image](https://user-images.githubusercontent.com/36050790/117226063-17fd7e80-ae14-11eb-8475-acd79f5ff8c6.png)
![image](https://user-images.githubusercontent.com/36050790/117226111-3499b680-ae14-11eb-8663-e307e352a9c1.png)
![image](https://user-images.githubusercontent.com/36050790/117226158-52ffb200-ae14-11eb-9840-7e3ce4f05401.png)
![image](https://user-images.githubusercontent.com/36050790/117226238-7cb8d900-ae14-11eb-97d6-04d611995af7.png)
![image](https://user-images.githubusercontent.com/36050790/117226274-90643f80-ae14-11eb-9a54-3373ccae63f8.png)
![image](https://user-images.githubusercontent.com/36050790/117226382-d6b99e80-ae14-11eb-8d23-39e291906a8e.png)



I am still getting this error: 
```
basic.p4(101): [--Werror=legacy] error: h1: unexpected algorithm
        hash(_h1,HashAlgorithm.h1,32w0, {ipAddr1},32w40);
```

Sorry for images, I could not reference repository. But images correspond to the files mentioned.

**Comment by antoninbas** [comment]
Looks like you made the correct changes. I assumed you re-built and re-installed the compiler after making these changes?

BTW, it seems you defined your hash function twice, once in targets/simple_switch/simple_switch.cpp and once in src/bm_sim/calculations.cpp. You don't need to do that.

In any case, the changes you made on the bmv2 side look correct me. The changes on the compiler side look correct to.

**Comment by gogamid** [comment]
How to re-build and re-install the compiler?

**Comment by jafingerhut** [comment]
Given that you made changes in the /home/vagrant directory it sounds like this was a VM created via `vagrant up` from the p4lang/tutorials repository.

Log out from the 'p4' user account, and log in as the 'vagrant' user (password is 'vagrant' by default).

To build p4c from source code:
```
cd ~
cd p4
mkdir build
cd build
cmake ..
make
# Only run the following two commands if there were no errors from the previous command:
sudo make install
sudo ldconfig
```

Here are the lines from the `vagrant up` script `user-bootstrap.sh` in the tutorials repo that originally did this when creating your VM: https://github.com/p4lang/tutorials/blob/master/vm/user-bootstrap.sh#L102-L112

To build both of the `simple_switch` and `simple_switch_grpc` executables from source code (I do not know which one you are using, but probably `simple_switch_grpc`, but doesn't take too much more time to build them both):
```
cd ~
cd behavioral-model
./autogen.sh
./configure --enable-debugger --with-pi
make
# Only run the following two commands if there were no errors from the previous command:
sudo make install
sudo ldconfig
# Simple_switch_grpc target
cd targets/simple_switch_grpc
./autogen.sh
./configure --with-thrift
make
# Only run the following two commands if there were no errors from the previous command:
sudo make install
sudo ldconfig
```

Here are the lines from the `vagrant up` script `user-bootstrap.sh` in the tutorials repo that originally did this when creating your VM: https://github.com/p4lang/tutorials/blob/master/vm/user-bootstrap.sh#L81-L93

**Comment by gogamid** [comment]
Instructions were very clear, works perfectly !

Thank you @jafingerhut @antoninbas !

**Comment by gogamid** [comment]
Maybe some small notice, in case some other person will try this. 
To build p4c from source code for me was not "p4" folder but "p4c"

**Comment by jafingerhut** [comment]
Thanks for finding that typo, which I have edited in my comment above to fix it.
